return {
    mod_name = {
        en = "Tweaker: Careers",
    },
    mod_description = {
        en = "Swap talents and abilities between careers, and toggle talent reworks.",
    },
    -- ============================================================
    -- Character experience level override
    -- ============================================================
    experience_levels_group                 = { en = "Character Experience Level" },
    level_override_dwarf_ranger             = { en = "Bardin - level (0 = no override)" },
    level_override_dwarf_ranger_tooltip     = { en = "Force Bardin's reported experience level. All four Bardin careers share this value (XP is per-character, not per-career). 0 = use real XP. 1-35 = report that level everywhere (inventory badge, character-select tile, mission spawn). Modded realm only - does not write to the backend." },
    level_override_empire_soldier           = { en = "Kruber - level (0 = no override)" },
    level_override_empire_soldier_tooltip   = { en = "Force Kruber's reported experience level. All four Kruber careers share this value. 0 = use real XP. 1-35 = report that level. Modded realm only - does not write to the backend." },
    level_override_wood_elf                 = { en = "Kerillian - level (0 = no override)" },
    level_override_wood_elf_tooltip         = { en = "Force Kerillian's reported experience level. All four Kerillian careers share this value. 0 = use real XP. 1-35 = report that level. Modded realm only - does not write to the backend." },
    level_override_witch_hunter             = { en = "Saltzpyre - level (0 = no override)" },
    level_override_witch_hunter_tooltip     = { en = "Force Saltzpyre's reported experience level. All four Saltzpyre careers share this value. 0 = use real XP. 1-35 = report that level. Modded realm only - does not write to the backend." },
    level_override_bright_wizard            = { en = "Sienna - level (0 = no override)" },
    level_override_bright_wizard_tooltip    = { en = "Force Sienna's reported experience level. All four Sienna careers share this value. 0 = use real XP. 1-35 = report that level. Modded realm only - does not write to the backend." },
    -- ============================================================
    -- Career swapping
    -- ============================================================
    career_swapping_group                   = { en = "Career Ability & Talent Swapping" },
    talent_swap_dr_ironbreaker              = { en = "Ironbreaker" },
    talent_swap_dr_slayer                   = { en = "Slayer" },
    talent_swap_dr_ranger                   = { en = "Ranger" },
    talent_swap_dr_engineer                 = { en = "Engineer" },
    talent_swap_es_huntsman                 = { en = "Huntsman" },
    talent_swap_es_knight                   = { en = "Foot Knight" },
    talent_swap_es_mercenary                = { en = "Mercenary" },
    talent_swap_es_questingknight           = { en = "Grail Knight" },
    talent_swap_we_shade                    = { en = "Shade" },
    talent_swap_we_maidenguard              = { en = "Handmaiden" },
    talent_swap_we_waywatcher                = { en = "Waystalker" },
    talent_swap_we_thornsister              = { en = "Sister of the Thorn" },
    talent_swap_wh_zealot                   = { en = "Zealot" },
    talent_swap_wh_bountyhunter             = { en = "Bounty Hunter" },
    talent_swap_wh_captain                  = { en = "Witch Hunter Captain" },
    talent_swap_wh_priest                   = { en = "Warrior Priest" },
    talent_swap_bw_scholar                  = { en = "Battle Wizard" },
    talent_swap_bw_adept                    = { en = "Pyromancer" },
    talent_swap_bw_unchained                = { en = "Unchained" },
    talent_swap_bw_necromancer              = { en = "Necromancer" },
    talent_swap_option_none                 = { en = "None (default)" },
    talent_swap_option_dr_ironbreaker       = { en = "Ironbreaker (Bardin)" },
    talent_swap_option_dr_slayer            = { en = "Slayer (Bardin)" },
    talent_swap_option_dr_ranger            = { en = "Ranger (Bardin)" },
    talent_swap_option_dr_engineer          = { en = "Engineer (Bardin)" },
    talent_swap_option_es_huntsman          = { en = "Huntsman (Markus)" },
    talent_swap_option_es_knight            = { en = "Foot Knight (Markus)" },
    talent_swap_option_es_mercenary         = { en = "Mercenary (Markus)" },
    talent_swap_option_es_questingknight    = { en = "Grail Knight (Markus)" },
    talent_swap_option_we_shade             = { en = "Shade (Kerillian)" },
    talent_swap_option_we_maidenguard       = { en = "Handmaiden (Kerillian)" },
    talent_swap_option_we_waywatcher        = { en = "Waystalker (Kerillian)" },
    talent_swap_option_we_thornsister       = { en = "Sister of the Thorn (Kerillian)" },
    talent_swap_option_wh_zealot            = { en = "Zealot (Victor)" },
    talent_swap_option_wh_bountyhunter      = { en = "Bounty Hunter (Victor)" },
    talent_swap_option_wh_captain           = { en = "Witch Hunter Captain (Victor)" },
    talent_swap_option_wh_priest            = { en = "Warrior Priest (Victor)" },
    talent_swap_option_bw_scholar           = { en = "Battle Wizard (Sienna)" },
    talent_swap_option_bw_adept             = { en = "Pyromancer (Sienna)" },
    talent_swap_option_bw_unchained         = { en = "Unchained (Sienna)" },
    talent_swap_option_bw_necromancer       = { en = "Necromancer (Sienna)" },
    -- ============================================================
    -- Talent Reworks - group headers (character names only, no "Rework:" prefix)
    -- ============================================================
    talent_reworks_group                    = { en = "Talent Reworks" },

    -- General (cross-career)
    rework_general_group                    = { en = "General" },
    rework_general_stagger_thp                          = { en = "General: Stagger THP (+50%% per-target, max 3 targets)" },
    rework_general_stagger_thp_description              = { en = "Reworks the Heal-on-Stagger talents: +50%% per-stagger THP base value (light/medium/heavy stagger now heal 0.375 / 1.5 / 3 THP per target, was 0.25 / 1 / 2) but caps the per-swing target count at 3 instead of 5." },
    rework_general_thp_kill_minimum                     = { en = "General: Minimum THP-on-kill = 1.5" },
    rework_general_thp_kill_minimum_description         = { en = "Clamps every breed's THP-on-kill payout to a minimum of 1.5, lifting skaven slaves (vanilla 1) up to the same payout as the other hordes. Affects every Heal-on-Kill source: weapon traits, Bloodlust talents, Warrior Priest aftershock." },
    rework_general_enhanced_power_10pct                  = { en = "General: Enhanced Power 7.5%% -> 10%% (all careers)" },
    rework_general_enhanced_power_10pct_description      = { en = "Lifts every base career's level-15 Enhanced Power talent from +7.5%% to +10%% power. One field patch on the shared power_level_unbalance buff template covers all 15 base careers simultaneously." },
    rework_general_mainstay_stagger_15pct                = { en = "General: Mainstay universal +15%% stagger" },
    rework_general_mainstay_stagger_15pct_description    = { en = "No vanilla talent named 'Mainstay' exists, so this applies a universal +15%% power_level_impact (stagger power) buff to every player whenever the toggle is on, regardless of career or talent." },

    -- Bardin
    rework_dr_group                         = { en = "Bardin" },
    rework_dr_ranger_group                  = { en = "Ranger Veteran" },
    rework_dr_ranger_attack_speed_5_to_10              = { en = "Ranger Veteran: +5%% AS talent -> +10%%" },
    rework_dr_ranger_attack_speed_5_to_10_description  = { en = "Doubles Ranger Veteran's row-2 flat +5%% Attack Speed talent to +10%%. The in-game talent tooltip is rewritten in-place." },
    rework_dr_ranger_base_hp_plus_25                   = { en = "Ranger Veteran: +25 base HP" },
    rework_dr_ranger_base_hp_plus_25_description       = { en = "Adds 25 to Ranger Veteran's base max HP (100 -> 125, matching Witch Hunter Captain). Applies on next mission load / hero respawn." },
    rework_dr_ranger_exuberance_stacking_dr             = { en = "Ranger Veteran: Exuberance -> 6%%/stack x5, lose on hit" },
    rework_dr_ranger_exuberance_stacking_dr_description = { en = "Vanilla Exuberance grants -30%% damage taken on ranged headshot (single stack). Rework: -6%% per stack, max 5x, one stack per shot (not per target), taking damage removes one stack." },
    rework_dr_slayer_group                              = { en = "Slayer" },
    rework_dr_slayer_trophy_hunter_30_stacks_bundle     = { en = "Slayer: Trophy Hunter 30x@1%% (Impatience 10%%->1%%)" },
    rework_dr_slayer_trophy_hunter_30_stacks_bundle_description = { en = "Trophy Hunter: 1%%/hit x 30 stacks x 2s (was 10%%/hit x 3). Impatience scaled to 1%%/stack to match. Same +30%% cap, smoother ramp." },
    rework_dr_slayer_dawi_drop_buffed                   = { en = "Slayer: Dawi Drop airborne damage 150%%->200%%" },
    rework_dr_slayer_dawi_drop_buffed_description       = { en = "Lifts airborne damage multiplier from 1.5 to 2.0. Airborne time +50%% is deferred (lives in Leap action / physics)." },
    rework_dr_slayer_no_escape_15s                      = { en = "Slayer: No Escape ability duration 10s->15s" },
    rework_dr_slayer_no_escape_15s_description          = { en = "Extends the post-Leap career-skill bonus window by 50%%." },
    rework_dr_slayer_adrenaline_surge_150pct_nerf       = { en = "Slayer: Adrenaline Surge nerf 200%%->150%% cooldown" },
    rework_dr_slayer_adrenaline_surge_150pct_nerf_description = { en = "Nerfs the cooldown regen rate while at max Trophy Hunter stacks. Intended balance offset for the Trophy Hunter rework, but independent." },
    rework_dr_engineer_group                            = { en = "Outcast Engineer" },
    rework_dr_engineer_ingenious_ordnance_240s          = { en = "Outcast Engineer: Ingenious Ordnance 80s->240s tick" },
    rework_dr_engineer_ingenious_ordnance_240s_description = { en = "Lengthens the free-bomb tick interval from 80s to 240s. (v1: interval only; the requested random-regular-bomb swap is deferred.)" },
    rework_dr_engineer_full_head_of_steam_4pct          = { en = "Outcast Engineer: Full Head of Steam 15%%->4%% AS/stack" },
    rework_dr_engineer_full_head_of_steam_4pct_description = { en = "Lowers per-stack attack speed from 15%% to 4%%." },
    rework_dr_engineer_gromril_plated_shot_full_speed   = { en = "Outcast Engineer: Gromril Plated Shot full speed" },
    rework_dr_engineer_gromril_plated_shot_full_speed_description = { en = "Eliminates the minigun spool-up when Gromril Plated Shot is selected. First shot fires at max RPS, visual spinup zeroed." },

    -- Kruber (Markus)
    rework_es_group                         = { en = "Kruber" },
    rework_es_huntsman_group                = { en = "Huntsman" },
    rework_es_huntsman_crit_aura_unlimited_range             = { en = "Huntsman: Unlimited crit aura range" },
    rework_es_huntsman_crit_aura_unlimited_range_description = { en = "Vanilla aura range is 5m. Patches range to math.huge so the +5%% crit chance reaches every teammate at all times." },
    rework_es_huntsman_base_hp_plus_25                  = { en = "Huntsman: +25 base HP" },
    rework_es_huntsman_base_hp_plus_25_description      = { en = "Adds 25 to Huntsman's base max HP (100 -> 125)." },
    rework_es_huntsman_prowl_monster_power              = { en = "Huntsman: Prowl +50%% damage vs monsters" },
    rework_es_huntsman_prowl_monster_power_description  = { en = "During Prowl, +50%% damage vs monsters (boss creatures - chaos spawn, troll, stormfiend, rat ogre). Caveat: also applies to melee-vs-monster during Prowl (no ranged-only-vs-monster stat buff exists in VT2)." },
    rework_es_mercenary_group               = { en = "Mercenary" },
    rework_es_mercenary_hellborgs_tutelage              = { en = "Mercenary: Hellborg's Tutelage -> -10%% random crit (keep crits)" },
    rework_es_mercenary_hellborgs_tutelage_description  = { en = "Hellborg's Tutelage no longer disables random crits. Instead, random crit chance is reduced by 10%% while the talent is selected. The guaranteed crit every 5 hits still procs." },
    rework_es_mercenary_blade_barrier_60x_minus_10_on_hit             = { en = "Mercenary: Blade Barrier 0.5%%/kill x60, -10/hit" },
    rework_es_mercenary_blade_barrier_60x_minus_10_on_hit_description = { en = "-0.5%% damage taken per kill, max 60 stacks (-30%% at cap). Taking damage strips 10 stacks at once." },
    rework_es_knight_group                                            = { en = "Foot Knight" },
    rework_es_knight_protective_presence_10m_rock_20m                 = { en = "Foot Knight: Protective Presence 5m->10m, Rock->20m" },
    rework_es_knight_protective_presence_10m_rock_20m_description     = { en = "Doubles Protective Presence base aura to 10m. Rock of the Reickland talent then extends to 20m." },
    rework_es_knight_valiant_charge_great_foes_45s_battering_ram_30s             = { en = "Foot Knight: Valiant Charge 45s base, Battering Ram->30s" },
    rework_es_knight_valiant_charge_great_foes_45s_battering_ram_30s_description = { en = "Base cooldown 30s -> 45s. When Battering Ram is selected, refunds 1/3 of the cooldown back to 30s. Talent keeps its doubled-width effect. ('Always charges through great foes' baseline deferred - collision gate lives in C++.)" },
    rework_es_knight_counter_punch_stagger_stack                                  = { en = "Foot Knight: Counter-Punch +30%% stagger/block, x5" },
    rework_es_knight_counter_punch_stagger_stack_description                      = { en = "Each successful block grants +30%% stagger (power_level_impact) stacking up to 5x. Each stack lasts 5s." },
    rework_es_questingknight_group                                                = { en = "Grail Knight" },
    rework_es_questingknight_virtue_of_ideal_3pct_per_kill                        = { en = "Grail Knight: Virtue of the Ideal +3%%/kill x10, indep. 10s" },
    rework_es_questingknight_virtue_of_ideal_3pct_per_kill_description            = { en = "Vanilla +8%%/kill x3 x10s refreshing -> +3%%/kill x10 x10s independent (each stack expires on its own timer). Cap +30%% at full stacks." },
    rework_es_questingknight_virtue_of_discipline_double_parry                    = { en = "Grail Knight: Virtue of Discipline double parry (no power)" },
    rework_es_questingknight_virtue_of_discipline_double_parry_description        = { en = "Replaces the +20%% power-on-parry effect with a doubled parry window (0.5s -> 1.0s)." },
    rework_es_questingknight_virtue_of_impetuous_buffed                           = { en = "Grail Knight: Impetuous Knight 20s, +20%% MS/AS/Power" },
    rework_es_questingknight_virtue_of_impetuous_buffed_description               = { en = "Vanilla +35%% MS for 15s on kill -> +20%% MS + +20%% AS + +20%% Power, 20s." },

    -- Kerillian
    rework_we_group                         = { en = "Kerillian" },
    rework_we_maidenguard_group             = { en = "Handmaiden" },
    rework_we_maidenguard_crit_chance_5_to_10              = { en = "Handmaiden: +5%% Crit Chance talent -> +10%%" },
    rework_we_maidenguard_crit_chance_5_to_10_description  = { en = "Doubles Handmaiden's row-2 flat +5%% Critical Strike Chance talent to +10%%." },
    rework_we_shade_group                                  = { en = "Shade" },
    rework_we_shade_hungry_wind_buffed                     = { en = "Shade: Hungry Wind 20s, +20%% MS / +20%% Power" },
    rework_we_shade_hungry_wind_buffed_description         = { en = "Vanilla 10s / +10%% MS / +15%% Power -> 20s / +20%% MS / +20%% Power post-stealth." },
    rework_we_waywatcher_group                                       = { en = "Waystalker" },
    rework_we_waywatcher_drakiras_alacrity_passive_as                = { en = "Waystalker: Drakira's Alacrity -> flat +10%% AS passive" },
    rework_we_waywatcher_drakiras_alacrity_passive_as_description    = { en = "Replaces the conditional +15%% AS for 5s on ranged headshot with a permanent flat +10%% attack speed. No trigger needed." },
    rework_we_waywatcher_fervent_huntress_passive_ms                 = { en = "Waystalker: Fervent Huntress -> flat +10%% MS passive" },
    rework_we_waywatcher_fervent_huntress_passive_ms_description     = { en = "Replaces the conditional +15%% MS for 10s on elite/special kill with a permanent flat +10%% movement speed." },
    rework_we_waywatcher_kurnous_reward_5pct                         = { en = "Waystalker: Kurnous' Reward 30%%->5%% ammo/kill" },
    rework_we_waywatcher_kurnous_reward_5pct_description             = { en = "Lowers ammo restore from 30%% to 5%% per special/elite killed by Waystalker's ability shot." },
    rework_we_waywatcher_ricochet_no_ff_5_bounces                    = { en = "Waystalker: Ricochet 3->5 bounces (no FF on bounces)" },
    rework_we_waywatcher_ricochet_no_ff_5_bounces_description        = { en = "Lifts projectile_bounces buff from +3 to +5." },

    -- Sienna (Bright Wizard)
    rework_bw_group                                                  = { en = "Sienna" },
    rework_bw_adept_group                                            = { en = "Pyromancer" },
    rework_bw_adept_famished_flames_buffed                           = { en = "Pyromancer: Famished Flames +150%% burn / -30%% non-burn" },
    rework_bw_adept_famished_flames_buffed_description               = { en = "Vanilla +100%%/-15%% -> +150%%/-30%%." },
    rework_bw_adept_volcanic_force_doubled                           = { en = "Pyromancer: Volcanic Force full charge +50%%->+100%%" },
    rework_bw_adept_volcanic_force_doubled_description               = { en = "Doubles the full-charge power bonus from +50%% to +100%%." },
    rework_bw_adept_fires_from_ash_1pct_plus_thp                     = { en = "Pyromancer: Fires from Ash 3%%->1%% CDR + 0.5 THP/burn-kill" },
    rework_bw_adept_fires_from_ash_1pct_plus_thp_description         = { en = "Lowers cooldown reduction from 3%% to 1%% per burning kill, but adds +0.5 THP per burning enemy killed." },
    rework_bw_necromancer_group                                      = { en = "Necromancer" },
    rework_bw_necromancer_lost_souls_double_radius                   = { en = "Necromancer: Lost Souls passive 5m->10m radius" },
    rework_bw_necromancer_lost_souls_double_radius_description       = { en = "Doubles the radius of the soul-devour effect. Career passive perk; always active when Sienna plays Necromancer." },
    rework_bw_necromancer_withering_touch_30s                        = { en = "Necromancer: Withering Touch 15s->30s duration" },
    rework_bw_necromancer_withering_touch_30s_description            = { en = "Doubles the buff duration." },
    rework_bw_necromancer_malediction_5_souls                        = { en = "Necromancer: Malediction of Nagash 8->5 souls for crit" },
    rework_bw_necromancer_malediction_5_souls_description            = { en = "Lowers the soul-stack threshold for guaranteed crit." },
    rework_bw_necromancer_vanhels_per_skeleton_as                    = { en = "Necromancer: Vanhel's Danse Macabre +2%%/skel cap 24%%" },
    rework_bw_necromancer_vanhels_per_skeleton_as_description        = { en = "Vanilla binary +12%% AS at >=4 skeletons -> per-skeleton stacking +2%%/skel, max 12 stacks (+24%% cap)." },
    rework_bw_necromancer_death_ascendant_10s                        = { en = "Necromancer: Death Ascendant 6s->10s stack duration" },
    rework_bw_necromancer_death_ascendant_10s_description            = { en = "Extends the cooldown-regen buff stack duration." },
    rework_bw_necromancer_army_of_dead_buffed                        = { en = "Necromancer: Army of the Dead 55s CD, 40s decay" },
    rework_bw_necromancer_army_of_dead_buffed_description            = { en = "Halves the ability cooldown (110s -> 55s) and doubles the despawn timer on extra skeletons (20s -> 40s)." },
    rework_bw_unchained_group                                        = { en = "Unchained" },
    rework_bw_unchained_wildfire_burst_and_radius                    = { en = "Unchained: Wildfire +50%% burst, +25%% radius" },
    rework_bw_unchained_wildfire_burst_and_radius_description        = { en = "Lifts Wildfire's explosion radius +25%% (5 -> 6.25) and damage +50%% (0.15 -> 0.225). ('Make innate' baseline portion deferred - requires hooking the ability's explosion selection.)" },
    rework_bw_unchained_numb_to_pain_4x_burn_kill_lose_on_hit                       = { en = "Unchained: Numb to Pain x4, burn-elite kill, lose on hit" },
    rework_bw_unchained_numb_to_pain_4x_burn_kill_lose_on_hit_description           = { en = "Each kill of a burning elite or special grants -5%% damage taken (max 4 stacks, -20%% at cap), no timeout. Each hit you take strips one stack." },

    -- Saltzpyre (Victor)
    rework_wh_group                         = { en = "Saltzpyre" },
    rework_wh_zealot_group                  = { en = "Zealot" },
    rework_wh_zealot_smite_random_crits                 = { en = "Zealot: Smite allow random crits" },
    rework_wh_zealot_smite_random_crits_description     = { en = "Smite normally disables all random crits. This removes that restriction so you can still get lucky crits between the guaranteed ones." },
    rework_wh_zealot_power_5_to_10                      = { en = "Zealot: +5%% Power talent -> +10%%" },
    rework_wh_zealot_power_5_to_10_description          = { en = "Doubles Zealot's row-1 flat +5%% Power talent to +10%%." },
    rework_wh_zealot_ability_green_to_thp               = { en = "Zealot: Ability converts green HP to THP" },
    rework_wh_zealot_ability_green_to_thp_description   = { en = "Every Holy Fervour activation converts all permanent (green) HP into temporary (white) HP. Synergizes with Zealot's missing-HP damage passive." },
    rework_wh_zealot_fiery_faith_1pct_per_5_hp_max_30                 = { en = "Zealot: Fiery Faith +1%%/5 missing HP, max 30 stacks" },
    rework_wh_zealot_fiery_faith_1pct_per_5_hp_max_30_description     = { en = "Vanilla 5%%/stack x6 (25 HP chunks) -> 1%%/stack x30 (5 HP chunks). Same +30%% cap, smoother ramp." },
    rework_wh_zealot_castigate_4pct_as_per_fiery_faith                = { en = "Zealot: Castigate +4%% AS/Fiery Faith stack (cap +20%%)" },
    rework_wh_zealot_castigate_4pct_as_per_fiery_faith_description    = { en = "Threshold tiers -> chunk-based scaling matching Fiery Faith. +4%% AS per 30 HP missing, max 5 stacks." },
    rework_wh_zealot_holy_fortitude_30_max_hp                         = { en = "Zealot: Holy Fortitude -> +30 max HP" },
    rework_wh_zealot_holy_fortitude_30_max_hp_description             = { en = "Replaces the level-20 healing-received talent with a flat +30 max HP buff." },
    rework_wh_bountyhunter_group            = { en = "Bounty Hunter" },
    rework_wh_bountyhunter_double_shotted_80              = { en = "Bounty Hunter: Double-Shotted 80%% refund on headshot" },
    rework_wh_bountyhunter_double_shotted_80_description  = { en = "Vanilla Double-Shotted refunds 60%% on headshot; rework lifts to 80%%." },
    rework_wh_bountyhunter_double_shotted_damage_double                   = { en = "Bounty Hunter: Double-Shotted also doubles damage" },
    rework_wh_bountyhunter_double_shotted_damage_double_description       = { en = "Independent of the 80%% refund toggle. Activating Locked And Loaded grants +100%% ranged power for 3 seconds." },
    rework_wh_bountyhunter_blessed_combat_25_and_passive_melee_reset                  = { en = "Bounty Hunter: Blessed Combat 25%%/stack (+melee-reset innate)" },
    rework_wh_bountyhunter_blessed_combat_25_and_passive_melee_reset_description      = { en = "Stack multipliers lifted from 15%% to 25%% (max +150%%). 'Melee kills reset Blessed Shots cooldown' becomes innate across all lvl-20 talents." },
    rework_wh_bountyhunter_rile_the_mob_movement                          = { en = "Bounty Hunter: Rile the Mob -> +10%% MS permanent" },
    rework_wh_bountyhunter_rile_the_mob_movement_description              = { en = "Replaces the conditional team-speed-on-ranged-crit with a permanent self-only +10%% movement speed." },
    rework_wh_bountyhunter_salvaged_ammo_no_gate_and_passive_reload                   = { en = "Bounty Hunter: Salvaged Ammo no gate (+reload innate)" },
    rework_wh_bountyhunter_salvaged_ammo_no_gate_and_passive_reload_description       = { en = "Drops the 'must be out of ammo' gate. Also promotes 'melee kills reload ranged weapon' to innate across all lvl-25 talents." },
    rework_wh_bountyhunter_job_well_done_passive_and_special_kill_dr                  = { en = "    (A) BH passive: Job Well Done innate +5%%/stack DR" },
    rework_wh_bountyhunter_job_well_done_passive_and_special_kill_dr_description      = { en = "Vanilla effect becomes innate. Talent slot replaced: special-kill grants -5%% damage taken per stack, max 6x, lose 1 stack on damage." },
    rework_wh_bountyhunter_job_well_done_passive_and_special_kill_dr_tooltip          = { en = "BH passive choice (A) of (B). Alternative to '(B) BH passive: perks rework (Big Rebalance)' — these are mutually exclusive (toggling either one off-checks the other; both off = vanilla).\n\nThis is my rework: vanilla Job Well Done effect becomes innate. Talent slot replaced — special-kill grants -5%% damage taken per stack, max 6 stacks, lose 1 stack on damage." },
    rework_wh_bountyhunter_just_reward_5s_cooldown                        = { en = "Bounty Hunter: Just Reward 10s->5s cooldown" },
    rework_wh_bountyhunter_just_reward_5s_cooldown_description            = { en = "Tightens the proc gate to 5 seconds so the refund can proc twice as often." },
    rework_wh_bountyhunter_indiscriminate_blast_refund_per_kill           = { en = "Bounty Hunter: Indiscriminate Blast +1%%/ability kill" },
    rework_wh_bountyhunter_indiscriminate_blast_refund_per_kill_description = { en = "Each kill from the BH active ability refunds an extra 1%% of the ability's cooldown, on top of vanilla." },
    rework_wh_captain_group                 = { en = "Witch Hunter Captain" },
    rework_wh_captain_parry_window                      = { en = "Witch Hunter Captain: Extended parry window (1.0s)" },
    rework_wh_captain_parry_window_description          = { en = "Doubles the parry timing window from 0.5s to 1.0s." },
    rework_wh_priest_group                              = { en = "Warrior Priest" },
    rework_wh_priest_shield_of_faith_10s_110s_cd_plus_unyielding_20s              = { en = "Warrior Priest: Shield of Faith 10s base / 110s CD / Unyielding +20s" },
    rework_wh_priest_shield_of_faith_10s_110s_cd_plus_unyielding_20s_description  = { en = "Doubles Shield of Faith base duration (5s -> 10s) and cooldown (70s -> 110s). Unyielding Blessing bonus 10s -> 20s. Combined uptime with Unyielding = 30s." },
    rework_wh_priest_prayer_of_vengeance_self_40_others_20                        = { en = "Warrior Priest: Prayer of Vengeance self +40%%, allies +20%%" },
    rework_wh_priest_prayer_of_vengeance_self_40_others_20_description            = { en = "Team aura +20%% damage vs monsters; Warrior Priest gets an extra +20%% self-only on top for +40%% total." },

    -- ============================================================
    -- Big Rebalance (Core's Big Rebalance integration) — ~160 opt-in toggles
    -- ============================================================
    -- Top-level group labels
    cbr_group                              = { en = "Big Rebalance" },
    cbr_group_description                  = { en = "Opt-in Core's Big Rebalance career changes. All toggles default OFF. REQUIRES the companion mod 'Tweaker: Buffs' (internal id `bt`) installed and its master toggle ON — subscribe to it separately, then restart the game. Without bt's master on, every toggle here is inert." },

    -- Group headers
    cbr_general_group                      = { en = "General — cross-career framework" },
    cbr_es_group                           = { en = "Kruber" },
    cbr_es_mercenary_group                 = { en = "Mercenary" },
    cbr_es_knight_group                    = { en = "Foot Knight" },
    cbr_es_huntsman_group                  = { en = "Huntsman" },
    cbr_es_questingknight_group            = { en = "Grail Knight" },
    cbr_dr_group                           = { en = "Bardin" },
    cbr_dr_ironbreaker_group               = { en = "Ironbreaker" },
    cbr_dr_ranger_group                    = { en = "Ranger Veteran" },
    cbr_dr_slayer_group                    = { en = "Slayer" },
    cbr_dr_engineer_group                  = { en = "Outcast Engineer" },
    cbr_we_group                           = { en = "Kerillian" },
    cbr_we_waywatcher_group                = { en = "Waystalker" },
    cbr_we_maidenguard_group               = { en = "Handmaiden" },
    cbr_we_shade_group                     = { en = "Shade" },
    cbr_we_thornsister_group               = { en = "Sister of the Thorn" },
    cbr_wh_group                           = { en = "Saltzpyre" },
    cbr_wh_captain_group                   = { en = "Witch Hunter Captain" },
    cbr_wh_zealot_group                    = { en = "Zealot" },
    cbr_wh_bountyhunter_group              = { en = "Bounty Hunter" },
    cbr_wh_priest_group                    = { en = "Warrior Priest" },
    cbr_bw_group                           = { en = "Sienna" },
    cbr_bw_adept_group                     = { en = "Battle Wizard / Adept" },
    cbr_bw_scholar_group                   = { en = "Pyromancer (Scholar)" },
    cbr_bw_unchained_group                 = { en = "Unchained" },
    cbr_bw_necromancer_group               = { en = "Necromancer" },
    cbr_cross_buffs_group                  = { en = "Cross-character buffs & explosions" },

    -- General
    cbr_thp_talents_rebalanced             = { en = "Custom THP talents (row 1 rewire)" },
    cbr_stagger_talents_rebalanced         = { en = "Custom stagger talents (row 3 rewire)" },
    cbr_timed_block_framework              = { en = "Timed-block (parry) framework" },
    cbr_default_dodge_count_2              = { en = "Default dodge_count = 2" },
    cbr_infinite_wounds_perk               = { en = "infinite_wounds perk gate" },
    cbr_grab_proof_ledge_self_rescue       = { en = "Grab-proof (ledge_self_rescue perk)" },
    cbr_melee_action_three_zoom            = { en = "Variable zoom on melee action_three" },
    cbr_power_level_on_hit_extended        = { en = "Extended power-level multipliers (armoured/large/etc.)" },
    cbr_damage_taken_pipeline_extras       = { en = "Damage-pipeline extras (protection_aoe / team_burn / trash DR — needs et)" },
    cbr_weak_bomb_template                 = { en = "weak_bomb explosion + burn dot" },
    cbr_trait_conqueror_rename             = { en = "Conqueror necklace trait rename" },
    cbr_force_load_dlc_packages            = { en = "Force-load DLC career packages" },

    -- Mercenary
    cbr_merc_row2_talent_2_2_desc          = { en = "Mercenary Row 2.2: description values 1%%" },
    cbr_merc_row2_talent_2_3_clear_perks   = { en = "Mercenary Row 2.3: clear perks" },
    cbr_merc_row4_talent_4_1_desc          = { en = "Mercenary Row 4.1: description values 0.2" },
    cbr_merc_row5_talent_5_3_ammo_on_elite_melee = { en = "Mercenary Row 5.3: ammo on elite melee kill" },
    cbr_merc_row6_talent_6_3_ult_revive    = { en = "Mercenary Row 6.3: ult revives downed allies" },
    cbr_merc_passive_paced_strikes_single_target = { en = "Mercenary Passive: Paced Strikes single-target" },
    cbr_merc_passive_custom_proc           = { en = "Mercenary Passive: custom proc fn" },
    cbr_merc_passive_power_level           = { en = "Mercenary Passive: power level 20%%" },
    cbr_merc_cdr_on_damage_taken           = { en = "Mercenary CDR on damage taken: 25%%" },
    cbr_merc_power_cleave_multiplier_1     = { en = "Mercenary power cleave multiplier = 1" },
    cbr_merc_dodge_range_infinite_dodges   = { en = "Mercenary dodge-range adds infinite dodges" },
    cbr_merc_ult_cooldown_40               = { en = "Mercenary ult cooldown: 40s" },

    -- Foot Knight
    cbr_fk_row2_talent_2_3_buffer_both     = { en = "Foot Knight Row 2.3: buffer = both" },
    cbr_fk_row5_talent_5_1_ult_cdr_on_incap = { en = "Foot Knight Row 5.1: ult CDR on incapacitated ally" },
    cbr_fk_row5_talent_5_2_piston          = { en = "Foot Knight Row 5.2: Piston" },
    cbr_fk_row6_talent_6_2_heavy_buff      = { en = "Foot Knight Row 6.2: heavy buff" },
    cbr_fk_passive_dr_15                   = { en = "Foot Knight passive damage reduction 15%%" },
    cbr_fk_aura_range_dr_10                = { en = "Foot Knight aura range DR 10%%" },
    cbr_fk_aura_dr_10                      = { en = "Foot Knight aura DR 10%%" },
    cbr_fk_passive_range_10                = { en = "Foot Knight aura range 10m" },
    cbr_fk_passive_range_config            = { en = "Foot Knight aura range-config rewire" },
    cbr_fk_passive_guard_defence_config    = { en = "Foot Knight aura guard-defence config" },
    cbr_fk_passive_guard_power_config      = { en = "Foot Knight aura guard-power config" },
    cbr_fk_passive_proximity_stacks_config = { en = "Foot Knight aura proximity-stacks config" },
    cbr_fk_passive_proximity_dr_per_ally   = { en = "Foot Knight proximity DR per ally: -3.3%%" },
    cbr_fk_cdr_on_damage_taken_35          = { en = "Foot Knight CDR on damage taken: 35%%" },
    cbr_fk_on_stagger_changed_to_on_kill   = { en = "Foot Knight power-on-stagger -> on-kill" },
    cbr_fk_attack_speed_on_cleave_hit2     = { en = "Foot Knight attack speed on cleave hit" },
    cbr_fk_free_push_duration_2            = { en = "Foot Knight free push duration: 2s" },
    cbr_fk_cdr_on_stagger_elite_func       = { en = "Foot Knight CDR on stagger-elite func" },
    cbr_fk_cdr_on_stagger_elite_buff_config = { en = "Foot Knight CDR on stagger-elite buff config" },
    cbr_fk_ult_invuln_4s_ledge_rescue      = { en = "Foot Knight ult: invuln 4s + ledge rescue" },
    cbr_fk_ult_as_per_hit_2pc              = { en = "Foot Knight ult: AS per hit 2%%" },
    cbr_fk_ult_charge_overhaul             = { en = "Foot Knight ult: wide charge / no mass interrupt" },

    -- Huntsman
    cbr_huntsman_ult_cooldown_60           = { en = "Huntsman ult cooldown: 60s" },
    cbr_huntsman_passive_buff_list_overhaul = { en = "Huntsman passive buff-list overhaul" },
    cbr_huntsman_cdr_on_damage_taken_25    = { en = "Huntsman CDR on damage taken: 25%%" },
    cbr_huntsman_passive_crit_aura_range_10 = { en = "Huntsman crit-aura range 10m" },
    cbr_huntsman_passive_icon_stacks       = { en = "Huntsman passive icon + max_stacks" },
    cbr_huntsman_thp_on_ranged_kill_bloodlust = { en = "Huntsman THP on ranged kill (bloodlust)" },
    cbr_huntsman_row2_talent_2_2_haste     = { en = "Huntsman Row 2.2: Haste" },
    cbr_huntsman_row4_talent_4_3_desc      = { en = "Huntsman Row 4.3: description update" },
    cbr_huntsman_row5_talent_5_1_bleed_on_crit = { en = "Huntsman Row 5.1: bleed on crit" },
    cbr_huntsman_row5_talent_5_2_dr_on_elite_kill = { en = "Huntsman Row 5.2: DR on elite kill" },
    cbr_huntsman_row5_talent_5_3_sniper_perfect_accuracy = { en = "Huntsman Row 5.3: sniper / perfect accuracy" },
    cbr_huntsman_row6_talent_6_1_add_ult_penetration = { en = "Huntsman Row 6.1: add ult penetration" },
    cbr_huntsman_row6_talent_6_2_ult_pierce_big = { en = "Huntsman Row 6.2: ult pierce (big)" },
    cbr_huntsman_row6_talent_6_3_ult_pierce = { en = "Huntsman Row 6.3: ult pierce" },
    cbr_huntsman_ult_explosion_overhaul    = { en = "Huntsman ult explosion overhaul" },

    -- Grail Knight
    cbr_gk_ult_cooldown_60                 = { en = "Grail Knight ult cooldown: 60s" },
    cbr_gk_row2_talent_2_2_crit_insta_kill = { en = "Grail Knight Row 2.2: crit insta-kill" },
    cbr_gk_row2_talent_2_3_first_target_45pc = { en = "Grail Knight Row 2.3: first-target 45%%" },
    cbr_gk_row5_talent_5_2_infinite_dodges = { en = "Grail Knight Row 5.2: infinite dodges" },
    cbr_gk_row6_talent_6_2_cdr_30pc        = { en = "Grail Knight Row 6.2: CDR 30%%" },
    cbr_gk_ult_kill_buff_no_ranged_knockback = { en = "Grail Knight ult kill buff: no ranged knockback" },
    cbr_gk_ult_vfx_and_kill_buff           = { en = "Grail Knight ult: VFX + on-kill buff" },
    cbr_gk_side_quest_rework_strength_potion = { en = "Grail Knight side-quest rework: strength potion" },

    -- Ironbreaker
    cbr_ib_ult_overhaul_50pc_dr_talents    = { en = "Ironbreaker ult: 50%% DR taunt overhaul" },
    cbr_ib_passive_overcharge_no_slow      = { en = "Ironbreaker passive: overcharge no slow" },
    cbr_ib_row2_talent_2_1_drakefire_heat_and_speed = { en = "Ironbreaker Row 2.1: drakefire heat + speed" },
    cbr_ib_passive_power_on_ally_75pc_range_10 = { en = "Ironbreaker passive: power on ally 7.5%% / range 10" },
    cbr_ib_party_power_on_block_3pc_15s    = { en = "Ironbreaker party power on block: 3%% / 15s" },
    cbr_ib_rising_anger_3pc_as             = { en = "Ironbreaker rising anger: 3%% AS" },
    cbr_ib_gromril_as_6pc_15s              = { en = "Ironbreaker gromril: 6%% AS / 15s" },
    cbr_ib_row5_talent_5_3_piston_power    = { en = "Ironbreaker Row 5.3: piston power (cross-career)" },
    cbr_ib_piston_icon_swaps               = { en = "Ironbreaker piston icon swaps" },

    -- Ranger Veteran
    cbr_ranger_row2_talent_2_1_dupe_10pc   = { en = "Ranger Row 2.1: 10%% dupe (heal/potion/bomb)" },
    cbr_ranger_row2_talent_2_3_as_on_empty_clip = { en = "Ranger Row 2.3: AS on empty clip" },
    cbr_ranger_passive_custom_drops        = { en = "Ranger passive: custom potion/bomb/ale drops" },
    cbr_ranger_passive_throwing_axes_ammo  = { en = "Ranger passive: throwing-axes ammo on melee kill" },
    cbr_ranger_row5_talent_5_1_sniper_perfect_accuracy = { en = "Ranger Row 5.1: sniper / perfect accuracy" },
    cbr_ranger_thp_headshot_dr_20pc        = { en = "Ranger headshot THP DR: 20%%" },
    cbr_ranger_row5_talent_5_2_desc        = { en = "Ranger Row 5.2: description update" },
    cbr_ranger_extended_ranged_boost_multipliers = { en = "Ranger ranged boost: GK-style multipliers" },
    cbr_ranger_row6_talent_6_3_free_grenade_on_disengage = { en = "Ranger Row 6.3: free grenade on disengage" },
    cbr_ranger_free_grenade_buff_10s       = { en = "Ranger free grenade buff: 10s refresh" },
    cbr_ranger_smoke_screen_buff_additions = { en = "Ranger smoke screen: buff additions" },
    cbr_ranger_ult_explosion_templates     = { en = "Ranger ult: fire/AOE explosion templates" },

    -- Slayer
    cbr_slayer_passive_perks_reflow        = { en = "Slayer passive perks reflow + Juggernaut" },
    cbr_slayer_melee_charge_dr_25pc        = { en = "Slayer melee charge DR: 25%%" },
    cbr_slayer_row5_talent_5_2_desc        = { en = "Slayer Row 5.2: description update" },
    cbr_slayer_row2_talent_2_1_dual_wield_combos = { en = "Slayer Row 2.1: dual-wield combos" },
    cbr_slayer_row2_talent_2_2_add_max_stacks = { en = "Slayer Row 2.2: NEW talent (max-stacks)" },
    cbr_slayer_row2_talent_2_3_crit_below_hp = { en = "Slayer Row 2.3: crit below HP" },
    cbr_slayer_passive_custom_stack_proc   = { en = "Slayer passive: custom stack proc" },
    cbr_slayer_row4_talent_4_2_add_blood_drunk = { en = "Slayer Row 4.2: NEW talent Blood Drunk" },
    cbr_slayer_row4_talent_4_3_desc        = { en = "Slayer Row 4.3: description update" },
    cbr_slayer_row5_talent_5_3_scaling_dr  = { en = "Slayer Row 5.3: scaling DR" },
    cbr_slayer_ult_double_leap_overhaul    = { en = "Slayer ult: double leap overhaul" },

    -- Engineer
    cbr_engineer_max_hp_125                = { en = "Engineer max HP: 125" },
    cbr_engineer_base_crit_10pc            = { en = "Engineer base crit: 10%%" },
    cbr_engineer_passive_add_falling_stacks = { en = "Engineer passive: add falling_stacks" },
    cbr_engineer_pump_buff_no_timeout      = { en = "Engineer pump buff: no timeout" },
    cbr_engineer_row2_talent_2_3_clip_size_vs_power = { en = "Engineer Row 2.3: clip size vs power" },
    cbr_engineer_row4_talent_4_1_as_and_crank_debuff = { en = "Engineer Row 4.1: AS + crank debuff" },
    cbr_engineer_row5_talent_5_3_crit_heavy_explosion = { en = "Engineer Row 5.3: crit + heavy explosion" },
    cbr_engineer_row6_talent_6_2_ability_check = { en = "Engineer Row 6.2: ability check" },
    cbr_engineer_crank_gun_no_slowdown_ramp = { en = "Engineer crank gun: no slowdown ramp" },
    cbr_engineer_survival_ale_buffs        = { en = "Engineer survival ale: 3-buff rework" },

    -- Waywatcher
    cbr_ww_ult_cd_60                       = { en = "Waystalker ult cooldown: 60s" },
    cbr_ww_passive_zoom                    = { en = "Waystalker passive: increased zoom" },
    cbr_ww_passive_faster_bows             = { en = "Waystalker passive: faster bows" },
    cbr_ww_passive_ammo_50pct              = { en = "Waystalker passive: increased ammunition 50%%" },
    cbr_ww_amaranthe_rework                = { en = "Waystalker: Amaranthe regen rework" },
    cbr_ww_rangedhs_as_20                  = { en = "Waystalker ranged HS AS: 20%% / 10s" },
    cbr_ww_row2_talent_2_2_poison_on_special = { en = "Waystalker Row 2.2: poison on special kill" },
    cbr_ww_row2_talent_2_3_desc            = { en = "Waystalker Row 2.3: description values" },
    cbr_ww_row4_talent_4_1_desc            = { en = "Waystalker Row 4.1: description swap" },
    cbr_ww_row4_talent_4_2_desc            = { en = "Waystalker Row 4.2: description swap" },
    cbr_ww_row5_talent_5_1_hs_dmg          = { en = "Waystalker Row 5.1: headshot damage" },
    cbr_ww_row5_talent_5_2_ricochet_plus_crit = { en = "Waystalker Row 5.2: ricochet + crit" },
    cbr_ww_row5_talent_5_3_ammo_on_melee_kills = { en = "Waystalker Row 5.3: ammo on melee kills" },
    cbr_ww_row6_talent_6_3_clear_buffs     = { en = "Waystalker Row 6.3: clear buffs" },
    cbr_ww_extra_shots_loop                = { en = "Waystalker Trueflight: extra-shots multi-fire" },
    cbr_ww_cd_on_headshot_proc             = { en = "Waystalker CDR-on-headshot proc" },
    cbr_ww_throw_speed_action_time_scale   = { en = "Waystalker throw speed / reduced ranged charge time" },

    -- Handmaiden
    cbr_hm_ult_cd_40                       = { en = "Handmaiden ult cooldown: 40s" },
    cbr_hm_cdr_on_damage_25                = { en = "Handmaiden CDR on damage taken: 25%%" },
    cbr_hm_passive_zoom                    = { en = "Handmaiden passive: increased zoom" },
    cbr_hm_dash_toggle                     = { en = "Handmaiden passive: dash ult toggle" },
    cbr_hm_banner_as                       = { en = "Handmaiden passive: banner attack speed" },
    cbr_hm_banner_as_large                 = { en = "Handmaiden passive: banner attack speed (large)" },
    cbr_hm_passive_perks_rework            = { en = "Handmaiden passive: perks rework" },
    cbr_hm_stam_aura_range_10              = { en = "Handmaiden stamina aura: range 10" },
    cbr_hm_stam_aura_50pct                 = { en = "Handmaiden stamina aura: 50%%" },
    cbr_hm_banner_ult_rework               = { en = "Handmaiden ult: banner rework" },
    cbr_hm_power_on_unharmed_20            = { en = "Handmaiden power on unharmed: 20%%" },
    cbr_hm_unharmed_cd_5                   = { en = "Handmaiden unharmed cooldown: 5s" },
    cbr_hm_row2_talent_2_2_crit_allies     = { en = "Handmaiden Row 2.2: crit allies" },
    cbr_hm_row2_talent_2_3_desc            = { en = "Handmaiden Row 2.3: description" },
    cbr_hm_block_speed_stacks_3            = { en = "Handmaiden block speed: 3 stacks" },
    cbr_hm_push_speed_stacks_3             = { en = "Handmaiden push speed: 3 stacks" },
    cbr_hm_block_speed_20pct               = { en = "Handmaiden block speed: 20%%" },
    cbr_hm_block_cleave_75pct              = { en = "Handmaiden block cleave: 75%%" },
    cbr_hm_block_dummy_stacks_3            = { en = "Handmaiden block dummy stacks: 3" },
    cbr_hm_row4_talent_4_3_armoured_on_dodge = { en = "Handmaiden Row 4.3: armoured on dodge" },
    cbr_hm_row5_talent_5_3_moonbow_speed_plus_ammo = { en = "Handmaiden Row 5.3: moonbow speed + ammo" },
    cbr_hm_max_ammo_50pct                  = { en = "Handmaiden max ammo: 50%%" },
    cbr_hm_row6_talent_6_1_aoe_immunity    = { en = "Handmaiden Row 6.1: AOE immunity description" },
    cbr_hm_row6_talent_6_2_max_hp_50       = { en = "Handmaiden Row 6.2: 50%% max HP description" },
    cbr_hm_row6_talent_6_3_grabber_immunity = { en = "Handmaiden Row 6.3: grabber immunity" },

    -- Shade
    cbr_shade_max_hp_125                   = { en = "Shade max HP: 125" },
    cbr_shade_passive_zoom                 = { en = "Shade passive: increased zoom" },
    cbr_shade_passive_parry_crit           = { en = "Shade passive: parry crit" },
    cbr_shade_hs_stack_20_5                = { en = "Shade headshot stack: 20%% / 5 stacks" },
    cbr_shade_poison_bleed_dmg_30          = { en = "Shade poison/bleed damage: 30%%" },
    cbr_shade_crit_dmg_75                  = { en = "Shade crit damage: 75%%" },
    cbr_shade_backstab_ammo_5              = { en = "Shade backstab ammo: 5%%" },
    cbr_shade_ult_phasing_restealth        = { en = "Shade ult: phasing + restealth" },

    -- Thornsister
    cbr_ts_passive_zoom                    = { en = "Thornsister passive: increased zoom" },
    cbr_ts_vent_nerf                       = { en = "Thornsister passive: vent nerf" },
    cbr_ts_ult_cd_50                       = { en = "Thornsister ult cooldown: 50s" },
    cbr_ts_poison_debuff_15                = { en = "Thornsister poison debuff: 15%%" },
    cbr_ts_poison_debuff_improved_15       = { en = "Thornsister poison debuff (improved): 15%%" },
    cbr_ts_cdr_on_hit_35                   = { en = "Thornsister CDR on hit: 35%%" },
    cbr_ts_cdr_on_damage_25                = { en = "Thornsister CDR on damage taken: 25%%" },
    cbr_ts_set_back_3s                     = { en = "Thornsister set-back: 3s" },
    cbr_ts_temp_health_funnel_40           = { en = "Thornsister temp health funnel: 40%%" },
    cbr_ts_row2_talent_2_1_as_on_health_stack = { en = "Thornsister Row 2.1: AS on health stack" },
    cbr_ts_as_on_full_5_per_25             = { en = "Thornsister AS on full: 5%% per 25%% (max 5)" },
    cbr_ts_crit_on_ability_3               = { en = "Thornsister crit on ability: 3 stacks" },
    cbr_ts_row2_talent_2_3_desc            = { en = "Thornsister Row 2.3: description" },
    cbr_ts_row6_talent_6_1_drain_bush      = { en = "Thornsister Row 6.1: drain bush" },
    cbr_ts_wall_radius_5_5                 = { en = "Thornsister wall radius: 5.5" },
    cbr_ts_wall_radius_improved_5_5        = { en = "Thornsister wall radius (improved): 5.5" },
    cbr_ts_wall_overhaul                   = { en = "Thornsister wall: targeting + spawn overhaul" },

    -- WHC
    cbr_whc_row2_talent_2_1_add_push_power = { en = "WHC Row 2.1: add push-power" },
    cbr_whc_parry_trigger_long             = { en = "WHC parry crit: long trigger" },
    cbr_whc_parry_crit_duration_3          = { en = "WHC parry crit duration: 3s" },
    cbr_whc_row5_talent_5_3_ammo_on_melee  = { en = "WHC Row 5.3: ammo on melee" },
    cbr_whc_row6_talent_6_1_tag_on_hit     = { en = "WHC Row 6.1: tag on hit" },
    cbr_whc_ult_party_crit_15              = { en = "WHC ult: party crit 15%%" },
    cbr_whc_ult_explosion_rework           = { en = "WHC ult: explosion rework" },
    cbr_whc_ult_rework                     = { en = "WHC ult: rework" },
    cbr_whc_ping_persist                   = { en = "WHC ping persist during crit buff" },
    cbr_whc_ping_handle_rework             = { en = "WHC ping handle rework" },

    -- Zealot
    cbr_zealot_passive_rework              = { en = "Zealot passive: 8-buff rework" },
    cbr_zealot_passive_perks_rework        = { en = "Zealot passive: perks rework" },
    cbr_zealot_row2_talent_2_1_as_scaling  = { en = "Zealot Row 2.1: AS scaling" },
    cbr_zealot_row2_talent_2_2_perks_clear = { en = "Zealot Row 2.2: clear perks" },
    cbr_zealot_row2_talent_2_3_first_target = { en = "Zealot Row 2.3: first-target damage" },
    cbr_zealot_row4_talent_4_1_heart_iron_rework = { en = "Zealot Row 4.1: Heart of Iron rework" },
    cbr_zealot_row4_talent_4_2_high_health_as = { en = "Zealot Row 4.2: high-health AS" },
    cbr_zealot_row4_talent_4_3_dr_low_hp   = { en = "Zealot Row 4.3: DR low HP" },
    cbr_zealot_row5_talent_5_1_as_on_hit   = { en = "Zealot Row 5.1: AS on hit" },
    cbr_zealot_row5_talent_5_2_power_on_hit = { en = "Zealot Row 5.2: power on hit" },
    cbr_zealot_row5_talent_5_3_cleave_on_hit = { en = "Zealot Row 5.3: cleave on hit" },
    cbr_zealot_ult_power_2_5               = { en = "Zealot ult power on hit: 2.5%%" },
    cbr_zealot_big_hit_buffs               = { en = "Zealot big-hit buff set" },
    cbr_zealot_ult_rework                  = { en = "Zealot ult rework" },

    -- Bounty Hunter
    cbr_bh_passive_melee_kill              = { en = "BH passive: melee kill activates" },
    cbr_bh_passive_perks_rework            = { en = "    (B) BH passive: perks rework (Big Rebalance)" },
    cbr_bh_passive_perks_rework_tooltip    = { en = "BH passive choice (B) of (B). Alternative to '(A) BH passive: Job Well Done innate +5%%/stack DR (Tweaker)' — these are mutually exclusive (toggling either one off-checks the other; both off = vanilla).\n\nThis is Big Rebalance's version: full passive-perk list rewrite." },
    cbr_bh_railgun_delayed_80              = { en = "BH railgun delayed CDR: 80%%" },
    cbr_bh_row6_talent_6_3_shotgun_cdr     = { en = "BH Row 6.3: shotgun CDR" },
    cbr_bh_row2_talent_2_2_as_every_3_shots = { en = "BH Row 2.2: AS every 3 shots" },
    cbr_bh_row5_talent_5_1_party_heal_on_crit = { en = "BH Row 5.1: party heal on crit" },
    cbr_bh_clip_power_rework               = { en = "BH clip power: rework" },
    cbr_bh_row4_talent_4_1_blessed_combat_desc = { en = "BH Row 4.1: Blessed Combat description" },
    cbr_bh_reload_on_melee_kill            = { en = "BH reload on melee kill" },
    cbr_bh_ammo_on_elite_when_empty        = { en = "BH ammo on elite (when empty)" },
    cbr_bh_stacking_dr_20                  = { en = "BH stacking DR: 20 stacks" },
    cbr_bh_row5_talent_5_3_desc            = { en = "BH Row 5.3: description" },
    cbr_bh_row6_talent_6_1_locked_loaded_buffs = { en = "BH Row 6.1: locked & loaded buffs" },
    cbr_bh_clip_full_fix                   = { en = "BH clip-full ammo fix" },
    cbr_bh_railgun_cd_proc                 = { en = "BH railgun CDR-on-headshot proc" },

    -- Warrior Priest
    cbr_wp_super_armour_50                 = { en = "WP super-armour damage: 50%%" },
    cbr_wp_monster_damage_buff             = { en = "WP monster damage buff" },
    cbr_wp_row2_talent_2_2_charge_power_rework = { en = "WP Row 2.2: charge power rework" },
    cbr_wp_row2_talent_2_3_buff_tune       = { en = "WP Row 2.3: buff tune" },
    cbr_wp_row2_talent_2_3_desc            = { en = "WP Row 2.3: description" },
    cbr_wp_row5_talent_5_1_cleave_power_20 = { en = "WP Row 5.1: cleave power 20%%" },
    cbr_wp_row5_talent_5_2_as_5            = { en = "WP Row 5.2: AS 5%%" },
    cbr_wp_aftershock_hit_force            = { en = "WP aftershock: hit_force" },
    cbr_wp_aftershock_mult_10              = { en = "WP aftershock: multiplier 10" },
    cbr_wp_activated_noclip                = { en = "WP activated noclip pulse buff" },
    cbr_wp_row6_talent_6_1_desc            = { en = "WP Row 6.1: description" },
    cbr_wp_row6_talent_6_3_heal_window_4   = { en = "WP Row 6.3: heal window 4" },
    cbr_wp_prayer_toggle                   = { en = "WP prayer toggle system" },
    cbr_wp_attack_speed_on_fury            = { en = "WP attack speed on fury" },
    cbr_wp_fury_on_ult                     = { en = "WP fury on ult" },
    cbr_wp_fury_rework                     = { en = "WP fury system rework" },
    cbr_wp_target_action_init              = { en = "WP target action init" },
    cbr_wp_target_buff_list                = { en = "WP target buff list (spell_data)" },
    cbr_wp_nuke_enemy_debuff               = { en = "WP nuke enemy debuff" },
    cbr_wp_lightning_explosion_templates   = { en = "WP lightning explosion templates" },

    -- Adept
    cbr_adept_ult_cooldown_60              = { en = "Adept ult cooldown: 60s" },
    cbr_adept_passive_zoom                 = { en = "Adept passive: increased zoom" },
    cbr_adept_row5_talent_5_2_dr_from_overcharge = { en = "Adept Row 5.2: DR from overcharge" },
    cbr_adept_ult_rework                   = { en = "Adept ult: leap rework" },
    cbr_adept_burn_damage_100              = { en = "Adept burn damage: 100%%" },
    cbr_adept_row2_talent_2_2_burn_damage  = { en = "Adept Row 2.2: burn damage description" },
    cbr_adept_tranquility_attack_speed     = { en = "Adept tranquility: attack speed" },
    cbr_adept_dr_on_ignite_rework          = { en = "Adept DR on ignite rework" },
    cbr_adept_row5_talent_5_1_dr_on_ignite_desc = { en = "Adept Row 5.1: DR on ignite description" },
    cbr_adept_row6_talent_6_3_double_firewalk = { en = "Adept Row 6.3: double firewalk" },

    -- Scholar
    cbr_scholar_ult_cooldown_40            = { en = "Scholar ult cooldown: 40s" },
    cbr_scholar_passive_zoom               = { en = "Scholar passive: increased zoom" },
    cbr_scholar_row4_talent_4_3_spawn_heads = { en = "Scholar Row 4.3: spawn heads on elite kill" },
    cbr_scholar_attack_speed_10            = { en = "Scholar attack speed: 10%%" },
    cbr_scholar_row5_talent_5_3_first_hit_and_proj_speed = { en = "Scholar Row 5.3: first hit + projectile speed" },

    -- Unchained
    cbr_unchained_overcharge_explode_onexit_rewrite = { en = "Unchained overcharge-explode on_exit rewrite" },
    cbr_unchained_passive_zoom             = { en = "Unchained passive: increased zoom" },
    cbr_unchained_passive_health_to_ult    = { en = "Unchained passive: health-to-ult" },
    cbr_unchained_passive_overcharge_on_melee_kills = { en = "Unchained passive: overcharge on melee kills" },
    cbr_unchained_passive_melee_power_rework = { en = "Unchained passive: melee power rework" },
    cbr_unchained_health_to_cooldown_rewrite = { en = "Unchained health-to-cooldown rewrite" },
    cbr_unchained_talent_2_1_flaming_weapons_headshot = { en = "Unchained Row 2.1: Flaming Weapons on headshot" },
    cbr_unchained_talent_2_2_explode_on_elite_kill = { en = "Unchained Row 2.2: explode on elite kill" },
    cbr_unchained_exploding_burning_enemies_rework = { en = "Unchained exploding burning enemies rework" },
    cbr_unchained_talent_4_1_attack_speed_high_oc = { en = "Unchained Row 4.1: AS high overcharge" },
    cbr_unchained_talent_4_2_team_burn     = { en = "Unchained Row 4.2: team burn" },
    cbr_unchained_talent_max_health_on_burn_kill = { en = "Unchained: max-health on burn kill" },
    cbr_unchained_talent_5_2_overcharged_blocks = { en = "Unchained Row 5.2: overcharged blocks" },
    cbr_unchained_thorn_skin               = { en = "Unchained thorn skin (buff registration only — wt owns dmg profile)" },
    cbr_unchained_talent_4_3_overcharge_decay_and_cd = { en = "Unchained Row 4.3: overcharge decay + CD" },
    cbr_unchained_talent_5_3_blood_magic_tradeoff = { en = "Unchained Row 5.3: blood magic tradeoff" },
    cbr_unchained_talent_6_1_cd_reduction  = { en = "Unchained Row 6.1: CD reduction" },
    cbr_unchained_talent_6_2_fire_aura     = { en = "Unchained Row 6.2: fire aura" },

    -- Necromancer
    cbr_necromancer_max_hp_125             = { en = "Necromancer max HP: 125" },
    cbr_necromancer_passive_zoom           = { en = "Necromancer passive: increased zoom" },
    cbr_necromancer_crit_burst             = { en = "Necromancer crit burst + cooldown buff" },
    cbr_necromancer_stagger_zero_set       = { en = "Necromancer all ability stagger -> impact 0 (wt-owned)" },
    cbr_necromancer_talent_2_3_unlimited_crit_cleave = { en = "Necromancer Row 2.3: unlimited crit cleave" },
    cbr_necromancer_talent_2_1_as_per_skeleton = { en = "Necromancer Row 2.1: AS per skeleton" },
    cbr_necromancer_talent_2_2_ranged_power = { en = "Necromancer Row 2.2: ranged power" },
    cbr_necromancer_talent_4_2_soul_rip_stacks_6 = { en = "Necromancer Row 4.2: soul-rip 6 stacks" },
    cbr_necromancer_talent_4_3_buffed_dot  = { en = "Necromancer Row 4.3: buffed DOT" },
    cbr_necromancer_talent_5_1_cd_on_elite_kill = { en = "Necromancer Row 5.1: CD on elite kill" },
    cbr_necromancer_talent_5_2_big_hit_protection = { en = "Necromancer Row 5.2: big-hit protection" },
    cbr_necromancer_talent_6_1_extra_skeletons_40s = { en = "Necromancer Row 6.1: extra skeletons 40s" },
    cbr_necromancer_cursed_blood_propagation_10pct = { en = "Necromancer cursed blood propagation: 10%%" },

    -- Cross-character buffs
    cbr_buff_zealot_burning_debuff         = { en = "Cross: Zealot burning debuff" },
    cbr_buff_wp_fury_burn                  = { en = "Cross: WP fury burn" },
    cbr_buff_engineer_melee_burn           = { en = "Cross: Engineer melee burn" },
    cbr_buff_huntsman_defence_debuff       = { en = "Cross: Huntsman defence debuff" },
    cbr_buff_wp_lightning_debuff           = { en = "Cross: WP lightning debuff" },
    cbr_buff_wp_bubble_debuff              = { en = "Cross: WP bubble debuff" },
    cbr_buff_wp_tome_debuff                = { en = "Cross: WP tome debuff" },
    cbr_buff_shield_bash_debuff            = { en = "Cross: shield-bash attack debuff" },
    cbr_buff_long_burn_low_damage          = { en = "Cross: long-burn low damage DoT" },
    cbr_buff_long_burn_extra_low_damage    = { en = "Cross: long-burn extra-low DoT" },
    cbr_buff_burning_magma_dot             = { en = "Cross: burning magma DOT" },
    cbr_buff_unchained_push_burn           = { en = "Cross: Unchained push-burn DoT" },
    cbr_buff_infinite_burn_dot_clones      = { en = "Cross: infinite-burn DOT auto-clone loop" },
    cbr_buff_warp_lightning_strike_delayed = { en = "Cross: warp lightning strike (delayed)" },
    cbr_buff_timed_warp_explosion          = { en = "Cross: timed warp explosion" },
}
