return {
    mod_name = { en = "Career Tweaker" },
    mod_description = { en = "Career-specific tweaks split out from the old monolithic Tweaker mod." },
    career_group = { en = "Career" },
    talents_group = { en = "Talent Swaps" },
    allow_melee_in_ranged_slot = { en = "Allow Melee Weapons in Ranged Slots" },
    allow_duplicate_careers = { en = "Allow Duplicate Careers (host only)" },
    talent_source_none = { en = "None" },
    cname_dr_ironbreaker = { en = "Ironbreaker" },
    cname_dr_slayer = { en = "Slayer" },
    cname_dr_ranger = { en = "Ranger Veteran" },
    cname_dr_engineer = { en = "Engineer" },
    cname_es_huntsman = { en = "Huntsman" },
    cname_es_knight = { en = "Foot Knight" },
    cname_es_mercenary = { en = "Mercenary" },
    cname_es_questingknight = { en = "Grail Knight" },
    cname_we_shade = { en = "Shade" },
    cname_we_maidenguard = { en = "Handmaiden" },
    cname_we_waywatcher = { en = "Waystalker" },
    cname_we_thornsister = { en = "Sister of the Thorn" },
    cname_wh_zealot = { en = "Zealot" },
    cname_wh_bountyhunter = { en = "Bounty Hunter" },
    cname_wh_captain = { en = "Witch Hunter Captain" },
    cname_wh_priest = { en = "Warrior Priest" },
    cname_bw_scholar = { en = "Battle Wizard" },
    cname_bw_adept = { en = "Pyromancer" },
    cname_bw_unchained = { en = "Unchained" },
    cname_bw_necromancer = { en = "Necromancer" },
    talent_swap_dr_ironbreaker = { en = "Ironbreaker" },
    talent_swap_dr_slayer = { en = "Slayer" },
    talent_swap_dr_ranger = { en = "Ranger Veteran" },
    talent_swap_dr_engineer = { en = "Engineer" },
    talent_swap_es_huntsman = { en = "Huntsman" },
    talent_swap_es_knight = { en = "Foot Knight" },
    talent_swap_es_mercenary = { en = "Mercenary" },
    talent_swap_es_questingknight = { en = "Grail Knight" },
    talent_swap_we_shade = { en = "Shade" },
    talent_swap_we_maidenguard = { en = "Handmaiden" },
    talent_swap_we_waywatcher = { en = "Waystalker" },
    talent_swap_we_thornsister = { en = "Sister of the Thorn" },
    talent_swap_wh_zealot = { en = "Zealot" },
    talent_swap_wh_bountyhunter = { en = "Bounty Hunter" },
    talent_swap_wh_captain = { en = "Witch Hunter Captain" },
    talent_swap_wh_priest = { en = "Warrior Priest" },
    talent_swap_bw_scholar = { en = "Battle Wizard" },
    talent_swap_bw_adept = { en = "Pyromancer" },
    talent_swap_bw_unchained = { en = "Unchained" },
    talent_swap_bw_necromancer = { en = "Necromancer" },
}
