-- Generated from decompiled source revisions; do not hand-edit.
return {
    new_revision = "90c7c21adb7aa2b7de5fcdca5094727895fbeb1a",
    old_revision = "6d41bab482ac64ebebc5c8bba2c3a47954952af9",
    records = {
        [1] = {
            ops = {
                [1] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 1,
                        [6] = "end_time",
                    },
                    unset = true,
                },
                [2] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 1,
                        [6] = "start_time",
                    },
                    unset = false,
                    value = 0.59999999999999998,
                },
                [3] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 1,
                        [6] = "sub_action",
                    },
                    unset = false,
                    value = "default_right",
                },
                [4] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 2,
                        [6] = "end_time",
                    },
                    unset = true,
                },
                [5] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 2,
                        [6] = "start_time",
                    },
                    unset = false,
                    value = 0.59999999999999998,
                },
                [6] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "action",
                    },
                    unset = false,
                    value = "action_two",
                },
                [7] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "end_time",
                    },
                    unset = true,
                },
                [8] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "input",
                    },
                    unset = false,
                    value = "action_two_hold",
                },
                [9] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "release_required",
                    },
                    unset = true,
                },
                [10] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "start_time",
                    },
                    unset = false,
                    value = 0.45000000000000001,
                },
                [11] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 3,
                        [6] = "sub_action",
                    },
                    unset = false,
                    value = "default",
                },
                [12] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "action",
                    },
                    unset = false,
                    value = "action_wield",
                },
                [13] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "end_time",
                    },
                    unset = true,
                },
                [14] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "input",
                    },
                    unset = false,
                    value = "action_wield",
                },
                [15] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "release_required",
                    },
                    unset = true,
                },
                [16] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "start_time",
                    },
                    unset = false,
                    value = 0.45000000000000001,
                },
                [17] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 4,
                        [6] = "sub_action",
                    },
                    unset = false,
                    value = "default",
                },
                [18] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 5,
                    },
                    unset = true,
                },
                [19] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 6,
                    },
                    unset = true,
                },
                [20] = {
                    path = {
                        [1] = "actions",
                        [2] = "action_one",
                        [3] = "light_attack_down",
                        [4] = "allowed_chain_actions",
                        [5] = 7,
                    },
                    unset = true,
                },
            },
            source_path = "scripts/settings/equipment/weapon_templates/halberds.lua",
            template = "two_handed_halberds_template_1",
            unsupported = {},
        },
    },
}
