local mod = get_mod("gt")

return {
    name = "Tweaker: General",
    description = mod:localize("mod_description"),
    is_togglable = true,

    options = {
        widgets = {
            {
                setting_id  = "tp_camera_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id    = "tp_camera_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("tp_camera_enabled_tooltip"),
                    },
                    {
                        setting_id    = "tp_distance",
                        type          = "numeric",
                        default_value = 3.0,
                        range         = { 1.0, 10.0 },
                        decimals_number = 1,
                        tooltip       = mod:localize("tp_distance_tooltip"),
                    },
                    {
                        setting_id    = "tp_height",
                        type          = "numeric",
                        default_value = 1.0,
                        range         = { -1.0, 5.0 },
                        decimals_number = 1,
                        tooltip       = mod:localize("tp_height_tooltip"),
                    },
                    {
                        setting_id    = "tp_side_offset",
                        type          = "numeric",
                        default_value = 0.8,
                        range         = { -3.0, 3.0 },
                        decimals_number = 1,
                        tooltip       = mod:localize("tp_side_offset_tooltip"),
                    },
                    {
                        setting_id    = "tp_disable_zoom_in",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("tp_disable_zoom_in_tooltip"),
                    },
                    {
                        setting_id    = "freecam_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("freecam_enabled_tooltip"),
                    },
                },
            },
            {
                setting_id  = "gameplay_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id    = "godmode_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("godmode_enabled_tooltip"),
                    },
                    {
                        setting_id    = "allow_duplicate_careers",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("allow_duplicate_careers_tooltip"),
                    },
                    {
                        setting_id    = "disable_friendly_fire",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("disable_friendly_fire_tooltip"),
                    },
                    {
                        setting_id    = "noclip_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("noclip_enabled_tooltip"),
                    },
                    {
                        setting_id    = "noclip_speed",
                        type          = "numeric",
                        default_value = 15.0,
                        range         = { 1.0, 60.0 },
                        decimals_number = 1,
                        tooltip       = mod:localize("noclip_speed_tooltip"),
                    },
                    {
                        setting_id    = "noclip_boost_multiplier",
                        type          = "numeric",
                        default_value = 3.0,
                        range         = { 1.0, 10.0 },
                        decimals_number = 1,
                        tooltip       = mod:localize("noclip_boost_multiplier_tooltip"),
                    },
                    {
                        setting_id    = "disable_enemy_spawns",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("disable_enemy_spawns_tooltip"),
                    },
                    {
                        setting_id    = "ai_takeover_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("ai_takeover_enabled_tooltip"),
                    },
                },
            },
            {
                setting_id  = "mission_inventory_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id    = "mission_inventory_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("mission_inventory_enabled_tooltip"),
                    },
                },
            },
            {
                setting_id  = "startup_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id    = "skip_intro_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("skip_intro_enabled_tooltip"),
                    },
                },
            },
            {
                setting_id  = "player_state_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id      = "cloak_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_cloak_toggle",
                        default_value   = {},
                        tooltip         = mod:localize("cloak_hotkey_tooltip"),
                    },
                },
            },
            {
                setting_id  = "buffs_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id      = "base_crit_chance",
                        type            = "numeric",
                        default_value   = 5,
                        range           = { 0, 100 },
                        decimals_number = 1,
                        tooltip         = mod:localize("base_crit_chance_tooltip"),
                    },
                    {
                        setting_id      = "movement_speed",
                        type            = "numeric",
                        default_value   = 4,
                        range           = { 0, 30 },
                        decimals_number = 1,
                        tooltip         = mod:localize("movement_speed_tooltip"),
                    },
                },
            },
            {
                setting_id  = "ult_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id      = "ult_reset_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_ult_reset",
                        default_value   = {},
                        tooltip         = mod:localize("ult_reset_hotkey_tooltip"),
                    },
                    {
                        setting_id    = "ult_player_cap_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("ult_player_cap_enabled_tooltip"),
                        sub_widgets   = {
                            {
                                setting_id      = "ult_player_cap_value",
                                type            = "numeric",
                                default_value   = 0,
                                range           = { 0, 120 },
                                decimals_number = 1,
                                tooltip         = mod:localize("ult_player_cap_value_tooltip"),
                            },
                        },
                    },
                    {
                        setting_id    = "ult_bot_cap_enabled",
                        type          = "checkbox",
                        default_value = false,
                        tooltip       = mod:localize("ult_bot_cap_enabled_tooltip"),
                        sub_widgets   = {
                            {
                                setting_id      = "ult_bot_cap_value",
                                type            = "numeric",
                                default_value   = 0,
                                range           = { 0, 120 },
                                decimals_number = 1,
                                tooltip         = mod:localize("ult_bot_cap_value_tooltip"),
                            },
                        },
                    },
                },
            },
            {
                setting_id  = "time_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id    = "time_scale_value",
                        type          = "numeric",
                        default_value = 13,
                        range         = { 1, 24 },
                        tooltip       = mod:localize("time_scale_value_tooltip"),
                    },
                    {
                        setting_id      = "time_faster_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_time_faster",
                        default_value   = {},
                        tooltip         = mod:localize("time_faster_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "time_slower_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_time_slower",
                        default_value   = {},
                        tooltip         = mod:localize("time_slower_hotkey_tooltip"),
                    },
                    {
                        setting_id    = "pause_value",
                        type          = "numeric",
                        default_value = 1,
                        range         = { 1, 24 },
                        tooltip       = mod:localize("pause_value_tooltip"),
                    },
                    {
                        setting_id      = "pause_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_pause_toggle",
                        default_value   = {},
                        tooltip         = mod:localize("pause_hotkey_tooltip"),
                    },
                },
            },
            {
                setting_id  = "level_control_group",
                type        = "group",
                sub_widgets = {
                    {
                        setting_id      = "win_level_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_win_level",
                        default_value   = {},
                        tooltip         = mod:localize("win_level_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "fail_level_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_fail_level",
                        default_value   = {},
                        tooltip         = mod:localize("fail_level_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "restart_level_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_restart_level",
                        default_value   = {},
                        tooltip         = mod:localize("restart_level_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "kill_bots_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_kill_bots",
                        default_value   = {},
                        tooltip         = mod:localize("kill_bots_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "die_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_die",
                        default_value   = {},
                        tooltip         = mod:localize("die_hotkey_tooltip"),
                    },
                    {
                        setting_id      = "fix_sound_hotkey",
                        type            = "keybind",
                        keybind_trigger = "pressed",
                        keybind_type    = "function_call",
                        function_name   = "gt_fix_sound",
                        default_value   = {},
                        tooltip         = mod:localize("fix_sound_hotkey_tooltip"),
                    },
                },
            },
        },
    },
}
