#!/usr/bin/env python3
"""Generate Character Dialogue's deterministic sound-event catalogue.

The source tree is Fatshark's decompiled ``dialogues/generated/*.lua``.  This
script deliberately parses only the regular generated ``add_dialogues`` data
shape; it never evaluates game Lua and therefore remains safe for CI.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


FIELD_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)\s*,?\s*$")
ENTRY_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{\s*$")
STRING_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def brace_delta(line: str) -> int:
    """Count braces outside quoted strings and line comments."""
    delta = 0
    quoted = False
    escaped = False
    i = 0
    while i < len(line):
        c = line[i]
        if quoted:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                quoted = False
        else:
            if c == '"':
                quoted = True
            elif c == "-" and i + 1 < len(line) and line[i + 1] == "-":
                break
            elif c == "{":
                delta += 1
            elif c == "}":
                delta -= 1
        i += 1
    return delta


def string_array(block: str, field: str) -> list[str]:
    m = re.search(rf"\b{re.escape(field)}\s*=\s*\{{(.*?)\n\s*\}},", block, re.S)
    return STRING_RE.findall(m.group(1)) if m else []


def number_array(block: str, field: str) -> list[float]:
    m = re.search(rf"\b{re.escape(field)}\s*=\s*\{{(.*?)\n\s*\}},", block, re.S)
    if not m:
        return []
    return [float(v) for v in re.findall(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", m.group(1))]


def scalar_string(block: str, field: str) -> str:
    m = re.search(rf'\b{re.escape(field)}\s*=\s*"([^"]*)"', block)
    return m.group(1) if m else ""


def dialogue_blocks(path: Path):
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    in_add = False
    add_depth = 0
    current: list[str] | None = None
    current_name = ""
    entry_depth = 0

    for line in lines:
        if not in_add:
            if "add_dialogues({" in line:
                in_add = True
                add_depth = brace_delta(line)
            continue

        if current is None and add_depth == 1:
            match = ENTRY_RE.match(line)
            if match:
                current_name = match.group(1)
                current = [line]
                entry_depth = brace_delta(line)
                add_depth += brace_delta(line)
                continue

        if current is not None:
            current.append(line)
            d = brace_delta(line)
            entry_depth += d
            add_depth += d
            if entry_depth == 0:
                yield current_name, "\n".join(current)
                current = None
                current_name = ""
            continue

        add_depth += brace_delta(line)
        if add_depth <= 0:
            in_add = False


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generate(source: Path, output: Path) -> tuple[int, int]:
    events: dict[str, dict] = {}
    groups = 0
    for path in sorted(source.glob("*.lua")):
        for group, block in dialogue_blocks(path):
            sound_events = string_array(block, "sound_events")
            if not sound_events:
                continue
            groups += 1
            locs = string_array(block, "localization_strings")
            durations = number_array(block, "sound_events_duration")
            category = scalar_string(block, "category")
            database = scalar_string(block, "database")
            for index, event in enumerate(sound_events, 1):
                if event in events:
                    continue
                events[event] = {
                    "id": event,
                    "group": group,
                    "index": index,
                    "subtitle": locs[index - 1] if index <= len(locs) else event,
                    "duration": durations[index - 1] if index <= len(durations) else 0,
                    "category": category,
                    "database": database,
                    "source": path.stem,
                }

    lines = [
        "-- AUTO-GENERATED by tools/dialogue/generate_catalogue.py. DO NOT HAND-EDIT.",
        "-- Stable sound-event IDs are the persistence keys; array order is lexical.",
        "-- Tuple: { sound_event, subtitle_key, dialogue_group, source_file }.",
        "return {",
    ]
    for event in sorted(events):
        e = events[event]
        lines.append("    {%s,%s,%s,%s}," % (
            lua_quote(e["id"]), lua_quote(e["subtitle"]),
            lua_quote(e["group"]), lua_quote(e["source"]),
        ))
    lines.append("}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return len(events), groups


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    count, groups = generate(args.source, args.output)
    print(f"generated {count} unique events from {groups} dialogue groups -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
