local function en(s) return { en = s } end

return {
    mod_description = en("Host-side mutator picker. Activate any vanilla VT2 mutator on the lobby — difficulty modifiers, special spawns, hordes, winds of magic, plus dormant live-event mutators (Geheimnisnacht ritual sites, Khorne skull pickups). Mutators broadcast to clients via the vanilla mutator handler; vanilla clients work fine, only the host needs the mod."),

    -- Event presets (handle the active_events string magic some
    -- mutators inspect inside their server_start_function)
    event_preset = en("Event Preset"),
    event_preset_tooltip = en("Pick a canonical live event. Drives three things: (1) the mutator list, (2) the active_events string the mutator inspects internally (mutator_geheimnisnacht_2021 reads `active_events` to choose its ritual-site map list), (3) the keep level — Geheimnisnacht swaps to inn_level_halloween, Skulls to inn_level_skulls (decorations are baked into the level file, not runtime-spawned). Changing the preset mid-game auto-reloads the level so the new mutators/keep variant take effect immediately (host only). For Geheimnisnacht, the year you pick decides which 5 maps spawn ritual sites — see per-option text. Off = hand-pick mutators below without preset bundling. Individual mutator checkboxes apply on next level load or via /event_apply."),
    preset_off                 = en("Off (no preset)"),
    preset_geheimnisnacht_2021 = en("Geheimnisnacht 2021 (rituals on dlc_portals/bell/military/dlc_castle/ussingen)"),
    preset_geheimnisnacht_2025 = en("Geheimnisnacht 2025 (rituals on dlc_termite_1/military/mines/warcamp/dlc_portals)"),
    preset_skulls_2023         = en("Khorne's Skulls 2023 (skull pickups → +hordes_galore at 5 stacks)"),

    -- Categories
    cat_difficulty = en("Difficulty Modifiers"),
    cat_specials   = en("Special / Elite Spawns"),
    cat_hordes     = en("Hordes & Waves"),
    cat_atmosphere = en("Atmosphere & Hazards"),
    cat_objectives = en("Objective Modifiers"),
    cat_winds      = en("Winds of Magic (Weave-style)"),
    cat_events     = en("Live-Event Mutators (raw)"),

    -- Difficulty modifiers
    mut_no_ammo                    = en("No Ammo"),
    mut_no_ammo_tooltip            = en("[no_ammo] Ranged weapons cannot be used / start empty."),
    mut_no_pickups                 = en("No Pickups"),
    mut_no_pickups_tooltip         = en("[no_pickups] Removes most pickups from the level (potions, bombs, ammo)."),
    mut_player_dot                 = en("Player DoT"),
    mut_player_dot_tooltip         = en("[player_dot] Players take damage over time (e.g. corrupted)."),
    mut_instant_death              = en("Instant Death"),
    mut_instant_death_tooltip     = en("[instant_death] Any damage downs you instantly. Hardcore."),
    mut_no_respawn                 = en("No Respawn"),
    mut_no_respawn_tooltip         = en("[no_respawn] Dead players don't respawn (deed-style)."),
    mut_elite_run                  = en("Elite Run"),
    mut_elite_run_tooltip          = en("[elite_run] Trash replaced with elites."),
    mut_shared_health_pool         = en("Shared Health Pool"),
    mut_shared_health_pool_tooltip = en("[shared_health_pool] All players share one HP bar."),
    mut_whiterun                   = en("Whiterun"),
    mut_whiterun_tooltip           = en("[whiterun] Take an arrow to the knee. (Damage-on-knee or similar deed effect.)"),
    mut_realism                    = en("Realism"),
    mut_realism_tooltip            = en("[realism] Aim assist / hit indicators stripped (deed-style)."),

    -- Specials
    mut_specials_frequency         = en("Specials Frequency"),
    mut_specials_frequency_tooltip = en("[specials_frequency] Specials spawn more often."),
    mut_more_specials              = en("More Specials"),
    mut_more_specials_tooltip      = en("[more_specials] Larger groups of specials per spawn."),
    mut_same_specials              = en("Same Specials"),
    mut_same_specials_tooltip      = en("[same_specials] All specials in a wave are the same type."),
    mut_big_specials               = en("Big Specials"),
    mut_big_specials_tooltip       = en("[big_specials] Specials are scaled up."),
    mut_elite_specials             = en("Elite Specials"),
    mut_elite_specials_tooltip     = en("[elite_specials] Specials replaced with elites."),
    mut_gutter_runner_mayhem       = en("Gutter Runner Mayhem"),
    mut_gutter_runner_mayhem_tooltip = en("[gutter_runner_mayhem] Pure assassin spawns."),
    mut_chaos_warriors_trickle     = en("Chaos Warriors Trickle"),
    mut_chaos_warriors_trickle_tooltip = en("[chaos_warriors_trickle] Steady flow of chaos warriors."),
    mut_mixed_horde                = en("Mixed Horde"),
    mut_mixed_horde_tooltip        = en("[mixed_horde] Hordes contain both factions."),
    mut_multiple_bosses            = en("Multiple Bosses"),
    mut_multiple_bosses_tooltip    = en("[multiple_bosses] More than one boss spawns."),
    mut_hordes_galore              = en("Hordes Galore"),
    mut_hordes_galore_tooltip      = en("[hordes_galore] Continuous hordes — much higher spawn rate."),
    mut_powerful_elites            = en("Powerful Elites"),
    mut_powerful_elites_tooltip    = en("[powerful_elites] Elites buffed."),
    mut_skulking_sorcerer          = en("Skulking Sorcerer"),
    mut_skulking_sorcerer_tooltip  = en("[skulking_sorcerer] Roving sorcerer enemy stalks the team."),

    -- Hordes / waves
    mut_wave_of_plague_monks         = en("Wave of Plague Monks"),
    mut_wave_of_plague_monks_tooltip = en("[wave_of_plague_monks] Plague monk waves replace standard hordes."),
    mut_wave_of_berzerkers           = en("Wave of Berserkers"),
    mut_wave_of_berzerkers_tooltip   = en("[wave_of_berzerkers] Berserker waves replace standard hordes."),
    mut_high_intensity               = en("High Intensity"),
    mut_high_intensity_tooltip       = en("[high_intensity] Conflict director runs hot — more enemies overall."),
    mut_splitting_enemies            = en("Splitting Enemies"),
    mut_splitting_enemies_tooltip    = en("[splitting_enemies] Enemies split into smaller versions on death."),
    mut_explosive_loot_rats          = en("Explosive Loot Rats"),
    mut_explosive_loot_rats_tooltip  = en("[explosive_loot_rats] Loot rats explode."),
    mut_bloodlust                    = en("Bloodlust"),
    mut_bloodlust_tooltip            = en("[bloodlust] (DLC batch 02) Buff/feedback on kills."),

    -- Atmosphere & hazards
    mut_night_mode                   = en("Night Mode"),
    mut_night_mode_tooltip           = en("[night_mode] Reduced lighting on the level."),
    mut_darkness                     = en("Darkness"),
    mut_darkness_tooltip             = en("[darkness] (DLC batch 01) Heavier darkness — torch dependence."),
    mut_ticking_bomb                 = en("Ticking Bomb"),
    mut_ticking_bomb_tooltip         = en("[ticking_bomb] (DLC batch 01) Periodic explosive event."),
    mut_flames                       = en("Flames"),
    mut_flames_tooltip               = en("[flames] (DLC batch 04) Periodic fire hazard."),
    mut_lightning_strike             = en("Lightning Strike"),
    mut_lightning_strike_tooltip     = en("[lightning_strike] (DLC batch 04) Periodic lightning hazard."),
    mut_chasing_spirits              = en("Chasing Spirits"),
    mut_chasing_spirits_tooltip      = en("[chasing_spirits] (DLC batch 04) Spectral pursuers."),

    -- Objectives
    mut_escort                       = en("Escort"),
    mut_escort_tooltip               = en("[escort] (DLC batch 02) Escort objective overlay."),
    mut_slayer_curse                 = en("Slayer Curse"),
    mut_slayer_curse_tooltip         = en("[slayer_curse] (DLC batch 02) Slayer-flavored curse mechanic."),
    mut_leash                        = en("Leash"),
    mut_leash_tooltip                = en("[leash] (DLC batch 02) Players tethered together."),

    -- Winds of magic
    mut_life_tooltip      = en("[life] Wind of life. Healing-themed mutator."),
    mut_life              = en("Wind: Life"),
    mut_metal             = en("Wind: Metal"),
    mut_metal_tooltip     = en("[metal] Wind of metal. Damage-resistance mutator."),
    mut_heavens           = en("Wind: Heavens"),
    mut_heavens_tooltip   = en("[heavens] Wind of heavens. Lightning effects."),
    mut_light             = en("Wind: Light"),
    mut_light_tooltip     = en("[light] Wind of light. Truesight effects."),
    mut_shadow            = en("Wind: Shadow"),
    mut_shadow_tooltip    = en("[shadow] Wind of shadow. Stealth effects."),
    mut_fire              = en("Wind: Fire"),
    mut_fire_tooltip      = en("[fire] Wind of fire. Burn effects."),
    mut_death             = en("Wind: Death"),
    mut_death_tooltip     = en("[death] Wind of death. Necromantic effects."),
    mut_beasts            = en("Wind: Beasts"),
    mut_beasts_tooltip    = en("[beasts] Wind of beasts. Beastmen-themed."),

    -- Live event mutators (raw)
    mut_geheimnisnacht_2021              = en("Geheimnisnacht 2021"),
    mut_geheimnisnacht_2021_tooltip      = en("[geheimnisnacht_2021] Spawns ritual sites on the canonical 5 maps for the year picked in the Event Preset above. If no preset, the mutator runs but won't spawn rituals — set the preset to Geheimnisnacht 20XX to drive the active_events string the mutator inspects."),
    mut_geheimnisnacht_2021_hard_mode    = en("Geheimnisnacht Hard Mode"),
    mut_geheimnisnacht_2021_hard_mode_tooltip = en("[geheimnisnacht_2021_hard_mode] Activated automatically when a player picks up the side objective in normal Geheimnisnacht mode. You can also force-enable here."),
    mut_skulls_2023                      = en("Khorne's Skulls 2023"),
    mut_skulls_2023_tooltip              = en("[skulls_2023] Spawns skull pickups; 5 picked grants hordes_galore. Self-contained — no preset string required."),
}
