-- Generated from immutable decompiled source revisions; do not hand-edit.
return {
	new_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
	old_revision = "3f0e3ba442d8dcafb8b5f829ff6c2a95ae24ae63",
	profile_sources = {
		shot_machinegun_shotgun = "scripts/settings/equipment/damage_profile_templates.lua",
		shot_shotgun = "scripts/settings/equipment/damage_profile_templates.lua",
		shot_sniper = "scripts/settings/equipment/damage_profile_templates.lua",
		throwing_axe = "scripts/settings/equipment/damage_profile_templates.lua",
		throwing_axe_charged = "scripts/settings/equipment/damage_profile_templates.lua",
	},
	profiles = {
		shot_machinegun_shotgun = {
			armor_modifier_far = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.25, 1, 1, 1, 0, }, impact = {1, 0.25, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.3, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.175, }, impact_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.125, }, },
			default_target = {
				attack_template = "shot_machinegun",
				boost_curve_coefficient = 0.4,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "ninja_curve",
				power_distribution_far = {attack = 0.25, impact = 0.05, },
				power_distribution_near = {attack = 0.275, impact = 0.15, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 10, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		shot_shotgun = {
			armor_modifier_far = {attack = {1, 0, 0.25, 0.75, 1, 0, }, impact = {1, 0.5, 0.5, 0, 1, 0.5, }, },
			armor_modifier_near = {attack = {1, 0.2, 0.4, 0.75, 1, 0, }, impact = {1, 0.75, 3, 0, 1, 0.75, }, },
			charge_value = "instant_projectile",
			cleave_distribution = {attack = 0.1, impact = 0.1, },
			critical_strike = {attack_armor_power_modifer = {1, 0.3, 0.5, 1, 1, 0, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 0.5, }, },
			default_target = {
				attack_template = "shot_shotgun",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 0.75,
				boost_curve_type = "linesman_curve",
				power_distribution_far = {attack = 0.15, impact = 0.15, },
				power_distribution_near = {attack = 0.25, impact = 0.3, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 10, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
		shot_sniper = {
			armor_modifier_far = {attack = {1, 1, 1, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.75, }, },
			armor_modifier_near = {attack = {1, 1.2, 1.5, 1, 0.75, 0.5, }, impact = {1, 1, 1, 1, 1, 1, }, },
			charge_value = "instant_projectile",
			cleave_distribution = {attack = 0.3, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 1.4, 1.5, 1, 0.75, 0.6, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 1, }, },
			default_target = {
				attack_template = "shot_sniper",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "smiter_curve",
				headshot_boost_boss = 0.5,
				power_distribution_far = {attack = 0.8, impact = 0.5, },
				power_distribution_near = {attack = 1, impact = 0.5, },
				range_dropoff_settings = {dropoff_end = 50, dropoff_start = 30, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
		throwing_axe = {
			armor_modifier_far = {attack = {1, 0.6, 1.3, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.5, }, },
			armor_modifier_near = {attack = {1, 0.8, 1.3, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.75, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.01, impact = 0.01, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 1.3, 1, 0.75, 0.5, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 0.75, }, },
			default_target = {
				attack_template = "throwing_axe",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "smiter_curve",
				power_distribution_far = {attack = 0.5, impact = 0.75, },
				power_distribution_near = {attack = 0.8, impact = 0.85, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
		throwing_axe_charged = {
			armor_modifier_far = {attack = {1, 0.6, 1.3, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.5, }, },
			armor_modifier_near = {attack = {1, 0.8, 1.3, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.75, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.4, impact = 0.4, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 1.3, 1, 0.75, 0.5, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 0.75, }, },
			default_target = {
				attack_template = "throwing_axe",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "smiter_curve",
				power_distribution_far = {attack = 0.5, impact = 0.75, },
				power_distribution_near = {attack = 0.8, impact = 0.85, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
	},
}
