-- Generated from immutable decompiled source revisions; do not hand-edit.
return {
	new_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
	old_revision = "3f0e3ba442d8dcafb8b5f829ff6c2a95ae24ae63",
	profile_sources = {
		arrow_carbine = "scripts/settings/equipment/damage_profile_templates.lua",
		arrow_carbine_shortbow = "scripts/settings/equipment/damage_profile_templates.lua",
		arrow_machinegun = "scripts/settings/equipment/damage_profile_templates.lua",
		arrow_sniper_kruber = "scripts/settings/equipment/damage_profile_templates.lua",
		beam = "scripts/settings/equipment/damage_profile_templates.lua",
		beam_initial = "scripts/settings/equipment/damage_profile_templates.lua",
		beam_shot = "scripts/settings/equipment/damage_profile_templates.lua",
		blast = "scripts/settings/equipment/damage_profile_templates.lua",
		crossbow_bolt_repeating = "scripts/settings/equipment/damage_profile_templates.lua",
		dagger_burning_slam_fencer = "scripts/settings/equipment/damage_profile_templates.lua",
		dagger_burning_slam_fencer_aoe = "scripts/settings/equipment/damage_profile_templates.lua",
		dagger_burning_slam_target_fencer = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_blunt_smiter_burn = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_blunt_smiter_charged = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_blunt_smiter_pick = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_blunt_tank = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_blunt_tank_light = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_axe_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_linesman_executioner = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_linesman_polearm = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter_executioner = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter_glaive = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter_polearm = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter_stab = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_smiter_stab_polearm = "scripts/settings/equipment/damage_profile_templates.lua",
		heavy_slashing_tank = "scripts/settings/equipment/damage_profile_templates.lua",
		light_blunt_smiter = "scripts/settings/equipment/damage_profile_templates.lua",
		light_blunt_tank = "scripts/settings/equipment/damage_profile_templates.lua",
		light_blunt_tank_diag = "scripts/settings/equipment/damage_profile_templates.lua",
		light_blunt_tank_spiked = "scripts/settings/equipment/damage_profile_templates.lua",
		light_fencer_stab = "scripts/settings/equipment/damage_profile_templates.lua",
		light_fencer_stab_diag = "scripts/settings/equipment/damage_profile_templates.lua",
		light_push = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_axe_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_axe_linesman_upper = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_dual = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_dual_medium = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_dual_swords = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_elf = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_fencer = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_linesman_finesse = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_diag = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_diag_dual_L = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_dual = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_dual_bopp = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_finesse = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_flat = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_stab = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_stab_dual = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_stab_swords = "scripts/settings/equipment/damage_profile_templates.lua",
		light_slashing_smiter_upper = "scripts/settings/equipment/damage_profile_templates.lua",
		longbow_empire = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_smiter_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_smiter_2h_hammer = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_smiter_2h_hammer_upper = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_smiter_flat_2h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_smiter_heavy = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_tank = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_tank_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_tank_spiked = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_blunt_tank_upper_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_burning_smiter_stab_H = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_pointy_smiter_upper_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_push = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_axe_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_axe_linesman_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_linesman = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_linesman_executioner = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_linesman_finesse = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_linesman_spear = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_1h_axe = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_2h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_stab = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_stab_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_stab_elf = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_smiter_upper = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_tank_1h = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_slashing_tank_1h_finesse = "scripts/settings/equipment/damage_profile_templates.lua",
		medium_spear_smiter_stab = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_push = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_slam = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_slam_aoe = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_slam_shotgun = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_slam_shotgun_aoe = "scripts/settings/equipment/damage_profile_templates.lua",
		shield_slam_target = "scripts/settings/equipment/damage_profile_templates.lua",
		shot_drakefire = "scripts/settings/equipment/damage_profile_templates.lua",
		shot_machinegun = "scripts/settings/equipment/damage_profile_templates.lua",
	},
	profiles = {
		arrow_carbine = {
			armor_modifier_far = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.25, 1, 1, 1, 0, }, impact = {1, 0.1, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.15, impact = 0.15, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "arrow_carbine",
				boost_curve_coefficient = 1.25,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "ninja_curve",
				power_distribution_far = {attack = 0.3, impact = 0.1, },
				power_distribution_near = {attack = 0.4, impact = 0.15, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		arrow_carbine_shortbow = {
			armor_modifier_far = {attack = {1, 0, 1.3, 1, 1, 0, }, impact = {1, 0, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.5, 1.3, 1, 1, 0, }, impact = {1, 0.1, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.2, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.3, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "arrow_carbine",
				boost_curve_coefficient = 1.25,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "ninja_curve",
				power_distribution_far = {attack = 0.3, impact = 0.1, },
				power_distribution_near = {attack = 0.4, impact = 0.15, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		arrow_machinegun = {
			armor_modifier_far = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0.1, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0.25, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.15, impact = 0.15, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "arrow_machinegun",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "ninja_curve",
				power_distribution_far = {attack = 0.125, impact = 0.05, },
				power_distribution_near = {attack = 0.25, impact = 0.075, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 10, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		arrow_sniper_kruber = {
			armor_modifier_far = {attack = {1, 0.5, 1.5, 1, 0.75, 0, }, impact = {1, 0.75, 1, 1, 1, 0.5, }, },
			armor_modifier_near = {attack = {1, 1, 1.5, 1, 0.75, 0.25, }, impact = {1, 1, 1, 1, 1, 0.75, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.3, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 1.5, 1, 0.75, 0.5, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 0.75, }, },
			default_target = {
				attack_template = "bolt_sniper",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 2.5,
				boost_curve_type = "smiter_curve",
				power_distribution_far = {attack = 0.5, impact = 0.5, },
				power_distribution_near = {attack = 0.75, impact = 0.5, },
				range_dropoff_settings = {dropoff_end = 50, dropoff_start = 30, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
		beam = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 1, 0, }, impact = {1, 0.8, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.01, impact = 0.01, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "wizard_staff_beam",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 2,
				boost_curve_type = "linesman_curve",
				dot_template_name = "beam_burning_dot",
				power_distribution_far = {attack = 0.025, impact = 0.05, },
				power_distribution_near = {attack = 0.075, impact = 0.065, },
				range_dropoff_settings = {dropoff_end = 50, dropoff_start = 30, },
			},
			ignore_stagger_reduction = true,
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		beam_initial = {
			armor_modifier_far = {attack = {1, 0.1, 1.5, 1, 1, 0, }, impact = {1, 0.2, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.5, 1.5, 1, 1, 0, }, impact = {1, 0.8, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.01, impact = 0.01, },
			critical_strike = {attack_armor_power_modifer = {1, 0.1, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.2, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "wizard_staff_beam",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 2,
				boost_curve_type = "linesman_curve",
				power_distribution_far = {attack = 0.025, impact = 0.05, },
				power_distribution_near = {attack = 0.05, impact = 0.065, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_procs = true,
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		beam_shot = {
			armor_modifier_far = {attack = {1, 0.5, 1, 1, 1, 0, }, impact = {1, 0.5, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.8, 1.5, 1, 1, 0, }, impact = {1, 0.8, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.15, impact = 0.05, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 1.5, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "wizard_staff_beam_sniper",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "ninja_curve",
				dot_template_name = "burning_3W_dot",
				power_distribution_far = {attack = 0.5, impact = 0.2, },
				power_distribution_near = {attack = 0.7, impact = 0.3, },
				range_dropoff_settings = {dropoff_end = 50, dropoff_start = 30, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		blast = {
			armor_modifier = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0.25, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.05, impact = 0.05, },
			critical_strike = {attack_armor_power_modifer = {1, 0.2, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "flame_blast",
				boost_curve_coefficient = 0.5,
				boost_curve_coefficient_headshot = 2,
				boost_curve_type = "linesman_curve",
				power_distribution_far = {attack = 0.05, impact = 0.15, },
				power_distribution_near = {attack = 0.1, impact = 0.275, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			dot_template_name = "burning_1W_dot",
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		crossbow_bolt_repeating = {
			armor_modifier_far = {attack = {1, 0.4, 1.5, 1, 0.5, 0, }, impact = {1, 0.4, 1, 1, 1, 0.25, }, },
			armor_modifier_near = {attack = {1, 0.5, 1.5, 1, 0.5, 0, }, impact = {1, 0.5, 1, 1, 1, 0.25, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.2, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 0.5, 0.25, }, impact_armor_power_modifer = {1, 0.5, 1, 1, 1, 0.5, }, },
			default_target = {
				attack_template = "bolt_carbine",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 1.5,
				boost_curve_type = "smiter_curve",
				power_distribution_far = {attack = 0.25, impact = 0.15, },
				power_distribution_near = {attack = 0.375, impact = 0.25, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		dagger_burning_slam_fencer = {
			armor_modifier = {attack = {1, 0.25, 1, 1, 0.5, }, impact = {1, 0.8, 1, 1, 1, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack = {1, 0.25, 1, 1, 0.5, }, impact = {1, 0.8, 1, 1, 1, }, },
			default_target = {attack_template = "flame_blast", boost_curve_type = "tank_curve", dot_template_name = "burning_1W_dot", power_distribution = {attack = 0.075, impact = 0.1, }, },
			ignore_stagger_reduction = true,
			stagger_duration_modifier = 1.75,
			targets = { },
		},
		dagger_burning_slam_fencer_aoe = {
			armor_modifier = {attack = {1, 0, 1, 1, 0.5, }, impact = {1, 0.5, 1, 1, 1, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack = {1, 0, 1, 1, 0.5, }, impact = {1, 0.5, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_fencer", boost_curve_type = "tank_curve", dead_attack_template = "flame_blast", power_distribution = {attack = 0, impact = 0.075, }, },
			ignore_stagger_reduction = true,
			no_damage = true,
			stagger_duration_modifier = 1.5,
			targets = { },
		},
		dagger_burning_slam_target_fencer = {
			armor_modifier = {attack = {1, 0.5, 1, 1, 0.5, }, impact = {1, 0.8, 1, 1, 1, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack = {1, 0.5, 1, 1, 0.5, }, impact = {1, 0.8, 1, 1, 1, }, },
			default_target = {attack_template = "flame_blast", boost_curve_type = "tank_curve", dot_template_name = "burning_3W_dot", power_distribution = {attack = 0.15, impact = 0.25, }, },
			ignore_stagger_reduction = true,
			stagger_duration_modifier = 1.75,
			targets = { },
		},
		heavy_blunt_smiter_burn = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "burning_smiter", boost_curve_type = "smiter_curve", dot_template_name = "burning_3W_dot", power_distribution = {attack = 0.25, impact = 0.95, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		heavy_blunt_smiter_charged = {
			armor_modifier = {attack = {1, 0.85, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			default_target = {attack_template = "heavy_blunt_smiter", boost_curve_coefficient = 0.5, boost_curve_coefficient_headshot = 1, boost_curve_type = "smiter_curve", power_distribution = {attack = 1.2, impact = 0.5, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_blunt_smiter_pick = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			default_target = {attack_template = "heavy_blunt_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 0.75, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.65, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_blunt_tank = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.6, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.125, }, },
			stagger_duration_modifier = 1.8,
			targets = {
				{armor_modifier = {attack = {1, 0.5, 2, 1, 0.75, }, impact = {1.5, 1, 1, 1, 0.75, }, }, attack_template = "heavy_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.275, impact = 0.3, }, },
				{attack_template = "heavy_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.15, impact = 0.225, }, },
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.2, }, },
			},
		},
		heavy_blunt_tank_light = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.6, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.125, }, },
			stagger_duration_modifier = 1.8,
			targets = {
				{armor_modifier = {attack = {1, 0.5, 2, 1, 0.75, }, impact = {1.5, 1, 1, 1, 0.75, }, }, attack_template = "heavy_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.275, impact = 0.3, }, },
				{attack_template = "heavy_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.15, impact = 0.225, }, },
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.2, }, },
			},
		},
		heavy_slashing_axe_linesman = {
			armor_modifier = {attack = {0.9, 0, 1.5, 1, 0.75, 0, }, impact = {0.9, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.35, impact = 0.35, },
			critical_strike = {attack_armor_power_modifer = {1, 0.75, 2, 1, 1, 0.75, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 0.75, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.125, }, },
			targets = {
				{
					armor_modifier = {attack = {0.9, 0.75, 2, 1, 0.75, }, impact = {0.9, 0.75, 1, 1, 0.75, }, },
					attack_template = "heavy_slashing_linesman",
					boost_curve_coefficient_headshot = 0.75,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.45, impact = 0.5, },
				},
				{attack_template = "slashing_linesman", boost_curve_coefficient_headshot = 0.75, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.25, impact = 0.15, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 0.75, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.125, }, },
			},
		},
		heavy_slashing_linesman = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.75, impact = 0.4, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 0.25, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "heavy_slashing_linesman", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.45, impact = 0.275, }, },
				{attack_template = "heavy_slashing_linesman", boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.25, impact = 0.15, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.15, impact = 0.1, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		heavy_slashing_linesman_executioner = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.4, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 0.25, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "slashing_linesman", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.275, impact = 0.25, }, },
				{attack_template = "slashing_linesman", boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.2, impact = 0.125, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.15, impact = 0.1, }, },
			},
		},
		heavy_slashing_linesman_polearm = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.4, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 0.25, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {0.9, 0.5, 1, 1, 0.75, }, },
					attack_template = "heavy_slashing_linesman",
					boost_curve_coefficient_headshot = 1,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.325, impact = 0.25, },
				},
				{attack_template = "heavy_slashing_linesman", boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.25, impact = 0.15, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.15, impact = 0.1, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		heavy_slashing_smiter = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "heavy_slashing_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 0.75, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.65, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_slashing_smiter_executioner = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {
				armor_modifier = {attack = {1, 0.85, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 1.25, }, },
				attack_template = "heavy_slashing_smiter_hs_executioner",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1.5,
				boost_curve_type = "ninja_curve",
				power_distribution = {attack = 0.65, impact = 0.275, },
			},
			shield_break = true,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_slashing_smiter_glaive = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {
				armor_modifier = {attack = {1, 0.75, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
				attack_template = "heavy_slashing_smiter_hs",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1.25,
				boost_curve_type = "ninja_curve",
				power_distribution = {attack = 0.65, impact = 0.225, },
			},
			melee_boost_override = 3,
			shield_break = true,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_slashing_smiter_polearm = {
			armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "heavy_slashing_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 0.75, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.65, impact = 0.25, }, },
			no_stagger_damage_reduction = false,
			shield_break = false,
			targets = {[2] = {attack_template = "stab_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.2, impact = 0.1, }, }, },
		},
		heavy_slashing_smiter_stab = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.65, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "heavy_stab_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 1, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.2, impact = 0.15, }, },
			melee_boost_override = 3,
			targets = {
				{
					armor_modifier = {attack = {1, 0.65, 2, 1, 0.75, }, impact = {1, 0.65, 1, 1, 0.75, }, },
					attack_template = "heavy_stab_smiter",
					boost_curve_coefficient = 0.75,
					boost_curve_coefficient_headshot = 1.5,
					boost_curve_type = "ninja_curve",
					power_distribution = {attack = 0.45, impact = 0.25, },
				},
			},
		},
		heavy_slashing_smiter_stab_polearm = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "heavy_stab_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 1, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.2, impact = 0.15, }, },
			melee_boost_override = 2.5,
			targets = {
				{
					armor_modifier = {attack = {1, 0.45, 2, 1, 0.75, }, impact = {1, 0.65, 1, 1, 0.75, }, },
					attack_template = "heavy_stab_smiter",
					boost_curve_coefficient = 0.75,
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "ninja_curve",
					power_distribution = {attack = 0.45, impact = 0.25, },
				},
			},
		},
		heavy_slashing_tank = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.6, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "heavy_slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.125, }, },
			stagger_duration_modifier = 1.8,
			targets = {
				{armor_modifier = {attack = {1, 0.5, 2, 1, 0.75, }, impact = {1.5, 1, 1, 1, 0.75, }, }, attack_template = "slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.275, impact = 0.3, }, },
				{attack_template = "slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.15, impact = 0.225, }, },
				{attack_template = "light_slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.2, }, },
			},
		},
		light_blunt_smiter = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "light_blunt_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_blunt_tank = {
			armor_modifier = {attack = {1, 0, 1, 1, 1, }, impact = {1, 1, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.2, impact = 0.6, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.15, }, },
			stagger_duration_modifier = 1.25,
			targets = {
				{attack_template = "blunt_tank", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "tank_curve", power_distribution = {attack = 0.175, impact = 0.25, }, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.175, }, },
			},
		},
		light_blunt_tank_diag = {
			armor_modifier = {attack = {1, 0, 1, 1, 1, }, impact = {1, 1, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.2, impact = 0.6, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_linesman", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.15, }, },
			stagger_duration_modifier = 1.25,
			targets = {
				{attack_template = "blunt_linesman", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "tank_curve", power_distribution = {attack = 0.175, impact = 0.25, }, },
				{attack_template = "light_blunt_linesman", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.175, }, },
			},
		},
		light_blunt_tank_spiked = {
			armor_modifier = {attack = {1, 0.25, 1.5, 1, 1, }, impact = {1, 1, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.25, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			stagger_duration_modifier = 1.5,
			targets = {
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.2, impact = 0.125, }, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, },
			},
		},
		light_fencer_stab = {
			armor_modifier = {attack = {1, 0.25, 1.5, 1, 0.75, }, impact = {1, 0.1, 0.5, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_stab_smiter", boost_curve_coefficient_headshot = 3, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			require_damage_for_dot = true,
			targets = {{attack_template = "light_stab_smiter", boost_curve_coefficient_headshot = 3, boost_curve_type = "ninja_curve", dot_template_name = "weapon_bleed_dot_dagger", power_distribution = {attack = 0.12, impact = 0.08, }, }, },
		},
		light_fencer_stab_diag = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 0.75, }, impact = {1, 0.1, 0.5, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.1, impact = 0.1, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman_hs", boost_curve_coefficient_headshot = 3, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			require_damage_for_dot = true,
			targets = {
				{
					attack_template = "light_slashing_linesman_hs",
					boost_curve_coefficient_headshot = 3,
					boost_curve_type = "ninja_curve",
					dot_template_name = "weapon_bleed_dot_dagger",
					power_distribution = {attack = 0.12, impact = 0.08, },
				},
			},
		},
		light_push = {
			armor_modifier = {attack = {0, 0, 0, 0, 0, }, impact = {1, 0.5, 0.5, 1, 0.5, }, },
			charge_value = "action_push",
			cleave_distribution = {attack = 0, impact = 1, },
			damage_type = "push",
			default_target = {attack_template = "basic_sweep_push", boost_curve_type = "default", damage_type = "push", power_distribution = {attack = 0, impact = 0.125, }, },
			is_push = true,
			no_damage = true,
			targets = { },
		},
		light_slashing_axe_linesman = {
			armor_modifier = {attack = {0.9, 0, 1.5, 1, 0.75, }, impact = {0.9, 0.25, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.25, 1.5, 1, 0.75, 0, }, impact = {0.9, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_linesman",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.195, impact = 0.125, },
				},
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.1, }, },
				{attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.08, }, },
			},
		},
		light_slashing_axe_linesman_upper = {
			armor_modifier = {attack = {0.9, 0, 1.5, 1, 0.75, }, impact = {0.9, 0.25, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_upper", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.25, 1.5, 1, 0.75, 0, }, impact = {0.9, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_upper",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.195, impact = 0.125, },
				},
				{attack_template = "slashing_upper", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.1, }, },
				{attack_template = "slashing_upper", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.08, }, },
			},
		},
		light_slashing_linesman = {
			armor_modifier = {attack = {1, 0, 2, 1, 1, }, impact = {1, 0.3, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 1.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.175, impact = 0.1, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		light_slashing_linesman_dual = {
			armor_modifier = {attack = {1, 0, 2, 1, 1, }, impact = {1, 0.2, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.3, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.25, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.135, impact = 0.075, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.09, impact = 0.05, }, },
			},
		},
		light_slashing_linesman_dual_medium = {
			armor_modifier = {attack = {1, 0.25, 2, 1, 1, }, impact = {1, 0.25, 0.5, 1, 1, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.75, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			melee_boost_override = 3.5,
			targets = {
				{
					armor_modifier = {attack = {1, 0.4, 2, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
					attack_template = "light_slashing_linesman_hs",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "ninja_curve",
					power_distribution = {attack = 0.15, impact = 0.125, },
				},
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		light_slashing_linesman_dual_swords = {
			armor_modifier = {attack = {1.25, 0, 2, 1, 1, }, impact = {1, 0.2, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.3, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.25, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.135, impact = 0.075, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.09, impact = 0.05, }, },
			},
		},
		light_slashing_linesman_elf = {
			armor_modifier = {attack = {0.8, 0, 2, 1, 1, }, impact = {0.75, 0.3, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.175, impact = 0.1, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		light_slashing_linesman_fencer = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 1, }, impact = {1, 0.1, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman_hs", boost_curve_type = "ninja_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient_headshot = 2.5, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.125, impact = 0.05, }, }, },
		},
		light_slashing_linesman_finesse = {
			armor_modifier = {attack = {1, 0, 2, 1, 1, }, impact = {1, 0.3, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "light_slashing_linesman_hs", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.175, impact = 0.1, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.075, }, },
			},
		},
		light_slashing_smiter = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_diag = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_linesman", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_diag_dual_L = {
			armor_modifier = {attack = {1, 0.4, 2.5, 1, 0.75, }, impact = {0.75, 0.5, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient_headshot = 1.4, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.225, impact = 0.125, }, },
			ignore_stagger_reduction = false,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_dual = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient_headshot = 1.6, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.225, impact = 0.15, }, },
			ignore_stagger_reduction = false,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_dual_bopp = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient_headshot = 1.4, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.225, impact = 0.125, }, },
			ignore_stagger_reduction = false,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_finesse = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient_headshot = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_flat = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_tank", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		light_slashing_smiter_stab = {
			armor_modifier = {attack = {1, 0.25, 1.5, 1, 0.75, }, impact = {1, 0.25, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.1, impact = 0.075, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
					attack_template = "stab_smiter",
					boost_curve_coefficient = 0.75,
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.2, impact = 0.1, },
				},
			},
		},
		light_slashing_smiter_stab_dual = {
			armor_modifier = {attack = {1, 0.75, 2.25, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.1, impact = 0.075, }, },
			melee_boost_override = 4,
			targets = {
				{
					armor_modifier = {attack = {1, 0.8, 2.5, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
					attack_template = "stab_smiter",
					boost_curve_coefficient = 1.5,
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.24, impact = 0.1, },
				},
			},
		},
		light_slashing_smiter_stab_swords = {
			armor_modifier = {attack = {1, 0.45, 1.5, 1, 0.75, }, impact = {1, 0.25, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.7, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 0.75, boost_curve_coefficient_headshot = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.1, impact = 0.075, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.7, 1.5, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
					attack_template = "stab_smiter",
					boost_curve_coefficient = 0.75,
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.2, impact = 0.1, },
				},
			},
		},
		light_slashing_smiter_upper = {
			armor_modifier = {attack = {1.25, 0.65, 2.5, 1, 0.75, 0.6, }, impact = {1, 0.5, 1, 1, 0.75, 0.25, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.75, 2.75, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_upper", boost_curve_type = "smiter_curve", power_distribution = {attack = 0.25, impact = 0.175, }, },
			ignore_stagger_reduction = true,
			targets = {
				[2] = {
					armor_modifier = {attack = {1, 0.25, 1, 1, 0.75, }, impact = {0.75, 0.25, 1, 1, 0.75, }, },
					attack_template = "slashing_smiter",
					boost_curve_type = "smiter_curve",
					power_distribution = {attack = 0.075, impact = 0.075, },
				},
			},
		},
		longbow_empire = {
			armor_modifier_far = {attack = {1, 0.8, 1, 1, 1, 0, }, impact = {1, 0.8, 1, 1, 1, 0.25, }, },
			armor_modifier_near = {attack = {1, 0.8, 1, 1, 1, 0, }, impact = {1, 0.8, 1, 1, 1, 0.25, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.3, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 1.5, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {
				attack_template = "bolt_sniper",
				boost_curve_coefficient = 1,
				boost_curve_coefficient_headshot = 1.5,
				boost_curve_type = "smiter_curve",
				power_distribution_far = {attack = 0.35, impact = 0.2, },
				power_distribution_near = {attack = 0.5, impact = 0.5, },
				range_dropoff_settings = {dropoff_end = 50, dropoff_start = 30, },
			},
			no_stagger_damage_reduction_ranged = true,
			shield_break = true,
			targets = { },
		},
		medium_blunt_smiter_1h = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "blunt_smiter", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_blunt_smiter_2h_hammer = {
			armor_modifier = {attack = {1, 0.8, 2, 1, 0.75, 1, }, impact = {1, 0.8, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_smiter", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_blunt_smiter_2h_hammer_upper = {
			armor_modifier = {attack = {1, 0.8, 2, 1, 0.75, 1, }, impact = {1, 0.8, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_tank_uppercut", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_blunt_smiter_flat_2h = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "blunt_tank", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_blunt_smiter_heavy = {
			armor_modifier = {attack = {1, 0.8, 2, 1, 0.75, 1, }, impact = {1, 0.8, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "blunt_smiter", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_blunt_tank = {
			armor_modifier = {attack = {1, 0.2, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, },
			stagger_duration_modifier = 1.5,
			targets = {
				{attack_template = "blunt_tank", boost_curve_coefficient_headshot = 1, boost_curve_type = "tank_curve", power_distribution = {attack = 0.2, impact = 0.2, }, },
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.15, }, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, },
			},
		},
		medium_blunt_tank_1h = {
			armor_modifier = {attack = {1, 0.35, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, },
			stagger_duration_modifier = 1.5,
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
					attack_template = "blunt_tank",
					boost_curve_coefficient_headshot = 1,
					boost_curve_type = "tank_curve",
					power_distribution = {attack = 0.3, impact = 0.2, },
				},
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.15, }, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, },
			},
		},
		medium_blunt_tank_spiked = {
			armor_modifier = {attack = {1.3, 0.8, 1.3, 1.3, 1, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.6, impact = 0.65, },
			critical_strike = {attack_armor_power_modifer = {1.3, 1, 1.3, 1.3, 1.3, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, stagger_duration_modifier = 1.5, },
			stagger_duration_modifier = 1.5,
			targets = {
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.3, impact = 0.3, }, stagger_duration_modifier = 1.5, },
				{attack_template = "blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.15, impact = 0.15, }, stagger_duration_modifier = 1.5, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, stagger_duration_modifier = 1.5, },
			},
		},
		medium_blunt_tank_upper_1h = {
			armor_modifier = {attack = {1.3, 0.8, 1.3, 1.3, 1, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.6, impact = 0.65, },
			critical_strike = {attack_armor_power_modifer = {1.3, 1, 1.3, 1.3, 1.3, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_blunt_linesman", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, stagger_duration_modifier = 1.5, },
			stagger_duration_modifier = 1.5,
			targets = {
				{attack_template = "blunt_tank_uppercut", boost_curve_type = "tank_curve", power_distribution = {attack = 0.3, impact = 0.3, }, stagger_duration_modifier = 1.5, },
				{attack_template = "light_blunt_linesman", boost_curve_type = "tank_curve", power_distribution = {attack = 0.15, impact = 0.15, }, stagger_duration_modifier = 1.5, },
				{attack_template = "light_blunt_linesman", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, stagger_duration_modifier = 1.5, },
			},
		},
		medium_burning_smiter_stab_H = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "flame_blast", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "ninja_curve", dot_template_name = "burning_3W_dot", power_distribution = {attack = 0.275, impact = 0.125, }, },
			ignore_stagger_reduction = true,
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_pointy_smiter_upper_1h = {
			armor_modifier = {attack = {1, 0.9, 2, 1, 1, 0.9, }, impact = {1, 1, 1, 1, 1, 0.5, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "blunt_tank_uppercut", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_push = {
			armor_modifier = {attack = {0, 0, 0, 0, 0, }, impact = {1, 0.5, 0.5, 1, 0.5, }, },
			charge_value = "action_push",
			cleave_distribution = {attack = 0, impact = 1, },
			damage_type = "push",
			default_target = {attack_template = "basic_sweep_push", boost_curve_type = "default", damage_type = "push", power_distribution = {attack = 0, impact = 0.2, }, },
			is_push = true,
			no_damage = true,
			stagger_duration_modifier = 1.3,
			targets = { },
		},
		medium_slashing_axe_linesman = {
			armor_modifier = {attack = {0.9, 0, 1.5, 1, 0.75, }, impact = {0.9, 0.5, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.275, impact = 0.25, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			targets = {
				{
					armor_modifier = {attack = {1, 0.3, 1.5, 1, 0.75, }, impact = {0.9, 0.75, 1, 1, 0.75, }, },
					attack_template = "heavy_slashing_linesman",
					boost_curve_coefficient_headshot = 1.5,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.25, impact = 0.2, },
				},
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.15, impact = 0.125, }, },
				{attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_axe_linesman_1h = {
			armor_modifier = {attack = {0.9, 0, 1.5, 1, 0.75, }, impact = {0.9, 0.5, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.275, impact = 0.25, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.075, }, },
			melee_boost_override = 6,
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1.5, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
					attack_template = "heavy_slashing_linesman",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "linesman_curve",
					power_distribution = {attack = 0.275, impact = 0.2, },
				},
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.2, impact = 0.125, }, },
				{attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_linesman = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "slashing_linesman", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 1.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.225, impact = 0.15, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.125, }, },
				{attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_linesman_executioner = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.25, impact = 0.25, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman_executioner", boost_curve_coefficient_headshot = 0.25, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "slashing_linesman_executioner", boost_curve_coefficient_headshot = 4, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.2, impact = 0.25, }, },
				{attack_template = "slashing_linesman_executioner", boost_curve_coefficient_headshot = 3, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.15, impact = 0.175, }, },
				{attack_template = "light_slashing_linesman_executioner", boost_curve_coefficient_headshot = 2.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_linesman_finesse = {
			armor_modifier = {attack = {1, 0, 1.5, 1, 1, }, impact = {1, 0.5, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.3, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 1.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "slashing_linesman", boost_curve_coefficient = 2, boost_curve_coefficient_headshot = 2, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.225, impact = 0.15, }, },
				{attack_template = "slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.125, }, },
				{attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_linesman_spear = {
			armor_modifier = {attack = {1, 0, 2, 1, 1, }, impact = {1, 0.3, 0.5, 1, 1, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.35, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.5, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_linesman", boost_curve_type = "linesman_curve", power_distribution = {attack = 0.075, impact = 0.05, }, },
			targets = {
				{attack_template = "slashing_linesman", boost_curve_coefficient_headshot = 4, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.175, impact = 0.2, }, },
				{attack_template = "slashing_linesman", boost_curve_coefficient_headshot = 3, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.125, impact = 0.175, }, },
				{attack_template = "light_slashing_linesman", boost_curve_coefficient_headshot = 2.5, boost_curve_type = "linesman_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			},
		},
		medium_slashing_smiter_1h = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			melee_boost_override = 5,
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_slashing_smiter_1h_axe = {
			armor_modifier = {attack = {1, 0.8, 2, 1, 0.75, 1, }, impact = {1, 0.8, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "slashing_smiter", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_slashing_smiter_2h = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1.25, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {
				armor_modifier = {attack = {1.25, 0.8, 2.5, 1, 0.75, }, impact = {1, 0.8, 1, 1, 0.75, }, },
				attack_template = "slashing_smiter",
				boost_curve_type = "smiter_curve",
				power_distribution = {attack = 0.325, impact = 0.2, },
			},
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_slashing_smiter_stab = {
			armor_modifier = {attack = {1, 0.25, 2.25, 1, 0.75, }, impact = {1, 0.75, 1, 1, 0.75, }, },
			charge_value = "light_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.4, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 1, boost_curve_coefficient_headshot = 2, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.2, impact = 0.125, }, },
			melee_boost_override = 2.5,
			targets = { },
		},
		medium_slashing_smiter_stab_1h = {
			armor_modifier = {attack = {1, 0.75, 2.25, 1, 0.75, }, impact = {1, 1, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 1, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 1, boost_curve_coefficient_headshot = 2, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.3, impact = 0.175, }, },
			targets = { },
		},
		medium_slashing_smiter_stab_elf = {
			armor_modifier = {attack = {1, 0.25, 2.25, 1, 0.75, }, impact = {1, 0.75, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.4, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 1, boost_curve_coefficient_headshot = 2, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.25, impact = 0.125, }, },
			melee_boost_override = 2.5,
			targets = { },
		},
		medium_slashing_smiter_upper = {
			armor_modifier = {attack = {1, 0.8, 1.75, 1, 0.75, }, impact = {1, 0.6, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.8, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 0.8, 1, 1, 1, 0.5, }, },
			default_target = {attack_template = "slashing_upper", boost_curve_coefficient = 2, boost_curve_type = "smiter_curve", power_distribution = {attack = 0.4, impact = 0.25, }, },
			shield_break = true,
			targets = {[2] = {attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, }, },
		},
		medium_slashing_tank_1h = {
			armor_modifier = {attack = {1, 0.35, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, },
			stagger_duration_modifier = 1.5,
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
					attack_template = "slashing_tank",
					boost_curve_coefficient_headshot = 1,
					boost_curve_type = "tank_curve",
					power_distribution = {attack = 0.3, impact = 0.2, },
				},
				{attack_template = "slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.15, }, },
				{attack_template = "light_slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, },
			},
		},
		medium_slashing_tank_1h_finesse = {
			armor_modifier = {attack = {1, 0.35, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.3, impact = 0.8, },
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 1, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "light_slashing_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.05, impact = 0.05, }, },
			stagger_duration_modifier = 1.5,
			targets = {
				{
					armor_modifier = {attack = {1, 0.5, 1, 1, 0.75, }, impact = {1, 1, 0.5, 1, 0.75, }, },
					attack_template = "blunt_tank",
					boost_curve_coefficient_headshot = 2,
					boost_curve_type = "tank_curve",
					power_distribution = {attack = 0.3, impact = 0.2, },
				},
				{attack_template = "blunt_tank", boost_curve_coefficient_headshot = 2, boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.15, }, },
				{attack_template = "light_blunt_tank", boost_curve_type = "tank_curve", power_distribution = {attack = 0.075, impact = 0.1, }, },
			},
		},
		medium_spear_smiter_stab = {
			armor_modifier = {attack = {1, 0.25, 2.25, 1, 0.75, }, impact = {1, 0.75, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			cleave_distribution = {attack = 0.075, impact = 0.075, },
			critical_strike = {attack_armor_power_modifer = {1, 0.4, 2.5, 1, 1, }, impact_armor_power_modifer = {1, 1, 1, 1, 1, }, },
			default_target = {attack_template = "stab_smiter", boost_curve_coefficient = 1, boost_curve_coefficient_headshot = 1.5, boost_curve_type = "ninja_curve", power_distribution = {attack = 0.25, impact = 0.25, }, },
			melee_boost_override = 2.5,
			targets = { },
		},
		shield_push = {
			armor_modifier = {attack = {0, 0, 0, 0, 0, }, impact = {1, 0.75, 0.5, 1, 1, }, },
			charge_value = "action_push",
			cleave_distribution = {attack = 0, impact = 1, },
			damage_type = "push",
			default_target = {attack_template = "basic_sweep_push", boost_curve_type = "default", damage_type = "push", power_distribution = {attack = 0, impact = 0.2, }, },
			ignore_stagger_reduction = true,
			is_push = true,
			no_damage = true,
			stagger_duration_modifier = 1.8,
			targets = { },
		},
		shield_slam = {
			armor_modifier = {attack = {1, 0, 1, 1, 0.75, }, impact = {1, 0.8, 1, 1, 1.5, 0.8, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "heavy_blunt_fencer", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.3, }, },
			stagger_duration_modifier = 1.75,
			targets = { },
		},
		shield_slam_aoe = {
			armor_modifier = {attack = {1, 0, 0, 1, 0.75, }, impact = {1, 0.5, 1, 1, 0.75, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "blunt_fencer", boost_curve_type = "tank_curve", dead_attack_template = "blunt_fencer", power_distribution = {attack = 0, impact = 0.125, }, },
			no_damage = true,
			stagger_duration_modifier = 1.5,
			targets = { },
		},
		shield_slam_shotgun = {
			armor_modifier = {attack = {1, 0, 1, 1, 0.75, }, impact = {1, 0.5, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, }, impact_armor_power_modifer = {1, 0.6, 0.5, 1, 1, }, },
			default_target = {attack_template = "blunt_fencer", boost_curve_type = "tank_curve", power_distribution = {attack = 0.1, impact = 0.1, }, },
			targets = { },
		},
		shield_slam_shotgun_aoe = {
			armor_modifier = {attack = {1, 0, 1, 1, 0.75, }, impact = {1, 0.5, 0.5, 1, 0.75, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, }, impact_armor_power_modifer = {1, 0.6, 0.5, 1, 1, }, },
			default_target = {attack_template = "blunt_fencer", boost_curve_type = "tank_curve", dead_attack_template = "blunt_fencer", power_distribution = {attack = 0, impact = 0.075, }, },
			no_damage = true,
			targets = { },
		},
		shield_slam_target = {
			armor_modifier = {attack = {1, 0.3, 2, 1, 0.75, }, impact = {1, 0.8, 1, 1, 2, 1.25, }, },
			charge_value = "heavy_attack",
			critical_strike = {attack_armor_power_modifer = {1, 0.5, 2, 1, 1, }, impact_armor_power_modifer = {1, 1, 0.5, 1, 1, }, },
			default_target = {attack_template = "heavy_blunt_fencer", boost_curve_type = "tank_curve", power_distribution = {attack = 0.2, impact = 0.375, }, },
			shield_break = true,
			stagger_duration_modifier = 1.75,
			targets = { },
		},
		shot_drakefire = {
			armor_modifier_far = {attack = {1, 0.25, 1, 1, 1, 0, }, impact = {1, 0.25, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.25, 1, 1, 1, 0, }, impact = {1, 0.25, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.15, impact = 0.15, },
			critical_strike = {attack_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.25, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "shot_carbine",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 1,
				boost_curve_type = "linesman_curve",
				power_distribution_far = {attack = 0.15, impact = 0.1, },
				power_distribution_near = {attack = 0.275, impact = 0.25, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 15, },
			},
			dot_template_name = "burning_1W_dot",
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
		shot_machinegun = {
			armor_modifier_far = {attack = {1, 0, 1, 1, 1, 0, }, impact = {1, 0, 1, 1, 1, 0, }, },
			armor_modifier_near = {attack = {1, 0.5, 1, 1, 1, 0, }, impact = {1, 0.5, 1, 1, 1, 0, }, },
			charge_value = "projectile",
			cleave_distribution = {attack = 0.2, impact = 0.2, },
			critical_strike = {attack_armor_power_modifer = {1, 0.75, 1, 1, 1, 0.25, }, impact_armor_power_modifer = {1, 0.75, 1, 1, 1, 0.25, }, },
			default_target = {
				attack_template = "shot_machinegun",
				boost_curve_coefficient = 0.75,
				boost_curve_coefficient_headshot = 1.5,
				boost_curve_type = "ninja_curve",
				power_distribution_far = {attack = 0.175, impact = 0.075, },
				power_distribution_near = {attack = 0.3, impact = 0.175, },
				range_dropoff_settings = {dropoff_end = 30, dropoff_start = 10, },
			},
			no_stagger_damage_reduction_ranged = true,
			targets = { },
		},
	},
}
