-- Source-exact historical weapon metadata; inert until loaded by the history runtime.
return {
	completeness = {
		excluded_function_deltas = {
			["3_0_0_4"] = {
				billhook = {"actions.action_three.default.chain_condition_func (function changed)", },
				empire_longbow = {"actions.action_one.default.condition_func (function changed)", "default_projectile_action.condition_func (function changed)", },
				hammer_and_shield_shared = {"actions.action_one.default_right_bopp (function-bearing value changed)", "actions.action_one.heavy_attack_right (function-bearing value changed)", },
				throwing_axes = {
					"actions.action_one.default.anim_end_event_condition_func (function changed)",
					"actions.action_one.throw_charged.anim_end_event_condition_func (function changed)",
					"default_projectile_action.anim_end_event_condition_func (function changed)",
				},
				war_pick = {"actions.action_one.default_left_sweep (function-bearing value changed)", "actions.action_one.heavy_attack_left_sweep (function-bearing value changed)", },
			},
			["3_1_0"] = {
				empire_longbow = {"actions.action_one.default.condition_func (function changed)", "default_projectile_action.condition_func (function changed)", },
				hammer_and_shield_shared = {"actions.action_one.heavy_attack_right (function-bearing value changed)", },
				throwing_axes = {
					"actions.action_one.default.anim_end_event_condition_func (function changed)",
					"actions.action_one.throw_charged.anim_end_event_condition_func (function changed)",
					"default_projectile_action.anim_end_event_condition_func (function changed)",
				},
				war_pick = {"actions.action_one.default_left_sweep (function-bearing value changed)", "actions.action_one.heavy_attack_left_sweep (function-bearing value changed)", },
			},
		},
		exclusions = {
			"Function-body deltas are recorded by exact source path but never projected.",
			"The adjacent bounty_hunter_shotgun SpreadTemplates delta belongs to the Bounty Hunter career skill, not an equippable player weapon.",
			"The adjacent explosion_bw_unchained_ability_increased_radius delta belongs to Unchained's career skill, not an equippable player weapon.",
		},
		owned_scalar_and_table_data = "source_exact",
	},
	current_source_label = "6.11.3",
	current_source_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
	derived_profile_routes = { },
	era_id = "3_1",
	families = {
		{
			aliases = {"axe_and_falchion", "dual_wield_axe_falchion", },
			id = "axe_and_falchion",
			label = "Saltzpyre's Axe and Falchion",
			setting_id = "wt_history_axe_and_falchion",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_axe_falchion.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_axe_falchion_template", },
		},
		{
			aliases = {"bardin_axe_and_shield", "1h_axes_shield", },
			id = "bardin_axe_and_shield",
			label = "Bardin's Axe and Shield",
			setting_id = "wt_history_bardin_axe_and_shield",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_axes_shield.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_hand_axe_shield_template_1", },
		},
		{
			aliases = {"bardin_two_handed_axe", "2h_axes", },
			id = "bardin_two_handed_axe",
			label = "Bardin's Two-handed Axe",
			setting_id = "wt_history_bardin_two_handed_axe",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_axes.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_axes_template_1", },
		},
		{
			aliases = {"beam_staff", "staff_blast_beam", },
			id = "beam_staff",
			label = "Sienna's Beam Staff",
			setting_id = "wt_history_beam_staff",
			source_paths = {"scripts/settings/equipment/weapon_templates/staff_blast_beam.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"staff_blast_beam_template_1", },
		},
		{
			aliases = {"billhook", "2h_billhooks", },
			id = "billhook",
			label = "Saltzpyre's Billhook",
			setting_id = "wt_history_billhook",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_billhooks.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_billhooks_template", },
		},
		{
			aliases = {"blunderbuss", "blunderbusses", },
			id = "blunderbuss",
			label = "Kruber's Blunderbuss",
			setting_id = "wt_history_blunderbuss",
			source_paths = {"scripts/settings/equipment/weapon_templates/blunderbusses.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"blunderbuss_template_1", },
		},
		{
			aliases = {"drakefire_pistols", "brace_of_drake_pistols", },
			id = "drakefire_pistols",
			label = "Bardin's Drakefire Pistols",
			setting_id = "wt_history_drakefire_pistols",
			source_paths = {"scripts/settings/equipment/weapon_templates/brace_of_drake_pistols.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"brace_of_drakefirepistols_template_1", },
		},
		{
			aliases = {"dual_axes", "dual_wield_axes", },
			id = "dual_axes",
			label = "Bardin's Dual Axes",
			setting_id = "wt_history_dual_axes",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_axes.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_axes_template_1", },
		},
		{
			aliases = {"dual_daggers", "dual_wield_daggers", },
			id = "dual_daggers",
			label = "Kerillian's Dual Daggers",
			setting_id = "wt_history_dual_daggers",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_daggers.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_daggers_template_1", },
		},
		{
			aliases = {"dual_swords", "dual_wield_swords", },
			id = "dual_swords",
			label = "Kerillian's Dual Swords",
			setting_id = "wt_history_dual_swords",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_swords.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_swords_template_1", },
		},
		{
			aliases = {"elf_greatsword", "2h_swords_wood_elf", },
			id = "elf_greatsword",
			label = "Kerillian's Greatsword",
			setting_id = "wt_history_elf_greatsword",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_swords_wood_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_swords_wood_elf_template", },
		},
		{
			aliases = {"elf_one_handed_axe", "1h_axes_wood_elf", },
			id = "elf_one_handed_axe",
			label = "Kerillian's One-handed Axe",
			setting_id = "wt_history_elf_one_handed_axe",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_axes_wood_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"we_one_hand_axe_template", },
		},
		{
			aliases = {"elf_one_handed_sword", "1h_swords_wood_elf", },
			id = "elf_one_handed_sword",
			label = "Kerillian's One-handed Sword",
			setting_id = "wt_history_elf_one_handed_sword",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_swords_wood_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"we_one_hand_sword_template_1", },
		},
		{
			aliases = {"elf_spear", "spears_wood_elf", },
			id = "elf_spear",
			label = "Kerillian's Spear",
			setting_id = "wt_history_elf_spear",
			source_paths = {"scripts/settings/equipment/weapon_templates/spears_wood_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_spears_elf_template_1", },
		},
		{
			aliases = {"elf_spear_and_shield", "1h_spears_shield", },
			id = "elf_spear_and_shield",
			label = "Kerillian's Spear and Shield",
			setting_id = "wt_history_elf_spear_and_shield",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_spears_shield.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_spears_shield_template", },
		},
		{
			aliases = {"empire_longbow", "longbows_empire", },
			id = "empire_longbow",
			label = "Kruber's Longbow",
			setting_id = "wt_history_empire_longbow",
			source_paths = {"scripts/settings/equipment/weapon_templates/longbows_empire.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"longbow_empire_template", },
		},
		{
			aliases = {"executioner_sword", "2h_swords_executioner", },
			id = "executioner_sword",
			label = "Kruber's Executioner Sword",
			setting_id = "wt_history_executioner_sword",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_swords_executioner.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_swords_executioner_template_1", },
		},
		{
			aliases = {"falchion", "1h_falchions", },
			id = "falchion",
			label = "Saltzpyre's Falchion",
			setting_id = "wt_history_falchion",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_falchions.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_hand_falchion_template_1", },
		},
		{
			aliases = {"flaming_flail", "1h_flails_flaming", },
			id = "flaming_flail",
			label = "Sienna's Flaming Flail",
			setting_id = "wt_history_flaming_flail",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_flails_flaming.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_flails_flaming_template", },
		},
		{
			aliases = {"glaive", "2h_axes_wood_elf", },
			id = "glaive",
			label = "Kerillian's Glaive",
			setting_id = "wt_history_glaive",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_axes_wood_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_axes_template_2", },
		},
		{
			aliases = {"grudge_raker", "grudge_raker", },
			id = "grudge_raker",
			label = "Bardin's Grudge-Raker",
			setting_id = "wt_history_grudge_raker",
			source_paths = {"scripts/settings/equipment/weapon_templates/grudge_raker.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"grudge_raker_template_1", },
		},
		{
			aliases = {"halberd", "halberds", },
			id = "halberd",
			label = "Kruber's Halberd",
			setting_id = "wt_history_halberd",
			source_paths = {"scripts/settings/equipment/weapon_templates/halberds.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_halberds_template_1", },
		},
		{
			aliases = {"hammer_and_shield_shared", "1h_hammers_shield", },
			id = "hammer_and_shield_shared",
			label = "Hammer/Mace and Shield (Bardin and Kruber)",
			setting_id = "wt_history_hammer_and_shield_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_hammers_shield.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_hammer_shield_template_1", "one_handed_hammer_shield_template_2", },
		},
		{
			aliases = {"handgun_shared", "handguns", },
			id = "handgun_shared",
			label = "Handgun (Bardin and Kruber)",
			setting_id = "wt_history_handgun_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/handguns.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"handgun_template_1", "handgun_template_2", },
		},
		{
			aliases = {"mace_and_sword", "dual_wield_hammer_sword", },
			id = "mace_and_sword",
			label = "Kruber's Mace and Sword",
			setting_id = "wt_history_mace_and_sword",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_hammer_sword.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_hammer_sword_template", },
		},
		{
			aliases = {"one_handed_axe_shared", "1h_axes", },
			id = "one_handed_axe_shared",
			label = "One-handed Axe (Bardin and Saltzpyre)",
			setting_id = "wt_history_one_handed_axe_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_axes.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_hand_axe_template_1", "one_hand_axe_template_2", },
		},
		{
			aliases = {"one_handed_flail", "1h_flails", },
			id = "one_handed_flail",
			label = "Saltzpyre's Flail",
			setting_id = "wt_history_one_handed_flail",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_flails.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_flail_template_1", },
		},
		{
			aliases = {"one_handed_hammer_shared", "1h_hammers", },
			id = "one_handed_hammer_shared",
			label = "One-handed Hammer/Mace (Bardin and Kruber)",
			setting_id = "wt_history_one_handed_hammer_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_hammers.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_hammer_template_1", "one_handed_hammer_template_2", },
		},
		{
			aliases = {"one_handed_sword_shared", "1h_swords", },
			id = "one_handed_sword_shared",
			label = "One-handed Sword (Kruber and Sienna)",
			setting_id = "wt_history_one_handed_sword_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_swords.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_swords_template_1", },
		},
		{
			aliases = {"repeater_pistol", "repeating_pistols", },
			id = "repeater_pistol",
			label = "Saltzpyre's Repeater Pistol",
			setting_id = "wt_history_repeater_pistol",
			source_paths = {"scripts/settings/equipment/weapon_templates/repeating_pistols.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"repeating_pistol_template_1", },
		},
		{
			aliases = {"saltzpyre_volley_crossbow", "repeating_crossbows", },
			id = "saltzpyre_volley_crossbow",
			label = "Saltzpyre's Volley Crossbow",
			setting_id = "wt_history_saltzpyre_volley_crossbow",
			source_paths = {"scripts/settings/equipment/weapon_templates/repeating_crossbows.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"repeating_crossbow_template_1", },
		},
		{
			aliases = {"shade_volley_crossbow", "repeating_crossbows_elf", },
			id = "shade_volley_crossbow",
			label = "Kerillian's Volley Crossbow",
			setting_id = "wt_history_shade_volley_crossbow",
			source_paths = {"scripts/settings/equipment/weapon_templates/repeating_crossbows_elf.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"repeating_crossbow_elf_template", },
		},
		{
			aliases = {"sienna_dagger", "1h_dagger_wizard", },
			id = "sienna_dagger",
			label = "Sienna's Dagger",
			setting_id = "wt_history_sienna_dagger",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_dagger_wizard.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_daggers_template_1", },
		},
		{
			aliases = {"sienna_mace", "1h_hammers_wizard", },
			id = "sienna_mace",
			label = "Sienna's Mace",
			setting_id = "wt_history_sienna_mace",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_hammers_wizard.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_hammer_wizard_template_1", },
		},
		{
			aliases = {"swiftbow", "shortbows", },
			id = "swiftbow",
			label = "Kerillian's Swift Bow",
			setting_id = "wt_history_swiftbow",
			source_paths = {"scripts/settings/equipment/weapon_templates/shortbows.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"shortbow_template_1", },
		},
		{
			aliases = {"sword_and_dagger", "dual_wield_sword_dagger", },
			id = "sword_and_dagger",
			label = "Kerillian's Sword and Dagger",
			setting_id = "wt_history_sword_and_dagger",
			source_paths = {"scripts/settings/equipment/weapon_templates/dual_wield_sword_dagger.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"dual_wield_sword_dagger_template_1", },
		},
		{
			aliases = {"throwing_axes", "1h_throwing_axes", },
			id = "throwing_axes",
			label = "Bardin's Throwing Axes",
			setting_id = "wt_history_throwing_axes",
			source_paths = {"scripts/settings/equipment/weapon_templates/1h_throwing_axes.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"one_handed_throwing_axes_template", },
		},
		{
			aliases = {"tuskgor_spear", "2h_heavy_spears", },
			id = "tuskgor_spear",
			label = "Kruber's Tuskgor Spear",
			setting_id = "wt_history_tuskgor_spear",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_heavy_spears.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_heavy_spears_template", },
		},
		{
			aliases = {"two_handed_hammer_shared", "2h_hammers", },
			id = "two_handed_hammer_shared",
			label = "Two-handed Hammer (Bardin and Kruber)",
			setting_id = "wt_history_two_handed_hammer_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_hammers.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_hammers_template_1", },
		},
		{
			aliases = {"two_handed_sword_shared", "2h_swords", },
			id = "two_handed_sword_shared",
			label = "Two-handed Sword (Kruber and Saltzpyre)",
			setting_id = "wt_history_two_handed_sword_shared",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_swords.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_swords_template_1", },
		},
		{
			aliases = {"war_pick", "2h_picks", },
			id = "war_pick",
			label = "Bardin's War Pick",
			setting_id = "wt_history_war_pick",
			source_paths = {"scripts/settings/equipment/weapon_templates/2h_picks.lua", },
			states = {"3_0_0_4", "3_1_0", },
			templates = {"two_handed_picks_template_1", },
		},
	},
	global_records = {
		["3_0_0_4"] = {
			{
				expected_current = 4.62,
				expected_current_unset = false,
				family_id = "beam_staff",
				path = {"overcharge_values", "shotgun", },
				root = "PlayerUnitStatusSettings",
				source_path = "scripts/settings/player_unit_status_settings.lua",
				unset = true,
			},
		},
		["3_1_0"] = { },
	},
	live_game_label = "6.12.0",
	private_profile_contract = {
		fallback_registry = "mod._wt431_custom_profile_fallback",
		key_format = "wt_hist_<state_id>_<native_profile_name>",
		parity_guard = "wt431_damage_profile_parity",
		register = "unconditionally_at_load",
		remap = "selected_family_references_only",
	},
	profile_routes = {
		["3_0_0_4"] = {
			axe_and_falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_smiter", "light_slashing_smiter_dual", "light_slashing_smiter_flat", "medium_push", },
			bardin_axe_and_shield = {
				"light_slashing_smiter",
				"light_slashing_smiter_diag",
				"light_slashing_smiter_upper",
				"medium_push",
				"medium_slashing_smiter_1h",
				"medium_slashing_tank_1h",
				"shield_push",
				"shield_slam",
				"shield_slam_aoe",
				"shield_slam_target",
			},
			bardin_two_handed_axe = {"heavy_slashing_axe_linesman", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", },
			beam_staff = {"beam", "beam_initial", "beam_shot", "blast", },
			billhook = {"heavy_slashing_smiter_polearm", "heavy_slashing_smiter_stab_polearm", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab", },
			blunderbuss = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			drakefire_pistols = {"blast", "shot_drakefire", },
			dual_axes = {"light_push", "light_slashing_smiter_diag_dual_L", "light_slashing_smiter_dual", "light_slashing_smiter_dual_bopp", "medium_push", },
			dual_daggers = {"light_fencer_stab", "light_fencer_stab_diag", "light_push", "light_slashing_smiter_stab_dual", },
			dual_swords = {"light_push", "light_slashing_linesman_dual", "light_slashing_linesman_dual_medium", "light_slashing_smiter_stab", "medium_push", },
			elf_greatsword = {"heavy_slashing_linesman_executioner", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_linesman", },
			elf_one_handed_axe = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h", },
			elf_one_handed_sword = {"light_push", "light_slashing_linesman_elf", "light_slashing_smiter_stab", "medium_push", "medium_slashing_axe_linesman_1h", "medium_slashing_smiter_1h", },
			elf_spear = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab", },
			elf_spear_and_shield = {"heavy_slashing_smiter", "light_slashing_smiter_stab", "medium_push", "medium_slashing_smiter_stab_1h", "medium_slashing_tank_1h", "shield_push", },
			empire_longbow = {"arrow_carbine", "arrow_sniper_kruber", "longbow_empire", },
			executioner_sword = {"heavy_slashing_smiter_executioner", "light_push", "medium_push", "medium_slashing_linesman_executioner", },
			falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_axe_linesman_upper", "light_slashing_smiter", "medium_push", "medium_slashing_axe_linesman_1h", },
			flaming_flail = {"flaming_flail_explosion", "heavy_blunt_smiter_burn", "light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			glaive = {"heavy_slashing_smiter_glaive", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_upper", },
			grudge_raker = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			halberd = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", "medium_slashing_smiter_stab", },
			hammer_and_shield_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "medium_blunt_tank_1h", "medium_push", "shield_push", "shield_slam", "shield_slam_aoe", "shield_slam_target", },
			handgun_shared = {"shot_sniper", },
			mace_and_sword = {"light_blunt_tank_spiked", "light_push", "light_slashing_axe_linesman", "medium_blunt_tank_dual", "medium_push", "medium_slashing_axe_linesman_dual", },
			one_handed_axe_shared = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h", },
			one_handed_flail = {"light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			one_handed_hammer_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_1h", "medium_push", },
			one_handed_sword_shared = {"light_push", "light_slashing_linesman", "light_slashing_linesman_flat", "light_slashing_smiter", "medium_push", "medium_slashing_linesman", "medium_slashing_tank_1h", },
			repeater_pistol = {"shot_machinegun", "shot_machinegun_shotgun", },
			saltzpyre_volley_crossbow = {"crossbow_bolt_repeating", },
			shade_volley_crossbow = {"crossbow_bolt_repeating", },
			sienna_dagger = {"dagger_burning_slam_fencer", "dagger_burning_slam_fencer_aoe", "dagger_burning_slam_target_fencer", "light_fencer_stab", "light_push", "light_slashing_linesman_fencer", "medium_burning_smiter_stab_H", },
			sienna_mace = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_burn", "medium_blunt_tank_upper_1h", "medium_push", },
			swiftbow = {"arrow_carbine", "arrow_machinegun", },
			sword_and_dagger = {"light_fencer_stab_diag", "light_push", "light_slashing_linesman_dual", "light_slashing_linesman_dual_medium", "light_slashing_smiter_stab", "light_slashing_smiter_stab_dual", "medium_push", },
			throwing_axes = {"throwing_axe", "throwing_axe_charged", },
			tuskgor_spear = {"heavy_slashing_smiter_stab_polearm", "heavy_slashing_tank", "light_push", "medium_push", "medium_slashing_linesman_spear", "medium_spear_smiter_stab", },
			two_handed_hammer_shared = {"heavy_blunt_tank", "light_push", "medium_blunt_smiter_2h_hammer", "medium_blunt_smiter_2h_hammer_diag", "medium_blunt_smiter_2h_hammer_upper", "medium_push", },
			two_handed_sword_shared = {"heavy_slashing_linesman", "light_push", "medium_push", "medium_slashing_linesman", "medium_slashing_smiter_2h", },
			war_pick = {"heavy_blunt_smiter_charged", "heavy_blunt_smiter_pick", "light_push", "medium_blunt_smiter_flat_2h", "medium_blunt_tank", "medium_push", },
		},
		["3_1_0"] = {
			axe_and_falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_smiter", "light_slashing_smiter_dual", "light_slashing_smiter_flat", "medium_push", },
			bardin_axe_and_shield = {
				"light_slashing_smiter",
				"light_slashing_smiter_diag",
				"light_slashing_smiter_upper",
				"medium_push",
				"medium_slashing_smiter_1h",
				"medium_slashing_tank_1h",
				"shield_push",
				"shield_slam",
				"shield_slam_aoe",
				"shield_slam_target",
			},
			bardin_two_handed_axe = {"heavy_slashing_axe_linesman", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", },
			beam_staff = {"beam", "beam_initial", "beam_shot", "blast", },
			billhook = {"heavy_slashing_smiter_polearm", "heavy_slashing_smiter_stab_polearm", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab", },
			blunderbuss = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			drakefire_pistols = {"blast", "shot_drakefire", },
			dual_axes = {"light_push", "light_slashing_smiter_diag_dual_L", "light_slashing_smiter_dual", "light_slashing_smiter_dual_bopp", "medium_push", },
			dual_daggers = {"light_fencer_stab", "light_fencer_stab_diag", "light_push", "light_slashing_smiter_stab_dual", },
			dual_swords = {"light_push", "light_slashing_linesman_dual_medium", "light_slashing_linesman_dual_swords", "light_slashing_smiter_stab", "medium_push", },
			elf_greatsword = {"heavy_slashing_linesman_executioner", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_linesman", },
			elf_one_handed_axe = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h_axe", },
			elf_one_handed_sword = {"light_push", "light_slashing_linesman_elf", "light_slashing_smiter_stab_swords", "medium_pointy_smiter_upper_1h", "medium_push", "medium_slashing_smiter_1h", },
			elf_spear = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab_elf", },
			elf_spear_and_shield = {"heavy_slashing_smiter", "light_slashing_smiter_stab", "medium_push", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab_1h", "medium_slashing_tank_1h", "shield_push", },
			empire_longbow = {"arrow_carbine", "arrow_sniper_kruber", "longbow_empire", },
			executioner_sword = {"heavy_slashing_smiter_executioner", "light_push", "medium_push", "medium_slashing_linesman_executioner", },
			falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_axe_linesman_upper", "medium_push", "medium_slashing_smiter_1h", },
			flaming_flail = {"heavy_blunt_smiter_burn", "light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			glaive = {"heavy_slashing_smiter_glaive", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_upper", },
			grudge_raker = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			halberd = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", "medium_slashing_smiter_stab", },
			hammer_and_shield_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "medium_blunt_tank_1h", "medium_push", "shield_push", "shield_slam", "shield_slam_aoe", "shield_slam_target", },
			handgun_shared = {"shot_sniper", },
			mace_and_sword = {"light_blunt_tank_diag", "light_blunt_tank_spiked", "light_push", "light_slashing_axe_linesman", "light_slashing_linesman", "medium_push", "medium_slashing_axe_linesman_1h", },
			one_handed_axe_shared = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h_axe", },
			one_handed_flail = {"light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			one_handed_hammer_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_push", "medium_blunt_smiter_1h", "medium_push", },
			one_handed_sword_shared = {"light_push", "light_slashing_linesman_finesse", "light_slashing_smiter_finesse", "medium_push", "medium_slashing_linesman_finesse", "medium_slashing_tank_1h_finesse", },
			repeater_pistol = {"shot_machinegun", "shot_machinegun_shotgun", },
			saltzpyre_volley_crossbow = {"crossbow_bolt_repeating", },
			shade_volley_crossbow = {"crossbow_bolt_repeating", },
			sienna_dagger = {"dagger_burning_slam_fencer", "dagger_burning_slam_fencer_aoe", "dagger_burning_slam_target_fencer", "light_fencer_stab", "light_push", "light_slashing_linesman_fencer", "medium_burning_smiter_stab_H", },
			sienna_mace = {"light_blunt_smiter", "light_blunt_tank", "light_push", "medium_blunt_smiter_heavy", "medium_blunt_tank_upper_1h", "medium_push", },
			swiftbow = {"arrow_carbine", "arrow_carbine_shortbow", "arrow_machinegun", },
			sword_and_dagger = {"light_fencer_stab_diag", "light_push", "light_slashing_linesman_dual", "light_slashing_linesman_dual_medium", "light_slashing_smiter_stab", "light_slashing_smiter_stab_dual", "medium_push", },
			throwing_axes = {"throwing_axe", "throwing_axe_charged", },
			tuskgor_spear = {"heavy_slashing_smiter_stab_polearm", "heavy_slashing_tank", "light_push", "medium_push", "medium_slashing_linesman_spear", "medium_spear_smiter_stab", },
			two_handed_hammer_shared = {"heavy_blunt_tank", "heavy_blunt_tank_light", "light_push", "medium_blunt_smiter_2h_hammer", "medium_blunt_smiter_2h_hammer_upper", "medium_push", },
			two_handed_sword_shared = {"heavy_slashing_linesman", "light_push", "medium_push", "medium_slashing_linesman", "medium_slashing_smiter_2h", },
			war_pick = {"heavy_blunt_smiter_charged", "heavy_blunt_smiter_pick", "light_push", "medium_blunt_smiter_flat_2h", "medium_blunt_tank", "medium_push", },
		},
	},
	provenance = {
		artifact_sha256 = {
			_wt_history_profiles_3_0_0_4_part_01_generated = "7890984b92774294d38db99d1becf326920f4b45cde7355270d206aebec7cf81",
			_wt_history_profiles_3_0_0_4_part_02_generated = "77e3ebd9c163ee004623b021cec4ca5083a42e78e4be669dcd24df32dab49978",
			_wt_history_profiles_3_1_0_part_01_generated = "6caea7813d905231efe969f0b4ef3d4856ddcab96aee090b0a7fa3423ec46ec8",
			_wt_history_profiles_3_1_0_part_02_generated = "e94d7285c9a3f0a8b178c8b6696f6b249d8547af93ecc3c4e56bef27b31d9584",
			_wt_history_snapshot_3_0_0_4_part_01_generated = "ddf06803e8e78719272a9fbcc00212a6d8119ee6f96af86498ca140dce9d2b95",
			_wt_history_snapshot_3_0_0_4_part_02_generated = "ef3caf890df92ce568511b6e5a37a805b7cbfad7d4b7a25e6f8bd7e03c9ecdac",
			_wt_history_snapshot_3_0_0_4_part_03_generated = "022e20e0b38c31397eda845857945c6c63fca9a28c4c4ac57cd94fd40d8fe4d5",
			_wt_history_snapshot_3_0_0_4_part_04_generated = "f2ee1546d62b0c00e19dffc5716794b3f8dbb3fd02c46732b1ccde4799e409bb",
			_wt_history_snapshot_3_1_0_part_01_generated = "e08028795a68450482de96fb62f886607a6c72e635c7c293ff2ff5535fd918e2",
			_wt_history_snapshot_3_1_0_part_02_generated = "fcb54d2ebdd9e807a95598f789521e5c04001c7d8eb5ff1ed2630703d105e64b",
			_wt_history_snapshot_3_1_0_part_03_generated = "b0afcc52f29e5e3ed5418d3ceeae86e2ca19a9eb6f739d1323d1167327dedc72",
		},
		direct_projection = true,
		official_patch_notes = "https://forums.fatsharkgames.com/t/vermintide-2-patch-3-1/41271",
		source_repository = "Aussiemon/Vermintide-2-Source-Code",
	},
	schema = 1,
	state_order = {"3_0_0_4", "3_1_0", },
	states = {
		["3_0_0_4"] = {
			direct_to_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
			label = "Patch 3.0.0.4 (Pre-3.1)",
			profile_modules = {"scripts/mods/weapon_tweaker/_wt_history_profiles_3_0_0_4_part_01_generated", "scripts/mods/weapon_tweaker/_wt_history_profiles_3_0_0_4_part_02_generated", },
			revision = "c96aa3858011ecd557d55d80b66fe3bb8342eeb2",
			snapshot_modules = {
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_0_0_4_part_01_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_0_0_4_part_02_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_0_0_4_part_03_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_0_0_4_part_04_generated",
			},
			version_settings = "3.0.0",
		},
		["3_1_0"] = {
			direct_to_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
			label = "Patch 3.1",
			profile_modules = {"scripts/mods/weapon_tweaker/_wt_history_profiles_3_1_0_part_01_generated", "scripts/mods/weapon_tweaker/_wt_history_profiles_3_1_0_part_02_generated", },
			revision = "3f0e3ba442d8dcafb8b5f829ff6c2a95ae24ae63",
			snapshot_modules = {
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_1_0_part_01_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_1_0_part_02_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_3_1_0_part_03_generated",
			},
			version_settings = "3.1.0",
		},
	},
	template_families = {
		blunderbuss_template_1 = "blunderbuss",
		brace_of_drakefirepistols_template_1 = "drakefire_pistols",
		dual_wield_axe_falchion_template = "axe_and_falchion",
		dual_wield_axes_template_1 = "dual_axes",
		dual_wield_daggers_template_1 = "dual_daggers",
		dual_wield_hammer_sword_template = "mace_and_sword",
		dual_wield_sword_dagger_template_1 = "sword_and_dagger",
		dual_wield_swords_template_1 = "dual_swords",
		grudge_raker_template_1 = "grudge_raker",
		handgun_template_1 = "handgun_shared",
		handgun_template_2 = "handgun_shared",
		longbow_empire_template = "empire_longbow",
		one_hand_axe_shield_template_1 = "bardin_axe_and_shield",
		one_hand_axe_template_1 = "one_handed_axe_shared",
		one_hand_axe_template_2 = "one_handed_axe_shared",
		one_hand_falchion_template_1 = "falchion",
		one_handed_daggers_template_1 = "sienna_dagger",
		one_handed_flail_template_1 = "one_handed_flail",
		one_handed_flails_flaming_template = "flaming_flail",
		one_handed_hammer_shield_template_1 = "hammer_and_shield_shared",
		one_handed_hammer_shield_template_2 = "hammer_and_shield_shared",
		one_handed_hammer_template_1 = "one_handed_hammer_shared",
		one_handed_hammer_template_2 = "one_handed_hammer_shared",
		one_handed_hammer_wizard_template_1 = "sienna_mace",
		one_handed_spears_shield_template = "elf_spear_and_shield",
		one_handed_swords_template_1 = "one_handed_sword_shared",
		one_handed_throwing_axes_template = "throwing_axes",
		repeating_crossbow_elf_template = "shade_volley_crossbow",
		repeating_crossbow_template_1 = "saltzpyre_volley_crossbow",
		repeating_pistol_template_1 = "repeater_pistol",
		shortbow_template_1 = "swiftbow",
		staff_blast_beam_template_1 = "beam_staff",
		two_handed_axes_template_1 = "bardin_two_handed_axe",
		two_handed_axes_template_2 = "glaive",
		two_handed_billhooks_template = "billhook",
		two_handed_halberds_template_1 = "halberd",
		two_handed_hammers_template_1 = "two_handed_hammer_shared",
		two_handed_heavy_spears_template = "tuskgor_spear",
		two_handed_picks_template_1 = "war_pick",
		two_handed_spears_elf_template_1 = "elf_spear",
		two_handed_swords_executioner_template_1 = "executioner_sword",
		two_handed_swords_template_1 = "two_handed_sword_shared",
		two_handed_swords_wood_elf_template = "elf_greatsword",
		we_one_hand_axe_template = "elf_one_handed_axe",
		we_one_hand_sword_template_1 = "elf_one_handed_sword",
	},
}
