-- Source-exact historical weapon metadata; inert until loaded by the history runtime.
return {
	completeness = {
		excluded_function_deltas = {
			["1_2_2"] = {
				bardin_axe_and_shield = {"actions.action_two.default.enter_function (function changed)", },
				bardin_two_handed_axe = {"actions.action_two.default.enter_function (function changed)", },
				brace_of_pistols = {
					"actions.action_one.special_action_shoot (function-bearing value changed)",
					"actions.action_three (function-bearing value changed)",
					"actions.action_two.default.condition_func (function changed)",
					"actions.weapon_reload (function-bearing value changed)",
				},
				burning_sword = {"actions.action_one.heavy_attack_right (function-bearing value changed)", "actions.action_one.light_attack_spell (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				drakefire_pistols = {"actions.weapon_reload.default.enter_function (function changed)", },
				dual_axes = {
					"actions.action_one.default_down (function-bearing value changed)",
					"actions.action_one.default_left_down (function-bearing value changed)",
					"actions.action_one.default_right_down (function-bearing value changed)",
					"actions.action_one.light_attack_down (function-bearing value changed)",
					"actions.action_one.light_attack_down_left (function-bearing value changed)",
					"actions.action_one.light_attack_down_right (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				dual_daggers = {"actions.action_one.light_attack_stab (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				dual_swords = {"actions.action_two.default.enter_function (function changed)", },
				elf_greatsword = {"actions.action_two.default.enter_function (function changed)", },
				elf_one_handed_sword = {"actions.action_two.default.enter_function (function changed)", },
				elf_spear = {"actions.action_one.default_right (function-bearing value changed)", "actions.action_one.light_attack_stab (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				empire_longbow = {"actions.action_one.default.condition_func (function changed)", "default_projectile_action.condition_func (function changed)", },
				executioner_sword = {"actions.action_one.default_right_diagonal (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				falchion = {"actions.action_one.default_up (function-bearing value changed)", "actions.action_one.light_attack_up (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				glaive = {"actions.action_two.default.enter_function (function changed)", },
				halberd = {"actions.action_two.default.enter_function (function changed)", },
				hammer_and_shield_shared = {
					"actions.action_one.default_right_bopp (function-bearing value changed)",
					"actions.action_one.default_right_heavy (function-bearing value changed)",
					"actions.action_one.heavy_attack_right (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				kruber_sword_and_shield = {
					"actions.action_one.default_right_heavy (function-bearing value changed)",
					"actions.action_one.heavy_attack_left (function-bearing value changed)",
					"actions.action_one.light_attack_stab (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				one_handed_axe_shared = {"actions.action_one.default_last (function-bearing value changed)", "actions.action_one.light_attack_down (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				one_handed_flail = {"actions.action_two.default.enter_function (function changed)", },
				one_handed_hammer_shared = {"actions.action_two.default.enter_function (function changed)", },
				one_handed_sword_shared = {"actions.action_two.default.enter_function (function changed)", },
				rapier = {"actions.action_two.default.enter_function (function changed)", },
				repeater_handgun = {"actions.action_one.bullet_spray.enter_function (function changed)", "actions.action_two.default.enter_function (function changed)", "actions.action_two.spray_loop (function-bearing value changed)", },
				sienna_dagger = {"actions.action_two.default.enter_function (function changed)", },
				sienna_mace = {"actions.action_two.default.enter_function (function changed)", },
				sword_and_dagger = {"actions.action_two.default.enter_function (function changed)", },
				two_handed_hammer_shared = {"actions.action_two.default.enter_function (function changed)", },
				two_handed_sword_shared = {"actions.action_two.default.enter_function (function changed)", },
				war_pick = {"actions.action_one.default_left_sweep (function-bearing value changed)", "actions.action_one.heavy_attack_left_sweep (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
			},
			["1_3_0"] = {
				bardin_axe_and_shield = {"actions.action_two.default.enter_function (function changed)", },
				bardin_two_handed_axe = {"actions.action_two.default.enter_function (function changed)", },
				brace_of_pistols = {
					"actions.action_one.special_action_shoot (function-bearing value changed)",
					"actions.action_three (function-bearing value changed)",
					"actions.action_two.default.condition_func (function changed)",
					"actions.weapon_reload (function-bearing value changed)",
				},
				burning_sword = {"actions.action_one.heavy_attack_right (function-bearing value changed)", "actions.action_one.light_attack_spell (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				drakefire_pistols = {"actions.weapon_reload.default.enter_function (function changed)", },
				dual_axes = {
					"actions.action_one.default_down (function-bearing value changed)",
					"actions.action_one.default_left_down (function-bearing value changed)",
					"actions.action_one.default_right_down (function-bearing value changed)",
					"actions.action_one.light_attack_down (function-bearing value changed)",
					"actions.action_one.light_attack_down_left (function-bearing value changed)",
					"actions.action_one.light_attack_down_right (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				dual_daggers = {"actions.action_one.light_attack_stab (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				dual_swords = {"actions.action_two.default.enter_function (function changed)", },
				elf_greatsword = {"actions.action_two.default.enter_function (function changed)", },
				elf_one_handed_sword = {"actions.action_two.default.enter_function (function changed)", },
				elf_spear = {"actions.action_one.default_right (function-bearing value changed)", "actions.action_one.light_attack_stab (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				empire_longbow = {"actions.action_one.default.condition_func (function changed)", "default_projectile_action.condition_func (function changed)", },
				executioner_sword = {"actions.action_one.default_right_diagonal (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				falchion = {"actions.action_one.default_up (function-bearing value changed)", "actions.action_one.light_attack_up (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				glaive = {"actions.action_two.default.enter_function (function changed)", },
				halberd = {"actions.action_two.default.enter_function (function changed)", },
				hammer_and_shield_shared = {
					"actions.action_one.default_right_bopp (function-bearing value changed)",
					"actions.action_one.default_right_heavy (function-bearing value changed)",
					"actions.action_one.heavy_attack_right (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				kruber_sword_and_shield = {
					"actions.action_one.default_right_heavy (function-bearing value changed)",
					"actions.action_one.heavy_attack_left (function-bearing value changed)",
					"actions.action_one.light_attack_stab (function-bearing value changed)",
					"actions.action_two.default.enter_function (function changed)",
				},
				one_handed_axe_shared = {"actions.action_one.default_last (function-bearing value changed)", "actions.action_one.light_attack_down (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
				one_handed_flail = {"actions.action_two.default.enter_function (function changed)", },
				one_handed_hammer_shared = {"actions.action_two.default.enter_function (function changed)", },
				one_handed_sword_shared = {"actions.action_two.default.enter_function (function changed)", },
				rapier = {"actions.action_two.default.enter_function (function changed)", },
				repeater_handgun = {"actions.action_one.bullet_spray.enter_function (function changed)", "actions.action_two.default.enter_function (function changed)", "actions.action_two.spray_loop (function-bearing value changed)", },
				sienna_dagger = {"actions.action_two.default.enter_function (function changed)", },
				sienna_mace = {"actions.action_two.default.enter_function (function changed)", },
				sword_and_dagger = {"actions.action_two.default.enter_function (function changed)", },
				two_handed_hammer_shared = {"actions.action_two.default.enter_function (function changed)", },
				two_handed_sword_shared = {"actions.action_two.default.enter_function (function changed)", },
				war_pick = {"actions.action_one.default_left_sweep (function-bearing value changed)", "actions.action_one.heavy_attack_left_sweep (function-bearing value changed)", "actions.action_two.default.enter_function (function changed)", },
			},
		},
		exclusions = {
			"Function-body deltas are recorded by exact source path but never projected.",
			"General combat, temporary-health, trait, career, enemy, and action-extension changes are outside per-weapon selector ownership.",
			"The historical shared Handgun template is projected to both current Kruber and Bardin Handgun templates; their current gameplay fields are cloned from the same source and differ only on excluded presentation roots.",
		},
		owned_scalar_and_table_data = "source_exact",
	},
	current_source_label = "6.11.3",
	current_source_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
	derived_profile_routes = { },
	era_id = "1_3",
	families = {
		{
			aliases = {"bardin_axe_and_shield", "1h_axes_shield", },
			id = "bardin_axe_and_shield",
			label = "Bardin's Axe and Shield",
			setting_id = "wt_history_bardin_axe_and_shield",
			source_paths = {"scripts/settings/equipment/1h_axes_shield.lua", "scripts/settings/equipment/weapon_templates/1h_axes_shield.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_hand_axe_shield_template_1", },
		},
		{
			aliases = {"bardin_two_handed_axe", "2h_axes", },
			id = "bardin_two_handed_axe",
			label = "Bardin's Two-handed Axe",
			setting_id = "wt_history_bardin_two_handed_axe",
			source_paths = {"scripts/settings/equipment/2h_axes.lua", "scripts/settings/equipment/weapon_templates/2h_axes.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_axes_template_1", },
		},
		{
			aliases = {"blunderbuss", "blunderbusses", },
			id = "blunderbuss",
			label = "Kruber's Blunderbuss",
			setting_id = "wt_history_blunderbuss",
			source_paths = {"scripts/settings/equipment/blunderbusses.lua", "scripts/settings/equipment/weapon_templates/blunderbusses.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"blunderbuss_template_1", },
		},
		{
			aliases = {"brace_of_pistols", "brace_of_pistols", },
			id = "brace_of_pistols",
			label = "Saltzpyre's Brace of Pistols",
			setting_id = "wt_history_brace_of_pistols",
			source_paths = {"scripts/settings/equipment/brace_of_pistols.lua", "scripts/settings/equipment/weapon_templates/brace_of_pistols.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"brace_of_pistols_template_1", },
		},
		{
			aliases = {"burning_sword", "1h_swords_flaming_spell", },
			id = "burning_sword",
			label = "Sienna's Burning Sword",
			setting_id = "wt_history_burning_sword",
			source_paths = {"scripts/settings/equipment/1h_swords_flaming_spell.lua", "scripts/settings/equipment/weapon_templates/1h_swords_flaming_spell.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"flaming_sword_spell_template_1", },
		},
		{
			aliases = {"crossbow_shared", "crossbows", },
			id = "crossbow_shared",
			label = "Crossbow (Bardin and Saltzpyre)",
			setting_id = "wt_history_crossbow_shared",
			source_paths = {"scripts/settings/equipment/crossbows.lua", "scripts/settings/equipment/weapon_templates/crossbows.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"crossbow_template_1", },
		},
		{
			aliases = {"drakefire_pistols", "brace_of_drake_pistols", },
			id = "drakefire_pistols",
			label = "Bardin's Drakefire Pistols",
			setting_id = "wt_history_drakefire_pistols",
			source_paths = {"scripts/settings/equipment/brace_of_drake_pistols.lua", "scripts/settings/equipment/weapon_templates/brace_of_drake_pistols.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"brace_of_drakefirepistols_template_1", },
		},
		{
			aliases = {"drakegun", "drakegun", },
			id = "drakegun",
			label = "Bardin's Drakegun",
			setting_id = "wt_history_drakegun",
			source_paths = {"scripts/settings/equipment/drakegun.lua", "scripts/settings/equipment/weapon_templates/drakegun.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"drakegun_template_1", },
		},
		{
			aliases = {"dual_axes", "dual_wield_axes", },
			id = "dual_axes",
			label = "Bardin's Dual Axes",
			setting_id = "wt_history_dual_axes",
			source_paths = {"scripts/settings/equipment/dual_wield_axes.lua", "scripts/settings/equipment/weapon_templates/dual_wield_axes.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"dual_wield_axes_template_1", },
		},
		{
			aliases = {"dual_daggers", "dual_wield_daggers", },
			id = "dual_daggers",
			label = "Kerillian's Dual Daggers",
			setting_id = "wt_history_dual_daggers",
			source_paths = {"scripts/settings/equipment/dual_wield_daggers.lua", "scripts/settings/equipment/weapon_templates/dual_wield_daggers.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"dual_wield_daggers_template_1", },
		},
		{
			aliases = {"dual_swords", "dual_wield_swords", },
			id = "dual_swords",
			label = "Kerillian's Dual Swords",
			setting_id = "wt_history_dual_swords",
			source_paths = {"scripts/settings/equipment/dual_wield_swords.lua", "scripts/settings/equipment/weapon_templates/dual_wield_swords.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"dual_wield_swords_template_1", },
		},
		{
			aliases = {"elf_greatsword", "2h_swords_wood_elf", },
			id = "elf_greatsword",
			label = "Kerillian's Greatsword",
			setting_id = "wt_history_elf_greatsword",
			source_paths = {"scripts/settings/equipment/2h_swords_wood_elf.lua", "scripts/settings/equipment/weapon_templates/2h_swords_wood_elf.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_swords_wood_elf_template", },
		},
		{
			aliases = {"elf_one_handed_sword", "1h_swords_wood_elf", },
			id = "elf_one_handed_sword",
			label = "Kerillian's One-handed Sword",
			setting_id = "wt_history_elf_one_handed_sword",
			source_paths = {"scripts/settings/equipment/1h_swords_wood_elf.lua", "scripts/settings/equipment/weapon_templates/1h_swords_wood_elf.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"we_one_hand_sword_template_1", },
		},
		{
			aliases = {"elf_spear", "spears_wood_elf", },
			id = "elf_spear",
			label = "Kerillian's Spear",
			setting_id = "wt_history_elf_spear",
			source_paths = {"scripts/settings/equipment/spears_wood_elf.lua", "scripts/settings/equipment/weapon_templates/spears_wood_elf.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_spears_elf_template_1", },
		},
		{
			aliases = {"empire_longbow", "longbows_empire", },
			id = "empire_longbow",
			label = "Kruber's Longbow",
			setting_id = "wt_history_empire_longbow",
			source_paths = {"scripts/settings/equipment/longbows_empire.lua", "scripts/settings/equipment/weapon_templates/longbows_empire.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"longbow_empire_template", },
		},
		{
			aliases = {"executioner_sword", "2h_swords_executioner", },
			id = "executioner_sword",
			label = "Kruber's Executioner Sword",
			setting_id = "wt_history_executioner_sword",
			source_paths = {"scripts/settings/equipment/2h_swords_executioner.lua", "scripts/settings/equipment/weapon_templates/2h_swords_executioner.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_swords_executioner_template_1", },
		},
		{
			aliases = {"falchion", "1h_falchions", },
			id = "falchion",
			label = "Saltzpyre's Falchion",
			setting_id = "wt_history_falchion",
			source_paths = {"scripts/settings/equipment/1h_falchions.lua", "scripts/settings/equipment/weapon_templates/1h_falchions.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_hand_falchion_template_1", },
		},
		{
			aliases = {"flamestorm_staff", "staff_firefly_flamewave", },
			id = "flamestorm_staff",
			label = "Sienna's Flamestorm Staff",
			setting_id = "wt_history_flamestorm_staff",
			source_paths = {"scripts/settings/equipment/staff_firefly_flamewave.lua", "scripts/settings/equipment/weapon_templates/staff_flamethrower.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"staff_flamethrower_template", },
		},
		{
			aliases = {"glaive", "2h_axes_wood_elf", },
			id = "glaive",
			label = "Kerillian's Glaive",
			setting_id = "wt_history_glaive",
			source_paths = {"scripts/settings/equipment/2h_axes_wood_elf.lua", "scripts/settings/equipment/weapon_templates/2h_axes_wood_elf.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_axes_template_2", },
		},
		{
			aliases = {"grudge_raker", "grudge_raker", },
			id = "grudge_raker",
			label = "Bardin's Grudge-Raker",
			setting_id = "wt_history_grudge_raker",
			source_paths = {"scripts/settings/equipment/grudge_raker.lua", "scripts/settings/equipment/weapon_templates/grudge_raker.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"grudge_raker_template_1", },
		},
		{
			aliases = {"halberd", "halberds", },
			id = "halberd",
			label = "Kruber's Halberd",
			setting_id = "wt_history_halberd",
			source_paths = {"scripts/settings/equipment/halberds.lua", "scripts/settings/equipment/weapon_templates/halberds.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_halberds_template_1", },
		},
		{
			aliases = {"hammer_and_shield_shared", "1h_hammers_shield", },
			id = "hammer_and_shield_shared",
			label = "Hammer/Mace and Shield (Bardin and Kruber)",
			setting_id = "wt_history_hammer_and_shield_shared",
			source_paths = {"scripts/settings/equipment/1h_hammers_shield.lua", "scripts/settings/equipment/weapon_templates/1h_hammers_shield.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_hammer_shield_template_1", "one_handed_hammer_shield_template_2", },
		},
		{
			aliases = {"handgun_shared", "handguns", },
			id = "handgun_shared",
			label = "Handgun (Bardin and Kruber)",
			setting_id = "wt_history_handgun_shared",
			source_paths = {"scripts/settings/equipment/handguns.lua", "scripts/settings/equipment/weapon_templates/handguns.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"handgun_template_1", "handgun_template_2", },
		},
		{
			aliases = {"kruber_sword_and_shield", "1h_swords_shield", },
			id = "kruber_sword_and_shield",
			label = "Kruber's Sword and Shield",
			setting_id = "wt_history_kruber_sword_and_shield",
			source_paths = {"scripts/settings/equipment/1h_swords_shield.lua", "scripts/settings/equipment/weapon_templates/1h_swords_shield.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_sword_shield_template_1", },
		},
		{
			aliases = {"one_handed_axe_shared", "1h_axes", },
			id = "one_handed_axe_shared",
			label = "One-handed Axe (Bardin and Saltzpyre)",
			setting_id = "wt_history_one_handed_axe_shared",
			source_paths = {"scripts/settings/equipment/1h_axes.lua", "scripts/settings/equipment/weapon_templates/1h_axes.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_hand_axe_template_1", "one_hand_axe_template_2", },
		},
		{
			aliases = {"one_handed_flail", "1h_flails", },
			id = "one_handed_flail",
			label = "Saltzpyre's Flail",
			setting_id = "wt_history_one_handed_flail",
			source_paths = {"scripts/settings/equipment/1h_flails.lua", "scripts/settings/equipment/weapon_templates/1h_flails.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_flail_template_1", },
		},
		{
			aliases = {"one_handed_hammer_shared", "1h_hammers", },
			id = "one_handed_hammer_shared",
			label = "One-handed Hammer/Mace (Bardin and Kruber)",
			setting_id = "wt_history_one_handed_hammer_shared",
			source_paths = {"scripts/settings/equipment/1h_hammers.lua", "scripts/settings/equipment/weapon_templates/1h_hammers.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_hammer_template_1", "one_handed_hammer_template_2", },
		},
		{
			aliases = {"one_handed_sword_shared", "1h_swords", },
			id = "one_handed_sword_shared",
			label = "One-handed Sword (Kruber and Sienna)",
			setting_id = "wt_history_one_handed_sword_shared",
			source_paths = {"scripts/settings/equipment/1h_swords.lua", "scripts/settings/equipment/weapon_templates/1h_swords.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_swords_template_1", },
		},
		{
			aliases = {"rapier", "fencing_swords", },
			id = "rapier",
			label = "Saltzpyre's Rapier",
			setting_id = "wt_history_rapier",
			source_paths = {"scripts/settings/equipment/fencing_swords.lua", "scripts/settings/equipment/weapon_templates/fencing_swords.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"fencing_sword_template_1", },
		},
		{
			aliases = {"repeater_handgun", "repeating_handguns", },
			id = "repeater_handgun",
			label = "Kruber's Repeater Handgun",
			setting_id = "wt_history_repeater_handgun",
			source_paths = {"scripts/settings/equipment/repeating_handguns.lua", "scripts/settings/equipment/weapon_templates/repeating_handguns.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"repeating_handgun_template_1", },
		},
		{
			aliases = {"repeater_pistol", "brace_of_repeating_pistols", },
			id = "repeater_pistol",
			label = "Saltzpyre's Repeater Pistol",
			setting_id = "wt_history_repeater_pistol",
			source_paths = {"scripts/settings/equipment/brace_of_repeating_pistols.lua", "scripts/settings/equipment/weapon_templates/repeating_pistols.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"repeating_pistol_template_1", },
		},
		{
			aliases = {"sienna_dagger", "1h_dagger_wizard", },
			id = "sienna_dagger",
			label = "Sienna's Dagger",
			setting_id = "wt_history_sienna_dagger",
			source_paths = {"scripts/settings/equipment/1h_dagger_wizard.lua", "scripts/settings/equipment/weapon_templates/1h_dagger_wizard.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_daggers_template_1", },
		},
		{
			aliases = {"sienna_mace", "1h_hammers_wizard", },
			id = "sienna_mace",
			label = "Sienna's Mace",
			setting_id = "wt_history_sienna_mace",
			source_paths = {"scripts/settings/equipment/1h_hammers_wizard.lua", "scripts/settings/equipment/weapon_templates/1h_hammers_wizard.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"one_handed_hammer_wizard_template_1", },
		},
		{
			aliases = {"sword_and_dagger", "dual_wield_sword_dagger", },
			id = "sword_and_dagger",
			label = "Kerillian's Sword and Dagger",
			setting_id = "wt_history_sword_and_dagger",
			source_paths = {"scripts/settings/equipment/dual_wield_sword_dagger.lua", "scripts/settings/equipment/weapon_templates/dual_wield_sword_dagger.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"dual_wield_sword_dagger_template_1", },
		},
		{
			aliases = {"two_handed_hammer_shared", "2h_hammers", },
			id = "two_handed_hammer_shared",
			label = "Two-handed Hammer (Bardin and Kruber)",
			setting_id = "wt_history_two_handed_hammer_shared",
			source_paths = {"scripts/settings/equipment/2h_hammers.lua", "scripts/settings/equipment/weapon_templates/2h_hammers.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_hammers_template_1", },
		},
		{
			aliases = {"two_handed_sword_shared", "2h_swords", },
			id = "two_handed_sword_shared",
			label = "Two-handed Sword (Kruber and Saltzpyre)",
			setting_id = "wt_history_two_handed_sword_shared",
			source_paths = {"scripts/settings/equipment/2h_swords.lua", "scripts/settings/equipment/weapon_templates/2h_swords.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_swords_template_1", },
		},
		{
			aliases = {"war_pick", "2h_picks", },
			id = "war_pick",
			label = "Bardin's War Pick",
			setting_id = "wt_history_war_pick",
			source_paths = {"scripts/settings/equipment/2h_picks.lua", "scripts/settings/equipment/weapon_templates/2h_picks.lua", },
			states = {"1_2_2", "1_3_0", },
			templates = {"two_handed_picks_template_1", },
		},
	},
	global_records = {
		["1_2_2"] = {
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "crouch_moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "crouch_moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "crouch_still", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.6,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "crouch_still", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.6,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.8,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.8,
			},
			{
				expected_current = 0.4,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "still", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.65,
			},
			{
				expected_current = 0.4,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "continuous", "still", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.65,
			},
			{
				expected_current = 0.4,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "immediate", "being_hit", "immediate_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1.4,
			},
			{
				expected_current = 0.4,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"brace_of_pistols", "immediate", "being_hit", "immediate_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1.4,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "crouch_still", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.6,
			},
			{
				expected_current = 0.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "crouch_still", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.6,
			},
			{
				expected_current = 1.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.8,
			},
			{
				expected_current = 1.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.8,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "still", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.65,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "still", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.65,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "zoomed_crouch_moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.4,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "zoomed_crouch_moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.4,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "zoomed_moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.4,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "zoomed_moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 0.4,
			},
		},
		["1_3_0"] = {
			{
				expected_current = 1.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "moving", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1,
			},
			{
				expected_current = 1.5,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "moving", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "still", "max_pitch", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1.5,
			},
			{
				expected_current = 1,
				expected_current_unset = false,
				family_id = "brace_of_pistols",
				path = {"pistol_special", "continuous", "still", "max_yaw", },
				root = "SpreadTemplates",
				source_path = "scripts/unit_extensions/weapons/spread/spread_templates.lua",
				unset = false,
				value = 1.5,
			},
		},
	},
	live_game_label = "6.12.0",
	private_profile_contract = {
		fallback_registry = "mod._wt431_custom_profile_fallback",
		key_format = "wt_hist_<state_id>_<native_profile_name>",
		parity_guard = "wt431_damage_profile_parity",
		register = "unconditionally_at_load",
		remap = "selected_family_references_only",
	},
	profile_routes = {
		["1_2_2"] = {
			bardin_axe_and_shield = {"heavy_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_upper", "medium_push", "medium_slashing_smiter_1h", "medium_slashing_smiter_flat_1h", "shield_slam", "shield_slam_aoe", },
			bardin_two_handed_axe = {"heavy_slashing_axe_linesman", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", "medium_slashing_smiter_2h_upper", },
			blunderbuss = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			brace_of_pistols = {"shot_carbine", },
			burning_sword = {"dagger_burning_slam", "dagger_burning_slam_aoe", "light_push", "light_slashing_linesman", "light_slashing_smiter_stab", "medium_burning_tank", "medium_push", },
			crossbow_shared = {"crossbow_bolt", },
			drakefire_pistols = {"shot_drakefire", },
			drakegun = {"flamethrower", "flamethrower_initial", "flamethrower_spray", },
			dual_axes = {"light_push", "light_slashing_smiter_diag_dual_L", "light_slashing_smiter_dual", "medium_push", },
			dual_daggers = {"light_fencer_stab", "light_fencer_stab_diag", "light_push", "light_slashing_smiter_stab_dual", },
			dual_swords = {"light_push", "light_slashing_linesman_dual", "light_slashing_linesman_dual_medium", "light_slashing_smiter_stab", "medium_push", },
			elf_greatsword = {"heavy_slashing_linesman_executioner", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_linesman", },
			elf_one_handed_sword = {"light_push", "light_slashing_linesman", "light_slashing_smiter_stab", "medium_push", "medium_slashing_axe_linesman_1h", "medium_slashing_smiter_1h", },
			elf_spear = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_linesman_executioner", "medium_slashing_smiter_stab", },
			empire_longbow = {"arrow_carbine", "arrow_sniper_kruber", "longbow_empire", },
			executioner_sword = {"heavy_slashing_linesman_bopp", "heavy_slashing_smiter_executioner", "light_push", "medium_push", "medium_slashing_linesman_executioner", },
			falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_axe_linesman_upper", "light_slashing_smiter", "medium_push", "medium_slashing_axe_linesman_1h", },
			glaive = {"heavy_slashing_smiter_glaive", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_upper", },
			grudge_raker = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			halberd = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter", "medium_slashing_smiter_stab", },
			hammer_and_shield_shared = {"heavy_push", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "medium_blunt_smiter", "medium_blunt_tank_1h", "medium_push", "shield_slam", "shield_slam_aoe", "shield_slam_default_target", },
			handgun_shared = {"shot_sniper", },
			kruber_sword_and_shield = {
				"heavy_push",
				"light_slashing_linesman",
				"light_slashing_smiter_flat",
				"light_slashing_smiter_stab",
				"medium_push",
				"medium_slashing_linesman_1h",
				"medium_slashing_smiter_stab_1h",
				"shield_slam",
				"shield_slam_aoe",
				"shield_slam_default_target",
			},
			one_handed_axe_shared = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h", },
			one_handed_flail = {"light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			one_handed_hammer_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_1h", "medium_push", },
			one_handed_sword_shared = {"light_push", "light_slashing_linesman", "light_slashing_linesman_flat", "light_slashing_smiter", "medium_push", "medium_slashing_tank_1h", },
			rapier = {"light_push", "light_slashing_linesman_fencer", "medium_fencer_stab", "medium_fencer_stab_charged", "shot_carbine_rapier", },
			repeater_handgun = {"shot_repeating", },
			sienna_dagger = {"dagger_burning_slam", "dagger_burning_slam_aoe", "light_fencer_stab", "light_push", "light_slashing_linesman_fencer", "medium_burning_smiter_stab_H", },
			sienna_mace = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_burn", "medium_blunt_tank_upper_1h", "medium_push", },
			sword_and_dagger = {"light_fencer_stab_diag", "light_push", "light_slashing_linesman_dual_medium", "light_slashing_linesman_fencer", "light_slashing_smiter_stab", "light_slashing_smiter_stab_dual", "medium_push", },
			two_handed_hammer_shared = {"heavy_blunt_tank", "light_push", "medium_blunt_smiter_2h_hammer", "medium_blunt_smiter_2h_hammer_diag", "medium_blunt_smiter_2h_hammer_upper", "medium_push", },
			two_handed_sword_shared = {"heavy_slashing_linesman", "light_push", "light_slashing_smiter_dual_bopp", "medium_push", "medium_slashing_linesman", },
			war_pick = {"heavy_blunt_smiter", "heavy_blunt_smiter_charged", "light_push", "medium_blunt_smiter_flat_2h", "medium_blunt_tank", "medium_push", },
		},
		["1_3_0"] = {
			bardin_axe_and_shield = {
				"light_slashing_smiter",
				"light_slashing_smiter_diag",
				"light_slashing_smiter_upper",
				"medium_push",
				"medium_slashing_smiter_1h",
				"medium_slashing_tank_1h",
				"shield_push",
				"shield_slam",
				"shield_slam_aoe",
				"shield_slam_target",
			},
			bardin_two_handed_axe = {"heavy_slashing_axe_linesman", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", },
			blunderbuss = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			brace_of_pistols = {"shot_carbine", },
			burning_sword = {"dagger_burning_slam", "dagger_burning_slam_aoe", "light_push", "light_slashing_linesman", "light_slashing_smiter_stab", "medium_burning_tank", "medium_push", },
			crossbow_shared = {"crossbow_bolt", },
			drakefire_pistols = {"blast", "shot_drakefire", },
			drakegun = {"flamethrower", "flamethrower_initial", "flamethrower_spray", },
			dual_axes = {"light_push", "light_slashing_smiter_diag_dual_L", "light_slashing_smiter_dual", "light_slashing_smiter_dual_bopp", "medium_push", },
			dual_daggers = {"light_fencer_stab", "light_fencer_stab_diag", "light_push", "light_slashing_smiter_stab_dual", },
			dual_swords = {"light_push", "light_slashing_linesman_dual", "light_slashing_linesman_dual_medium", "light_slashing_smiter_stab", "medium_push", },
			elf_greatsword = {"heavy_slashing_linesman_executioner", "heavy_slashing_smiter_stab", "light_push", "medium_push", "medium_slashing_linesman", },
			elf_one_handed_sword = {"light_push", "light_slashing_linesman_elf", "light_slashing_smiter_stab", "medium_push", "medium_slashing_axe_linesman_1h", "medium_slashing_smiter_1h", },
			elf_spear = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_linesman_spear", "medium_slashing_smiter_stab", },
			empire_longbow = {"arrow_carbine", "arrow_sniper_kruber", "longbow_empire", },
			executioner_sword = {"heavy_slashing_smiter_executioner", "light_push", "medium_push", "medium_slashing_linesman_executioner", },
			falchion = {"light_push", "light_slashing_axe_linesman", "light_slashing_axe_linesman_upper", "light_slashing_smiter", "medium_push", "medium_slashing_axe_linesman_1h", },
			glaive = {"heavy_slashing_smiter_glaive", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_upper", },
			grudge_raker = {"shield_slam_shotgun", "shield_slam_shotgun_aoe", "shot_shotgun", },
			halberd = {"heavy_slashing_linesman_polearm", "heavy_slashing_smiter_stab_polearm", "light_push", "medium_push", "medium_slashing_axe_linesman", "medium_slashing_smiter_2h", "medium_slashing_smiter_stab", },
			hammer_and_shield_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "medium_blunt_tank_1h", "medium_push", "shield_push", "shield_slam", "shield_slam_aoe", "shield_slam_target", },
			handgun_shared = {"shot_sniper", },
			kruber_sword_and_shield = {
				"light_slashing_linesman",
				"light_slashing_smiter_flat",
				"light_slashing_smiter_stab",
				"medium_push",
				"medium_slashing_linesman_1h",
				"medium_slashing_smiter_stab_1h",
				"shield_push",
				"shield_slam",
				"shield_slam_aoe",
				"shield_slam_target",
			},
			one_handed_axe_shared = {"light_push", "light_slashing_smiter", "light_slashing_smiter_diag", "light_slashing_smiter_flat", "medium_push", "medium_slashing_smiter_1h", },
			one_handed_flail = {"light_blunt_smiter", "light_blunt_tank_spiked", "light_push", "medium_blunt_tank_spiked", "medium_push", },
			one_handed_hammer_shared = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_diag", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_1h", "medium_push", },
			one_handed_sword_shared = {"light_push", "light_slashing_linesman", "light_slashing_linesman_flat", "light_slashing_smiter", "medium_push", "medium_slashing_linesman", "medium_slashing_tank_1h", },
			rapier = {"light_push", "light_slashing_linesman_fencer", "medium_fencer_stab", "medium_fencer_stab_charged", "shot_carbine_rapier", },
			repeater_handgun = {"shot_repeating", },
			sienna_dagger = {"dagger_burning_slam_fencer", "dagger_burning_slam_fencer_aoe", "dagger_burning_slam_target_fencer", "light_fencer_stab", "light_push", "light_slashing_linesman_fencer", "medium_burning_smiter_stab_H", },
			sienna_mace = {"light_blunt_smiter", "light_blunt_tank", "light_blunt_tank_upper", "light_push", "medium_blunt_smiter_burn", "medium_blunt_tank_upper_1h", "medium_push", },
			sword_and_dagger = {"light_fencer_stab_diag", "light_push", "light_slashing_linesman_dual_medium", "light_slashing_linesman_fencer", "light_slashing_smiter_stab", "light_slashing_smiter_stab_dual", "medium_push", },
			two_handed_hammer_shared = {"heavy_blunt_tank", "light_push", "medium_blunt_smiter_2h_hammer", "medium_blunt_smiter_2h_hammer_diag", "medium_blunt_smiter_2h_hammer_upper", "medium_push", },
			two_handed_sword_shared = {"heavy_slashing_linesman", "light_push", "medium_push", "medium_slashing_linesman", "medium_slashing_smiter_2h", },
			war_pick = {"heavy_blunt_smiter_charged", "heavy_blunt_smiter_pick", "light_push", "medium_blunt_smiter_flat_2h", "medium_blunt_tank", "medium_push", },
		},
	},
	provenance = {
		artifact_sha256 = {
			_wt_history_profiles_1_2_2_part_01_generated = "da809195d9e40a746228ad78df242898a122a4a90d868f2460b0fa45233f73d7",
			_wt_history_profiles_1_3_0_part_01_generated = "ef6cfffada115762139564048d2dcb2693a0576c396369cb24d28de2bd218c3c",
			_wt_history_snapshot_1_2_2_part_01_generated = "8aca42ae02e8ee236c80f38be2c1afa939685def5a854514e8286c0d83251504",
			_wt_history_snapshot_1_2_2_part_02_generated = "7962abf2e448adc089c8e1af47226ff3bf7b4ee70e49e43a06879b4e3cc51952",
			_wt_history_snapshot_1_2_2_part_03_generated = "786ea94f8a7464eb90f166f8b3c187db36b35e42fef275cd437397baeb673b3f",
			_wt_history_snapshot_1_2_2_part_04_generated = "17b1a230a9bbd7b079c86c2af48630b1965128b2577290ab2bcc16d21817892d",
			_wt_history_snapshot_1_2_2_part_05_generated = "a5c97c37dabc598955f35708b379d06a9aa6c597424d9896bd9631d63f600ed8",
			_wt_history_snapshot_1_2_2_part_06_generated = "25458d89bd7460eb447130deef53d620fc4be44413b09deea4a7ef7687dacd1d",
			_wt_history_snapshot_1_3_0_part_01_generated = "c7679ed66d3dcf8fe31be3c08e5f30d50bdbfc399125c80ee259e2e611ecbf05",
			_wt_history_snapshot_1_3_0_part_02_generated = "c15adef068d175355e8549d872e42b18619e7fef0051f33584b8a7b61099f241",
			_wt_history_snapshot_1_3_0_part_03_generated = "3015cd92b83eb7ea8326bab5265e4f3449a9c624f526b96e92206fda7fd774b7",
			_wt_history_snapshot_1_3_0_part_04_generated = "351527af5815c1c0290d1c237012d3b9320ded54d2f73ec59e05077aafe3a996",
			_wt_history_snapshot_1_3_0_part_05_generated = "03de2df2a4fb860833877c46100d9c6a54edd826179d8ded65d207e2ce6647fc",
		},
		direct_projection = true,
		official_patch_notes = "https://forums.fatsharkgames.com/t/pc-vermintide-2-patch-1-3-now-live/29121",
		source_repository = "Aussiemon/Vermintide-2-Source-Code",
	},
	schema = 1,
	state_order = {"1_2_2", "1_3_0", },
	states = {
		["1_2_2"] = {
			direct_to_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
			label = "Patch 1.2.2 (Pre-1.3)",
			profile_modules = {"scripts/mods/weapon_tweaker/_wt_history_profiles_1_2_2_part_01_generated", },
			revision = "cbd47f4e862209e0867c09b4a13ea8ee76c703a0",
			snapshot_modules = {
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_01_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_02_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_03_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_04_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_05_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_2_2_part_06_generated",
			},
			version_settings = "1.2.2",
		},
		["1_3_0"] = {
			direct_to_revision = "c5e4968b1fbb00c49884e56d640ef990a9c04dd0",
			label = "Patch 1.3",
			profile_modules = {"scripts/mods/weapon_tweaker/_wt_history_profiles_1_3_0_part_01_generated", },
			revision = "833f3539729cf30f7ce4fc48ae9aa5d0e96ed130",
			snapshot_modules = {
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_3_0_part_01_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_3_0_part_02_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_3_0_part_03_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_3_0_part_04_generated",
				"scripts/mods/weapon_tweaker/_wt_history_snapshot_1_3_0_part_05_generated",
			},
			version_settings = "1.3",
		},
	},
	template_families = {
		blunderbuss_template_1 = "blunderbuss",
		brace_of_drakefirepistols_template_1 = "drakefire_pistols",
		brace_of_pistols_template_1 = "brace_of_pistols",
		crossbow_template_1 = "crossbow_shared",
		drakegun_template_1 = "drakegun",
		dual_wield_axes_template_1 = "dual_axes",
		dual_wield_daggers_template_1 = "dual_daggers",
		dual_wield_sword_dagger_template_1 = "sword_and_dagger",
		dual_wield_swords_template_1 = "dual_swords",
		fencing_sword_template_1 = "rapier",
		flaming_sword_spell_template_1 = "burning_sword",
		grudge_raker_template_1 = "grudge_raker",
		handgun_template_1 = "handgun_shared",
		handgun_template_2 = "handgun_shared",
		longbow_empire_template = "empire_longbow",
		one_hand_axe_shield_template_1 = "bardin_axe_and_shield",
		one_hand_axe_template_1 = "one_handed_axe_shared",
		one_hand_axe_template_2 = "one_handed_axe_shared",
		one_hand_falchion_template_1 = "falchion",
		one_handed_daggers_template_1 = "sienna_dagger",
		one_handed_flail_template_1 = "one_handed_flail",
		one_handed_hammer_shield_template_1 = "hammer_and_shield_shared",
		one_handed_hammer_shield_template_2 = "hammer_and_shield_shared",
		one_handed_hammer_template_1 = "one_handed_hammer_shared",
		one_handed_hammer_template_2 = "one_handed_hammer_shared",
		one_handed_hammer_wizard_template_1 = "sienna_mace",
		one_handed_sword_shield_template_1 = "kruber_sword_and_shield",
		one_handed_swords_template_1 = "one_handed_sword_shared",
		repeating_handgun_template_1 = "repeater_handgun",
		repeating_pistol_template_1 = "repeater_pistol",
		staff_flamethrower_template = "flamestorm_staff",
		two_handed_axes_template_1 = "bardin_two_handed_axe",
		two_handed_axes_template_2 = "glaive",
		two_handed_halberds_template_1 = "halberd",
		two_handed_hammers_template_1 = "two_handed_hammer_shared",
		two_handed_picks_template_1 = "war_pick",
		two_handed_spears_elf_template_1 = "elf_spear",
		two_handed_swords_executioner_template_1 = "executioner_sword",
		two_handed_swords_template_1 = "two_handed_sword_shared",
		two_handed_swords_wood_elf_template = "elf_greatsword",
		we_one_hand_sword_template_1 = "elf_one_handed_sword",
	},
}
