return {
    mod_name = { en = "Tweaker: Weapons" },
    mod_description = { en = "Weapon unlock and runtime experimentation for Vermintide 2. Requires VMF." },
    -- Top-level groups
    weapon_availability = { en = "Weapon Availability" },
    melee_weapons = { en = "Melee" },
    ranged_weapons = { en = "Ranged" },
    -- Melee character groups
    melee_kruber = { en = "Melee: Kruber" },
    melee_bardin = { en = "Melee: Bardin" },
    melee_kerillian = { en = "Melee: Kerillian" },
    melee_saltzpyre = { en = "Melee: Saltzpyre" },
    melee_sienna = { en = "Melee: Sienna" },
    -- Melee career groups
    melee_es_mercenary = { en = "Melee: Mercenary" },
    melee_es_huntsman = { en = "Melee: Huntsman" },
    melee_es_knight = { en = "Melee: Foot Knight" },
    melee_es_questingknight = { en = "Melee: Grail Knight" },
    melee_dr_ranger = { en = "Melee: Ranger Veteran" },
    melee_dr_ironbreaker = { en = "Melee: Ironbreaker" },
    melee_dr_slayer = { en = "Melee: Slayer" },
    melee_dr_engineer = { en = "Melee: Engineer" },
    melee_we_waywatcher = { en = "Melee: Waystalker" },
    melee_we_maidenguard = { en = "Melee: Handmaiden" },
    melee_we_shade = { en = "Melee: Shade" },
    melee_we_thornsister = { en = "Melee: Sister of the Thorn" },
    melee_wh_captain = { en = "Melee: Witch Hunter Captain" },
    melee_wh_bountyhunter = { en = "Melee: Bounty Hunter" },
    melee_wh_zealot = { en = "Melee: Zealot" },
    melee_wh_priest = { en = "Melee: Warrior Priest" },
    melee_bw_adept = { en = "Melee: Battle Wizard" },
    melee_bw_scholar = { en = "Melee: Pyromancer" },
    melee_bw_unchained = { en = "Melee: Unchained" },
    melee_bw_necromancer = { en = "Melee: Necromancer" },
    -- Ranged character groups
    ranged_kruber = { en = "Ranged: Kruber" },
    ranged_bardin = { en = "Ranged: Bardin" },
    ranged_kerillian = { en = "Ranged: Kerillian" },
    ranged_saltzpyre = { en = "Ranged: Saltzpyre" },
    ranged_sienna = { en = "Ranged: Sienna" },
    -- Ranged career groups
    ranged_es_mercenary = { en = "Ranged: Mercenary" },
    ranged_es_huntsman = { en = "Ranged: Huntsman" },
    ranged_es_knight = { en = "Ranged: Foot Knight" },
    ranged_es_questingknight = { en = "Ranged: Grail Knight" },
    ranged_dr_ranger = { en = "Ranged: Ranger Veteran" },
    ranged_dr_ironbreaker = { en = "Ranged: Ironbreaker" },
    ranged_dr_slayer = { en = "Ranged: Slayer" },
    ranged_dr_engineer = { en = "Ranged: Engineer" },
    ranged_we_waywatcher = { en = "Ranged: Waystalker" },
    ranged_we_maidenguard = { en = "Ranged: Handmaiden" },
    ranged_we_shade = { en = "Ranged: Shade" },
    ranged_we_thornsister = { en = "Ranged: Sister of the Thorn" },
    ranged_wh_captain = { en = "Ranged: Witch Hunter Captain" },
    ranged_wh_bountyhunter = { en = "Ranged: Bounty Hunter" },
    ranged_wh_zealot = { en = "Ranged: Zealot" },
    ranged_bw_adept = { en = "Ranged: Battle Wizard" },
    ranged_bw_scholar = { en = "Ranged: Pyromancer" },
    ranged_bw_unchained = { en = "Ranged: Unchained" },
    ranged_bw_necromancer = { en = "Ranged: Necromancer" },
    -- Kruber: Mercenary
    unlock_es_mercenary_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_mercenary_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_mercenary_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_es_mercenary_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_es_mercenary_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_mercenary_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_mercenary_we_spear = { en = "Kerillian: Spear" },
    unlock_es_mercenary_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_mercenary_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_mercenary_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_mercenary_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_mercenary_es_sword_shield_breton = { en = "Kruber: Bretonnian Sword and Shield" },
    unlock_es_mercenary_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_mercenary_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_mercenary_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_mercenary_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_mercenary_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_mercenary_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_mercenary_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_mercenary_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_mercenary_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_mercenary_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_mercenary_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_mercenary_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_mercenary_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_mercenary_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_mercenary_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_mercenary_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_mercenary_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_mercenary_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_mercenary_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_mercenary_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_mercenary_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_mercenary_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    -- Kruber: Huntsman
    unlock_es_huntsman_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_huntsman_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_huntsman_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_es_huntsman_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_es_huntsman_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_huntsman_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_huntsman_we_spear = { en = "Kerillian: Spear" },
    unlock_es_huntsman_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_huntsman_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_huntsman_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_huntsman_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_huntsman_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_huntsman_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_huntsman_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_huntsman_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_huntsman_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_huntsman_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_huntsman_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_huntsman_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_huntsman_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_huntsman_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_huntsman_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_huntsman_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_huntsman_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_huntsman_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_huntsman_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_huntsman_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_huntsman_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_huntsman_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_huntsman_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_huntsman_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_huntsman_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_huntsman_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    -- Kruber: Foot Knight
    unlock_es_knight_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_knight_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_knight_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_es_knight_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_es_knight_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_knight_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_knight_we_spear = { en = "Kerillian: Spear" },
    unlock_es_knight_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_knight_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_knight_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_knight_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_knight_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_knight_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_knight_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_knight_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_knight_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_knight_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_knight_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_knight_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_knight_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_knight_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_knight_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_knight_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_knight_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_knight_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_knight_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_knight_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_knight_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_knight_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_knight_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_knight_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_knight_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_knight_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    -- Kruber: Grail Knight
    unlock_es_questingknight_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_questingknight_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_questingknight_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_es_questingknight_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_es_questingknight_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_questingknight_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_questingknight_we_spear = { en = "Kerillian: Spear" },
    unlock_es_questingknight_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_questingknight_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_questingknight_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_questingknight_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_questingknight_es_sword_shield_breton = { en = "Kruber: Bretonnian Sword and Shield" },
    unlock_es_questingknight_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_questingknight_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_questingknight_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_questingknight_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_questingknight_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_questingknight_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_questingknight_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_questingknight_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_questingknight_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_questingknight_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_questingknight_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_questingknight_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_questingknight_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_questingknight_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_questingknight_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_questingknight_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_questingknight_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_questingknight_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_questingknight_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_questingknight_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_questingknight_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_questingknight_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    -- Bardin: Ranger Veteran
    unlock_dr_ranger_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_ranger_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_ranger_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_ranger_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_ranger_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_ranger_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_ranger_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_ranger_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_ranger_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_ranger_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_ranger_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_ranger_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_ranger_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_ranger_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_ranger_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_ranger_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_ranger_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_ranger_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_ranger_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_ranger_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_ranger_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_ranger_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Bardin: Ironbreaker
    unlock_dr_ironbreaker_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_ironbreaker_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_ironbreaker_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_ironbreaker_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_ironbreaker_dr_drake_pistol = { en = "Bardin: Drakefire Pistols" },
    unlock_dr_ironbreaker_dr_drakegun = { en = "Bardin: Drakegun" },
    unlock_dr_ironbreaker_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_ironbreaker_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_ironbreaker_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_ironbreaker_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_ironbreaker_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_ironbreaker_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_ironbreaker_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_ironbreaker_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_ironbreaker_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_ironbreaker_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_ironbreaker_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_ironbreaker_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_ironbreaker_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_ironbreaker_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_ironbreaker_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_ironbreaker_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_ironbreaker_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Bardin: Slayer
    unlock_dr_slayer_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_slayer_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_slayer_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_slayer_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_slayer_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_slayer_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_slayer_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_slayer_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_slayer_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_slayer_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_slayer_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_slayer_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_slayer_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_slayer_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_slayer_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_slayer_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_slayer_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_slayer_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_slayer_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_slayer_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_slayer_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_slayer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Bardin: Engineer
    unlock_dr_engineer_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_engineer_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_engineer_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_engineer_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_engineer_dr_drake_pistol = { en = "Bardin: Drakefire Pistols" },
    unlock_dr_engineer_dr_drakegun = { en = "Bardin: Drakegun" },
    unlock_dr_engineer_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_engineer_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_engineer_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_engineer_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_engineer_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_engineer_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_engineer_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_engineer_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_engineer_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_engineer_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_engineer_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_engineer_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_engineer_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_engineer_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_engineer_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_engineer_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_engineer_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_engineer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Kerillian: Waystalker
    unlock_we_waywatcher_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_waywatcher_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_waywatcher_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_waywatcher_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_waywatcher_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_waywatcher_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_waywatcher_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_waywatcher_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_waywatcher_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_waywatcher_we_spear = { en = "Kerillian: Spear" },
    unlock_we_waywatcher_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_waywatcher_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_waywatcher_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_waywatcher_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_waywatcher_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_waywatcher_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_waywatcher_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_waywatcher_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_waywatcher_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_waywatcher_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    -- Kerillian: Handmaiden
    unlock_we_maidenguard_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_maidenguard_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_maidenguard_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_maidenguard_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_maidenguard_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_maidenguard_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_maidenguard_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_maidenguard_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_maidenguard_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_maidenguard_we_spear = { en = "Kerillian: Spear" },
    unlock_we_maidenguard_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_maidenguard_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_maidenguard_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_maidenguard_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_maidenguard_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_maidenguard_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_maidenguard_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_maidenguard_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_maidenguard_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_maidenguard_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    -- Kerillian: Shade
    unlock_we_shade_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_shade_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_shade_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_shade_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_shade_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_shade_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_shade_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_shade_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_shade_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_shade_we_spear = { en = "Kerillian: Spear" },
    unlock_we_shade_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_shade_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_shade_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_shade_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_shade_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_shade_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_shade_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_shade_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_shade_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_shade_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    -- Kerillian: Sister of the Thorn
    unlock_we_thornsister_we_life_staff = { en = "Kerillian: Deepwood Staff" },
    unlock_we_thornsister_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_thornsister_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_thornsister_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_thornsister_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_thornsister_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_thornsister_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_thornsister_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_thornsister_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_thornsister_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_thornsister_we_spear = { en = "Kerillian: Spear" },
    unlock_we_thornsister_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_thornsister_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_thornsister_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_thornsister_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_thornsister_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_thornsister_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_thornsister_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_thornsister_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_thornsister_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_thornsister_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    -- Saltzpyre: Witch Hunter Captain
    unlock_wh_captain_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_captain_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_captain_we_longbow = { en = "Kerillian: Longbow" },
    unlock_wh_captain_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_captain_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_captain_es_longbow = { en = "Kruber: Longbow" },
    unlock_wh_captain_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_captain_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_captain_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_captain_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_captain_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_captain_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_captain_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_captain_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_captain_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_captain_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_captain_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_captain_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_captain_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_captain_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_captain_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_captain_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_captain_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_captain_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_captain_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Saltzpyre: Bounty Hunter
    unlock_wh_bountyhunter_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_bountyhunter_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_bountyhunter_we_longbow = { en = "Kerillian: Longbow" },
    unlock_wh_bountyhunter_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_bountyhunter_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_bountyhunter_es_longbow = { en = "Kruber: Longbow" },
    unlock_wh_bountyhunter_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_bountyhunter_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_bountyhunter_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_bountyhunter_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_bountyhunter_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_bountyhunter_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_bountyhunter_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_bountyhunter_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_bountyhunter_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_bountyhunter_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_bountyhunter_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_bountyhunter_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_bountyhunter_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_bountyhunter_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_bountyhunter_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_bountyhunter_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_bountyhunter_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_bountyhunter_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_bountyhunter_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Saltzpyre: Zealot
    unlock_wh_zealot_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_zealot_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_zealot_we_longbow = { en = "Kerillian: Longbow" },
    unlock_wh_zealot_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_zealot_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_zealot_es_longbow = { en = "Kruber: Longbow" },
    unlock_wh_zealot_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_zealot_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_zealot_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_zealot_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_zealot_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_zealot_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_zealot_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_zealot_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_zealot_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_zealot_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_zealot_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_zealot_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_zealot_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_zealot_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_zealot_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_zealot_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_zealot_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_zealot_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_zealot_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    -- Saltzpyre: Warrior Priest
    unlock_wh_priest_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_priest_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_priest_wh_flail_shield = { en = "Saltzpyre: Flail and Shield" },
    unlock_wh_priest_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_priest_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_wh_priest_wh_hammer_book = { en = "Saltzpyre: Hammer and Tome" },
    unlock_wh_priest_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    -- Sienna: Battle Wizard
    unlock_bw_adept_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_adept_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_adept_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_adept_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_adept_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_adept_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_adept_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_adept_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_adept_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_adept_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_adept_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_adept_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_adept_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Pyromancer
    unlock_bw_scholar_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_scholar_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_scholar_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_scholar_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_scholar_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_scholar_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_scholar_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_scholar_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_scholar_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_scholar_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_scholar_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_scholar_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_scholar_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Unchained
    unlock_bw_unchained_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_unchained_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_unchained_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_unchained_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_unchained_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_unchained_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_unchained_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_unchained_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_unchained_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_unchained_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_unchained_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_unchained_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_unchained_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Necromancer
    unlock_bw_necromancer_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_necromancer_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_necromancer_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_necromancer_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_necromancer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_necromancer_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_necromancer_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_necromancer_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_necromancer_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_necromancer_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_necromancer_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_necromancer_bw_necromancy_staff = { en = "Sienna: Soulstealer Staff" },
    unlock_bw_necromancer_bw_sword = { en = "Sienna: Sword" },
    -- Feature toggles
    enable_weapon_unlocks_core = { en = "Enable Weapon Unlock Core" },
    enable_weapon_backend_hooks = { en = "Enable Backend Loadout Hooks" },
    enable_weapon_ui_hooks = { en = "Enable UI Inventory Hooks" },
    enable_weapon_animation_redirects = { en = "Enable Animation Redirects" },
    enable_weapon_runtime_guards = { en = "Enable Runtime Guard Hooks" },
    enable_weapon_wield_slot_guard = { en = "Enable Wield Slot Guard" },
    enable_weapon_create_equipment_guard = { en = "Enable Create Equipment Guard" },
    enable_weapon_career_action_injection = { en = "Enable Career Action Injection" },
    force_bretonnian_shield_unlock = { en = "Force Bretonnian Shield Unlock" },
    -- Weapon override toggles (template patches that change weapon behavior)
    weapon_overrides = { en = "Weapon Overrides" },
    weapon_overrides_description = { en = "Toggleable behavior changes that patch existing weapon templates." },
    authentic_brace_of_pistols = { en = "Authentic Brace of Pistols" },
    authentic_brace_of_pistols_description = { en = "Restart required. Replaces Saltzpyre's Brace of Pistols moveset with a flintlock-style \"authentic\" version:\n• Damage: handgun shot (shot_sniper) instead of vanilla brace shot — armor-piercing and shield-breaking. Distance dropoff is flattened, so damage is consistent at all ranges.\n• Right-click (aim down sights / rapid-fire mode) is disabled. Only single-shot left-click fires the weapon.\n• No manual reload. Like throwing axes / bows, the weapon always carries 1 shot in the chamber and automatically reloads the next one after each shot.\n• Total ammo capped at 12 (down from 24).\n• Accuracy DRAMATICALLY reduced — spread widened 4× on every stance (and on rapid-fire / pistol_special too). Flintlocks weren't tack-drivers; these definitely aren't either." },
    moonfire_cosmetic_puff = { en = "Moonfire Bow: cosmetic AOE puff" },
    moonfire_cosmetic_puff_description = { en = "Cosmetic only. Spawns the small blue moonfire puff (vanilla arrow-impact VFX) on every Moonfire Bow hit. No damage, no friendly fire — just the lost visual. Overridden by the pre-nerf AOE toggle when both are on." },
    moonfire_aoe_revert = { en = "Moonfire Bow: revert pre-nerf AOE" },
    moonfire_aoe_revert_description = { en = "Restores the original pre-nerf Moonfire Bow behavior — every arrow detonates with a small magical AOE on impact, dealing area damage in a 1.5m radius (max-damage core 0.75m). Visual is a larger cluster of blue moonfire puffs. Friendly-fire and prop damage are off. Damage applies host-side; VFX plays on every peer. Overrides the cosmetic-only toggle when both are on." },
    kruber_longbow_disable_zoom = { en = "Kruber Longbow: disable zoom" },
    kruber_longbow_disable_zoom_description = { en = "Restart required. Removes the Kruber Longbow's delayed sniper-style heavy zoom entirely. Holding right-click still draws the bow and slows you, but the camera never zooms in. Overridden by the manual-zoom toggle when both are on." },
    kruber_longbow_manual_zoom = { en = "Kruber Longbow: manual zoom (like Kerillian Longbow)" },
    kruber_longbow_manual_zoom_description = { en = "Restart required. Replaces the Kruber Longbow's delayed sniper-style heavy zoom with the instant-on-hold zoom Kerillian's Longbow uses (zoom_in stage, ~0.01s delay). Hold right-click → bow draws AND zooms immediately; release to unzoom. Overrides the disable-zoom toggle when both are on." },

    -- Debug
    debug_group = { en = "Debug" },
    debug = { en = "Debug Mode" },
    enable_weapon_debug_logging = { en = "Enable Debug Logging" },

    -- Weapon traits (adventure pool filter)
    weapon_traits                  = { en = "Weapon Traits (Adventure)" },
    weapon_traits_description      = { en = "Choose which weapon traits can roll on weapons crafted/rerolled in adventure or modded realm. Adventure traits are on by default; Chaos Wastes traits require the Crafting in Modded mod." },
    adventure_melee_traits         = { en = "Adventure Melee Traits" },
    adventure_ranged_traits        = { en = "Adventure Ranged Traits" },
    cw_melee_traits                = { en = "Chaos Wastes Melee Traits" },
    cw_melee_traits_description    = { en = "Adds Chaos Wastes melee traits to the adventure crafting pool. Compatible-weapon-list traits (Home Run, Shield of Splinters, Always Blocking, Big Swing Stagger, Serrated Blade, Crit Chain Lightning) only apply to weapons that originally supported them in CW." },
    cw_ranged_traits               = { en = "Chaos Wastes Ranged Traits" },
    cw_ranged_traits_description   = { en = "Adds Chaos Wastes ranged traits to the adventure crafting pool. Some traits have a CW compatible-weapon-list and only roll on weapons that originally supported them." },

    -- Adventure melee traits
    trait_melee_attack_speed_on_crit               = { en = "Swift Slaying" },
    trait_melee_attack_speed_on_crit_description   = { en = "Critical hits grant +20% attack speed for 5 seconds." },
    trait_melee_timed_block_cost                   = { en = "Parry" },
    trait_melee_timed_block_cost_description       = { en = "Timed blocks cost no stamina." },
    trait_melee_counter_push_power                 = { en = "Off Balance" },
    trait_melee_counter_push_power_description     = { en = "Pushes against attacks gain 50% bonus push power." },
    trait_melee_increase_damage_on_block           = { en = "Heroic Intervention" },
    trait_melee_increase_damage_on_block_description = { en = "Blocking an attack increases damage taken on the attacker by 20% for 5 seconds." },
    trait_melee_reduce_cooldown_on_crit            = { en = "Resourceful Combatant" },
    trait_melee_reduce_cooldown_on_crit_description = { en = "Critical hits reduce career skill cooldown by 5%." },
    trait_melee_shield_on_assist                   = { en = "Opportunist" },
    trait_melee_shield_on_assist_description       = { en = "Assisting an ally grants 15 temporary HP to both of you." },

    -- Adventure ranged traits
    trait_ranged_restore_stamina_headshot                       = { en = "Inspirational Shot" },
    trait_ranged_restore_stamina_headshot_description           = { en = "Headshots replenish nearby allies' stamina." },
    trait_ranged_replenish_ammo_headshot                        = { en = "Scrounger" },
    trait_ranged_replenish_ammo_headshot_description            = { en = "Headshots restore 1 ammo." },
    trait_ranged_replenish_ammo_on_crit                         = { en = "Conservative Shooter" },
    trait_ranged_replenish_ammo_on_crit_description             = { en = "Critical hits restore 5% of max ammo." },
    trait_ranged_reduce_cooldown_on_crit                        = { en = "Resourceful Sharpshooter" },
    trait_ranged_reduce_cooldown_on_crit_description            = { en = "Ranged critical hits reduce career skill cooldown by 5%." },
    trait_ranged_increase_power_level_vs_armour_crit            = { en = "Hunter" },
    trait_ranged_increase_power_level_vs_armour_crit_description = { en = "Ranged crits grant 25% power vs the hit target's armor type for 10 seconds." },
    trait_ranged_consecutive_hits_increase_power                = { en = "Barrage" },
    trait_ranged_consecutive_hits_increase_power_description    = { en = "Consecutive ranged hits stack bonus power (up to 5 stacks, +5% each)." },
    trait_ranged_reduced_overcharge                             = { en = "Thermal Equalizer" },
    trait_ranged_reduced_overcharge_description                 = { en = "Reduces overcharge generation by 20%." },
    trait_ranged_remove_overcharge_on_crit                      = { en = "Heat Sink" },
    trait_ranged_remove_overcharge_on_crit_description          = { en = "Critical hits with overcharge weapons cost no overcharge." },

    -- Chaos Wastes melee traits
    cw_trait_stagger_aoe_on_crit                                  = { en = "[CW] Shockwave" },
    cw_trait_stagger_aoe_on_crit_description                      = { en = "Critical hits create an AoE stagger around the target." },
    cw_trait_armor_breaker                                        = { en = "[CW] Armor Breaker" },
    cw_trait_armor_breaker_description                            = { en = "Killing armored enemies makes nearby enemies take more damage." },
    cw_trait_shield_of_isha                                       = { en = "[CW] Shield of Isha (shields only)" },
    cw_trait_shield_of_isha_description                           = { en = "Increases max damage taken before downing by 20." },
    cw_trait_bloodthirst                                          = { en = "[CW] Bloodthirst" },
    cw_trait_bloodthirst_description                              = { en = "Every 5 kills grants a stack of +2% attack speed (5 max). Resets after 30s without a kill." },
    cw_trait_headhunter                                           = { en = "[CW] Headhunter (melee + ranged)" },
    cw_trait_headhunter_description                               = { en = "Headshots grant stacking damage. Stacks are consumed on use." },
    cw_trait_home_run                                             = { en = "[CW] Home Run (2H hammers only)" },
    cw_trait_home_run_description                                 = { en = "Charged heavy attacks launch enemies a long distance. Only applies to compatible 2H hammers." },
    cw_trait_shield_splinters                                     = { en = "[CW] Shield of Splinters (melee + ranged)" },
    cw_trait_shield_splinters_description                         = { en = "Generates temporary HP on hit. Only applies to weapons CW originally allowed it on." },
    cw_trait_serrated_blade                                       = { en = "[CW] Serrated Blade (blades only)" },
    cw_trait_serrated_blade_description                           = { en = "Slashing hits apply a damage-over-time bleed. Only applies to compatible bladed weapons." },
    cw_trait_crescendo_strike                                     = { en = "[CW] Crescendo Strike" },
    cw_trait_crescendo_strike_description                         = { en = "Consecutive light attacks increase damage." },
    cw_trait_follow_up                                            = { en = "[CW] Follow Up" },
    cw_trait_follow_up_description                                = { en = "Hitting an enemy you just hit deals bonus damage." },
    cw_trait_always_blocking                                      = { en = "[CW] Always Blocking (shields only)" },
    cw_trait_always_blocking_description                          = { en = "Briefly retain block after the input is released. Only applies to compatible shields." },
    cw_trait_deus_big_swing_stagger                               = { en = "[CW] Big Swing Stagger (heavy 2H only)" },
    cw_trait_deus_big_swing_stagger_description                   = { en = "Heavy attacks that hit multiple enemies grant a brief stagger-power buff." },
    cw_trait_deus_crit_chain_lightning                            = { en = "[CW] Crit Chain Lightning (melee + ranged)" },
    cw_trait_deus_crit_chain_lightning_description                = { en = "Critical hits chain lightning to nearby enemies. Only applies to weapons CW allowed it on." },
    cw_trait_deus_collateral_damage_on_melee_killing_blow         = { en = "[CW] Collateral Damage" },
    cw_trait_deus_collateral_damage_on_melee_killing_blow_description = { en = "Killing blows have a chance to deal collateral damage in an arc." },
    cw_trait_melee_heal_on_crit                                   = { en = "[CW] Heal on Crit (Melee)" },
    cw_trait_melee_heal_on_crit_description                       = { en = "Critical hits heal 5 HP." },

    -- Chaos Wastes ranged traits
    cw_trait_refilling_shot                                       = { en = "[CW] Refilling Shot" },
    cw_trait_refilling_shot_description                           = { en = "Killing blows refill the chamber. Only applies to compatible ranged weapons." },
    cw_trait_piercing_projectiles                                 = { en = "[CW] Piercing Projectile" },
    cw_trait_piercing_projectiles_description                     = { en = "Projectiles pierce additional targets. Only applies to compatible projectile weapons." },
    cw_trait_deus_extra_shot                                      = { en = "[CW] Extra Shot" },
    cw_trait_deus_extra_shot_description                          = { en = "Increases max ammo. Only applies to compatible ranged weapons." },
    cw_trait_deus_ranged_crit_explosion                           = { en = "[CW] Ranged Crit Explosion" },
    cw_trait_deus_ranged_crit_explosion_description               = { en = "Ranged critical hits cause an explosion. Only applies to compatible ranged weapons." },
    cw_trait_deus_ammo_pickup_reload_speed                        = { en = "[CW] Ammo Pickup Reload Speed" },
    cw_trait_deus_ammo_pickup_reload_speed_description            = { en = "Picking up ammo grants a reload-speed buff. Only applies to compatible ranged weapons." },
}
