return {
    mod_name = { en = "Weapon Tweaker" },
    mod_description = { en = "Weapon unlock and runtime experimentation for Vermintide 2. Requires VMF." },
    -- Top-level groups
    melee_weapons = { en = "Melee" },
    ranged_weapons = { en = "Ranged" },
    -- Melee character groups
    melee_kruber = { en = "Kruber" },
    melee_bardin = { en = "Bardin" },
    melee_kerillian = { en = "Kerillian" },
    melee_saltzpyre = { en = "Saltzpyre" },
    melee_sienna = { en = "Sienna" },
    -- Melee career groups
    melee_es_mercenary = { en = "Mercenary" },
    melee_es_huntsman = { en = "Huntsman" },
    melee_es_knight = { en = "Foot Knight" },
    melee_es_questingknight = { en = "Grail Knight" },
    melee_dr_ranger = { en = "Ranger Veteran" },
    melee_dr_ironbreaker = { en = "Ironbreaker" },
    melee_dr_slayer = { en = "Slayer" },
    melee_dr_engineer = { en = "Engineer" },
    melee_we_waywatcher = { en = "Waystalker" },
    melee_we_maidenguard = { en = "Handmaiden" },
    melee_we_shade = { en = "Shade" },
    melee_we_thornsister = { en = "Sister of the Thorn" },
    melee_wh_captain = { en = "Witch Hunter Captain" },
    melee_wh_bountyhunter = { en = "Bounty Hunter" },
    melee_wh_zealot = { en = "Zealot" },
    melee_wh_priest = { en = "Warrior Priest" },
    melee_bw_scholar = { en = "Battle Wizard" },
    melee_bw_adept = { en = "Pyromancer" },
    melee_bw_unchained = { en = "Unchained" },
    melee_bw_necromancer = { en = "Necromancer" },
    -- Ranged character groups
    ranged_kerillian = { en = "Kerillian" },
    -- Ranged career groups
    ranged_we_waywatcher = { en = "Waystalker" },
    ranged_we_maidenguard = { en = "Handmaiden" },
    ranged_we_thornsister = { en = "Sister of the Thorn" },
    -- Kruber: Mercenary
    unlock_es_mercenary_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_es_mercenary_es_sword_shield_breton = { en = "Bretonnian Sword & Shield" },
    unlock_es_mercenary_bw_sword = { en = "Sword (Sienna)" },
    unlock_es_mercenary_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_es_mercenary_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_es_mercenary_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_es_mercenary_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_es_mercenary_dr_shield_hammer = { en = "Hammer & Shield (Bardin)" },
    -- Kruber: Huntsman
    unlock_es_huntsman_bw_sword = { en = "Sword (Sienna)" },
    unlock_es_huntsman_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_es_huntsman_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_es_huntsman_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_es_huntsman_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_es_huntsman_dr_shield_hammer = { en = "Hammer & Shield (Bardin)" },
    -- Kruber: Foot Knight
    unlock_es_knight_bw_sword = { en = "Sword (Sienna)" },
    unlock_es_knight_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_es_knight_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_es_knight_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_es_knight_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_es_knight_es_2h_heavy_spear = { en = "Spear" },
    unlock_es_knight_dr_shield_hammer = { en = "Hammer & Shield (Bardin)" },
    -- Kruber: Grail Knight
    unlock_es_questingknight_bw_sword = { en = "Sword (Sienna)" },
    unlock_es_questingknight_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_es_questingknight_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_es_questingknight_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_es_questingknight_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_es_questingknight_es_2h_heavy_spear = { en = "Spear" },
    unlock_es_questingknight_we_1h_spears_shield = { en = "Spear & Shield (Kerillian)" },
    unlock_es_questingknight_es_halberd = { en = "Halberd" },
    unlock_es_questingknight_dr_shield_hammer = { en = "Hammer & Shield (Bardin)" },
    -- Bardin: Ranger Veteran
    unlock_dr_ranger_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_dr_ranger_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_dr_ranger_bw_sword = { en = "Sword (Sienna)" },
    unlock_dr_ranger_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_dr_ranger_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_dr_ranger_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_dr_ranger_es_mace_shield = { en = "Mace & Shield (Kruber)" },
    -- Bardin: Ironbreaker
    unlock_dr_ironbreaker_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_dr_ironbreaker_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_dr_ironbreaker_bw_sword = { en = "Sword (Sienna)" },
    unlock_dr_ironbreaker_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_dr_ironbreaker_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_dr_ironbreaker_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_dr_ironbreaker_es_mace_shield = { en = "Mace & Shield (Kruber)" },
    -- Bardin: Slayer
    unlock_dr_slayer_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_dr_slayer_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_dr_slayer_bw_sword = { en = "Sword (Sienna)" },
    unlock_dr_slayer_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_dr_slayer_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_dr_slayer_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_dr_slayer_es_mace_shield = { en = "Mace & Shield (Kruber)" },
    -- Bardin: Engineer
    unlock_dr_engineer_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_dr_engineer_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_dr_engineer_bw_sword = { en = "Sword (Sienna)" },
    unlock_dr_engineer_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_dr_engineer_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_dr_engineer_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_dr_engineer_es_mace_shield = { en = "Mace & Shield (Kruber)" },
    -- Kerillian: Waystalker
    unlock_we_waywatcher_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_we_waywatcher_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_we_waywatcher_bw_sword = { en = "Sword (Sienna)" },
    unlock_we_waywatcher_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_we_waywatcher_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_we_waywatcher_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_we_waywatcher_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_we_waywatcher_we_1h_spears_shield = { en = "Spear & Shield" },
    unlock_we_waywatcher_we_crossbow_repeater = { en = "Volley Crossbow" },
    -- Kerillian: Handmaiden
    unlock_we_maidenguard_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_we_maidenguard_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_we_maidenguard_bw_sword = { en = "Sword (Sienna)" },
    unlock_we_maidenguard_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_we_maidenguard_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_we_maidenguard_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_we_maidenguard_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_we_maidenguard_we_crossbow_repeater = { en = "Volley Crossbow" },
    -- Kerillian: Shade
    unlock_we_shade_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_we_shade_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_we_shade_bw_sword = { en = "Sword (Sienna)" },
    unlock_we_shade_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_we_shade_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_we_shade_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_we_shade_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_we_shade_we_1h_spears_shield = { en = "Spear & Shield" },
    -- Kerillian: Sister of the Thorn
    unlock_we_thornsister_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_we_thornsister_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_we_thornsister_bw_sword = { en = "Sword (Sienna)" },
    unlock_we_thornsister_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_we_thornsister_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_we_thornsister_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_we_thornsister_dr_1h_hammer = { en = "Hammer (Bardin)" },
    unlock_we_thornsister_we_1h_spears_shield = { en = "Spear & Shield" },
    unlock_we_thornsister_we_crossbow_repeater = { en = "Volley Crossbow" },
    -- Saltzpyre: Witch Hunter Captain
    unlock_wh_captain_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_wh_captain_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_wh_captain_bw_sword = { en = "Sword (Sienna)" },
    unlock_wh_captain_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_wh_captain_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_wh_captain_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Saltzpyre: Bounty Hunter
    unlock_wh_bountyhunter_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_wh_bountyhunter_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_wh_bountyhunter_bw_sword = { en = "Sword (Sienna)" },
    unlock_wh_bountyhunter_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_wh_bountyhunter_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_wh_bountyhunter_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Saltzpyre: Zealot
    unlock_wh_zealot_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_wh_zealot_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_wh_zealot_bw_sword = { en = "Sword (Sienna)" },
    unlock_wh_zealot_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_wh_zealot_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_wh_zealot_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Saltzpyre: Warrior Priest
    unlock_wh_priest_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_wh_priest_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_wh_priest_bw_sword = { en = "Sword (Sienna)" },
    unlock_wh_priest_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_wh_priest_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_wh_priest_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Sienna: Battle Wizard
    unlock_bw_scholar_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_bw_scholar_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_bw_scholar_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_bw_scholar_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_bw_scholar_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_bw_scholar_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_bw_scholar_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Sienna: Pyromancer
    unlock_bw_adept_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_bw_adept_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_bw_adept_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_bw_adept_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_bw_adept_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_bw_adept_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_bw_adept_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Sienna: Unchained
    unlock_bw_unchained_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_bw_unchained_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_bw_unchained_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_bw_unchained_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_bw_unchained_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_bw_unchained_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_bw_unchained_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Sienna: Necromancer
    unlock_bw_necromancer_es_1h_sword = { en = "Sword (Kruber)" },
    unlock_bw_necromancer_es_1h_mace = { en = "Mace (Kruber)" },
    unlock_bw_necromancer_wh_1h_falchion = { en = "Falchion (Saltzpyre)" },
    unlock_bw_necromancer_dr_1h_axe = { en = "Axe (Bardin)" },
    unlock_bw_necromancer_wh_1h_axe = { en = "Axe (Saltzpyre)" },
    unlock_bw_necromancer_we_1h_sword = { en = "Sword (Kerillian)" },
    unlock_bw_necromancer_dr_1h_hammer = { en = "Hammer (Bardin)" },
    -- Feature toggles
    enable_weapon_unlocks_core = { en = "Enable Weapon Unlock Core" },
    enable_weapon_backend_hooks = { en = "Enable Backend Loadout Hooks" },
    enable_weapon_ui_hooks = { en = "Enable UI Inventory Hooks" },
    enable_weapon_animation_redirects = { en = "Enable Animation Redirects" },
    enable_weapon_runtime_guards = { en = "Enable Runtime Guard Hooks" },
    enable_weapon_wield_slot_guard = { en = "Enable Wield Slot Guard" },
    enable_weapon_create_equipment_guard = { en = "Enable Create Equipment Guard" },
    enable_weapon_career_action_injection = { en = "Enable Career Action Injection" },
    force_bretonnian_shield_unlock = { en = "Force Bretonnian Shield Unlock" },
    -- Debug
    debug_group = { en = "Debug" },
    debug = { en = "Debug Mode" },
    enable_weapon_debug_logging = { en = "Enable Debug Logging" },
}
