local mod = get_mod("wt")

local _has_cwv = false
if Managers and Managers.mod and Managers.mod._mods then
    for i = 1, #Managers.mod._mods do
        local m = Managers.mod._mods[i]
        if m and m.name == "character_weapon_variants" then
            _has_cwv = true
            break
        end
    end
end

local _cwv_managed_settings = {
    ["unlock_es_mercenary_wh_1h_axe"] = true,
    ["unlock_es_huntsman_wh_1h_axe"] = true,
    ["unlock_es_knight_wh_1h_axe"] = true,
    ["unlock_es_questingknight_wh_1h_axe"] = true,
}

local function _strip_cwv_widgets(widgets)
    if not widgets then return end
    for i = #widgets, 1, -1 do
        local w = widgets[i]
        if _cwv_managed_settings[w.setting_id] then
            table.remove(widgets, i)
        elseif w.sub_widgets then
            _strip_cwv_widgets(w.sub_widgets)
        end
    end
end

local data = {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "melee_weapons",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "melee_kruber",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "melee_es_mercenary",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_mercenary_dr_2h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_dr_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_es_bastard_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_sword_shield_breton", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_es_2h_sword_executioner", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_halberd", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_mace_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_dual_wield_hammer_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_sword_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_2h_heavy_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_wh_2h_billhook", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_es_huntsman",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_huntsman_dr_2h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_dr_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_es_bastard_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_2h_sword_executioner", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_halberd", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_mace_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_dual_wield_hammer_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_sword_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_2h_heavy_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_wh_2h_billhook", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_es_knight",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_knight_dr_2h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_dr_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_es_bastard_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_2h_sword_executioner", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_halberd", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_mace_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_dual_wield_hammer_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_sword_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_es_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_wh_2h_billhook", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_es_questingknight",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_questingknight_dr_2h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_dr_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_bastard_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_sword_shield_breton", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_2h_sword_executioner", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_mace_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_dual_wield_hammer_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_sword_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_questingknight_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_wh_2h_billhook", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "melee_bardin",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "melee_dr_ranger",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_ranger_dr_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_shield_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_2h_cog_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_dual_wield_axes", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_dr_dual_wield_hammers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_shield_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_2h_pick", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_es_mace_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_es_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_dr_ironbreaker",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_ironbreaker_dr_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_shield_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_2h_cog_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_dual_wield_axes", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_dr_dual_wield_hammers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_shield_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_2h_pick", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_es_mace_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_es_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_dr_slayer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_slayer_dr_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_shield_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_2h_cog_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_dual_wield_axes", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_dual_wield_hammers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_2h_pick", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_es_mace_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_es_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_dr_engineer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_engineer_dr_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_shield_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_2h_cog_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_dual_wield_axes", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_dr_dual_wield_hammers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_shield_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_2h_pick", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_es_mace_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_es_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_hammer_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "melee_kerillian",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "melee_we_waywatcher",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_waywatcher_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_we_dual_wield_daggers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_dual_wield_swords", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_we_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_dual_wield_sword_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_es_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_wh_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_we_maidenguard",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_maidenguard_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_we_dual_wield_daggers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_dual_wield_swords", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_1h_spears_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_dual_wield_sword_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_es_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_wh_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_we_shade",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_shade_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_we_dual_wield_daggers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_dual_wield_swords", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_we_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_dual_wield_sword_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_es_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_es_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_wh_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_we_thornsister",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_thornsister_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_we_dual_wield_daggers", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_dual_wield_swords", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_2h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_1h_spears_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_we_1h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_dual_wield_sword_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_es_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_wh_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "melee_saltzpyre",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "melee_wh_captain",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_captain_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_dr_dual_wield_hammers", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_wh_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_dual_wield_axe_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_2h_billhook", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_wh_1h_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_es_1h_flail", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_wh_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_wh_fencing_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_wh_bountyhunter",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_bountyhunter_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_dr_dual_wield_hammers", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_wh_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_dual_wield_axe_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_2h_billhook", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_dual_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_wh_1h_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_es_1h_flail", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_wh_2h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_wh_fencing_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_wh_zealot",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_zealot_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_dr_dual_wield_hammers", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_we_2h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_wh_1h_axe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_dual_wield_axe_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_2h_billhook", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_dual_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_1h_falchion", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_es_1h_flail", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_2h_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_fencing_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "melee_wh_priest",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_priest_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_dr_dual_wield_hammers", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_dr_shield_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_we_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_halberd", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_mace_shield", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_2h_heavy_spear", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_wh_2h_billhook", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_wh_dual_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_wh_flail_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_wh_1h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_wh_hammer_shield", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_wh_hammer_book", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_wh_2h_hammer", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_priest_bw_1h_crowbill", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_bw_1h_flail_flaming", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_priest_bw_sword", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "melee_sienna",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "melee_bw_adept",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_adept_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_adept_bw_1h_crowbill", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_ghost_scythe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_flame_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_1h_flail_flaming", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_sword", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "melee_bw_scholar",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_scholar_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_scholar_bw_1h_crowbill", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_ghost_scythe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_flame_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_1h_flail_flaming", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_sword", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "melee_bw_unchained",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_unchained_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_unchained_bw_1h_crowbill", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_ghost_scythe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_flame_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_1h_flail_flaming", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_sword", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "melee_bw_necromancer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_necromancer_dr_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_dr_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_we_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_es_1h_mace", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_es_1h_sword", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_wh_1h_axe", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_wh_1h_falchion", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_es_1h_flail", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_wh_1h_hammer", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_bw_necromancer_bw_1h_crowbill", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_dagger", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_ghost_scythe", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_flame_sword", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_1h_flail_flaming", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_1h_mace", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_sword", type = "checkbox", default_value = true },
                                },
                            },
                        },
                    },
                },
            },
            {
                setting_id = "ranged_weapons",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "ranged_kruber",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "ranged_es_mercenary",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_mercenary_dr_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_we_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_mercenary_es_blunderbuss", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_mercenary_es_repeating_handgun", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_es_huntsman",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_huntsman_dr_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_we_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_huntsman_es_blunderbuss", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_longbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_huntsman_es_repeating_handgun", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_es_knight",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_knight_dr_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_we_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_knight_es_blunderbuss", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_es_knight_es_repeating_handgun", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_es_questingknight",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_es_questingknight_dr_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_we_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_blunderbuss", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_es_questingknight_es_repeating_handgun", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "ranged_bardin",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "ranged_dr_ranger",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_ranger_dr_crossbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_rakegun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_steam_pistol", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_1h_throwing_axes", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ranger_dr_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_es_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ranger_wh_crossbow", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_dr_ironbreaker",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_ironbreaker_dr_crossbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_drake_pistol", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_drakegun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_rakegun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_dr_1h_throwing_axes", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_dr_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_ironbreaker_es_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_ironbreaker_wh_crossbow", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_dr_slayer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_slayer_dr_crossbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_rakegun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_steam_pistol", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_dr_1h_throwing_axes", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_slayer_dr_deus_01", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_es_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_slayer_wh_crossbow", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_dr_engineer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_dr_engineer_dr_crossbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_dr_drake_pistol", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_drakegun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_rakegun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_handgun", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_steam_pistol", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_dr_1h_throwing_axes", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_dr_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_dr_engineer_es_handgun", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_dr_engineer_wh_crossbow", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "ranged_kerillian",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "ranged_we_waywatcher",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_waywatcher_we_shortbow_hagbane", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_javelin", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_longbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_shortbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_waywatcher_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_es_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_waywatcher_wh_crossbow_repeater", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_we_maidenguard",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_maidenguard_we_shortbow_hagbane", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_javelin", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_longbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_shortbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_maidenguard_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_es_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_maidenguard_wh_crossbow_repeater", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_we_shade",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_shade_we_shortbow_hagbane", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_javelin", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_longbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_shortbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_we_crossbow_repeater", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_shade_es_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_shade_wh_crossbow_repeater", type = "checkbox", default_value = false },
                                },
                            },
                            {
                                setting_id = "ranged_we_thornsister",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_we_thornsister_we_life_staff", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_shortbow_hagbane", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_javelin", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_longbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_shortbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_we_thornsister_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_es_longbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_we_thornsister_wh_crossbow_repeater", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "ranged_saltzpyre",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "ranged_wh_captain",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_captain_dr_crossbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_captain_wh_brace_of_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_crossbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_repeating_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_captain_wh_crossbow_repeater", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_wh_bountyhunter",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_bountyhunter_dr_crossbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_bountyhunter_wh_brace_of_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_crossbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_repeating_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_bountyhunter_wh_crossbow_repeater", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_wh_zealot",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_zealot_dr_crossbow", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_we_crossbow_repeater", type = "checkbox", default_value = false },
                                    { setting_id = "unlock_wh_zealot_wh_brace_of_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_crossbow", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_repeating_pistols", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_wh_zealot_wh_crossbow_repeater", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_wh_priest",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_wh_priest_we_crossbow_repeater", type = "checkbox", default_value = false },
                                },
                            },
                        },
                    },
                    {
                        setting_id = "ranged_sienna",
                        type = "group",
                        sub_widgets = {
                            {
                                setting_id = "ranged_bw_adept",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_adept_bw_skullstaff_beam", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_skullstaff_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_skullstaff_geiser", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_skullstaff_fireball", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_adept_bw_skullstaff_flamethrower", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_bw_scholar",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_scholar_bw_skullstaff_beam", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_skullstaff_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_skullstaff_geiser", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_skullstaff_fireball", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_scholar_bw_skullstaff_flamethrower", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_bw_unchained",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_unchained_bw_skullstaff_beam", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_skullstaff_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_skullstaff_geiser", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_skullstaff_fireball", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_unchained_bw_skullstaff_flamethrower", type = "checkbox", default_value = true },
                                },
                            },
                            {
                                setting_id = "ranged_bw_necromancer",
                                type = "group",
                                sub_widgets = {
                                    { setting_id = "unlock_bw_necromancer_bw_skullstaff_beam", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_skullstaff_spear", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_skullstaff_geiser", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_deus_01", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_skullstaff_fireball", type = "checkbox", default_value = true },
                                    { setting_id = "unlock_bw_necromancer_bw_necromancy_staff", type = "checkbox", default_value = true },
                                },
                            },
                        },
                    },
                },
            },
            {
                setting_id = "forge_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "forge_hotkey",
                        type = "keybind",
                        default_value = {"b"},
                        keybind_trigger = "pressed",
                        keybind_type = "function_call",
                        function_name = "open_forge",
                    },
                },
            },
            {
                setting_id = "debug_group",
                type = "group",
                sub_widgets = {
                    { setting_id = "debug", type = "checkbox", default_value = false },
                    { setting_id = "enable_weapon_debug_logging", type = "checkbox", default_value = false },
                },
            },
        },
    },
}

if _has_cwv then
    _strip_cwv_widgets(data.options.widgets)
end

return data
