return {
    mod_name = { en = "Tweaker: Weapons" },
    mod_description = { en = "Weapon unlock and runtime experimentation for Vermintide 2. Requires VMF." },
    -- Top-level groups
    melee_weapons = { en = "Melee" },
    ranged_weapons = { en = "Ranged" },
    -- Melee character groups
    melee_kruber = { en = "Kruber" },
    melee_bardin = { en = "Bardin" },
    melee_kerillian = { en = "Kerillian" },
    melee_saltzpyre = { en = "Saltzpyre" },
    melee_sienna = { en = "Sienna" },
    -- Melee career groups
    melee_es_mercenary = { en = "Mercenary" },
    melee_es_huntsman = { en = "Huntsman" },
    melee_es_knight = { en = "Foot Knight" },
    melee_es_questingknight = { en = "Grail Knight" },
    melee_dr_ranger = { en = "Ranger Veteran" },
    melee_dr_ironbreaker = { en = "Ironbreaker" },
    melee_dr_slayer = { en = "Slayer" },
    melee_dr_engineer = { en = "Engineer" },
    melee_we_waywatcher = { en = "Waystalker" },
    melee_we_maidenguard = { en = "Handmaiden" },
    melee_we_shade = { en = "Shade" },
    melee_we_thornsister = { en = "Sister of the Thorn" },
    melee_wh_captain = { en = "Witch Hunter Captain" },
    melee_wh_bountyhunter = { en = "Bounty Hunter" },
    melee_wh_zealot = { en = "Zealot" },
    melee_wh_priest = { en = "Warrior Priest" },
    melee_bw_adept = { en = "Battle Wizard" },
    melee_bw_scholar = { en = "Pyromancer" },
    melee_bw_unchained = { en = "Unchained" },
    melee_bw_necromancer = { en = "Necromancer" },
    -- Ranged character groups
    ranged_kruber = { en = "Kruber" },
    ranged_bardin = { en = "Bardin" },
    ranged_kerillian = { en = "Kerillian" },
    ranged_saltzpyre = { en = "Saltzpyre" },
    ranged_sienna = { en = "Sienna" },
    -- Ranged career groups
    ranged_es_mercenary = { en = "Mercenary" },
    ranged_es_huntsman = { en = "Huntsman" },
    ranged_es_knight = { en = "Foot Knight" },
    ranged_es_questingknight = { en = "Grail Knight" },
    ranged_dr_ranger = { en = "Ranger Veteran" },
    ranged_dr_ironbreaker = { en = "Ironbreaker" },
    ranged_dr_slayer = { en = "Slayer" },
    ranged_dr_engineer = { en = "Engineer" },
    ranged_we_waywatcher = { en = "Waystalker" },
    ranged_we_maidenguard = { en = "Handmaiden" },
    ranged_we_shade = { en = "Shade" },
    ranged_we_thornsister = { en = "Sister of the Thorn" },
    ranged_wh_captain = { en = "Witch Hunter Captain" },
    ranged_wh_bountyhunter = { en = "Bounty Hunter" },
    ranged_wh_zealot = { en = "Zealot" },
    ranged_wh_priest = { en = "Warrior Priest" },
    ranged_bw_adept = { en = "Battle Wizard" },
    ranged_bw_scholar = { en = "Pyromancer" },
    ranged_bw_unchained = { en = "Unchained" },
    ranged_bw_necromancer = { en = "Necromancer" },
    -- Kruber: Mercenary
    unlock_es_mercenary_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_mercenary_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_es_mercenary_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_es_mercenary_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_mercenary_dr_handgun = { en = "Bardin: Handgun" },
    unlock_es_mercenary_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_mercenary_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_mercenary_we_spear = { en = "Kerillian: Spear" },
    unlock_es_mercenary_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_mercenary_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_mercenary_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_mercenary_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_mercenary_es_sword_shield_breton = { en = "Kruber: Bretonnian Sword and Shield" },
    unlock_es_mercenary_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_mercenary_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_mercenary_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_mercenary_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_mercenary_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_mercenary_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_mercenary_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_mercenary_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_mercenary_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_mercenary_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_mercenary_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_mercenary_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_mercenary_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_mercenary_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_mercenary_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_mercenary_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_mercenary_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_mercenary_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_mercenary_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_mercenary_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_mercenary_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_es_mercenary_bw_sword = { en = "Sienna: Sword" },
    -- Kruber: Huntsman
    unlock_es_huntsman_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_huntsman_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_es_huntsman_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_es_huntsman_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_huntsman_dr_handgun = { en = "Bardin: Handgun" },
    unlock_es_huntsman_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_huntsman_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_huntsman_we_spear = { en = "Kerillian: Spear" },
    unlock_es_huntsman_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_huntsman_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_huntsman_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_huntsman_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_huntsman_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_huntsman_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_huntsman_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_huntsman_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_huntsman_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_huntsman_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_huntsman_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_huntsman_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_huntsman_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_huntsman_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_huntsman_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_huntsman_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_huntsman_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_huntsman_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_huntsman_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_huntsman_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_huntsman_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_huntsman_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_huntsman_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_huntsman_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_huntsman_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_huntsman_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_es_huntsman_bw_sword = { en = "Sienna: Sword" },
    -- Kruber: Foot Knight
    unlock_es_knight_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_knight_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_es_knight_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_es_knight_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_knight_dr_handgun = { en = "Bardin: Handgun" },
    unlock_es_knight_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_knight_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_knight_we_spear = { en = "Kerillian: Spear" },
    unlock_es_knight_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_knight_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_knight_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_knight_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_knight_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_knight_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_knight_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_knight_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_knight_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_knight_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_knight_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_knight_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_knight_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_knight_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_knight_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_knight_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_knight_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_knight_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_knight_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_knight_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_knight_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_knight_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_knight_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_knight_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_knight_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_es_knight_bw_sword = { en = "Sienna: Sword" },
    -- Kruber: Grail Knight
    unlock_es_questingknight_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_es_questingknight_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_es_questingknight_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_es_questingknight_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_es_questingknight_dr_handgun = { en = "Bardin: Handgun" },
    unlock_es_questingknight_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_es_questingknight_we_longbow = { en = "Kerillian: Longbow" },
    unlock_es_questingknight_we_spear = { en = "Kerillian: Spear" },
    unlock_es_questingknight_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_es_questingknight_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_es_questingknight_es_blunderbuss = { en = "Kruber: Blunderbuss" },
    unlock_es_questingknight_es_bastard_sword = { en = "Kruber: Bretonnian Longsword" },
    unlock_es_questingknight_es_sword_shield_breton = { en = "Kruber: Bretonnian Sword and Shield" },
    unlock_es_questingknight_es_2h_sword_executioner = { en = "Kruber: Executioner Sword" },
    unlock_es_questingknight_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_es_questingknight_es_halberd = { en = "Kruber: Halberd" },
    unlock_es_questingknight_es_handgun = { en = "Kruber: Handgun" },
    unlock_es_questingknight_es_longbow = { en = "Kruber: Longbow" },
    unlock_es_questingknight_es_1h_mace = { en = "Kruber: Mace" },
    unlock_es_questingknight_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_es_questingknight_es_dual_wield_hammer_sword = { en = "Kruber: Mace and Sword" },
    unlock_es_questingknight_es_repeating_handgun = { en = "Kruber: Repeating Handgun" },
    unlock_es_questingknight_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_es_questingknight_es_1h_sword = { en = "Kruber: Sword" },
    unlock_es_questingknight_es_sword_shield = { en = "Kruber: Sword and Shield" },
    unlock_es_questingknight_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_es_questingknight_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_es_questingknight_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_es_questingknight_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_es_questingknight_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_es_questingknight_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_es_questingknight_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_es_questingknight_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_es_questingknight_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_es_questingknight_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_es_questingknight_bw_sword = { en = "Sienna: Sword" },
    -- Bardin: Ranger Veteran
    unlock_dr_ranger_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_ranger_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_ranger_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_ranger_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_ranger_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_ranger_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_ranger_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_ranger_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_ranger_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_ranger_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_ranger_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_ranger_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_ranger_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_ranger_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_ranger_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_ranger_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_ranger_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_ranger_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_ranger_es_1h_mace = { en = "Kruber: Mace" },
    unlock_dr_ranger_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_dr_ranger_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_ranger_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_dr_ranger_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_dr_ranger_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_ranger_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_dr_ranger_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_ranger_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_dr_ranger_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_dr_ranger_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_dr_ranger_bw_sword = { en = "Sienna: Sword" },
    -- Bardin: Ironbreaker
    unlock_dr_ironbreaker_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_ironbreaker_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_ironbreaker_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_ironbreaker_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_ironbreaker_dr_drake_pistol = { en = "Bardin: Drakefire Pistols" },
    unlock_dr_ironbreaker_dr_drakegun = { en = "Bardin: Drakegun" },
    unlock_dr_ironbreaker_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_ironbreaker_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_ironbreaker_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_ironbreaker_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_ironbreaker_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_ironbreaker_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_ironbreaker_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_ironbreaker_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_ironbreaker_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_ironbreaker_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_ironbreaker_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_ironbreaker_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_ironbreaker_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_ironbreaker_es_1h_mace = { en = "Kruber: Mace" },
    unlock_dr_ironbreaker_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_dr_ironbreaker_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_ironbreaker_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_dr_ironbreaker_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_dr_ironbreaker_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_ironbreaker_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_dr_ironbreaker_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_ironbreaker_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_dr_ironbreaker_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_dr_ironbreaker_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_dr_ironbreaker_bw_sword = { en = "Sienna: Sword" },
    -- Bardin: Slayer
    unlock_dr_slayer_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_slayer_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_slayer_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_slayer_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_slayer_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_slayer_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_slayer_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_slayer_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_slayer_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_slayer_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_slayer_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_slayer_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_slayer_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_slayer_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_slayer_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_slayer_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_slayer_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_slayer_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_slayer_es_1h_mace = { en = "Kruber: Mace" },
    unlock_dr_slayer_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_dr_slayer_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_slayer_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_dr_slayer_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_dr_slayer_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_slayer_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_dr_slayer_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_slayer_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_dr_slayer_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_dr_slayer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_dr_slayer_bw_sword = { en = "Sienna: Sword" },
    -- Bardin: Engineer
    unlock_dr_engineer_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_dr_engineer_dr_shield_axe = { en = "Bardin: Axe and Shield" },
    unlock_dr_engineer_dr_2h_cog_hammer = { en = "Bardin: Cog Hammer" },
    unlock_dr_engineer_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_dr_engineer_dr_drake_pistol = { en = "Bardin: Drakefire Pistols" },
    unlock_dr_engineer_dr_drakegun = { en = "Bardin: Drakegun" },
    unlock_dr_engineer_dr_dual_wield_axes = { en = "Bardin: Dual Axes" },
    unlock_dr_engineer_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_dr_engineer_dr_2h_axe = { en = "Bardin: Great Axe" },
    unlock_dr_engineer_dr_2h_hammer = { en = "Bardin: Great Hammer" },
    unlock_dr_engineer_dr_rakegun = { en = "Bardin: Grudge-Raker" },
    unlock_dr_engineer_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_dr_engineer_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_dr_engineer_dr_handgun = { en = "Bardin: Handgun" },
    unlock_dr_engineer_dr_steam_pistol = { en = "Bardin: Masterwork Pistol" },
    unlock_dr_engineer_dr_1h_throwing_axes = { en = "Bardin: Throwing Axes" },
    unlock_dr_engineer_dr_deus_01 = { en = "Bardin: Trollhammer Torpedo" },
    unlock_dr_engineer_dr_2h_pick = { en = "Bardin: War Pick" },
    unlock_dr_engineer_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_dr_engineer_es_handgun = { en = "Kruber: Handgun" },
    unlock_dr_engineer_es_1h_mace = { en = "Kruber: Mace" },
    unlock_dr_engineer_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_dr_engineer_es_1h_sword = { en = "Kruber: Sword" },
    unlock_dr_engineer_es_2h_hammer = { en = "Kruber: Two-Handed Hammer" },
    unlock_dr_engineer_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_dr_engineer_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_dr_engineer_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_dr_engineer_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_dr_engineer_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_dr_engineer_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_dr_engineer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_dr_engineer_bw_sword = { en = "Sienna: Sword" },
    -- Kerillian: Waystalker
    unlock_we_waywatcher_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_we_waywatcher_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_we_waywatcher_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_waywatcher_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_waywatcher_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_waywatcher_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_waywatcher_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_waywatcher_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_waywatcher_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_waywatcher_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_waywatcher_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_waywatcher_we_spear = { en = "Kerillian: Spear" },
    unlock_we_waywatcher_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_waywatcher_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_waywatcher_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_waywatcher_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_waywatcher_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_waywatcher_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_waywatcher_es_halberd = { en = "Kruber: Halberd" },
    unlock_we_waywatcher_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_waywatcher_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_waywatcher_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_waywatcher_es_1h_sword = { en = "Kruber: Sword" },
    unlock_we_waywatcher_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_we_waywatcher_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_we_waywatcher_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_we_waywatcher_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_we_waywatcher_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_we_waywatcher_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_we_waywatcher_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_we_waywatcher_bw_sword = { en = "Sienna: Sword" },
    -- Kerillian: Handmaiden
    unlock_we_maidenguard_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_we_maidenguard_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_we_maidenguard_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_maidenguard_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_maidenguard_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_maidenguard_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_maidenguard_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_maidenguard_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_maidenguard_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_maidenguard_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_maidenguard_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_maidenguard_we_spear = { en = "Kerillian: Spear" },
    unlock_we_maidenguard_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_maidenguard_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_maidenguard_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_maidenguard_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_maidenguard_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_maidenguard_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_maidenguard_es_halberd = { en = "Kruber: Halberd" },
    unlock_we_maidenguard_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_maidenguard_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_maidenguard_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_maidenguard_es_1h_sword = { en = "Kruber: Sword" },
    unlock_we_maidenguard_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_we_maidenguard_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_we_maidenguard_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_we_maidenguard_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_we_maidenguard_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_we_maidenguard_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_we_maidenguard_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_we_maidenguard_bw_sword = { en = "Sienna: Sword" },
    -- Kerillian: Shade
    unlock_we_shade_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_we_shade_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_we_shade_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_shade_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_shade_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_shade_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_shade_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_shade_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_shade_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_shade_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_shade_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_shade_we_spear = { en = "Kerillian: Spear" },
    unlock_we_shade_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_shade_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_shade_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_shade_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_shade_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_shade_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_shade_es_halberd = { en = "Kruber: Halberd" },
    unlock_we_shade_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_shade_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_shade_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_shade_es_1h_sword = { en = "Kruber: Sword" },
    unlock_we_shade_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_we_shade_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_we_shade_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_we_shade_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_we_shade_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_we_shade_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_we_shade_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_we_shade_bw_sword = { en = "Sienna: Sword" },
    -- Kerillian: Sister of the Thorn
    unlock_we_thornsister_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_we_thornsister_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_we_thornsister_we_life_staff = { en = "Kerillian: Deepwood Staff" },
    unlock_we_thornsister_we_dual_wield_daggers = { en = "Kerillian: Dual Daggers" },
    unlock_we_thornsister_we_dual_wield_swords = { en = "Kerillian: Dual Swords" },
    unlock_we_thornsister_we_1h_axe = { en = "Kerillian: Elven Axe" },
    unlock_we_thornsister_we_2h_axe = { en = "Kerillian: Glaive" },
    unlock_we_thornsister_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_we_thornsister_we_shortbow_hagbane = { en = "Kerillian: Hagbane Short Bow" },
    unlock_we_thornsister_we_javelin = { en = "Kerillian: Javelins" },
    unlock_we_thornsister_we_longbow = { en = "Kerillian: Longbow" },
    unlock_we_thornsister_we_deus_01 = { en = "Kerillian: Moonfire Bow" },
    unlock_we_thornsister_we_spear = { en = "Kerillian: Spear" },
    unlock_we_thornsister_we_1h_spears_shield = { en = "Kerillian: Spear and Shield" },
    unlock_we_thornsister_we_shortbow = { en = "Kerillian: Swift Bow" },
    unlock_we_thornsister_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_we_thornsister_we_dual_wield_sword_dagger = { en = "Kerillian: Sword and Dagger" },
    unlock_we_thornsister_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_we_thornsister_es_2h_sword = { en = "Kruber: Greatsword" },
    unlock_we_thornsister_es_halberd = { en = "Kruber: Halberd" },
    unlock_we_thornsister_es_longbow = { en = "Kruber: Longbow" },
    unlock_we_thornsister_es_1h_mace = { en = "Kruber: Mace" },
    unlock_we_thornsister_es_deus_01 = { en = "Kruber: Spear and Shield" },
    unlock_we_thornsister_es_1h_sword = { en = "Kruber: Sword" },
    unlock_we_thornsister_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_we_thornsister_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_we_thornsister_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_we_thornsister_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_we_thornsister_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_we_thornsister_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_we_thornsister_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_we_thornsister_bw_sword = { en = "Sienna: Sword" },
    -- Saltzpyre: Witch Hunter Captain
    unlock_wh_captain_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_wh_captain_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_wh_captain_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_wh_captain_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_wh_captain_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_wh_captain_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_captain_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_captain_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_captain_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_captain_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_captain_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_captain_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_captain_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_captain_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_captain_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_captain_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_captain_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_captain_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_captain_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_captain_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_captain_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_captain_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_captain_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_captain_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_captain_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_captain_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_captain_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_captain_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_wh_captain_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_wh_captain_bw_sword = { en = "Sienna: Sword" },
    -- Saltzpyre: Bounty Hunter
    unlock_wh_bountyhunter_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_wh_bountyhunter_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_wh_bountyhunter_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_wh_bountyhunter_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_wh_bountyhunter_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_wh_bountyhunter_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_bountyhunter_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_bountyhunter_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_bountyhunter_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_bountyhunter_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_bountyhunter_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_bountyhunter_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_bountyhunter_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_bountyhunter_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_bountyhunter_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_bountyhunter_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_bountyhunter_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_bountyhunter_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_bountyhunter_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_bountyhunter_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_bountyhunter_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_bountyhunter_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_bountyhunter_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_bountyhunter_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_bountyhunter_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_bountyhunter_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_bountyhunter_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_bountyhunter_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_wh_bountyhunter_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_wh_bountyhunter_bw_sword = { en = "Sienna: Sword" },
    -- Saltzpyre: Zealot
    unlock_wh_zealot_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_wh_zealot_dr_crossbow = { en = "Bardin: Crossbow" },
    unlock_wh_zealot_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_wh_zealot_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_wh_zealot_we_2h_sword = { en = "Kerillian: Greatsword" },
    unlock_wh_zealot_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_zealot_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_zealot_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_zealot_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_zealot_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_zealot_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_zealot_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_zealot_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_zealot_wh_dual_wield_axe_falchion = { en = "Saltzpyre: Axe and Falchion" },
    unlock_wh_zealot_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_zealot_wh_brace_of_pistols = { en = "Saltzpyre: Brace of Pistols" },
    unlock_wh_zealot_wh_crossbow = { en = "Saltzpyre: Crossbow" },
    unlock_wh_zealot_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_zealot_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_zealot_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_zealot_wh_2h_sword = { en = "Saltzpyre: Greatsword" },
    unlock_wh_zealot_wh_deus_01 = { en = "Saltzpyre: Griffon-foot" },
    unlock_wh_zealot_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_zealot_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_zealot_wh_fencing_sword = { en = "Saltzpyre: Rapier" },
    unlock_wh_zealot_wh_repeating_pistols = { en = "Saltzpyre: Repeating Pistol" },
    unlock_wh_zealot_wh_crossbow_repeater = { en = "Saltzpyre: Volley Crossbow" },
    unlock_wh_zealot_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_wh_zealot_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_wh_zealot_bw_sword = { en = "Sienna: Sword" },
    -- Saltzpyre: Warrior Priest
    unlock_wh_priest_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_wh_priest_dr_dual_wield_hammers = { en = "Bardin: Dual Hammers" },
    unlock_wh_priest_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_wh_priest_dr_shield_hammer = { en = "Bardin: Hammer and Shield" },
    unlock_wh_priest_we_spear = { en = "Kerillian: Spear" },
    unlock_wh_priest_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_wh_priest_we_crossbow_repeater = { en = "Kerillian: Volley Crossbow" },
    unlock_wh_priest_es_halberd = { en = "Kruber: Halberd" },
    unlock_wh_priest_es_1h_mace = { en = "Kruber: Mace" },
    unlock_wh_priest_es_mace_shield = { en = "Kruber: Mace and Shield" },
    unlock_wh_priest_es_1h_sword = { en = "Kruber: Sword" },
    unlock_wh_priest_es_2h_heavy_spear = { en = "Kruber: Tuskgor Spear" },
    unlock_wh_priest_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_wh_priest_wh_2h_billhook = { en = "Saltzpyre: Billhook" },
    unlock_wh_priest_wh_dual_hammer = { en = "Saltzpyre: Dual Skull-Splitters" },
    unlock_wh_priest_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_wh_priest_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_wh_priest_wh_flail_shield = { en = "Saltzpyre: Flail and Shield" },
    unlock_wh_priest_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_wh_priest_wh_hammer_shield = { en = "Saltzpyre: Skull-Splitter and Shield" },
    unlock_wh_priest_wh_hammer_book = { en = "Saltzpyre: Hammer and Tome" },
    unlock_wh_priest_wh_2h_hammer = { en = "Saltzpyre: Holy Great Hammer" },
    unlock_wh_priest_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_wh_priest_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_wh_priest_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Battle Wizard
    unlock_bw_adept_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_bw_adept_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_bw_adept_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_bw_adept_es_1h_mace = { en = "Kruber: Mace" },
    unlock_bw_adept_es_1h_sword = { en = "Kruber: Sword" },
    unlock_bw_adept_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_bw_adept_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_bw_adept_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_bw_adept_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_bw_adept_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_adept_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_adept_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_adept_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_adept_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_adept_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_adept_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_adept_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_adept_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_adept_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_adept_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_adept_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_adept_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Pyromancer
    unlock_bw_scholar_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_bw_scholar_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_bw_scholar_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_bw_scholar_es_1h_mace = { en = "Kruber: Mace" },
    unlock_bw_scholar_es_1h_sword = { en = "Kruber: Sword" },
    unlock_bw_scholar_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_bw_scholar_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_bw_scholar_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_bw_scholar_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_bw_scholar_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_scholar_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_scholar_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_scholar_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_scholar_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_scholar_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_scholar_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_scholar_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_scholar_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_scholar_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_scholar_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_scholar_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_scholar_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Unchained
    unlock_bw_unchained_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_bw_unchained_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_bw_unchained_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_bw_unchained_es_1h_mace = { en = "Kruber: Mace" },
    unlock_bw_unchained_es_1h_sword = { en = "Kruber: Sword" },
    unlock_bw_unchained_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_bw_unchained_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_bw_unchained_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_bw_unchained_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_bw_unchained_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_unchained_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_unchained_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_unchained_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_unchained_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_unchained_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_unchained_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_unchained_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_unchained_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_unchained_bw_skullstaff_flamethrower = { en = "Sienna: Flamestorm Staff" },
    unlock_bw_unchained_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_unchained_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_unchained_bw_sword = { en = "Sienna: Sword" },
    -- Sienna: Necromancer
    unlock_bw_necromancer_dr_1h_axe = { en = "Bardin: Axe" },
    unlock_bw_necromancer_dr_1h_hammer = { en = "Bardin: Hammer" },
    unlock_bw_necromancer_we_1h_sword = { en = "Kerillian: Sword" },
    unlock_bw_necromancer_es_1h_mace = { en = "Kruber: Mace" },
    unlock_bw_necromancer_es_1h_sword = { en = "Kruber: Sword" },
    unlock_bw_necromancer_wh_1h_axe = { en = "Saltzpyre: Axe" },
    unlock_bw_necromancer_wh_1h_falchion = { en = "Saltzpyre: Falchion" },
    unlock_bw_necromancer_es_1h_flail = { en = "Saltzpyre: Flail" },
    unlock_bw_necromancer_wh_1h_hammer = { en = "Saltzpyre: Skull-Splitter" },
    unlock_bw_necromancer_bw_skullstaff_beam = { en = "Sienna: Beam Staff" },
    unlock_bw_necromancer_bw_skullstaff_spear = { en = "Sienna: Bolt Staff" },
    unlock_bw_necromancer_bw_skullstaff_geiser = { en = "Sienna: Conflagration Staff" },
    unlock_bw_necromancer_bw_deus_01 = { en = "Sienna: Coruscation Staff" },
    unlock_bw_necromancer_bw_1h_crowbill = { en = "Sienna: Crowbill" },
    unlock_bw_necromancer_bw_dagger = { en = "Sienna: Dagger" },
    unlock_bw_necromancer_bw_ghost_scythe = { en = "Sienna: Ensorcelled Reaper" },
    unlock_bw_necromancer_bw_skullstaff_fireball = { en = "Sienna: Fireball Staff" },
    unlock_bw_necromancer_bw_flame_sword = { en = "Sienna: Flame Sword" },
    unlock_bw_necromancer_bw_1h_flail_flaming = { en = "Sienna: Flaming Flail" },
    unlock_bw_necromancer_bw_1h_mace = { en = "Sienna: Mace" },
    unlock_bw_necromancer_bw_necromancy_staff = { en = "Sienna: Soulstealer Staff" },
    unlock_bw_necromancer_bw_sword = { en = "Sienna: Sword" },
    -- Feature toggles
    enable_weapon_unlocks_core = { en = "Enable Weapon Unlock Core" },
    enable_weapon_backend_hooks = { en = "Enable Backend Loadout Hooks" },
    enable_weapon_ui_hooks = { en = "Enable UI Inventory Hooks" },
    enable_weapon_animation_redirects = { en = "Enable Animation Redirects" },
    enable_weapon_runtime_guards = { en = "Enable Runtime Guard Hooks" },
    enable_weapon_wield_slot_guard = { en = "Enable Wield Slot Guard" },
    enable_weapon_create_equipment_guard = { en = "Enable Create Equipment Guard" },
    enable_weapon_career_action_injection = { en = "Enable Career Action Injection" },
    force_bretonnian_shield_unlock = { en = "Force Bretonnian Shield Unlock" },
    -- Forge
    forge_group = { en = "Weapon Forge" },
    forge_hotkey = { en = "Open Weapon Forge" },
    -- Debug
    debug_group = { en = "Debug" },
    debug = { en = "Debug Mode" },
    enable_weapon_debug_logging = { en = "Enable Debug Logging" },
}
