<#
.SYNOPSIS
    Rebuilds the private HUD/small portrait atlas used by DCP.

.DESCRIPTION
    Vanilla portrait identifiers resolve through UIAtlasHelper and are drawn
    with Gui.bitmap_uv. DCP's former HUD/small standalone materials fell
    through to Gui.bitmap instead; in the mission-completion portrait widget
    that branch rendered the full rectangle despite valid PNG alpha (#526).

    This script packs every 86x108 `portrait_*.png` and every 60x70
    `small_portrait_*.png` into one deterministic 512x512 atlas and writes the
    matching VMF atlas descriptor. Medium portraits remain standalone because
    their 110x130 hero-select path is already proven and intentionally
    full-bleed.

    Run this script whenever add_portrait.ps1 adds or replaces a portrait.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$modRoot = Split-Path -Parent $PSScriptRoot
$sourceDir = Join-Path $modRoot "gui\1080p\single_textures\custom_portraits"
$atlasPng = Join-Path $modRoot "textures\dynamic_cosmetic_portraits\dcp_portrait_atlas.png"
$atlasLua = Join-Path $modRoot "materials\dynamic_cosmetic_portraits\dcp_portrait_atlas.lua"
$atlasSize = 512
$padding = 2

$sprites = Get-ChildItem -LiteralPath $sourceDir -Filter "*.png" |
    Where-Object {
        $_.BaseName -like "portrait_*" -or $_.BaseName -like "small_portrait_*"
    } |
    Sort-Object @{ Expression = { if ($_.BaseName -like "small_portrait_*") { 1 } else { 0 } } }, Name

if ($sprites.Count -eq 0) {
    throw "No HUD/small portrait PNGs found under $sourceDir"
}

$atlasDir = Split-Path -Parent $atlasPng
$materialDir = Split-Path -Parent $atlasLua
[System.IO.Directory]::CreateDirectory($atlasDir) | Out-Null
[System.IO.Directory]::CreateDirectory($materialDir) | Out-Null

$atlas = New-Object System.Drawing.Bitmap $atlasSize, $atlasSize,
    ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)

$x = $padding
$y = $padding
$rowHeight = 0
$rows = New-Object System.Collections.Generic.List[object]

try {
    foreach ($spriteFile in $sprites) {
        $sprite = New-Object System.Drawing.Bitmap $spriteFile.FullName
        try {
            $expectedWidth = if ($spriteFile.BaseName -like "small_portrait_*") { 60 } else { 86 }
            $expectedHeight = if ($spriteFile.BaseName -like "small_portrait_*") { 70 } else { 108 }
            if ($sprite.Width -ne $expectedWidth -or $sprite.Height -ne $expectedHeight) {
                throw ("{0} is {1}x{2}; expected {3}x{4}" -f
                    $spriteFile.Name, $sprite.Width, $sprite.Height,
                    $expectedWidth, $expectedHeight)
            }

            if ($x + $sprite.Width + $padding -gt $atlasSize) {
                $x = $padding
                $y += $rowHeight + ($padding * 2)
                $rowHeight = 0
            }
            if ($y + $sprite.Height + $padding -gt $atlasSize) {
                throw "Portrait atlas overflow. Increase atlasSize or revise the deterministic packing policy."
            }

            # SetPixel is deliberate. GDI+ DrawImageUnscaled preserves alpha
            # but rewrites RGB under partially transparent pixels through its
            # premultiplied compositor. Exact source pixels matter at the
            # antialiased silhouette edge, and this atlas is small enough that
            # the deterministic copy cost is negligible.
            for ($py = 0; $py -lt $sprite.Height; $py++) {
                for ($px = 0; $px -lt $sprite.Width; $px++) {
                    $atlas.SetPixel($x + $px, $y + $py, $sprite.GetPixel($px, $py))
                }
            }
            $rows.Add([pscustomobject]@{
                Name = $spriteFile.BaseName
                X = $x
                Y = $y
                Width = $sprite.Width
                Height = $sprite.Height
            })

            $x += $sprite.Width + ($padding * 2)
            $rowHeight = [Math]::Max($rowHeight, $sprite.Height)
        }
        finally {
            $sprite.Dispose()
        }
    }

    $atlas.Save($atlasPng, [System.Drawing.Imaging.ImageFormat]::Png)
}
finally {
    $atlas.Dispose()
}

$culture = [System.Globalization.CultureInfo]::InvariantCulture
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("-- Generated by tools/rebuild_portrait_atlas.ps1. Do not hand-edit.")
$lines.Add("-- image source: textures/dynamic_cosmetic_portraits/dcp_portrait_atlas")
$lines.Add("local dcp_portrait_atlas = {")
foreach ($row in $rows) {
    $u0 = ($row.X / $atlasSize).ToString("0.########", $culture)
    $v0 = ($row.Y / $atlasSize).ToString("0.########", $culture)
    $u1 = (($row.X + $row.Width) / $atlasSize).ToString("0.########", $culture)
    $v1 = (($row.Y + $row.Height) / $atlasSize).ToString("0.########", $culture)
    $lines.Add(("    {0} = {{" -f $row.Name))
    $lines.Add(("        size = {{ {0}, {1} }}," -f $row.Width, $row.Height))
    $lines.Add(("        uv00 = {{ {0}, {1} }}," -f $u0, $v0))
    $lines.Add(("        uv11 = {{ {0}, {1} }}," -f $u1, $v1))
    $lines.Add("    },")
}
$lines.Add("}")
$lines.Add("")
$lines.Add("return dcp_portrait_atlas")
[System.IO.File]::WriteAllLines($atlasLua, $lines, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ("[ok] Rebuilt DCP portrait atlas: {0} sprites, {1}x{1}" -f $rows.Count, $atlasSize)
Write-Output "     PNG: $atlasPng"
Write-Output "     Lua: $atlasLua"
