local mod = get_mod("ct")

return {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "chaos_wastes_group",
                type = "group",
                sub_widgets = {
                    { setting_id = "coin_multiplier", type = "numeric", default_value = 1, range = { 0.1, 5 }, decimals_number = 2 },
                    { setting_id = "starting_coins", type = "numeric", default_value = 0, range = { 0, 3000 }, decimals_number = 0 },
                    { setting_id = "shrine_boon_count", type = "numeric", default_value = 4, range = { 1, 5 }, decimals_number = 0 },
                    { setting_id = "chest_boon_count", type = "numeric", default_value = 3, range = { 1, 5 }, decimals_number = 0 },
                    { setting_id = "force_belakor", type = "checkbox", default_value = false },
                    { setting_id = "finale_dominant_god", type = "numeric", default_value = 0, range = { 0, 4 }, decimals_number = 0 },
                    { setting_id = "chest_upgrade_count", type = "numeric", default_value = 1, range = { 0, 8 }, decimals_number = 0 },
                    { setting_id = "chest_swap_melee_count", type = "numeric", default_value = 1, range = { 0, 8 }, decimals_number = 0 },
                    { setting_id = "chest_swap_ranged_count", type = "numeric", default_value = 1, range = { 0, 8 }, decimals_number = 0 },
                    { setting_id = "chest_power_up_count", type = "numeric", default_value = 2, range = { 0, 8 }, decimals_number = 0 },
                    { setting_id = "cursed_chest_count", type = "numeric", default_value = 1, range = { 0, 10 }, decimals_number = 0 },
                    { setting_id = "arena_ammo_count", type = "numeric", default_value = 2, range = { 0, 10 }, decimals_number = 0 },
                    { setting_id = "enable_campaign_potions", type = "checkbox", default_value = false },
                    { setting_id = "any_trait_any_weapon", type = "checkbox", default_value = false },
                    {
                        setting_id = "curses_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_curse_abundance_of_life", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_belakor_totems", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_blood_storm", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_bolt_of_change", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_change_of_tzeentch", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_corrupted_flesh", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_egg_of_tzeentch", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_empathy", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_greed_pinata", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_khorne_champions", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_rotten_miasma", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_shadow_homing_skulls", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_skulking_sorcerer", type = "checkbox", default_value = false },
                            { setting_id = "disable_curse_skulls_of_fury", type = "checkbox", default_value = false },
                        },
                    },
                    {
                        setting_id = "banned_traits_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "ban_trait_always_blocking", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_armor_breaker", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_bloodthirst", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_crescendo_strike", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_ammo_pickup_reload_speed", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_big_swing_stagger", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_collateral_damage_on_melee_killing_blow", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_crit_chain_lightning", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_extra_shot", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_deus_ranged_crit_explosion", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_follow_up", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_headhunter", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_home_run", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_increased_punch_through", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_off_balance", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_power_vs_skaven", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_resourceful_combatant", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_scrounger", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_shockwave", type = "checkbox", default_value = false },
                            { setting_id = "ban_trait_swiftslaying", type = "checkbox", default_value = false },
                        },
                    },
                },
            },
        },
    },
}
