return {
    mod_name = { en = "Tweaker: Chaos Wastes" },
    mod_description = { en = "Chaos Wastes run modifiers split out from the old monolithic Tweaker mod." },
    chaos_wastes_group = { en = "Chaos Wastes" },
    curses_group = { en = "Curses" },
    banned_traits_group = { en = "Banned Weapon Traits" },
    coin_multiplier = { en = "Coin Pickup Multiplier" },
    starting_coins = { en = "Starting Coins" },
    shrine_boon_count = { en = "Shrine Boon Options" },
    chest_boon_count = { en = "Chest Boon Options" },
    force_belakor = { en = "Always Include Belakor's Temple" },
    finale_dominant_god = { en = "Finale God (0=weekly, 1=Nurgle, 2=Tzeentch, 3=Khorne, 4=Slaanesh)" },
    chest_upgrade_count = { en = "Upgrade Altars" },
    chest_swap_melee_count = { en = "Melee Swap Altars" },
    chest_swap_ranged_count = { en = "Ranged Swap Altars" },
    chest_power_up_count = { en = "Boon Altars" },
    cursed_chest_count = { en = "Chests of Trials per Mission" },
    arena_ammo_count = { en = "Arena Ammo Boxes" },
    enable_campaign_potions = { en = "Enable Strength/Speed/Ability Potions" },
    any_trait_any_weapon = { en = "Any Trait on Any Weapon" },
    disable_curse_abundance_of_life = { en = "Disable: Abundance of Life" },
    disable_curse_belakor_totems = { en = "Disable: Belakor's Totems" },
    disable_curse_blood_storm = { en = "Disable: Blood Storm" },
    disable_curse_bolt_of_change = { en = "Disable: Bolt of Change" },
    disable_curse_change_of_tzeentch = { en = "Disable: Change of Tzeentch" },
    disable_curse_corrupted_flesh = { en = "Disable: Corrupted Flesh" },
    disable_curse_egg_of_tzeentch = { en = "Disable: Egg of Tzeentch" },
    disable_curse_empathy = { en = "Disable: Empathy" },
    disable_curse_greed_pinata = { en = "Disable: Greed" },
    disable_curse_khorne_champions = { en = "Disable: Khorne Champions" },
    disable_curse_rotten_miasma = { en = "Disable: Rotten Miasma" },
    disable_curse_shadow_homing_skulls = { en = "Disable: Shadow Homing Skulls" },
    disable_curse_skulking_sorcerer = { en = "Disable: Skulking Sorcerer" },
    disable_curse_skulls_of_fury = { en = "Disable: Skulls of Fury" },
    ban_trait_always_blocking = { en = "Ban: Always Blocking" },
    ban_trait_armor_breaker = { en = "Ban: Armor Breaker" },
    ban_trait_bloodthirst = { en = "Ban: Bloodthirst" },
    ban_trait_crescendo_strike = { en = "Ban: Crescendo Strike" },
    ban_trait_deus_ammo_pickup_reload_speed = { en = "Ban: Ammo Pickup Reload Speed" },
    ban_trait_deus_big_swing_stagger = { en = "Ban: Big Swing Stagger" },
    ban_trait_deus_collateral_damage_on_melee_killing_blow = { en = "Ban: Collateral Damage on Melee Kill" },
    ban_trait_deus_crit_chain_lightning = { en = "Ban: Crit Chain Lightning" },
    ban_trait_deus_extra_shot = { en = "Ban: Extra Shot" },
    ban_trait_deus_ranged_crit_explosion = { en = "Ban: Ranged Crit Explosion" },
    ban_trait_follow_up = { en = "Ban: Follow Up" },
    ban_trait_headhunter = { en = "Ban: Headhunter" },
    ban_trait_home_run = { en = "Ban: Home Run" },
    ban_trait_increased_punch_through = { en = "Ban: Increased Punch Through" },
    ban_trait_off_balance = { en = "Ban: Off Balance" },
    ban_trait_power_vs_skaven = { en = "Ban: Power vs Skaven" },
    ban_trait_resourceful_combatant = { en = "Ban: Resourceful Combatant" },
    ban_trait_scrounger = { en = "Ban: Scrounger" },
    ban_trait_shockwave = { en = "Ban: Shockwave" },
    ban_trait_swiftslaying = { en = "Ban: Swift Slaying" },
}
