local loc = {
    mod_name = { en = "Tweaker: Chaos Wastes" },
    mod_description = { en = "Chaos Wastes run modifiers split out from the old monolithic Tweaker mod." },
    curses_group = { en = "Curses" },
    banned_traits_group = { en = "Banned Weapon Traits" },
    coin_multiplier = { en = "Coin Pickup Multiplier" },
    starting_coins = { en = "Starting Coins" },
    shrine_boon_count = { en = "Shrine Boon Options" },
    chest_boon_count = { en = "Chest Boon Options" },
    force_belakor = { en = "Always Include Belakor's Temple" },
    finale_dominant_god = { en = "Finale God (0=weekly, 1=Nurgle, 2=Tzeentch, 3=Khorne, 4=Slaanesh)" },
    chest_upgrade_count = { en = "Upgrade Altars" },
    chest_swap_melee_count = { en = "Melee Swap Altars" },
    chest_swap_ranged_count = { en = "Ranged Swap Altars" },
    chest_power_up_count = { en = "Boon Altars" },
    cursed_chest_count = { en = "Chests of Trials per Mission" },
    arena_ammo_count = { en = "Arena Ammo Boxes" },
    enable_campaign_potions = { en = "Enable Strength/Speed/Ability Potions" },
    any_trait_any_weapon = { en = "Any Trait on Any Weapon" },
    disable_curse_abundance_of_life = { en = "Disable: Abundance of Life" },
    disable_curse_belakor_totems = { en = "Disable: Belakor's Totems" },
    disable_curse_blood_storm = { en = "Disable: Blood Storm" },
    disable_curse_bolt_of_change = { en = "Disable: Bolt of Change" },
    disable_curse_change_of_tzeentch = { en = "Disable: Change of Tzeentch" },
    disable_curse_corrupted_flesh = { en = "Disable: Corrupted Flesh" },
    disable_curse_egg_of_tzeentch = { en = "Disable: Egg of Tzeentch" },
    disable_curse_empathy = { en = "Disable: Empathy" },
    disable_curse_greed_pinata = { en = "Disable: Greed" },
    disable_curse_khorne_champions = { en = "Disable: Khorne Champions" },
    disable_curse_rotten_miasma = { en = "Disable: Rotten Miasma" },
    disable_curse_shadow_homing_skulls = { en = "Disable: Shadow Homing Skulls" },
    disable_curse_skulking_sorcerer = { en = "Disable: Skulking Sorcerer" },
    disable_curse_skulls_of_fury = { en = "Disable: Skulls of Fury" },
    ban_trait_always_blocking = { en = "Ban: Always Blocking" },
    ban_trait_armor_breaker = { en = "Ban: Armor Breaker" },
    ban_trait_bloodthirst = { en = "Ban: Bloodthirst" },
    ban_trait_crescendo_strike = { en = "Ban: Crescendo Strike" },
    ban_trait_deus_ammo_pickup_reload_speed = { en = "Ban: Ammo Pickup Reload Speed" },
    ban_trait_deus_big_swing_stagger = { en = "Ban: Big Swing Stagger" },
    ban_trait_deus_collateral_damage_on_melee_killing_blow = { en = "Ban: Collateral Damage on Melee Kill" },
    ban_trait_deus_crit_chain_lightning = { en = "Ban: Crit Chain Lightning" },
    ban_trait_deus_extra_shot = { en = "Ban: Extra Shot" },
    ban_trait_deus_ranged_crit_explosion = { en = "Ban: Ranged Crit Explosion" },
    ban_trait_follow_up = { en = "Ban: Follow Up" },
    ban_trait_headhunter = { en = "Ban: Headhunter" },
    ban_trait_home_run = { en = "Ban: Home Run" },
    ban_trait_increased_punch_through = { en = "Ban: Increased Punch Through" },
    ban_trait_off_balance = { en = "Ban: Off Balance" },
    ban_trait_power_vs_skaven = { en = "Ban: Power vs Skaven" },
    ban_trait_resourceful_combatant = { en = "Ban: Resourceful Combatant" },
    ban_trait_scrounger = { en = "Ban: Scrounger" },
    ban_trait_shockwave = { en = "Ban: Shockwave" },
    ban_trait_swiftslaying = { en = "Ban: Swift Slaying" },
    disabled_boons_group = { en = "Disabled Boons" },
    starting_boons_group = { en = "Starting Boons" },
    modified_boons_group = { en = "Modified Boons" },
    tweak_reckless_swings = { en = "Tweak: Reckless Swings" },
    tweak_reckless_swings_tooltip = { en = "Reduces self-damage from 3 to 1 per hit and lowers the health threshold from 50%%%% to 25%%%%, letting the boon stay active longer." },
    disable_boon_properties_group = { en = "Properties" },
    disable_boon_talents_group = { en = "Talents" },
    disable_boon_skulls_and_sets_group = { en = "Skulls & Sets" },
    disable_boon_combat_group = { en = "Combat" },
    disable_boon_healing_and_sustain_group = { en = "Healing & Sustain" },
    disable_boon_utility_and_team_group = { en = "Utility & Team" },
    start_boon_properties_group = { en = "Properties" },
    start_boon_talents_group = { en = "Talents" },
    start_boon_skulls_and_sets_group = { en = "Skulls & Sets" },
    start_boon_combat_group = { en = "Combat" },
    start_boon_healing_and_sustain_group = { en = "Healing & Sustain" },
    start_boon_utility_and_team_group = { en = "Utility & Team" },
    -- Boon entries (generated)
    disable_boon_ability_cooldown_reduction = { en = "Cooldown Reduction" },
    start_boon_ability_cooldown_reduction = { en = "Cooldown Reduction" },
    disable_boon_ability_cooldown_reduction_tooltip = { en = "Reduces cooldown of career skill" },
    start_boon_ability_cooldown_reduction_tooltip = { en = "Reduces cooldown of career skill" },
    disable_boon_attack_speed = { en = "Attack Speed" },
    start_boon_attack_speed = { en = "Attack Speed" },
    disable_boon_attack_speed_tooltip = { en = "Increases speed of melee and ranged attacks by X" },
    start_boon_attack_speed_tooltip = { en = "Increases speed of melee and ranged attacks by X" },
    disable_boon_attack_speed_per_cooldown = { en = "Loec's Wardance" },
    start_boon_attack_speed_per_cooldown = { en = "Loec's Wardance" },
    disable_boon_attack_speed_per_cooldown_tooltip = { en = "Gain up to X%%%% Attack Speed based on your missing Ability Bar." },
    start_boon_attack_speed_per_cooldown_tooltip = { en = "Gain up to X%%%% Attack Speed based on your missing Ability Bar." },
    disable_boon_bad_breath = { en = "Sigmar's Intervention" },
    start_boon_bad_breath = { en = "Sigmar's Intervention" },
    disable_boon_bad_breath_tooltip = { en = "Every X seconds, if you are disabled a bolt of lightning knocks the disabler back." },
    start_boon_bad_breath_tooltip = { en = "Every X seconds, if you are disabled a bolt of lightning knocks the disabler back." },
    disable_boon_barkskin = { en = "Barkskin" },
    start_boon_barkskin = { en = "Barkskin" },
    disable_boon_barkskin_tooltip = { en = "Taking damage reduces the damage you take from subsequent sources by X%%%% for X seconds. This effect can only trigger every X seconds." },
    start_boon_barkskin_tooltip = { en = "Taking damage reduces the damage you take from subsequent sources by X%%%% for X seconds. This effect can only trigger every X seconds." },
    disable_boon_blazing_revenge = { en = "Addaioth's Embrace" },
    start_boon_blazing_revenge = { en = "Addaioth's Embrace" },
    disable_boon_blazing_revenge_tooltip = { en = "A halo of fire damages enemies around as long as you are downed." },
    start_boon_blazing_revenge_tooltip = { en = "A halo of fire damages enemies around as long as you are downed." },
    disable_boon_block_cost = { en = "Block Cost Reduction" },
    start_boon_block_cost = { en = "Block Cost Reduction" },
    disable_boon_block_cost_tooltip = { en = "Reduces the stamina required to block enemy attacks" },
    start_boon_block_cost_tooltip = { en = "Reduces the stamina required to block enemy attacks" },
    disable_boon_boon_aoe_02 = { en = "Ranald's Spiteful Plunder" },
    start_boon_boon_aoe_02 = { en = "Ranald's Spiteful Plunder" },
    disable_boon_boon_aoe_02_tooltip = { en = "When a Chest of Trials is activated, creates consecrated ground that grants you X%%%% Damage for X seconds." },
    start_boon_boon_aoe_02_tooltip = { en = "When a Chest of Trials is activated, creates consecrated ground that grants you X%%%% Damage for X seconds." },
    disable_boon_boon_aoe_03 = { en = "Ranald's Hearty Plunder" },
    start_boon_boon_aoe_03 = { en = "Ranald's Hearty Plunder" },
    disable_boon_boon_aoe_03_tooltip = { en = "When a Chest of Trials is activated, creates consecrated ground that grants you X%%%% Cooldown rate for X seconds." },
    start_boon_boon_aoe_03_tooltip = { en = "When a Chest of Trials is activated, creates consecrated ground that grants you X%%%% Cooldown rate for X seconds." },
    disable_boon_boon_aura_01 = { en = "Ulric's Valour" },
    start_boon_boon_aura_01 = { en = "Ulric's Valour" },
    disable_boon_boon_aura_01_tooltip = { en = "Enemies close to you take X%%%% damage from teammates." },
    start_boon_boon_aura_01_tooltip = { en = "Enemies close to you take X%%%% damage from teammates." },
    disable_boon_boon_aura_02 = { en = "Valaya's Boozy Grant" },
    start_boon_boon_aura_02 = { en = "Valaya's Boozy Grant" },
    disable_boon_boon_aura_02_tooltip = { en = "Enemies close to you take X%%%% Stagger from teammates." },
    start_boon_boon_aura_02_tooltip = { en = "Enemies close to you take X%%%% Stagger from teammates." },
    disable_boon_boon_aura_03 = { en = "Taal's Roar" },
    start_boon_boon_aura_03 = { en = "Taal's Roar" },
    disable_boon_boon_aura_03_tooltip = { en = "Periodically send out a shockwave that staggers nearby enemies. Cooldown decreases with missing health." },
    start_boon_boon_aura_03_tooltip = { en = "Periodically send out a shockwave that staggers nearby enemies. Cooldown decreases with missing health." },
    disable_boon_boon_bomb_heavy_01 = { en = "Grungni's Bombardment" },
    start_boon_boon_bomb_heavy_01 = { en = "Grungni's Bombardment" },
    disable_boon_boon_bomb_heavy_01_tooltip = { en = "Bombs have X%%%% reduced range, but have +X%%%% explosion radius and Damage." },
    start_boon_boon_bomb_heavy_01_tooltip = { en = "Bombs have X%%%% reduced range, but have +X%%%% explosion radius and Damage." },
    disable_boon_boon_careerskill_01 = { en = "Mathlann's Storm-Strike" },
    start_boon_boon_careerskill_01 = { en = "Mathlann's Storm-Strike" },
    disable_boon_boon_careerskill_01_tooltip = { en = "Your Career Skill also calls down lightning on nearby enemies." },
    start_boon_boon_careerskill_01_tooltip = { en = "Your Career Skill also calls down lightning on nearby enemies." },
    disable_boon_boon_careerskill_02 = { en = "Myrmidia's Cleansing Flame" },
    start_boon_boon_careerskill_02 = { en = "Myrmidia's Cleansing Flame" },
    disable_boon_boon_careerskill_02_tooltip = { en = "Your Career Skill also Burns nearby enemies for damage over time." },
    start_boon_boon_careerskill_02_tooltip = { en = "Your Career Skill also Burns nearby enemies for damage over time." },
    disable_boon_boon_careerskill_03 = { en = "Atharti's Venomous Affection" },
    start_boon_boon_careerskill_03 = { en = "Atharti's Venomous Affection" },
    disable_boon_boon_careerskill_03_tooltip = { en = "Your Career Skill also inflicts Poison on nearby enemies for damage over time." },
    start_boon_boon_careerskill_03_tooltip = { en = "Your Career Skill also inflicts Poison on nearby enemies for damage over time." },
    disable_boon_boon_careerskill_04 = { en = "Drakira's Flensing" },
    start_boon_boon_careerskill_04 = { en = "Drakira's Flensing" },
    disable_boon_boon_careerskill_04_tooltip = { en = "Your Career Skill also inflicts Bleed on nearby enemies." },
    start_boon_boon_careerskill_04_tooltip = { en = "Your Career Skill also inflicts Bleed on nearby enemies." },
    disable_boon_boon_careerskill_06 = { en = "Lileath's Blessed Destiny" },
    start_boon_boon_careerskill_06 = { en = "Lileath's Blessed Destiny" },
    disable_boon_boon_careerskill_06_tooltip = { en = "Increases your Career Skill maximum charge by X." },
    start_boon_boon_careerskill_06_tooltip = { en = "Increases your Career Skill maximum charge by X." },
    disable_boon_boon_careerskill_07 = { en = "Hekarti's Prophetic Bolt" },
    start_boon_boon_careerskill_07 = { en = "Hekarti's Prophetic Bolt" },
    disable_boon_boon_careerskill_07_tooltip = { en = "Your Career Skill also spawns X projectiles that seeks out enemies." },
    start_boon_boon_careerskill_07_tooltip = { en = "Your Career Skill also spawns X projectiles that seeks out enemies." },
    disable_boon_boon_deus_coins_greed = { en = "Pilgrim's Coins" },
    start_boon_boon_deus_coins_greed = { en = "Pilgrim's Coins" },
    disable_boon_boon_deus_coins_greed_tooltip = { en = "Increases the number of Pilgrim's Coins you receive." },
    start_boon_boon_deus_coins_greed_tooltip = { en = "Increases the number of Pilgrim's Coins you receive." },
    disable_boon_boon_dot_burning_01 = { en = "Myrmidia's Wildfire" },
    start_boon_boon_dot_burning_01 = { en = "Myrmidia's Wildfire" },
    disable_boon_boon_dot_burning_01_tooltip = { en = "An enemy that dies while Burning inflicts a Burning to nearby enemies, causing damage over time." },
    start_boon_boon_dot_burning_01_tooltip = { en = "An enemy that dies while Burning inflicts a Burning to nearby enemies, causing damage over time." },
    disable_boon_boon_meta_01 = { en = "Lileath's Favour" },
    start_boon_boon_meta_01 = { en = "Lileath's Favour" },
    disable_boon_boon_meta_01_tooltip = { en = "Gain X%%%% Damage and X%%%% Attack Speed per active Boon." },
    start_boon_boon_meta_01_tooltip = { en = "Gain X%%%% Damage and X%%%% Attack Speed per active Boon." },
    disable_boon_boon_range_01 = { en = "Anath Raema's Cruel Volley" },
    start_boon_boon_range_01 = { en = "Anath Raema's Cruel Volley" },
    disable_boon_boon_range_01_tooltip = { en = "Ranged attacks inflict +X%%%% Damage, but use +X%%%% ammo or Overcharge." },
    start_boon_boon_range_01_tooltip = { en = "Ranged attacks inflict +X%%%% Damage, but use +X%%%% ammo or Overcharge." },
    disable_boon_boon_range_02 = { en = "Taal's Crippling Shot" },
    start_boon_boon_range_02 = { en = "Taal's Crippling Shot" },
    disable_boon_boon_range_02_tooltip = { en = "Enemies hit with your Ranged Weapon take +X%%%% damage from you for X seconds." },
    start_boon_boon_range_02_tooltip = { en = "Enemies hit with your Ranged Weapon take +X%%%% damage from you for X seconds." },
    disable_boon_boon_skulls_01 = { en = "Righteous Frenzy" },
    start_boon_boon_skulls_01 = { en = "Righteous Frenzy" },
    disable_boon_boon_skulls_01_tooltip = { en = "X%%%% Attack Speed on hit (stacks X times). Upon X stacks, gain a further X%%%% Attack Speed for X seconds and refresh the duration of other Skull Boons." },
    start_boon_boon_skulls_01_tooltip = { en = "X%%%% Attack Speed on hit (stacks X times). Upon X stacks, gain a further X%%%% Attack Speed for X seconds and refresh the duration of other Skull Boons." },
    disable_boon_boon_skulls_02 = { en = "Righteous Strength" },
    start_boon_boon_skulls_02 = { en = "Righteous Strength" },
    disable_boon_boon_skulls_02_tooltip = { en = "X%%%% Power Level for each kill. Upon killing X enemies, gain a further X%%%% Power Level for X seconds and refresh the duration of other Skull Boons." },
    start_boon_boon_skulls_02_tooltip = { en = "X%%%% Power Level for each kill. Upon killing X enemies, gain a further X%%%% Power Level for X seconds and refresh the duration of other Skull Boons." },
    disable_boon_boon_skulls_03 = { en = "Righteous Finesse" },
    start_boon_boon_skulls_03 = { en = "Righteous Finesse" },
    disable_boon_boon_skulls_03_tooltip = { en = "Parrying an enemy inflicts a powerful Knockback and refreshes other Skull Boons. X seconds Cooldown." },
    start_boon_boon_skulls_03_tooltip = { en = "Parrying an enemy inflicts a powerful Knockback and refreshes other Skull Boons. X seconds Cooldown." },
    disable_boon_boon_skulls_04 = { en = "Righteous Regeneration" },
    start_boon_boon_skulls_04 = { en = "Righteous Regeneration" },
    disable_boon_boon_skulls_04_tooltip = { en = "Your Attacks consume up to X Temporary Health. Upon consuming X Temporary Health, gain a buff that provides X Temporary Health per second, X%%%% Cooldown Regen for X seconds and refreshes other Skull Boons." },
    start_boon_boon_skulls_04_tooltip = { en = "Your Attacks consume up to X Temporary Health. Upon consuming X Temporary Health, gain a buff that provides X Temporary Health per second, X%%%% Cooldown Regen for X seconds and refreshes other Skull Boons." },
    disable_boon_boon_skulls_05 = { en = "Righteous Smiting" },
    start_boon_boon_skulls_05 = { en = "Righteous Smiting" },
    disable_boon_boon_skulls_05_tooltip = { en = "Gain X%%%% stacking Power Level for X seconds on charged Melee Attacks. Upon reaching X Stacks, all Stacks are consumed, granting X%%%% Power Level for X seconds and refreshing the duration of all other Skulls Boons." },
    start_boon_boon_skulls_05_tooltip = { en = "Gain X%%%% stacking Power Level for X seconds on charged Melee Attacks. Upon reaching X Stacks, all Stacks are consumed, granting X%%%% Power Level for X seconds and refreshing the duration of all other Skulls Boons." },
    disable_boon_boon_skulls_06 = { en = "Skulls Power Boon" },
    start_boon_boon_skulls_06 = { en = "Skulls Power Boon" },
    disable_boon_boon_skulls_06_tooltip = { en = "+X%%%% power for every active Daemon Skull buff." },
    start_boon_boon_skulls_06_tooltip = { en = "+X%%%% power for every active Daemon Skull buff." },
    disable_boon_boon_skulls_07 = { en = "Skulls Pilgrim's Coin Boon" },
    start_boon_boon_skulls_07 = { en = "Skulls Pilgrim's Coin Boon" },
    disable_boon_boon_skulls_07_tooltip = { en = "Party members gain X Pilgrim's Coins when a Daemon Skull is picked up." },
    start_boon_boon_skulls_07_tooltip = { en = "Party members gain X Pilgrim's Coins when a Daemon Skull is picked up." },
    disable_boon_boon_skulls_08 = { en = "Skulls Cooldown Boon" },
    start_boon_boon_skulls_08 = { en = "Skulls Cooldown Boon" },
    disable_boon_boon_skulls_08_tooltip = { en = "Picking up a Daemon Skull refreshes X%%%% of your Ability Bar." },
    start_boon_boon_skulls_08_tooltip = { en = "Picking up a Daemon Skull refreshes X%%%% of your Ability Bar." },
    disable_boon_boon_skulls_set_bonus_01 = { en = "Skulls Slaughter Boon Set" },
    start_boon_boon_skulls_set_bonus_01 = { en = "Skulls Slaughter Boon Set" },
    disable_boon_boon_skulls_set_bonus_01_tooltip = { en = "Amplifies Set Effects by X%%%%. Increases duration of Set Buffs by X%%%%." },
    start_boon_boon_skulls_set_bonus_01_tooltip = { en = "Amplifies Set Effects by X%%%%. Increases duration of Set Buffs by X%%%%." },
    disable_boon_boon_skulls_set_bonus_02 = { en = "Skulls Pick Up Daemon Skull Boon Set" },
    start_boon_boon_skulls_set_bonus_02 = { en = "Skulls Pick Up Daemon Skull Boon Set" },
    disable_boon_boon_skulls_set_bonus_02_tooltip = { en = "Amplifies Set Effects by X%%%%. Increases duration of Daemon Skull Buffs by X%%%%." },
    start_boon_boon_skulls_set_bonus_02_tooltip = { en = "Amplifies Set Effects by X%%%%. Increases duration of Daemon Skull Buffs by X%%%%." },
    disable_boon_boon_supportbomb_concentration_01 = { en = "Bomb of Alchemical Concentration" },
    start_boon_boon_supportbomb_concentration_01 = { en = "Bomb of Alchemical Concentration" },
    disable_boon_boon_supportbomb_concentration_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Career Skill Cooldown rate." },
    start_boon_boon_supportbomb_concentration_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Career Skill Cooldown rate." },
    disable_boon_boon_supportbomb_crit_01 = { en = "Bomb of Alchemical Lethality" },
    start_boon_boon_supportbomb_crit_01 = { en = "Bomb of Alchemical Lethality" },
    disable_boon_boon_supportbomb_crit_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Critical Strike Chance." },
    start_boon_boon_supportbomb_crit_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Critical Strike Chance." },
    disable_boon_boon_supportbomb_healing_01 = { en = "Bomb of Alchemical Rejuvenation" },
    start_boon_boon_supportbomb_healing_01 = { en = "Bomb of Alchemical Rejuvenation" },
    disable_boon_boon_supportbomb_healing_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X healing per second." },
    start_boon_boon_supportbomb_healing_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X healing per second." },
    disable_boon_boon_supportbomb_speed_01 = { en = "Bomb of Alchemical Alacrity" },
    start_boon_boon_supportbomb_speed_01 = { en = "Bomb of Alchemical Alacrity" },
    disable_boon_boon_supportbomb_speed_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Attack Speed." },
    start_boon_boon_supportbomb_speed_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Attack Speed." },
    disable_boon_boon_supportbomb_strenght_01 = { en = "Bomb of Alchemical Strength" },
    start_boon_boon_supportbomb_strenght_01 = { en = "Bomb of Alchemical Strength" },
    disable_boon_boon_supportbomb_strenght_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Power." },
    start_boon_boon_supportbomb_strenght_01_tooltip = { en = "Your Bombs consecrate the ground for X seconds on impact. Players within the consecrated ground gain X%%%% Power." },
    disable_boon_boon_teamaura_01 = { en = "Eldrazor's Avenger" },
    start_boon_boon_teamaura_01 = { en = "Eldrazor's Avenger" },
    disable_boon_boon_teamaura_01_tooltip = { en = "You gain X%%%% Damage against enemies near to allies." },
    start_boon_boon_teamaura_01_tooltip = { en = "You gain X%%%% Damage against enemies near to allies." },
    disable_boon_boon_teamaura_02 = { en = "Vaul's Disruptor" },
    start_boon_boon_teamaura_02 = { en = "Vaul's Disruptor" },
    disable_boon_boon_teamaura_02_tooltip = { en = "You gain X%%%% Stagger against enemies near to allies." },
    start_boon_boon_teamaura_02_tooltip = { en = "You gain X%%%% Stagger against enemies near to allies." },
    disable_boon_boon_weaponrarity_01 = { en = "Ranald's Hasty Gamble" },
    start_boon_boon_weaponrarity_01 = { en = "Ranald's Hasty Gamble" },
    disable_boon_boon_weaponrarity_01_tooltip = { en = "You gain X%%%% Cooldown rate, decreased by X%%%% per Rarity Level of your Highest Rarity Weapon." },
    start_boon_boon_weaponrarity_01_tooltip = { en = "You gain X%%%% Cooldown rate, decreased by X%%%% per Rarity Level of your Highest Rarity Weapon." },
    disable_boon_boon_weaponrarity_02 = { en = "Ranald's Mighty Gamble" },
    start_boon_boon_weaponrarity_02 = { en = "Ranald's Mighty Gamble" },
    disable_boon_boon_weaponrarity_02_tooltip = { en = "You gain X%%%% Critical Hit Chance, decreased by X%%%% per Rarity Level of your Currently Equipped Weapon." },
    start_boon_boon_weaponrarity_02_tooltip = { en = "You gain X%%%% Critical Hit Chance, decreased by X%%%% per Rarity Level of your Currently Equipped Weapon." },
    disable_boon_boonset_crit_set_bonus = { en = "Divine Grant of Immortal Might" },
    start_boon_boonset_crit_set_bonus = { en = "Divine Grant of Immortal Might" },
    disable_boon_boonset_crit_set_bonus_tooltip = { en = "All Heavy Attacks cause Critical Hits" },
    start_boon_boonset_crit_set_bonus_tooltip = { en = "All Heavy Attacks cause Critical Hits" },
    disable_boon_boonset_drone_part1 = { en = "Harrying Boon of Anath Raema's Precision" },
    start_boon_boonset_drone_part1 = { en = "Harrying Boon of Anath Raema's Precision" },
    disable_boon_boonset_drone_part1_tooltip = { en = "Headshots spawn X projectiles that seek out enemies" },
    start_boon_boonset_drone_part1_tooltip = { en = "Headshots spawn X projectiles that seek out enemies" },
    disable_boon_boonset_drone_part2 = { en = "Harrying Boon of Anath Raema's Deflection" },
    start_boon_boonset_drone_part2 = { en = "Harrying Boon of Anath Raema's Deflection" },
    disable_boon_boonset_drone_part2_tooltip = { en = "Parries spawn X projectiles that seek out enemies" },
    start_boon_boonset_drone_part2_tooltip = { en = "Parries spawn X projectiles that seek out enemies" },
    disable_boon_boonset_drone_part3 = { en = "Harrying Boon of Anath Raema's Perfection" },
    start_boon_boonset_drone_part3 = { en = "Harrying Boon of Anath Raema's Perfection" },
    disable_boon_boonset_drone_part3_tooltip = { en = "Critical Hits spawn X projectiles that seek out enemies" },
    start_boon_boonset_drone_part3_tooltip = { en = "Critical Hits spawn X projectiles that seek out enemies" },
    disable_boon_boonset_drone_part4 = { en = "Grand Boon of Anath Raema" },
    start_boon_boonset_drone_part4 = { en = "Grand Boon of Anath Raema" },
    disable_boon_boonset_drone_part4_tooltip = { en = "Increases the number of projectiles spawned by the set's boons by X" },
    start_boon_boonset_drone_part4_tooltip = { en = "Increases the number of projectiles spawned by the set's boons by X" },
    disable_boon_boulder_bro = { en = "Khsar's Uplift" },
    start_boon_boulder_bro = { en = "Khsar's Uplift" },
    disable_boon_boulder_bro_tooltip = { en = "When hanging from a ledge, automatically recover." },
    start_boon_boulder_bro_tooltip = { en = "When hanging from a ledge, automatically recover." },
    disable_boon_cluster_barrel = { en = "Ranald's Explosive Surprise" },
    start_boon_cluster_barrel = { en = "Ranald's Explosive Surprise" },
    disable_boon_cluster_barrel_tooltip = { en = "When you trigger a barrel explosion, the barrel spawns smaller barrels. These explode after a short time." },
    start_boon_cluster_barrel_tooltip = { en = "When you trigger a barrel explosion, the barrel spawns smaller barrels. These explode after a short time." },
    disable_boon_comradery = { en = "Valaya's Heart" },
    start_boon_comradery = { en = "Valaya's Heart" },
    disable_boon_comradery_tooltip = { en = "Gain X%%%% Melee Power for each nearby ally." },
    start_boon_comradery_tooltip = { en = "Gain X%%%% Melee Power for each nearby ally." },
    disable_boon_cooldown_on_friendly_ability = { en = "Hekarti's Jealousy" },
    start_boon_cooldown_on_friendly_ability = { en = "Hekarti's Jealousy" },
    disable_boon_cooldown_on_friendly_ability_tooltip = { en = "Each time a nearby ally uses their Career Skill you replenish X%%%% of your Ability Bar." },
    start_boon_cooldown_on_friendly_ability_tooltip = { en = "Each time a nearby ally uses their Career Skill you replenish X%%%% of your Ability Bar." },
    disable_boon_crit_boost = { en = "Crit Power" },
    start_boon_crit_boost = { en = "Crit Power" },
    disable_boon_crit_boost_tooltip = { en = "Increases the power of critical strikes by X%%%%" },
    start_boon_crit_boost_tooltip = { en = "Increases the power of critical strikes by X%%%%" },
    disable_boon_crit_chance = { en = "Crit Chance" },
    start_boon_crit_chance = { en = "Crit Chance" },
    disable_boon_crit_chance_tooltip = { en = "Increases chance of triggering a critical attack" },
    start_boon_crit_chance_tooltip = { en = "Increases chance of triggering a critical attack" },
    disable_boon_curative_empowerment = { en = "Atharti's Vigour" },
    start_boon_curative_empowerment = { en = "Atharti's Vigour" },
    disable_boon_curative_empowerment_tooltip = { en = "Healing an ally with a health pack grants both of you X%%%% Power for X seconds." },
    start_boon_curative_empowerment_tooltip = { en = "Healing an ally with a health pack grants both of you X%%%% Power for X seconds." },
    disable_boon_curse_resistance = { en = "Curse Resistance" },
    start_boon_curse_resistance = { en = "Curse Resistance" },
    disable_boon_curse_resistance_tooltip = { en = "Reduces the negative effect of holding cursed items" },
    start_boon_curse_resistance_tooltip = { en = "Reduces the negative effect of holding cursed items" },
    disable_boon_decanter = { en = "Decanter" },
    start_boon_decanter = { en = "Decanter" },
    disable_boon_decanter_tooltip = { en = "Increases the duration of potions by X%%%%." },
    start_boon_decanter_tooltip = { en = "Increases the duration of potions by X%%%%." },
    disable_boon_detect_weakness = { en = "Taal's Hunt" },
    start_boon_detect_weakness = { en = "Taal's Hunt" },
    disable_boon_detect_weakness_tooltip = { en = "When you kill enemies marked as Taal's quarry, you gain +X%%%% Power for Xs" },
    start_boon_detect_weakness_tooltip = { en = "When you kill enemies marked as Taal's quarry, you gain +X%%%% Power for Xs" },
    disable_boon_deus_ammo_pickup_give_allies_ammo = { en = "Mathlann's Bounty" },
    start_boon_deus_ammo_pickup_give_allies_ammo = { en = "Mathlann's Bounty" },
    disable_boon_deus_ammo_pickup_give_allies_ammo_tooltip = { en = "When you pick up ammunition nearby party members regain X%%%% of their ammo." },
    start_boon_deus_ammo_pickup_give_allies_ammo_tooltip = { en = "When you pick up ammunition nearby party members regain X%%%% of their ammo." },
    disable_boon_deus_ammo_pickup_heal = { en = "Ualapt's Cunning" },
    start_boon_deus_ammo_pickup_heal = { en = "Ualapt's Cunning" },
    disable_boon_deus_ammo_pickup_heal_tooltip = { en = "Picking up ammunition grants X health." },
    start_boon_deus_ammo_pickup_heal_tooltip = { en = "Picking up ammunition grants X health." },
    disable_boon_deus_barrel_power = { en = "Ranald's Surprise" },
    start_boon_deus_barrel_power = { en = "Ranald's Surprise" },
    disable_boon_deus_barrel_power_tooltip = { en = "Powder Barrels you ignite deal X%%%% increased damage." },
    start_boon_deus_barrel_power_tooltip = { en = "Powder Barrels you ignite deal X%%%% increased damage." },
    disable_boon_deus_block_procs_parry = { en = "Hoeth's Sword-craft" },
    start_boon_deus_block_procs_parry = { en = "Hoeth's Sword-craft" },
    disable_boon_deus_block_procs_parry_tooltip = { en = "Every block counts as a parry." },
    start_boon_deus_block_procs_parry_tooltip = { en = "Every block counts as a parry." },
    disable_boon_deus_coin_pickup_regen = { en = "Bögenauer's Prosperity" },
    start_boon_deus_coin_pickup_regen = { en = "Bögenauer's Prosperity" },
    disable_boon_deus_coin_pickup_regen_tooltip = { en = "When you pick up Pilgrims' Coins, receive a moderate health regen for X seconds." },
    start_boon_deus_coin_pickup_regen_tooltip = { en = "When you pick up Pilgrims' Coins, receive a moderate health regen for X seconds." },
    disable_boon_deus_cooldown_reg_not_hit = { en = "Ladrielle's Meditation" },
    start_boon_deus_cooldown_reg_not_hit = { en = "Ladrielle's Meditation" },
    disable_boon_deus_cooldown_reg_not_hit_tooltip = { en = "Each X seconds not getting hit increases your Career Skill regeneration by X%%%%. Max stacks X." },
    start_boon_deus_cooldown_reg_not_hit_tooltip = { en = "Each X seconds not getting hit increases your Career Skill regeneration by X%%%%. Max stacks X." },
    disable_boon_deus_cooldown_regen = { en = "Verena's Inspiration" },
    start_boon_deus_cooldown_regen = { en = "Verena's Inspiration" },
    disable_boon_deus_cooldown_regen_tooltip = { en = "Increases Ability Bar cooldown rate by X%%%%." },
    start_boon_deus_cooldown_regen_tooltip = { en = "Increases Ability Bar cooldown rate by X%%%%." },
    disable_boon_deus_crit_on_damage_taken = { en = "Caxuatn's Frenzy" },
    start_boon_deus_crit_on_damage_taken = { en = "Caxuatn's Frenzy" },
    disable_boon_deus_crit_on_damage_taken_tooltip = { en = "Taking damage grants you guaranteed critical hits for X seconds." },
    start_boon_deus_crit_on_damage_taken_tooltip = { en = "Taking damage grants you guaranteed critical hits for X seconds." },
    disable_boon_deus_damage_reduction_on_incapacitated = { en = "Estreuth's Abstinence" },
    start_boon_deus_damage_reduction_on_incapacitated = { en = "Estreuth's Abstinence" },
    disable_boon_deus_damage_reduction_on_incapacitated_tooltip = { en = "Taking damage while incapacitated grants you X%%%% damage reduction for X seconds." },
    start_boon_deus_damage_reduction_on_incapacitated_tooltip = { en = "Taking damage while incapacitated grants you X%%%% damage reduction for X seconds." },
    disable_boon_deus_extra_stamina = { en = "Quetzl's Protection" },
    start_boon_deus_extra_stamina = { en = "Quetzl's Protection" },
    disable_boon_deus_extra_stamina_tooltip = { en = "Gain X stamina shields." },
    start_boon_deus_extra_stamina_tooltip = { en = "Gain X stamina shields." },
    disable_boon_deus_free_potion_use_on_ability = { en = "Valaya's Brew" },
    start_boon_deus_free_potion_use_on_ability = { en = "Valaya's Brew" },
    disable_boon_deus_free_potion_use_on_ability_tooltip = { en = "Using your Career Skill has a X%%%% chance of granting you the effect of the potion you are currently carrying." },
    start_boon_deus_free_potion_use_on_ability_tooltip = { en = "Using your Career Skill has a X%%%% chance of granting you the effect of the potion you are currently carrying." },
    disable_boon_deus_grenade_multi_throw = { en = "Sigmar's Comet" },
    start_boon_deus_grenade_multi_throw = { en = "Sigmar's Comet" },
    disable_boon_deus_grenade_multi_throw_tooltip = { en = "Throwing a bomb throws one additional bomb (of the same type)." },
    start_boon_deus_grenade_multi_throw_tooltip = { en = "Throwing a bomb throws one additional bomb (of the same type)." },
    disable_boon_deus_guard_aura_check = { en = "The Lady of the Lake's Vigil" },
    start_boon_deus_guard_aura_check = { en = "The Lady of the Lake's Vigil" },
    disable_boon_deus_guard_aura_check_tooltip = { en = "When you are above X%%%% Health you take half of the damage inflicted on nearby allies instead of them." },
    start_boon_deus_guard_aura_check_tooltip = { en = "When you are above X%%%% Health you take half of the damage inflicted on nearby allies instead of them." },
    disable_boon_deus_health_regeneration = { en = "Shallya's Rejuvenation" },
    start_boon_deus_health_regeneration = { en = "Shallya's Rejuvenation" },
    disable_boon_deus_health_regeneration_tooltip = { en = "Regenerate X health every X seconds." },
    start_boon_deus_health_regeneration_tooltip = { en = "Regenerate X health every X seconds." },
    disable_boon_deus_increased_healing_taken = { en = "Isha's Embrace" },
    start_boon_deus_increased_healing_taken = { en = "Isha's Embrace" },
    disable_boon_deus_increased_healing_taken_tooltip = { en = "Increase healing received by X%%%%." },
    start_boon_deus_increased_healing_taken_tooltip = { en = "Increase healing received by X%%%%." },
    disable_boon_deus_infinite_dodges = { en = "Lileath's Grace" },
    start_boon_deus_infinite_dodges = { en = "Lileath's Grace" },
    disable_boon_deus_infinite_dodges_tooltip = { en = "Removes the limit on dodging efficiently." },
    start_boon_deus_infinite_dodges_tooltip = { en = "Removes the limit on dodging efficiently." },
    disable_boon_deus_knockdown_damage_immunity_aura = { en = "Morr's Protection" },
    start_boon_deus_knockdown_damage_immunity_aura = { en = "Morr's Protection" },
    disable_boon_deus_knockdown_damage_immunity_aura_tooltip = { en = "Downed friends near you are invulnerable." },
    start_boon_deus_knockdown_damage_immunity_aura_tooltip = { en = "Downed friends near you are invulnerable." },
    disable_boon_deus_large_ammo_pickup_infinite_ammo = { en = "Nethu's Relentlessness" },
    start_boon_deus_large_ammo_pickup_infinite_ammo = { en = "Nethu's Relentlessness" },
    disable_boon_deus_large_ammo_pickup_infinite_ammo_tooltip = { en = "Picking up ammunition or using a crate grants infinite ammo and makes reloading unnecessary for X seconds." },
    start_boon_deus_large_ammo_pickup_infinite_ammo_tooltip = { en = "Picking up ammunition or using a crate grants infinite ammo and makes reloading unnecessary for X seconds." },
    disable_boon_deus_larger_clip = { en = "Grungni's Gift" },
    start_boon_deus_larger_clip = { en = "Grungni's Gift" },
    disable_boon_deus_larger_clip_tooltip = { en = "Increase the number of shots you make before reloading by X%%%%." },
    start_boon_deus_larger_clip_tooltip = { en = "Increase the number of shots you make before reloading by X%%%%." },
    disable_boon_deus_max_health = { en = "Ursun's Fortitude" },
    start_boon_deus_max_health = { en = "Ursun's Fortitude" },
    disable_boon_deus_max_health_tooltip = { en = "Max health increased by X%%%%." },
    start_boon_deus_max_health_tooltip = { en = "Max health increased by X%%%%." },
    disable_boon_deus_more_head_less_body_damage = { en = "Kurnous' Precision" },
    start_boon_deus_more_head_less_body_damage = { en = "Kurnous' Precision" },
    disable_boon_deus_more_head_less_body_damage_tooltip = { en = "Increases headshot damage by X%%%%. Lowers non-headshot damage by X%%%%." },
    start_boon_deus_more_head_less_body_damage_tooltip = { en = "Increases headshot damage by X%%%%. Lowers non-headshot damage by X%%%%." },
    disable_boon_deus_parry_damage_immune = { en = "Eldrazor's Deflection" },
    start_boon_deus_parry_damage_immune = { en = "Eldrazor's Deflection" },
    disable_boon_deus_parry_damage_immune_tooltip = { en = "Parrying an attack makes you immune to damage for the next X seconds." },
    start_boon_deus_parry_damage_immune_tooltip = { en = "Parrying an attack makes you immune to damage for the next X seconds." },
    disable_boon_deus_power_up_quest_granted_test_01 = { en = "Power Up Quest Granted Test 01" },
    start_boon_deus_power_up_quest_granted_test_01 = { en = "Power Up Quest Granted Test 01" },
    disable_boon_deus_powerup_attack_speed = { en = "Khsar's Speed" },
    start_boon_deus_powerup_attack_speed = { en = "Khsar's Speed" },
    disable_boon_deus_powerup_attack_speed_tooltip = { en = "Gain X%%%% Attack Speed." },
    start_boon_deus_powerup_attack_speed_tooltip = { en = "Gain X%%%% Attack Speed." },
    disable_boon_deus_push_charge = { en = "Gork's (or Mork's?) Might" },
    start_boon_deus_push_charge = { en = "Gork's (or Mork's?) Might" },
    disable_boon_deus_push_charge_tooltip = { en = "Pushing an enemy makes you do a short charge forwards." },
    start_boon_deus_push_charge_tooltip = { en = "Pushing an enemy makes you do a short charge forwards." },
    disable_boon_deus_push_cost_reduction = { en = "Hukon's Strength" },
    start_boon_deus_push_cost_reduction = { en = "Hukon's Strength" },
    disable_boon_deus_push_cost_reduction_tooltip = { en = "Reduce push cost by X%%%%." },
    start_boon_deus_push_cost_reduction_tooltip = { en = "Reduce push cost by X%%%%." },
    disable_boon_deus_push_increased_cleave = { en = "Geheb's Brawn" },
    start_boon_deus_push_increased_cleave = { en = "Geheb's Brawn" },
    disable_boon_deus_push_increased_cleave_tooltip = { en = "Pushing increases Cleave by X%%%% for X seconds." },
    start_boon_deus_push_increased_cleave_tooltip = { en = "Pushing increases Cleave by X%%%% for X seconds." },
    disable_boon_deus_reckless_swings = { en = "Khaine's Fury" },
    start_boon_deus_reckless_swings = { en = "Khaine's Fury" },
    disable_boon_deus_reckless_swings_tooltip = { en = "While above 25%%%% Health, gain 25%%%% Power but take 1 damage on each melee hit." },
    start_boon_deus_reckless_swings_tooltip = { en = "While above 25%%%% Health, gain 25%%%% Power but take 1 damage on each melee hit." },
    disable_boon_deus_revive_regen = { en = "Esmerelda's Solace" },
    start_boon_deus_revive_regen = { en = "Esmerelda's Solace" },
    disable_boon_deus_revive_regen_tooltip = { en = "Reviving a teammate grants both of you health regeneration for X seconds." },
    start_boon_deus_revive_regen_tooltip = { en = "Reviving a teammate grants both of you health regeneration for X seconds." },
    disable_boon_deus_second_wind = { en = "Grimnir's Implacability" },
    start_boon_deus_second_wind = { en = "Grimnir's Implacability" },
    disable_boon_deus_second_wind_tooltip = { en = "Falling below X%%%% health grants you X%%%% Attack Speed and Movement Speed and prevents incoming damage for X seconds." },
    start_boon_deus_second_wind_tooltip = { en = "Falling below X%%%% health grants you X%%%% Attack Speed and Movement Speed and prevents incoming damage for X seconds." },
    disable_boon_deus_skill_on_special_kill = { en = "Drakira's Thirst" },
    start_boon_deus_skill_on_special_kill = { en = "Drakira's Thirst" },
    disable_boon_deus_skill_on_special_kill_tooltip = { en = "Killing a Special replenishes X%%%% of your Ability Bar." },
    start_boon_deus_skill_on_special_kill_tooltip = { en = "Killing a Special replenishes X%%%% of your Ability Bar." },
    disable_boon_deus_standing_still_damage_reduction = { en = "Ptra's Endurance" },
    start_boon_deus_standing_still_damage_reduction = { en = "Ptra's Endurance" },
    disable_boon_deus_standing_still_damage_reduction_tooltip = { en = "Standing still grants you X%%%% damage reduction." },
    start_boon_deus_standing_still_damage_reduction_tooltip = { en = "Standing still grants you X%%%% damage reduction." },
    disable_boon_deus_target_full_health_damage_mult = { en = "Ellinill's Withering" },
    start_boon_deus_target_full_health_damage_mult = { en = "Ellinill's Withering" },
    disable_boon_deus_target_full_health_damage_mult_tooltip = { en = "Attacks against full health enemies deal X%%%% more damage." },
    start_boon_deus_target_full_health_damage_mult_tooltip = { en = "Attacks against full health enemies deal X%%%% more damage." },
    disable_boon_deus_throw_speed_increase = { en = "Hashut's Greeting" },
    start_boon_deus_throw_speed_increase = { en = "Hashut's Greeting" },
    disable_boon_deus_throw_speed_increase_tooltip = { en = "Throw objects with double speed." },
    start_boon_deus_throw_speed_increase_tooltip = { en = "Throw objects with double speed." },
    disable_boon_deus_timed_block_free_shot = { en = "Atharti's Sting" },
    start_boon_deus_timed_block_free_shot = { en = "Atharti's Sting" },
    disable_boon_deus_timed_block_free_shot_tooltip = { en = "Parrying an attack makes your next shot not cost any ammunition." },
    start_boon_deus_timed_block_free_shot_tooltip = { en = "Parrying an attack makes your next shot not cost any ammunition." },
    disable_boon_deus_transmute_into_coins = { en = "Smednir's Transmutation" },
    start_boon_deus_transmute_into_coins = { en = "Smednir's Transmutation" },
    disable_boon_deus_transmute_into_coins_tooltip = { en = "Charged melee headshots have low chance of transmuting the target into a bag of coins." },
    start_boon_deus_transmute_into_coins_tooltip = { en = "Charged melee headshots have low chance of transmuting the target into a bag of coins." },
    disable_boon_deus_uninterruptable_attacks = { en = "Ulric's Grim Resolve" },
    start_boon_deus_uninterruptable_attacks = { en = "Ulric's Grim Resolve" },
    disable_boon_deus_uninterruptable_attacks_tooltip = { en = "Your attacks cannot be interrupted." },
    start_boon_deus_uninterruptable_attacks_tooltip = { en = "Your attacks cannot be interrupted." },
    disable_boon_drop_item_on_ability_use = { en = "Kalita's Barter" },
    start_boon_drop_item_on_ability_use = { en = "Kalita's Barter" },
    disable_boon_drop_item_on_ability_use_tooltip = { en = "Using your Career Skill will drop a duplicate of one of your inventory items. Cooldown of this effect depends on the strength of the item." },
    start_boon_drop_item_on_ability_use_tooltip = { en = "Using your Career Skill will drop a duplicate of one of your inventory items. Cooldown of this effect depends on the strength of the item." },
    disable_boon_explosive_kills_on_elite_kills = { en = "Dazh's Peculiar Mirth" },
    start_boon_explosive_kills_on_elite_kills = { en = "Dazh's Peculiar Mirth" },
    disable_boon_explosive_kills_on_elite_kills_tooltip = { en = "After killing an elite with a melee attack the next enemy you kill will explode." },
    start_boon_explosive_kills_on_elite_kills_tooltip = { en = "After killing an elite with a melee attack the next enemy you kill will explode." },
    disable_boon_explosive_ordinance = { en = "Explosive Ordnance" },
    start_boon_explosive_ordinance = { en = "Explosive Ordnance" },
    disable_boon_explosive_ordinance_tooltip = { en = "Increases grenade explosion radius by X%%%%." },
    start_boon_explosive_ordinance_tooltip = { en = "Increases grenade explosion radius by X%%%%." },
    disable_boon_explosive_pushes_on_damage_taken = { en = "Chotec's Touch" },
    start_boon_explosive_pushes_on_damage_taken = { en = "Chotec's Touch" },
    disable_boon_explosive_pushes_on_damage_taken_tooltip = { en = "Taking damage makes pushes explosive for X seconds." },
    start_boon_explosive_pushes_on_damage_taken_tooltip = { en = "Taking damage makes pushes explosive for X seconds." },
    disable_boon_fatigue_regen = { en = "Stamina Recovery" },
    start_boon_fatigue_regen = { en = "Stamina Recovery" },
    disable_boon_fatigue_regen_tooltip = { en = "Increases the rate at which stamina is recovered" },
    start_boon_fatigue_regen_tooltip = { en = "Increases the rate at which stamina is recovered" },
    disable_boon_focused_accuracy = { en = "Nethu's Harvest" },
    start_boon_focused_accuracy = { en = "Nethu's Harvest" },
    disable_boon_focused_accuracy_tooltip = { en = "Every X seconds, when you inflict a headshot on an enemy, spawn an Essence Orb at their location. The Essence Orb grants increased Cooldown Regeneration for X seconds." },
    start_boon_focused_accuracy_tooltip = { en = "Every X seconds, when you inflict a headshot on an enemy, spawn an Essence Orb at their location. The Essence Orb grants increased Cooldown Regeneration for X seconds." },
    disable_boon_friendly_cooldown_on_ability = { en = "Xokha's Duty" },
    start_boon_friendly_cooldown_on_ability = { en = "Xokha's Duty" },
    disable_boon_friendly_cooldown_on_ability_tooltip = { en = "Using your Career Skill returns X%%%% of nearby allies' Ability Bars." },
    start_boon_friendly_cooldown_on_ability_tooltip = { en = "Using your Career Skill returns X%%%% of nearby allies' Ability Bars." },
    disable_boon_grenadier = { en = "Grenadier" },
    start_boon_grenadier = { en = "Grenadier" },
    disable_boon_grenadier_tooltip = { en = "X%%%% chance to not consume grenade on use." },
    start_boon_grenadier_tooltip = { en = "X%%%% chance to not consume grenade on use." },
    disable_boon_hand_of_shallya = { en = "Hand of Shallya" },
    start_boon_hand_of_shallya = { en = "Hand of Shallya" },
    disable_boon_hand_of_shallya_tooltip = { en = "Healing yourself with a First Aid Kit or a Healing Draught also heals your nearby allies for X%%%% of their maximum health. Clears any wounds." },
    start_boon_hand_of_shallya_tooltip = { en = "Healing yourself with a First Aid Kit or a Healing Draught also heals your nearby allies for X%%%% of their maximum health. Clears any wounds." },
    disable_boon_heal_on_dot_damage_dealt = { en = "Atharti's Malice" },
    start_boon_heal_on_dot_damage_dealt = { en = "Atharti's Malice" },
    disable_boon_heal_on_dot_damage_dealt_tooltip = { en = "Damaging enemies with damage over time effects grants X health." },
    start_boon_heal_on_dot_damage_dealt_tooltip = { en = "Damaging enemies with damage over time effects grants X health." },
    disable_boon_healers_touch = { en = "Healers Touch" },
    start_boon_healers_touch = { en = "Healers Touch" },
    disable_boon_healers_touch_tooltip = { en = "X%%%% chance to not consume healing item on use." },
    start_boon_healers_touch_tooltip = { en = "X%%%% chance to not consume healing item on use." },
    disable_boon_health = { en = "Health" },
    start_boon_health = { en = "Health" },
    disable_boon_health_tooltip = { en = "Increases max health" },
    start_boon_health_tooltip = { en = "Increases max health" },
    disable_boon_health_orbs = { en = "Caxuatan's Boiling Blood" },
    start_boon_health_orbs = { en = "Caxuatan's Boiling Blood" },
    disable_boon_health_orbs_tooltip = { en = "Spawn a Blood Orb for every X Health (or Temporary Health) damage taken. Each Blood Orb grants X Temporary Health." },
    start_boon_health_orbs_tooltip = { en = "Spawn a Blood Orb for every X Health (or Temporary Health) damage taken. Each Blood Orb grants X Temporary Health." },
    disable_boon_hidden_escape = { en = "Ladrielle's Veil" },
    start_boon_hidden_escape = { en = "Ladrielle's Veil" },
    disable_boon_hidden_escape_tooltip = { en = "Every X seconds, taking damage grants invisibility for Xs. Attacking removes the invisibility." },
    start_boon_hidden_escape_tooltip = { en = "Every X seconds, taking damage grants invisibility for Xs. Attacking removes the invisibility." },
    disable_boon_home_brewer = { en = "Home Brewer" },
    start_boon_home_brewer = { en = "Home Brewer" },
    disable_boon_home_brewer_tooltip = { en = "X%%%% chance to not consume potion on use." },
    start_boon_home_brewer_tooltip = { en = "X%%%% chance to not consume potion on use." },
    disable_boon_indomitable = { en = "Djaf's Rejection" },
    start_boon_indomitable = { en = "Djaf's Rejection" },
    disable_boon_indomitable_tooltip = { en = "You will always be downed, rather than be killed outright. (You can still bleed out.)" },
    start_boon_indomitable_tooltip = { en = "You will always be downed, rather than be killed outright. (You can still bleed out.)" },
    disable_boon_invigorating_strike = { en = "Grimnir's Mettle" },
    start_boon_invigorating_strike = { en = "Grimnir's Mettle" },
    disable_boon_invigorating_strike_tooltip = { en = "Every X seconds your next attack grants you Temporary Health. The amount of Temporary Health gains depends on the damage inflicted." },
    start_boon_invigorating_strike_tooltip = { en = "Every X seconds your next attack grants you Temporary Health. The amount of Temporary Health gains depends on the damage inflicted." },
    disable_boon_last_player_standing_power_reg = { en = "Ereth Khial's Pride" },
    start_boon_last_player_standing_power_reg = { en = "Ereth Khial's Pride" },
    disable_boon_last_player_standing_power_reg_tooltip = { en = "Gain X%%%% Power and rapid health regeneration for X seconds when all your allies are downed." },
    start_boon_last_player_standing_power_reg_tooltip = { en = "Gain X%%%% Power and rapid health regeneration for X seconds when all your allies are downed." },
    disable_boon_lucky = { en = "Hoeth's Method" },
    start_boon_lucky = { en = "Hoeth's Method" },
    disable_boon_lucky_tooltip = { en = "Each Attack that doesn't causes a Critical Hit adds X%%%% Critical Chance to the next Attack. These bonuses stack, and reset after making a Critical Hit." },
    start_boon_lucky_tooltip = { en = "Each Attack that doesn't causes a Critical Hit adds X%%%% Critical Chance to the next Attack. These bonuses stack, and reset after making a Critical Hit." },
    disable_boon_melee_killing_spree_speed = { en = "Stromfels' Savagery" },
    start_boon_melee_killing_spree_speed = { en = "Stromfels' Savagery" },
    disable_boon_melee_killing_spree_speed_tooltip = { en = "Killing X enemies with melee attacks in quick succession grants X%%%% attack speed and movement speed for X seconds." },
    start_boon_melee_killing_spree_speed_tooltip = { en = "Killing X enemies with melee attacks in quick succession grants X%%%% attack speed and movement speed for X seconds." },
    disable_boon_melee_wave = { en = "Hukon's Sundering" },
    start_boon_melee_wave = { en = "Hukon's Sundering" },
    disable_boon_melee_wave_tooltip = { en = "After using your Career Skill your next X Melee Attacks launch a shockwave that damages and stagger enemies." },
    start_boon_melee_wave_tooltip = { en = "After using your Career Skill your next X Melee Attacks launch a shockwave that damages and stagger enemies." },
    disable_boon_missing_health_power_up = { en = "Khaine's Thirst" },
    start_boon_missing_health_power_up = { en = "Khaine's Thirst" },
    disable_boon_missing_health_power_up_tooltip = { en = "X%%%% Damage Reduction for every X Health lost. Stacks up to X times." },
    start_boon_missing_health_power_up_tooltip = { en = "X%%%% Damage Reduction for every X Health lost. Stacks up to X times." },
    disable_boon_money_magnet = { en = "Smednir's Wealth" },
    start_boon_money_magnet = { en = "Smednir's Wealth" },
    disable_boon_money_magnet_tooltip = { en = "Auto-pickup Pilgrim's Coins in a Xm radius." },
    start_boon_money_magnet_tooltip = { en = "Auto-pickup Pilgrim's Coins in a Xm radius." },
    disable_boon_movement_speed_on_active_ability_use = { en = "Mork's (or Gork's?) Onslaught" },
    start_boon_movement_speed_on_active_ability_use = { en = "Mork's (or Gork's?) Onslaught" },
    disable_boon_movement_speed_on_active_ability_use_tooltip = { en = "Using your career skill grants X%%%% movement speed for X seconds." },
    start_boon_movement_speed_on_active_ability_use_tooltip = { en = "Using your career skill grants X%%%% movement speed for X seconds." },
    disable_boon_movespeed = { en = "Movement Speed" },
    start_boon_movespeed = { en = "Movement Speed" },
    disable_boon_movespeed_tooltip = { en = "Increases the speed of passive movement" },
    start_boon_movespeed_tooltip = { en = "Increases the speed of passive movement" },
    disable_boon_natural_bond = { en = "Natural Bond" },
    start_boon_natural_bond = { en = "Natural Bond" },
    disable_boon_natural_bond_tooltip = { en = "Passively regenerates X health every X seconds. Healing from First Aid Kits and Healing Draughts are converted to temporary health." },
    start_boon_natural_bond_tooltip = { en = "Passively regenerates X health every X seconds. Healing from First Aid Kits and Healing Draughts are converted to temporary health." },
    disable_boon_pent_up_anger = { en = "Myrmidia's Justice" },
    start_boon_pent_up_anger = { en = "Myrmidia's Justice" },
    disable_boon_pent_up_anger_tooltip = { en = "You gain a stack of Justice each time you Block an Attack. Once you have X stacks, your next Attack is automatically a Critical Hit and all stacks are lost." },
    start_boon_pent_up_anger_tooltip = { en = "You gain a stack of Justice each time you Block an Attack. Once you have X stacks, your next Attack is automatically a Critical Hit and all stacks are lost." },
    disable_boon_power_up_of_shallya = { en = "Boon of Shallya" },
    start_boon_power_up_of_shallya = { en = "Boon of Shallya" },
    disable_boon_power_up_of_shallya_tooltip = { en = "Increases effectiveness of healing on you by X%%%%." },
    start_boon_power_up_of_shallya_tooltip = { en = "Increases effectiveness of healing on you by X%%%%." },
    disable_boon_power_vs_armoured = { en = "Power vs Armoured" },
    start_boon_power_vs_armoured = { en = "Power vs Armoured" },
    disable_boon_power_vs_armoured_tooltip = { en = "Increases Hero Power when attacking Armoured enemies" },
    start_boon_power_vs_armoured_tooltip = { en = "Increases Hero Power when attacking Armoured enemies" },
    disable_boon_power_vs_chaos = { en = "Power vs Chaos" },
    start_boon_power_vs_chaos = { en = "Power vs Chaos" },
    disable_boon_power_vs_chaos_tooltip = { en = "Increase Hero Power when attacking Chaos enemies by X" },
    start_boon_power_vs_chaos_tooltip = { en = "Increase Hero Power when attacking Chaos enemies by X" },
    disable_boon_power_vs_frenzy = { en = "Power vs Berserkers" },
    start_boon_power_vs_frenzy = { en = "Power vs Berserkers" },
    disable_boon_power_vs_frenzy_tooltip = { en = "Increases Hero Power when attacking Frenzied enemies" },
    start_boon_power_vs_frenzy_tooltip = { en = "Increases Hero Power when attacking Frenzied enemies" },
    disable_boon_power_vs_large = { en = "Power vs Monsters" },
    start_boon_power_vs_large = { en = "Power vs Monsters" },
    disable_boon_power_vs_large_tooltip = { en = "Increases Hero Power when attacking Large enemies" },
    start_boon_power_vs_large_tooltip = { en = "Increases Hero Power when attacking Large enemies" },
    disable_boon_power_vs_skaven = { en = "Power vs Skaven" },
    start_boon_power_vs_skaven = { en = "Power vs Skaven" },
    disable_boon_power_vs_skaven_tooltip = { en = "Increases Hero Power when attacking Skaven enemies by X" },
    start_boon_power_vs_skaven_tooltip = { en = "Increases Hero Power when attacking Skaven enemies by X" },
    disable_boon_power_vs_unarmoured = { en = "Power vs Infantry" },
    start_boon_power_vs_unarmoured = { en = "Power vs Infantry" },
    disable_boon_power_vs_unarmoured_tooltip = { en = "Increases Hero Power when attacking Unarmoured enemies by X" },
    start_boon_power_vs_unarmoured_tooltip = { en = "Increases Hero Power when attacking Unarmoured enemies by X" },
    disable_boon_protection_aoe = { en = "Damage Reduction vs Area Damage" },
    start_boon_protection_aoe = { en = "Damage Reduction vs Area Damage" },
    disable_boon_protection_aoe_tooltip = { en = "Reduces damage taken from area attacks" },
    start_boon_protection_aoe_tooltip = { en = "Reduces damage taken from area attacks" },
    disable_boon_protection_chaos = { en = "Damage Reduction vs Chaos" },
    start_boon_protection_chaos = { en = "Damage Reduction vs Chaos" },
    disable_boon_protection_chaos_tooltip = { en = "Reduces damage taken from Chaos enemies" },
    start_boon_protection_chaos_tooltip = { en = "Reduces damage taken from Chaos enemies" },
    disable_boon_protection_orbs = { en = "Ptra's Protection" },
    start_boon_protection_orbs = { en = "Ptra's Protection" },
    disable_boon_protection_orbs_tooltip = { en = "Every X seconds, a Perfect Parry spawns an Orb that reduces Damage taken by X%%%% for X seconds." },
    start_boon_protection_orbs_tooltip = { en = "Every X seconds, a Perfect Parry spawns an Orb that reduces Damage taken by X%%%% for X seconds." },
    disable_boon_protection_skaven = { en = "Damage Reduction vs Skaven" },
    start_boon_protection_skaven = { en = "Damage Reduction vs Skaven" },
    disable_boon_protection_skaven_tooltip = { en = "Reduces damage taken from Skaven enemies" },
    start_boon_protection_skaven_tooltip = { en = "Reduces damage taken from Skaven enemies" },
    disable_boon_push_block_arc = { en = "Push/Block Angle" },
    start_boon_push_block_arc = { en = "Push/Block Angle" },
    disable_boon_push_block_arc_tooltip = { en = "Increases the angle of your melee weapon push attack" },
    start_boon_push_block_arc_tooltip = { en = "Increases the angle of your melee weapon push attack" },
    disable_boon_pyrotechnical_echo = { en = "Hashut's Echo" },
    start_boon_pyrotechnical_echo = { en = "Hashut's Echo" },
    disable_boon_pyrotechnical_echo_tooltip = { en = "Your grenades explode a second time (after a short delay)." },
    start_boon_pyrotechnical_echo_tooltip = { en = "Your grenades explode a second time (after a short delay)." },
    disable_boon_pyrrhic_strength = { en = "Khaine's Might" },
    start_boon_pyrrhic_strength = { en = "Khaine's Might" },
    disable_boon_pyrrhic_strength_tooltip = { en = "Gain X%%%% Power, but X%%%% Curse." },
    start_boon_pyrrhic_strength_tooltip = { en = "Gain X%%%% Power, but X%%%% Curse." },
    disable_boon_resolve = { en = "Isha's Gift" },
    start_boon_resolve = { en = "Isha's Gift" },
    disable_boon_resolve_tooltip = { en = "You revive with full Health. X second Cooldown." },
    start_boon_resolve_tooltip = { en = "You revive with full Health. X second Cooldown." },
    disable_boon_respawn_speed = { en = "Respawn Speed" },
    start_boon_respawn_speed = { en = "Respawn Speed" },
    disable_boon_respawn_speed_tooltip = { en = "Reduces time it takes to respawn in the mission after getting knocked out." },
    start_boon_respawn_speed_tooltip = { en = "Reduces time it takes to respawn in the mission after getting knocked out." },
    disable_boon_revive_speed = { en = "Revive Speed" },
    start_boon_revive_speed = { en = "Revive Speed" },
    disable_boon_revive_speed_tooltip = { en = "Increases the speed at which you help up knocked down allies" },
    start_boon_revive_speed_tooltip = { en = "Increases the speed at which you help up knocked down allies" },
    disable_boon_sharing_is_caring = { en = "Esmerelda's Generosity" },
    start_boon_sharing_is_caring = { en = "Esmerelda's Generosity" },
    disable_boon_sharing_is_caring_tooltip = { en = "On drinking a Potion spawn an Orb that grants the same effect." },
    start_boon_sharing_is_caring_tooltip = { en = "On drinking a Potion spawn an Orb that grants the same effect." },
    disable_boon_shrapnel = { en = "Shrapnel" },
    start_boon_shrapnel = { en = "Shrapnel" },
    disable_boon_shrapnel_tooltip = { en = "Grenades cause hit enemies to take X%%%% increased damage for X seconds." },
    start_boon_shrapnel_tooltip = { en = "Grenades cause hit enemies to take X%%%% increased damage for X seconds." },
    disable_boon_skill_by_block = { en = "Neru's Patience" },
    start_boon_skill_by_block = { en = "Neru's Patience" },
    disable_boon_skill_by_block_tooltip = { en = "Blocking enemy attacks reduces Career Skill Cooldown." },
    start_boon_skill_by_block_tooltip = { en = "Blocking enemy attacks reduces Career Skill Cooldown." },
    disable_boon_speed_over_stamina = { en = "Eldrazor's Revenge" },
    start_boon_speed_over_stamina = { en = "Eldrazor's Revenge" },
    disable_boon_speed_over_stamina_tooltip = { en = "When your Block is broken you gain X%%%% Attack Speed for Xs." },
    start_boon_speed_over_stamina_tooltip = { en = "When your Block is broken you gain X%%%% Attack Speed for Xs." },
    disable_boon_squats = { en = "Squats" },
    start_boon_squats = { en = "Squats" },
    disable_boon_staggering_force = { en = "Estreuth's Roar" },
    start_boon_staggering_force = { en = "Estreuth's Roar" },
    disable_boon_staggering_force_tooltip = { en = "Staggering X enemies at once grants X%%%% Power for X seconds." },
    start_boon_staggering_force_tooltip = { en = "Staggering X enemies at once grants X%%%% Power for X seconds." },
    disable_boon_stamina = { en = "Stamina" },
    start_boon_stamina = { en = "Stamina" },
    disable_boon_stamina_tooltip = { en = "Increases max stamina" },
    start_boon_stamina_tooltip = { en = "Increases max stamina" },
    disable_boon_static_blade = { en = "Stromfels' Retribution" },
    start_boon_static_blade = { en = "Stromfels' Retribution" },
    disable_boon_static_blade_tooltip = { en = "Every X seconds, Parrying an Attack triggers a lightning strike against the attacking enemy." },
    start_boon_static_blade_tooltip = { en = "Every X seconds, Parrying an Attack triggers a lightning strike against the attacking enemy." },
    disable_boon_static_charge = { en = "Mathlann's Spark" },
    start_boon_static_charge = { en = "Mathlann's Spark" },
    disable_boon_static_charge_tooltip = { en = "Spawns a static charge Orb every X kills. The Orb Damages and Staggers nearby enemies for X seconds." },
    start_boon_static_charge_tooltip = { en = "Spawns a static charge Orb every X kills. The Orb Damages and Staggers nearby enemies for X seconds." },
    disable_boon_surprise_strike = { en = "Morai-Heg's Doom" },
    start_boon_surprise_strike = { en = "Morai-Heg's Doom" },
    disable_boon_surprise_strike_tooltip = { en = "For X seconds after leaving invisibility, all Attacks are automatically Critical Hits." },
    start_boon_surprise_strike_tooltip = { en = "For X seconds after leaving invisibility, all Attacks are automatically Critical Hits." },
    disable_boon_talent_1_1 = { en = "Talent 1 1" },
    start_boon_talent_1_1 = { en = "Talent 1 1" },
    disable_boon_talent_1_2 = { en = "Talent 1 2" },
    start_boon_talent_1_2 = { en = "Talent 1 2" },
    disable_boon_talent_1_3 = { en = "Talent 1 3" },
    start_boon_talent_1_3 = { en = "Talent 1 3" },
    disable_boon_talent_2_1 = { en = "Talent 2 1" },
    start_boon_talent_2_1 = { en = "Talent 2 1" },
    disable_boon_talent_2_2 = { en = "Talent 2 2" },
    start_boon_talent_2_2 = { en = "Talent 2 2" },
    disable_boon_talent_2_3 = { en = "Talent 2 3" },
    start_boon_talent_2_3 = { en = "Talent 2 3" },
    disable_boon_talent_3_1 = { en = "Talent 3 1" },
    start_boon_talent_3_1 = { en = "Talent 3 1" },
    disable_boon_talent_3_2 = { en = "Talent 3 2" },
    start_boon_talent_3_2 = { en = "Talent 3 2" },
    disable_boon_talent_3_3 = { en = "Talent 3 3" },
    start_boon_talent_3_3 = { en = "Talent 3 3" },
    disable_boon_talent_4_1 = { en = "Talent 4 1" },
    start_boon_talent_4_1 = { en = "Talent 4 1" },
    disable_boon_talent_4_2 = { en = "Talent 4 2" },
    start_boon_talent_4_2 = { en = "Talent 4 2" },
    disable_boon_talent_4_3 = { en = "Talent 4 3" },
    start_boon_talent_4_3 = { en = "Talent 4 3" },
    disable_boon_talent_5_1 = { en = "Talent 5 1" },
    start_boon_talent_5_1 = { en = "Talent 5 1" },
    disable_boon_talent_5_2 = { en = "Talent 5 2" },
    start_boon_talent_5_2 = { en = "Talent 5 2" },
    disable_boon_talent_5_3 = { en = "Talent 5 3" },
    start_boon_talent_5_3 = { en = "Talent 5 3" },
    disable_boon_talent_6_1 = { en = "Talent 6 1" },
    start_boon_talent_6_1 = { en = "Talent 6 1" },
    disable_boon_talent_6_2 = { en = "Talent 6 2" },
    start_boon_talent_6_2 = { en = "Talent 6 2" },
    disable_boon_talent_6_3 = { en = "Talent 6 3" },
    start_boon_talent_6_3 = { en = "Talent 6 3" },
    disable_boon_tenacious = { en = "The Great Maw's Resurgence" },
    start_boon_tenacious = { en = "The Great Maw's Resurgence" },
    disable_boon_tenacious_tooltip = { en = "Gain X Health each second if below X%%%% Health." },
    start_boon_tenacious_tooltip = { en = "Gain X Health each second if below X%%%% Health." },
    disable_boon_thorn_skin = { en = "Drakira's Malice" },
    start_boon_thorn_skin = { en = "Drakira's Malice" },
    disable_boon_thorn_skin_tooltip = { en = "Taking damage deals damage to nearby enemies." },
    start_boon_thorn_skin_tooltip = { en = "Taking damage deals damage to nearby enemies." },
    disable_boon_transfer_temp_health_at_full = { en = "Salyak's Charity" },
    start_boon_transfer_temp_health_at_full = { en = "Salyak's Charity" },
    disable_boon_transfer_temp_health_at_full_tooltip = { en = "Gaining temporary health while at full health will give the temporary health to the nearest ally instead." },
    start_boon_transfer_temp_health_at_full_tooltip = { en = "Gaining temporary health while at full health will give the temporary health to the nearest ally instead." },
    disable_boon_triple_melee_headshot_power = { en = "Djaf's Reaping" },
    start_boon_triple_melee_headshot_power = { en = "Djaf's Reaping" },
    disable_boon_triple_melee_headshot_power_tooltip = { en = "Landing X Melee headshots in a row grants X%%%% increased Melee Power for X seconds." },
    start_boon_triple_melee_headshot_power_tooltip = { en = "Landing X Melee headshots in a row grants X%%%% increased Melee Power for X seconds." },
    disable_boon_wolfpack = { en = "Ulric's Pack" },
    start_boon_wolfpack = { en = "Ulric's Pack" },
    disable_boon_wolfpack_tooltip = { en = "Gain X%%%% bonus to Power. This is multiplied by the number of allies with the Boon." },
    start_boon_wolfpack_tooltip = { en = "Gain X%%%% bonus to Power. This is multiplied by the number of allies with the Boon." },
}

return loc
