local mod = get_mod("ct")

-- CLARIFY: `text` values are localization keys (resolved by VMF). `altar_count_default` resolves
-- to "Default" via _localization.lua; numeric strings "1".."9" are passed through verbatim by VMF
-- (they're not lookup keys since they don't match any loc entry). value=0 is the sentinel meaning
-- "leave vanilla random distribution untouched"; see chaos_wastes_tweaker.lua get_deus_weapon_chest_type.
local altar_count_options = {
    { text = "altar_count_default", value = 0 },
    { text = "1", value = 1 },
    { text = "2", value = 2 },
    { text = "3", value = 3 },
    { text = "4", value = 4 },
    { text = "5", value = 5 },
    { text = "6", value = 6 },
    { text = "7", value = 7 },
    { text = "8", value = 8 },
    { text = "9", value = 9 },
}

return {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            { setting_id = "coin_multiplier", type = "numeric", default_value = 1, range = { 0.1, 5 }, decimals_number = 2 },
            { setting_id = "starting_coins", type = "numeric", default_value = 0, range = { 0, 3000 }, decimals_number = 0 },
            { setting_id = "shrine_boon_count", type = "numeric", default_value = 4, range = { 1, 5 }, decimals_number = 0 },
            { setting_id = "chest_boon_count", type = "numeric", default_value = 3, range = { 1, 5 }, decimals_number = 0 },
            { setting_id = "force_belakor", type = "checkbox", default_value = false },
            { setting_id = "finale_dominant_god", type = "numeric", default_value = 0, range = { 0, 4 }, decimals_number = 0 },
            { setting_id = "chest_upgrade_count", type = "dropdown", default_value = 0, options = altar_count_options, tooltip = "altar_count_tooltip" },
            { setting_id = "chest_swap_melee_count", type = "dropdown", default_value = 0, options = altar_count_options, tooltip = "altar_count_tooltip" },
            { setting_id = "chest_swap_ranged_count", type = "dropdown", default_value = 0, options = altar_count_options, tooltip = "altar_count_tooltip" },
            { setting_id = "chest_power_up_count", type = "dropdown", default_value = 0, options = altar_count_options, tooltip = "altar_count_tooltip" },
            { setting_id = "cursed_chest_count", type = "numeric", default_value = 1, range = { 0, 10 }, decimals_number = 0 },
            { setting_id = "arena_ammo_count", type = "numeric", default_value = 2, range = { 0, 10 }, decimals_number = 0 },
            { setting_id = "enable_campaign_potions", type = "checkbox", default_value = false },
            { setting_id = "any_trait_any_weapon", type = "checkbox", default_value = false },
            {
                setting_id = "curses_group",
                type = "group",
                sub_widgets = {
                    { setting_id = "disable_curse_abundance_of_life", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_belakor_totems", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_blood_storm", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_bolt_of_change", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_change_of_tzeentch", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_corrupted_flesh", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_egg_of_tzeentch", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_empathy", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_greed_pinata", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_khorne_champions", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_rotten_miasma", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_shadow_homing_skulls", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_skulking_sorcerer", type = "checkbox", default_value = false },
                    { setting_id = "disable_curse_skulls_of_fury", type = "checkbox", default_value = false },
                },
            },
            {
                setting_id = "modified_boons_group",
                type = "group",
                sub_widgets = {
                    { setting_id = "tweak_reckless_swings", type = "checkbox", default_value = false, tooltip = "tweak_reckless_swings_tooltip" },
                },
            },
            {
                setting_id = "disabled_boons_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "disable_boon_properties_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_ability_cooldown_reduction",                        type = "checkbox", default_value = false, tooltip = "disable_boon_ability_cooldown_reduction_tooltip" },
                            { setting_id = "disable_boon_attack_speed",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_attack_speed_tooltip" },
                            { setting_id = "disable_boon_block_cost",                                        type = "checkbox", default_value = false, tooltip = "disable_boon_block_cost_tooltip" },
                            { setting_id = "disable_boon_crit_boost",                                        type = "checkbox", default_value = false, tooltip = "disable_boon_crit_boost_tooltip" },
                            { setting_id = "disable_boon_crit_chance",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_crit_chance_tooltip" },
                            { setting_id = "disable_boon_curse_resistance",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_curse_resistance_tooltip" },
                            { setting_id = "disable_boon_fatigue_regen",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_fatigue_regen_tooltip" },
                            { setting_id = "disable_boon_health",                                            type = "checkbox", default_value = false, tooltip = "disable_boon_health_tooltip" },
                            { setting_id = "disable_boon_movespeed",                                         type = "checkbox", default_value = false, tooltip = "disable_boon_movespeed_tooltip" },
                            { setting_id = "disable_boon_power_vs_armoured",                                 type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_armoured_tooltip" },
                            { setting_id = "disable_boon_power_vs_chaos",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_chaos_tooltip" },
                            { setting_id = "disable_boon_power_vs_frenzy",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_frenzy_tooltip" },
                            { setting_id = "disable_boon_power_vs_large",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_large_tooltip" },
                            { setting_id = "disable_boon_power_vs_skaven",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_skaven_tooltip" },
                            { setting_id = "disable_boon_power_vs_unarmoured",                               type = "checkbox", default_value = false, tooltip = "disable_boon_power_vs_unarmoured_tooltip" },
                            { setting_id = "disable_boon_protection_aoe",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_protection_aoe_tooltip" },
                            { setting_id = "disable_boon_protection_chaos",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_protection_chaos_tooltip" },
                            { setting_id = "disable_boon_protection_skaven",                                 type = "checkbox", default_value = false, tooltip = "disable_boon_protection_skaven_tooltip" },
                            { setting_id = "disable_boon_push_block_arc",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_push_block_arc_tooltip" },
                            { setting_id = "disable_boon_respawn_speed",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_respawn_speed_tooltip" },
                            { setting_id = "disable_boon_revive_speed",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_revive_speed_tooltip" },
                            { setting_id = "disable_boon_stamina",                                           type = "checkbox", default_value = false, tooltip = "disable_boon_stamina_tooltip" },
                        },
                    },
                    {
                        setting_id = "disable_boon_talents_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_talent_1_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_1_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_1_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_2_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_2_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_2_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_3_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_3_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_3_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_4_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_4_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_4_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_5_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_5_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_5_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_6_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_6_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_talent_6_3",                                        type = "checkbox", default_value = false },
                        },
                    },
                    {
                        setting_id = "disable_boon_skulls_and_sets_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_boon_skulls_01",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_01_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_02",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_02_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_03",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_03_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_04",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_04_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_05",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_05_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_06",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_06_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_07",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_07_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_08",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_08_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_set_bonus_01",                          type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_set_bonus_01_tooltip" },
                            { setting_id = "disable_boon_boon_skulls_set_bonus_02",                          type = "checkbox", default_value = false, tooltip = "disable_boon_boon_skulls_set_bonus_02_tooltip" },
                            { setting_id = "disable_boon_boonset_crit_set_bonus",                            type = "checkbox", default_value = false, tooltip = "disable_boon_boonset_crit_set_bonus_tooltip" },
                            { setting_id = "disable_boon_boonset_drone_part1",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boonset_drone_part1_tooltip" },
                            { setting_id = "disable_boon_boonset_drone_part2",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boonset_drone_part2_tooltip" },
                            { setting_id = "disable_boon_boonset_drone_part3",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boonset_drone_part3_tooltip" },
                            { setting_id = "disable_boon_boonset_drone_part4",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boonset_drone_part4_tooltip" },
                        },
                    },
                    {
                        setting_id = "disable_boon_combat_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_attack_speed_per_cooldown",                         type = "checkbox", default_value = false, tooltip = "disable_boon_attack_speed_per_cooldown_tooltip" },
                            { setting_id = "disable_boon_bad_breath",                                        type = "checkbox", default_value = false, tooltip = "disable_boon_bad_breath_tooltip" },
                            { setting_id = "disable_boon_barkskin",                                          type = "checkbox", default_value = false, tooltip = "disable_boon_barkskin_tooltip" },
                            { setting_id = "disable_boon_blazing_revenge",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_blazing_revenge_tooltip" },
                            { setting_id = "disable_boon_boon_aoe_02",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_boon_aoe_02_tooltip" },
                            { setting_id = "disable_boon_boon_aoe_03",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_boon_aoe_03_tooltip" },
                            { setting_id = "disable_boon_boon_bomb_heavy_01",                                type = "checkbox", default_value = false, tooltip = "disable_boon_boon_bomb_heavy_01_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_01",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_01_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_02",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_02_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_03",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_03_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_04",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_04_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_06",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_06_tooltip" },
                            { setting_id = "disable_boon_boon_careerskill_07",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_careerskill_07_tooltip" },
                            { setting_id = "disable_boon_boon_dot_burning_01",                               type = "checkbox", default_value = false, tooltip = "disable_boon_boon_dot_burning_01_tooltip" },
                            { setting_id = "disable_boon_boon_meta_01",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_boon_meta_01_tooltip" },
                            { setting_id = "disable_boon_boon_range_01",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_boon_range_01_tooltip" },
                            { setting_id = "disable_boon_boon_range_02",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_boon_range_02_tooltip" },
                            { setting_id = "disable_boon_boon_supportbomb_concentration_01",                 type = "checkbox", default_value = false, tooltip = "disable_boon_boon_supportbomb_concentration_01_tooltip" },
                            { setting_id = "disable_boon_boon_supportbomb_crit_01",                          type = "checkbox", default_value = false, tooltip = "disable_boon_boon_supportbomb_crit_01_tooltip" },
                            { setting_id = "disable_boon_boon_supportbomb_speed_01",                         type = "checkbox", default_value = false, tooltip = "disable_boon_boon_supportbomb_speed_01_tooltip" },
                            { setting_id = "disable_boon_boon_supportbomb_strenght_01",                      type = "checkbox", default_value = false, tooltip = "disable_boon_boon_supportbomb_strenght_01_tooltip" },
                            { setting_id = "disable_boon_boulder_bro",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_boulder_bro_tooltip" },
                            { setting_id = "disable_boon_cluster_barrel",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_cluster_barrel_tooltip" },
                            { setting_id = "disable_boon_deus_barrel_power",                                 type = "checkbox", default_value = false, tooltip = "disable_boon_deus_barrel_power_tooltip" },
                            { setting_id = "disable_boon_deus_block_procs_parry",                            type = "checkbox", default_value = false, tooltip = "disable_boon_deus_block_procs_parry_tooltip" },
                            { setting_id = "disable_boon_deus_crit_on_damage_taken",                         type = "checkbox", default_value = false, tooltip = "disable_boon_deus_crit_on_damage_taken_tooltip" },
                            { setting_id = "disable_boon_deus_damage_reduction_on_incapacitated",            type = "checkbox", default_value = false, tooltip = "disable_boon_deus_damage_reduction_on_incapacitated_tooltip" },
                            { setting_id = "disable_boon_deus_larger_clip",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_deus_larger_clip_tooltip" },
                            { setting_id = "disable_boon_deus_more_head_less_body_damage",                   type = "checkbox", default_value = false, tooltip = "disable_boon_deus_more_head_less_body_damage_tooltip" },
                            { setting_id = "disable_boon_deus_parry_damage_immune",                          type = "checkbox", default_value = false, tooltip = "disable_boon_deus_parry_damage_immune_tooltip" },
                            { setting_id = "disable_boon_deus_power_up_quest_granted_test_01",               type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_deus_powerup_attack_speed",                         type = "checkbox", default_value = false, tooltip = "disable_boon_deus_powerup_attack_speed_tooltip" },
                            { setting_id = "disable_boon_deus_push_charge",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_deus_push_charge_tooltip" },
                            { setting_id = "disable_boon_deus_push_cost_reduction",                          type = "checkbox", default_value = false, tooltip = "disable_boon_deus_push_cost_reduction_tooltip" },
                            { setting_id = "disable_boon_deus_push_increased_cleave",                        type = "checkbox", default_value = false, tooltip = "disable_boon_deus_push_increased_cleave_tooltip" },
                            { setting_id = "disable_boon_deus_reckless_swings",                              type = "checkbox", default_value = false, tooltip = "disable_boon_deus_reckless_swings_tooltip" },
                            { setting_id = "disable_boon_deus_standing_still_damage_reduction",              type = "checkbox", default_value = false, tooltip = "disable_boon_deus_standing_still_damage_reduction_tooltip" },
                            { setting_id = "disable_boon_deus_target_full_health_damage_mult",               type = "checkbox", default_value = false, tooltip = "disable_boon_deus_target_full_health_damage_mult_tooltip" },
                            { setting_id = "disable_boon_deus_timed_block_free_shot",                        type = "checkbox", default_value = false, tooltip = "disable_boon_deus_timed_block_free_shot_tooltip" },
                            { setting_id = "disable_boon_deus_uninterruptable_attacks",                      type = "checkbox", default_value = false, tooltip = "disable_boon_deus_uninterruptable_attacks_tooltip" },
                            { setting_id = "disable_boon_detect_weakness",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_detect_weakness_tooltip" },
                            { setting_id = "disable_boon_explosive_kills_on_elite_kills",                    type = "checkbox", default_value = false, tooltip = "disable_boon_explosive_kills_on_elite_kills_tooltip" },
                            { setting_id = "disable_boon_explosive_ordinance",                               type = "checkbox", default_value = false, tooltip = "disable_boon_explosive_ordinance_tooltip" },
                            { setting_id = "disable_boon_explosive_pushes_on_damage_taken",                  type = "checkbox", default_value = false, tooltip = "disable_boon_explosive_pushes_on_damage_taken_tooltip" },
                            { setting_id = "disable_boon_focused_accuracy",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_focused_accuracy_tooltip" },
                            { setting_id = "disable_boon_grenadier",                                         type = "checkbox", default_value = false, tooltip = "disable_boon_grenadier_tooltip" },
                            { setting_id = "disable_boon_indomitable",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_indomitable_tooltip" },
                            { setting_id = "disable_boon_last_player_standing_power_reg",                    type = "checkbox", default_value = false, tooltip = "disable_boon_last_player_standing_power_reg_tooltip" },
                            { setting_id = "disable_boon_lucky",                                             type = "checkbox", default_value = false, tooltip = "disable_boon_lucky_tooltip" },
                            { setting_id = "disable_boon_melee_killing_spree_speed",                         type = "checkbox", default_value = false, tooltip = "disable_boon_melee_killing_spree_speed_tooltip" },
                            { setting_id = "disable_boon_melee_wave",                                        type = "checkbox", default_value = false, tooltip = "disable_boon_melee_wave_tooltip" },
                            { setting_id = "disable_boon_missing_health_power_up",                           type = "checkbox", default_value = false, tooltip = "disable_boon_missing_health_power_up_tooltip" },
                            { setting_id = "disable_boon_pent_up_anger",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_pent_up_anger_tooltip" },
                            { setting_id = "disable_boon_pyrotechnical_echo",                                type = "checkbox", default_value = false, tooltip = "disable_boon_pyrotechnical_echo_tooltip" },
                            { setting_id = "disable_boon_pyrrhic_strength",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_pyrrhic_strength_tooltip" },
                            { setting_id = "disable_boon_resolve",                                           type = "checkbox", default_value = false, tooltip = "disable_boon_resolve_tooltip" },
                            { setting_id = "disable_boon_shrapnel",                                          type = "checkbox", default_value = false, tooltip = "disable_boon_shrapnel_tooltip" },
                            { setting_id = "disable_boon_skill_by_block",                                    type = "checkbox", default_value = false, tooltip = "disable_boon_skill_by_block_tooltip" },
                            { setting_id = "disable_boon_speed_over_stamina",                                type = "checkbox", default_value = false, tooltip = "disable_boon_speed_over_stamina_tooltip" },
                            { setting_id = "disable_boon_squats",                                            type = "checkbox", default_value = false },
                            { setting_id = "disable_boon_staggering_force",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_staggering_force_tooltip" },
                            { setting_id = "disable_boon_static_blade",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_static_blade_tooltip" },
                            { setting_id = "disable_boon_static_charge",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_static_charge_tooltip" },
                            { setting_id = "disable_boon_surprise_strike",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_surprise_strike_tooltip" },
                            { setting_id = "disable_boon_thorn_skin",                                        type = "checkbox", default_value = false, tooltip = "disable_boon_thorn_skin_tooltip" },
                            { setting_id = "disable_boon_triple_melee_headshot_power",                       type = "checkbox", default_value = false, tooltip = "disable_boon_triple_melee_headshot_power_tooltip" },
                        },
                    },
                    {
                        setting_id = "disable_boon_healing_and_sustain_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_boon_supportbomb_healing_01",                       type = "checkbox", default_value = false, tooltip = "disable_boon_boon_supportbomb_healing_01_tooltip" },
                            { setting_id = "disable_boon_curative_empowerment",                              type = "checkbox", default_value = false, tooltip = "disable_boon_curative_empowerment_tooltip" },
                            { setting_id = "disable_boon_deus_ammo_pickup_heal",                             type = "checkbox", default_value = false, tooltip = "disable_boon_deus_ammo_pickup_heal_tooltip" },
                            { setting_id = "disable_boon_deus_health_regeneration",                          type = "checkbox", default_value = false, tooltip = "disable_boon_deus_health_regeneration_tooltip" },
                            { setting_id = "disable_boon_deus_increased_healing_taken",                      type = "checkbox", default_value = false, tooltip = "disable_boon_deus_increased_healing_taken_tooltip" },
                            { setting_id = "disable_boon_deus_knockdown_damage_immunity_aura",               type = "checkbox", default_value = false, tooltip = "disable_boon_deus_knockdown_damage_immunity_aura_tooltip" },
                            { setting_id = "disable_boon_deus_max_health",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_deus_max_health_tooltip" },
                            { setting_id = "disable_boon_deus_revive_regen",                                 type = "checkbox", default_value = false, tooltip = "disable_boon_deus_revive_regen_tooltip" },
                            { setting_id = "disable_boon_deus_second_wind",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_deus_second_wind_tooltip" },
                            { setting_id = "disable_boon_hand_of_shallya",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_hand_of_shallya_tooltip" },
                            { setting_id = "disable_boon_heal_on_dot_damage_dealt",                          type = "checkbox", default_value = false, tooltip = "disable_boon_heal_on_dot_damage_dealt_tooltip" },
                            { setting_id = "disable_boon_healers_touch",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_healers_touch_tooltip" },
                            { setting_id = "disable_boon_health_orbs",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_health_orbs_tooltip" },
                            { setting_id = "disable_boon_hidden_escape",                                     type = "checkbox", default_value = false, tooltip = "disable_boon_hidden_escape_tooltip" },
                            { setting_id = "disable_boon_invigorating_strike",                               type = "checkbox", default_value = false, tooltip = "disable_boon_invigorating_strike_tooltip" },
                            { setting_id = "disable_boon_natural_bond",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_natural_bond_tooltip" },
                            { setting_id = "disable_boon_power_up_of_shallya",                               type = "checkbox", default_value = false, tooltip = "disable_boon_power_up_of_shallya_tooltip" },
                            { setting_id = "disable_boon_protection_orbs",                                   type = "checkbox", default_value = false, tooltip = "disable_boon_protection_orbs_tooltip" },
                            { setting_id = "disable_boon_tenacious",                                         type = "checkbox", default_value = false, tooltip = "disable_boon_tenacious_tooltip" },
                            { setting_id = "disable_boon_transfer_temp_health_at_full",                      type = "checkbox", default_value = false, tooltip = "disable_boon_transfer_temp_health_at_full_tooltip" },
                        },
                    },
                    {
                        setting_id = "disable_boon_utility_and_team_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "disable_boon_boon_aura_01",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_boon_aura_01_tooltip" },
                            { setting_id = "disable_boon_boon_aura_02",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_boon_aura_02_tooltip" },
                            { setting_id = "disable_boon_boon_aura_03",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_boon_aura_03_tooltip" },
                            { setting_id = "disable_boon_boon_deus_coins_greed",                             type = "checkbox", default_value = false, tooltip = "disable_boon_boon_deus_coins_greed_tooltip" },
                            { setting_id = "disable_boon_boon_teamaura_01",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_boon_teamaura_01_tooltip" },
                            { setting_id = "disable_boon_boon_teamaura_02",                                  type = "checkbox", default_value = false, tooltip = "disable_boon_boon_teamaura_02_tooltip" },
                            { setting_id = "disable_boon_boon_weaponrarity_01",                              type = "checkbox", default_value = false, tooltip = "disable_boon_boon_weaponrarity_01_tooltip" },
                            { setting_id = "disable_boon_boon_weaponrarity_02",                              type = "checkbox", default_value = false, tooltip = "disable_boon_boon_weaponrarity_02_tooltip" },
                            { setting_id = "disable_boon_comradery",                                         type = "checkbox", default_value = false, tooltip = "disable_boon_comradery_tooltip" },
                            { setting_id = "disable_boon_cooldown_on_friendly_ability",                      type = "checkbox", default_value = false, tooltip = "disable_boon_cooldown_on_friendly_ability_tooltip" },
                            { setting_id = "disable_boon_decanter",                                          type = "checkbox", default_value = false, tooltip = "disable_boon_decanter_tooltip" },
                            { setting_id = "disable_boon_deus_ammo_pickup_give_allies_ammo",                 type = "checkbox", default_value = false, tooltip = "disable_boon_deus_ammo_pickup_give_allies_ammo_tooltip" },
                            { setting_id = "disable_boon_deus_coin_pickup_regen",                            type = "checkbox", default_value = false, tooltip = "disable_boon_deus_coin_pickup_regen_tooltip" },
                            { setting_id = "disable_boon_deus_cooldown_reg_not_hit",                         type = "checkbox", default_value = false, tooltip = "disable_boon_deus_cooldown_reg_not_hit_tooltip" },
                            { setting_id = "disable_boon_deus_cooldown_regen",                               type = "checkbox", default_value = false, tooltip = "disable_boon_deus_cooldown_regen_tooltip" },
                            { setting_id = "disable_boon_deus_extra_stamina",                                type = "checkbox", default_value = false, tooltip = "disable_boon_deus_extra_stamina_tooltip" },
                            { setting_id = "disable_boon_deus_free_potion_use_on_ability",                   type = "checkbox", default_value = false, tooltip = "disable_boon_deus_free_potion_use_on_ability_tooltip" },
                            { setting_id = "disable_boon_deus_grenade_multi_throw",                          type = "checkbox", default_value = false, tooltip = "disable_boon_deus_grenade_multi_throw_tooltip" },
                            { setting_id = "disable_boon_deus_guard_aura_check",                             type = "checkbox", default_value = false, tooltip = "disable_boon_deus_guard_aura_check_tooltip" },
                            { setting_id = "disable_boon_deus_infinite_dodges",                              type = "checkbox", default_value = false, tooltip = "disable_boon_deus_infinite_dodges_tooltip" },
                            { setting_id = "disable_boon_deus_large_ammo_pickup_infinite_ammo",              type = "checkbox", default_value = false, tooltip = "disable_boon_deus_large_ammo_pickup_infinite_ammo_tooltip" },
                            { setting_id = "disable_boon_deus_skill_on_special_kill",                        type = "checkbox", default_value = false, tooltip = "disable_boon_deus_skill_on_special_kill_tooltip" },
                            { setting_id = "disable_boon_deus_throw_speed_increase",                         type = "checkbox", default_value = false, tooltip = "disable_boon_deus_throw_speed_increase_tooltip" },
                            { setting_id = "disable_boon_deus_transmute_into_coins",                         type = "checkbox", default_value = false, tooltip = "disable_boon_deus_transmute_into_coins_tooltip" },
                            { setting_id = "disable_boon_drop_item_on_ability_use",                          type = "checkbox", default_value = false, tooltip = "disable_boon_drop_item_on_ability_use_tooltip" },
                            { setting_id = "disable_boon_friendly_cooldown_on_ability",                      type = "checkbox", default_value = false, tooltip = "disable_boon_friendly_cooldown_on_ability_tooltip" },
                            { setting_id = "disable_boon_home_brewer",                                       type = "checkbox", default_value = false, tooltip = "disable_boon_home_brewer_tooltip" },
                            { setting_id = "disable_boon_money_magnet",                                      type = "checkbox", default_value = false, tooltip = "disable_boon_money_magnet_tooltip" },
                            { setting_id = "disable_boon_movement_speed_on_active_ability_use",              type = "checkbox", default_value = false, tooltip = "disable_boon_movement_speed_on_active_ability_use_tooltip" },
                            { setting_id = "disable_boon_sharing_is_caring",                                 type = "checkbox", default_value = false, tooltip = "disable_boon_sharing_is_caring_tooltip" },
                            { setting_id = "disable_boon_wolfpack",                                          type = "checkbox", default_value = false, tooltip = "disable_boon_wolfpack_tooltip" },
                        },
                    },
                },
            },
            {
                setting_id = "starting_boons_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "start_boon_properties_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_ability_cooldown_reduction",                        type = "checkbox", default_value = false, tooltip = "start_boon_ability_cooldown_reduction_tooltip" },
                            { setting_id = "start_boon_attack_speed",                                      type = "checkbox", default_value = false, tooltip = "start_boon_attack_speed_tooltip" },
                            { setting_id = "start_boon_block_cost",                                        type = "checkbox", default_value = false, tooltip = "start_boon_block_cost_tooltip" },
                            { setting_id = "start_boon_crit_boost",                                        type = "checkbox", default_value = false, tooltip = "start_boon_crit_boost_tooltip" },
                            { setting_id = "start_boon_crit_chance",                                       type = "checkbox", default_value = false, tooltip = "start_boon_crit_chance_tooltip" },
                            { setting_id = "start_boon_curse_resistance",                                  type = "checkbox", default_value = false, tooltip = "start_boon_curse_resistance_tooltip" },
                            { setting_id = "start_boon_fatigue_regen",                                     type = "checkbox", default_value = false, tooltip = "start_boon_fatigue_regen_tooltip" },
                            { setting_id = "start_boon_health",                                            type = "checkbox", default_value = false, tooltip = "start_boon_health_tooltip" },
                            { setting_id = "start_boon_movespeed",                                         type = "checkbox", default_value = false, tooltip = "start_boon_movespeed_tooltip" },
                            { setting_id = "start_boon_power_vs_armoured",                                 type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_armoured_tooltip" },
                            { setting_id = "start_boon_power_vs_chaos",                                    type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_chaos_tooltip" },
                            { setting_id = "start_boon_power_vs_frenzy",                                   type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_frenzy_tooltip" },
                            { setting_id = "start_boon_power_vs_large",                                    type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_large_tooltip" },
                            { setting_id = "start_boon_power_vs_skaven",                                   type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_skaven_tooltip" },
                            { setting_id = "start_boon_power_vs_unarmoured",                               type = "checkbox", default_value = false, tooltip = "start_boon_power_vs_unarmoured_tooltip" },
                            { setting_id = "start_boon_protection_aoe",                                    type = "checkbox", default_value = false, tooltip = "start_boon_protection_aoe_tooltip" },
                            { setting_id = "start_boon_protection_chaos",                                  type = "checkbox", default_value = false, tooltip = "start_boon_protection_chaos_tooltip" },
                            { setting_id = "start_boon_protection_skaven",                                 type = "checkbox", default_value = false, tooltip = "start_boon_protection_skaven_tooltip" },
                            { setting_id = "start_boon_push_block_arc",                                    type = "checkbox", default_value = false, tooltip = "start_boon_push_block_arc_tooltip" },
                            { setting_id = "start_boon_respawn_speed",                                     type = "checkbox", default_value = false, tooltip = "start_boon_respawn_speed_tooltip" },
                            { setting_id = "start_boon_revive_speed",                                      type = "checkbox", default_value = false, tooltip = "start_boon_revive_speed_tooltip" },
                            { setting_id = "start_boon_stamina",                                           type = "checkbox", default_value = false, tooltip = "start_boon_stamina_tooltip" },
                        },
                    },
                    {
                        setting_id = "start_boon_talents_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_talent_1_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_1_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_1_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_2_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_2_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_2_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_3_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_3_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_3_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_4_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_4_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_4_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_5_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_5_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_5_3",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_6_1",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_6_2",                                        type = "checkbox", default_value = false },
                            { setting_id = "start_boon_talent_6_3",                                        type = "checkbox", default_value = false },
                        },
                    },
                    {
                        setting_id = "start_boon_skulls_and_sets_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_boon_skulls_01",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_01_tooltip" },
                            { setting_id = "start_boon_boon_skulls_02",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_02_tooltip" },
                            { setting_id = "start_boon_boon_skulls_03",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_03_tooltip" },
                            { setting_id = "start_boon_boon_skulls_04",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_04_tooltip" },
                            { setting_id = "start_boon_boon_skulls_05",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_05_tooltip" },
                            { setting_id = "start_boon_boon_skulls_06",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_06_tooltip" },
                            { setting_id = "start_boon_boon_skulls_07",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_07_tooltip" },
                            { setting_id = "start_boon_boon_skulls_08",                                    type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_08_tooltip" },
                            { setting_id = "start_boon_boon_skulls_set_bonus_01",                          type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_set_bonus_01_tooltip" },
                            { setting_id = "start_boon_boon_skulls_set_bonus_02",                          type = "checkbox", default_value = false, tooltip = "start_boon_boon_skulls_set_bonus_02_tooltip" },
                            { setting_id = "start_boon_boonset_crit_set_bonus",                            type = "checkbox", default_value = false, tooltip = "start_boon_boonset_crit_set_bonus_tooltip" },
                            { setting_id = "start_boon_boonset_drone_part1",                               type = "checkbox", default_value = false, tooltip = "start_boon_boonset_drone_part1_tooltip" },
                            { setting_id = "start_boon_boonset_drone_part2",                               type = "checkbox", default_value = false, tooltip = "start_boon_boonset_drone_part2_tooltip" },
                            { setting_id = "start_boon_boonset_drone_part3",                               type = "checkbox", default_value = false, tooltip = "start_boon_boonset_drone_part3_tooltip" },
                            { setting_id = "start_boon_boonset_drone_part4",                               type = "checkbox", default_value = false, tooltip = "start_boon_boonset_drone_part4_tooltip" },
                        },
                    },
                    {
                        setting_id = "start_boon_combat_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_attack_speed_per_cooldown",                         type = "checkbox", default_value = false, tooltip = "start_boon_attack_speed_per_cooldown_tooltip" },
                            { setting_id = "start_boon_bad_breath",                                        type = "checkbox", default_value = false, tooltip = "start_boon_bad_breath_tooltip" },
                            { setting_id = "start_boon_barkskin",                                          type = "checkbox", default_value = false, tooltip = "start_boon_barkskin_tooltip" },
                            { setting_id = "start_boon_blazing_revenge",                                   type = "checkbox", default_value = false, tooltip = "start_boon_blazing_revenge_tooltip" },
                            { setting_id = "start_boon_boon_aoe_02",                                       type = "checkbox", default_value = false, tooltip = "start_boon_boon_aoe_02_tooltip" },
                            { setting_id = "start_boon_boon_aoe_03",                                       type = "checkbox", default_value = false, tooltip = "start_boon_boon_aoe_03_tooltip" },
                            { setting_id = "start_boon_boon_bomb_heavy_01",                                type = "checkbox", default_value = false, tooltip = "start_boon_boon_bomb_heavy_01_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_01",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_01_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_02",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_02_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_03",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_03_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_04",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_04_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_06",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_06_tooltip" },
                            { setting_id = "start_boon_boon_careerskill_07",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_careerskill_07_tooltip" },
                            { setting_id = "start_boon_boon_dot_burning_01",                               type = "checkbox", default_value = false, tooltip = "start_boon_boon_dot_burning_01_tooltip" },
                            { setting_id = "start_boon_boon_meta_01",                                      type = "checkbox", default_value = false, tooltip = "start_boon_boon_meta_01_tooltip" },
                            { setting_id = "start_boon_boon_range_01",                                     type = "checkbox", default_value = false, tooltip = "start_boon_boon_range_01_tooltip" },
                            { setting_id = "start_boon_boon_range_02",                                     type = "checkbox", default_value = false, tooltip = "start_boon_boon_range_02_tooltip" },
                            { setting_id = "start_boon_boon_supportbomb_concentration_01",                 type = "checkbox", default_value = false, tooltip = "start_boon_boon_supportbomb_concentration_01_tooltip" },
                            { setting_id = "start_boon_boon_supportbomb_crit_01",                          type = "checkbox", default_value = false, tooltip = "start_boon_boon_supportbomb_crit_01_tooltip" },
                            { setting_id = "start_boon_boon_supportbomb_speed_01",                         type = "checkbox", default_value = false, tooltip = "start_boon_boon_supportbomb_speed_01_tooltip" },
                            { setting_id = "start_boon_boon_supportbomb_strenght_01",                      type = "checkbox", default_value = false, tooltip = "start_boon_boon_supportbomb_strenght_01_tooltip" },
                            { setting_id = "start_boon_boulder_bro",                                       type = "checkbox", default_value = false, tooltip = "start_boon_boulder_bro_tooltip" },
                            { setting_id = "start_boon_cluster_barrel",                                    type = "checkbox", default_value = false, tooltip = "start_boon_cluster_barrel_tooltip" },
                            { setting_id = "start_boon_deus_barrel_power",                                 type = "checkbox", default_value = false, tooltip = "start_boon_deus_barrel_power_tooltip" },
                            { setting_id = "start_boon_deus_block_procs_parry",                            type = "checkbox", default_value = false, tooltip = "start_boon_deus_block_procs_parry_tooltip" },
                            { setting_id = "start_boon_deus_crit_on_damage_taken",                         type = "checkbox", default_value = false, tooltip = "start_boon_deus_crit_on_damage_taken_tooltip" },
                            { setting_id = "start_boon_deus_damage_reduction_on_incapacitated",            type = "checkbox", default_value = false, tooltip = "start_boon_deus_damage_reduction_on_incapacitated_tooltip" },
                            { setting_id = "start_boon_deus_larger_clip",                                  type = "checkbox", default_value = false, tooltip = "start_boon_deus_larger_clip_tooltip" },
                            { setting_id = "start_boon_deus_more_head_less_body_damage",                   type = "checkbox", default_value = false, tooltip = "start_boon_deus_more_head_less_body_damage_tooltip" },
                            { setting_id = "start_boon_deus_parry_damage_immune",                          type = "checkbox", default_value = false, tooltip = "start_boon_deus_parry_damage_immune_tooltip" },
                            { setting_id = "start_boon_deus_power_up_quest_granted_test_01",               type = "checkbox", default_value = false },
                            { setting_id = "start_boon_deus_powerup_attack_speed",                         type = "checkbox", default_value = false, tooltip = "start_boon_deus_powerup_attack_speed_tooltip" },
                            { setting_id = "start_boon_deus_push_charge",                                  type = "checkbox", default_value = false, tooltip = "start_boon_deus_push_charge_tooltip" },
                            { setting_id = "start_boon_deus_push_cost_reduction",                          type = "checkbox", default_value = false, tooltip = "start_boon_deus_push_cost_reduction_tooltip" },
                            { setting_id = "start_boon_deus_push_increased_cleave",                        type = "checkbox", default_value = false, tooltip = "start_boon_deus_push_increased_cleave_tooltip" },
                            { setting_id = "start_boon_deus_reckless_swings",                              type = "checkbox", default_value = false, tooltip = "start_boon_deus_reckless_swings_tooltip" },
                            { setting_id = "start_boon_deus_standing_still_damage_reduction",              type = "checkbox", default_value = false, tooltip = "start_boon_deus_standing_still_damage_reduction_tooltip" },
                            { setting_id = "start_boon_deus_target_full_health_damage_mult",               type = "checkbox", default_value = false, tooltip = "start_boon_deus_target_full_health_damage_mult_tooltip" },
                            { setting_id = "start_boon_deus_timed_block_free_shot",                        type = "checkbox", default_value = false, tooltip = "start_boon_deus_timed_block_free_shot_tooltip" },
                            { setting_id = "start_boon_deus_uninterruptable_attacks",                      type = "checkbox", default_value = false, tooltip = "start_boon_deus_uninterruptable_attacks_tooltip" },
                            { setting_id = "start_boon_detect_weakness",                                   type = "checkbox", default_value = false, tooltip = "start_boon_detect_weakness_tooltip" },
                            { setting_id = "start_boon_explosive_kills_on_elite_kills",                    type = "checkbox", default_value = false, tooltip = "start_boon_explosive_kills_on_elite_kills_tooltip" },
                            { setting_id = "start_boon_explosive_ordinance",                               type = "checkbox", default_value = false, tooltip = "start_boon_explosive_ordinance_tooltip" },
                            { setting_id = "start_boon_explosive_pushes_on_damage_taken",                  type = "checkbox", default_value = false, tooltip = "start_boon_explosive_pushes_on_damage_taken_tooltip" },
                            { setting_id = "start_boon_focused_accuracy",                                  type = "checkbox", default_value = false, tooltip = "start_boon_focused_accuracy_tooltip" },
                            { setting_id = "start_boon_grenadier",                                         type = "checkbox", default_value = false, tooltip = "start_boon_grenadier_tooltip" },
                            { setting_id = "start_boon_indomitable",                                       type = "checkbox", default_value = false, tooltip = "start_boon_indomitable_tooltip" },
                            { setting_id = "start_boon_last_player_standing_power_reg",                    type = "checkbox", default_value = false, tooltip = "start_boon_last_player_standing_power_reg_tooltip" },
                            { setting_id = "start_boon_lucky",                                             type = "checkbox", default_value = false, tooltip = "start_boon_lucky_tooltip" },
                            { setting_id = "start_boon_melee_killing_spree_speed",                         type = "checkbox", default_value = false, tooltip = "start_boon_melee_killing_spree_speed_tooltip" },
                            { setting_id = "start_boon_melee_wave",                                        type = "checkbox", default_value = false, tooltip = "start_boon_melee_wave_tooltip" },
                            { setting_id = "start_boon_missing_health_power_up",                           type = "checkbox", default_value = false, tooltip = "start_boon_missing_health_power_up_tooltip" },
                            { setting_id = "start_boon_pent_up_anger",                                     type = "checkbox", default_value = false, tooltip = "start_boon_pent_up_anger_tooltip" },
                            { setting_id = "start_boon_pyrotechnical_echo",                                type = "checkbox", default_value = false, tooltip = "start_boon_pyrotechnical_echo_tooltip" },
                            { setting_id = "start_boon_pyrrhic_strength",                                  type = "checkbox", default_value = false, tooltip = "start_boon_pyrrhic_strength_tooltip" },
                            { setting_id = "start_boon_resolve",                                           type = "checkbox", default_value = false, tooltip = "start_boon_resolve_tooltip" },
                            { setting_id = "start_boon_shrapnel",                                          type = "checkbox", default_value = false, tooltip = "start_boon_shrapnel_tooltip" },
                            { setting_id = "start_boon_skill_by_block",                                    type = "checkbox", default_value = false, tooltip = "start_boon_skill_by_block_tooltip" },
                            { setting_id = "start_boon_speed_over_stamina",                                type = "checkbox", default_value = false, tooltip = "start_boon_speed_over_stamina_tooltip" },
                            { setting_id = "start_boon_squats",                                            type = "checkbox", default_value = false },
                            { setting_id = "start_boon_staggering_force",                                  type = "checkbox", default_value = false, tooltip = "start_boon_staggering_force_tooltip" },
                            { setting_id = "start_boon_static_blade",                                      type = "checkbox", default_value = false, tooltip = "start_boon_static_blade_tooltip" },
                            { setting_id = "start_boon_static_charge",                                     type = "checkbox", default_value = false, tooltip = "start_boon_static_charge_tooltip" },
                            { setting_id = "start_boon_surprise_strike",                                   type = "checkbox", default_value = false, tooltip = "start_boon_surprise_strike_tooltip" },
                            { setting_id = "start_boon_thorn_skin",                                        type = "checkbox", default_value = false, tooltip = "start_boon_thorn_skin_tooltip" },
                            { setting_id = "start_boon_triple_melee_headshot_power",                       type = "checkbox", default_value = false, tooltip = "start_boon_triple_melee_headshot_power_tooltip" },
                        },
                    },
                    {
                        setting_id = "start_boon_healing_and_sustain_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_boon_supportbomb_healing_01",                       type = "checkbox", default_value = false, tooltip = "start_boon_boon_supportbomb_healing_01_tooltip" },
                            { setting_id = "start_boon_curative_empowerment",                              type = "checkbox", default_value = false, tooltip = "start_boon_curative_empowerment_tooltip" },
                            { setting_id = "start_boon_deus_ammo_pickup_heal",                             type = "checkbox", default_value = false, tooltip = "start_boon_deus_ammo_pickup_heal_tooltip" },
                            { setting_id = "start_boon_deus_health_regeneration",                          type = "checkbox", default_value = false, tooltip = "start_boon_deus_health_regeneration_tooltip" },
                            { setting_id = "start_boon_deus_increased_healing_taken",                      type = "checkbox", default_value = false, tooltip = "start_boon_deus_increased_healing_taken_tooltip" },
                            { setting_id = "start_boon_deus_knockdown_damage_immunity_aura",               type = "checkbox", default_value = false, tooltip = "start_boon_deus_knockdown_damage_immunity_aura_tooltip" },
                            { setting_id = "start_boon_deus_max_health",                                   type = "checkbox", default_value = false, tooltip = "start_boon_deus_max_health_tooltip" },
                            { setting_id = "start_boon_deus_revive_regen",                                 type = "checkbox", default_value = false, tooltip = "start_boon_deus_revive_regen_tooltip" },
                            { setting_id = "start_boon_deus_second_wind",                                  type = "checkbox", default_value = false, tooltip = "start_boon_deus_second_wind_tooltip" },
                            { setting_id = "start_boon_hand_of_shallya",                                   type = "checkbox", default_value = false, tooltip = "start_boon_hand_of_shallya_tooltip" },
                            { setting_id = "start_boon_heal_on_dot_damage_dealt",                          type = "checkbox", default_value = false, tooltip = "start_boon_heal_on_dot_damage_dealt_tooltip" },
                            { setting_id = "start_boon_healers_touch",                                     type = "checkbox", default_value = false, tooltip = "start_boon_healers_touch_tooltip" },
                            { setting_id = "start_boon_health_orbs",                                       type = "checkbox", default_value = false, tooltip = "start_boon_health_orbs_tooltip" },
                            { setting_id = "start_boon_hidden_escape",                                     type = "checkbox", default_value = false, tooltip = "start_boon_hidden_escape_tooltip" },
                            { setting_id = "start_boon_invigorating_strike",                               type = "checkbox", default_value = false, tooltip = "start_boon_invigorating_strike_tooltip" },
                            { setting_id = "start_boon_natural_bond",                                      type = "checkbox", default_value = false, tooltip = "start_boon_natural_bond_tooltip" },
                            { setting_id = "start_boon_power_up_of_shallya",                               type = "checkbox", default_value = false, tooltip = "start_boon_power_up_of_shallya_tooltip" },
                            { setting_id = "start_boon_protection_orbs",                                   type = "checkbox", default_value = false, tooltip = "start_boon_protection_orbs_tooltip" },
                            { setting_id = "start_boon_tenacious",                                         type = "checkbox", default_value = false, tooltip = "start_boon_tenacious_tooltip" },
                            { setting_id = "start_boon_transfer_temp_health_at_full",                      type = "checkbox", default_value = false, tooltip = "start_boon_transfer_temp_health_at_full_tooltip" },
                        },
                    },
                    {
                        setting_id = "start_boon_utility_and_team_group",
                        type = "group",
                        sub_widgets = {
                            { setting_id = "start_boon_boon_aura_01",                                      type = "checkbox", default_value = false, tooltip = "start_boon_boon_aura_01_tooltip" },
                            { setting_id = "start_boon_boon_aura_02",                                      type = "checkbox", default_value = false, tooltip = "start_boon_boon_aura_02_tooltip" },
                            { setting_id = "start_boon_boon_aura_03",                                      type = "checkbox", default_value = false, tooltip = "start_boon_boon_aura_03_tooltip" },
                            { setting_id = "start_boon_boon_deus_coins_greed",                             type = "checkbox", default_value = false, tooltip = "start_boon_boon_deus_coins_greed_tooltip" },
                            { setting_id = "start_boon_boon_teamaura_01",                                  type = "checkbox", default_value = false, tooltip = "start_boon_boon_teamaura_01_tooltip" },
                            { setting_id = "start_boon_boon_teamaura_02",                                  type = "checkbox", default_value = false, tooltip = "start_boon_boon_teamaura_02_tooltip" },
                            { setting_id = "start_boon_boon_weaponrarity_01",                              type = "checkbox", default_value = false, tooltip = "start_boon_boon_weaponrarity_01_tooltip" },
                            { setting_id = "start_boon_boon_weaponrarity_02",                              type = "checkbox", default_value = false, tooltip = "start_boon_boon_weaponrarity_02_tooltip" },
                            { setting_id = "start_boon_comradery",                                         type = "checkbox", default_value = false, tooltip = "start_boon_comradery_tooltip" },
                            { setting_id = "start_boon_cooldown_on_friendly_ability",                      type = "checkbox", default_value = false, tooltip = "start_boon_cooldown_on_friendly_ability_tooltip" },
                            { setting_id = "start_boon_decanter",                                          type = "checkbox", default_value = false, tooltip = "start_boon_decanter_tooltip" },
                            { setting_id = "start_boon_deus_ammo_pickup_give_allies_ammo",                 type = "checkbox", default_value = false, tooltip = "start_boon_deus_ammo_pickup_give_allies_ammo_tooltip" },
                            { setting_id = "start_boon_deus_coin_pickup_regen",                            type = "checkbox", default_value = false, tooltip = "start_boon_deus_coin_pickup_regen_tooltip" },
                            { setting_id = "start_boon_deus_cooldown_reg_not_hit",                         type = "checkbox", default_value = false, tooltip = "start_boon_deus_cooldown_reg_not_hit_tooltip" },
                            { setting_id = "start_boon_deus_cooldown_regen",                               type = "checkbox", default_value = false, tooltip = "start_boon_deus_cooldown_regen_tooltip" },
                            { setting_id = "start_boon_deus_extra_stamina",                                type = "checkbox", default_value = false, tooltip = "start_boon_deus_extra_stamina_tooltip" },
                            { setting_id = "start_boon_deus_free_potion_use_on_ability",                   type = "checkbox", default_value = false, tooltip = "start_boon_deus_free_potion_use_on_ability_tooltip" },
                            { setting_id = "start_boon_deus_grenade_multi_throw",                          type = "checkbox", default_value = false, tooltip = "start_boon_deus_grenade_multi_throw_tooltip" },
                            { setting_id = "start_boon_deus_guard_aura_check",                             type = "checkbox", default_value = false, tooltip = "start_boon_deus_guard_aura_check_tooltip" },
                            { setting_id = "start_boon_deus_infinite_dodges",                              type = "checkbox", default_value = false, tooltip = "start_boon_deus_infinite_dodges_tooltip" },
                            { setting_id = "start_boon_deus_large_ammo_pickup_infinite_ammo",              type = "checkbox", default_value = false, tooltip = "start_boon_deus_large_ammo_pickup_infinite_ammo_tooltip" },
                            { setting_id = "start_boon_deus_skill_on_special_kill",                        type = "checkbox", default_value = false, tooltip = "start_boon_deus_skill_on_special_kill_tooltip" },
                            { setting_id = "start_boon_deus_throw_speed_increase",                         type = "checkbox", default_value = false, tooltip = "start_boon_deus_throw_speed_increase_tooltip" },
                            { setting_id = "start_boon_deus_transmute_into_coins",                         type = "checkbox", default_value = false, tooltip = "start_boon_deus_transmute_into_coins_tooltip" },
                            { setting_id = "start_boon_drop_item_on_ability_use",                          type = "checkbox", default_value = false, tooltip = "start_boon_drop_item_on_ability_use_tooltip" },
                            { setting_id = "start_boon_friendly_cooldown_on_ability",                      type = "checkbox", default_value = false, tooltip = "start_boon_friendly_cooldown_on_ability_tooltip" },
                            { setting_id = "start_boon_home_brewer",                                       type = "checkbox", default_value = false, tooltip = "start_boon_home_brewer_tooltip" },
                            { setting_id = "start_boon_money_magnet",                                      type = "checkbox", default_value = false, tooltip = "start_boon_money_magnet_tooltip" },
                            { setting_id = "start_boon_movement_speed_on_active_ability_use",              type = "checkbox", default_value = false, tooltip = "start_boon_movement_speed_on_active_ability_use_tooltip" },
                            { setting_id = "start_boon_sharing_is_caring",                                 type = "checkbox", default_value = false, tooltip = "start_boon_sharing_is_caring_tooltip" },
                            { setting_id = "start_boon_wolfpack",                                          type = "checkbox", default_value = false, tooltip = "start_boon_wolfpack_tooltip" },
                        },
                    },
                },
            },
            {
                setting_id = "banned_traits_group",
                type = "group",
                sub_widgets = {
                    { setting_id = "ban_trait_always_blocking",                            type = "checkbox", default_value = false, tooltip = "ban_trait_always_blocking_tooltip" },
                    { setting_id = "ban_trait_armor_breaker",                              type = "checkbox", default_value = false, tooltip = "ban_trait_armor_breaker_tooltip" },
                    { setting_id = "ban_trait_bloodthirst",                                type = "checkbox", default_value = false, tooltip = "ban_trait_bloodthirst_tooltip" },
                    { setting_id = "ban_trait_crescendo_strike",                           type = "checkbox", default_value = false, tooltip = "ban_trait_crescendo_strike_tooltip" },
                    { setting_id = "ban_trait_deus_ammo_pickup_reload_speed",              type = "checkbox", default_value = false, tooltip = "ban_trait_deus_ammo_pickup_reload_speed_tooltip" },
                    { setting_id = "ban_trait_deus_big_swing_stagger",                     type = "checkbox", default_value = false, tooltip = "ban_trait_deus_big_swing_stagger_tooltip" },
                    { setting_id = "ban_trait_deus_collateral_damage_on_melee_killing_blow", type = "checkbox", default_value = false, tooltip = "ban_trait_deus_collateral_damage_on_melee_killing_blow_tooltip" },
                    { setting_id = "ban_trait_deus_crit_chain_lightning",                  type = "checkbox", default_value = false, tooltip = "ban_trait_deus_crit_chain_lightning_tooltip" },
                    { setting_id = "ban_trait_deus_extra_shot",                            type = "checkbox", default_value = false, tooltip = "ban_trait_deus_extra_shot_tooltip" },
                    { setting_id = "ban_trait_deus_ranged_crit_explosion",                 type = "checkbox", default_value = false, tooltip = "ban_trait_deus_ranged_crit_explosion_tooltip" },
                    { setting_id = "ban_trait_follow_up",                                  type = "checkbox", default_value = false, tooltip = "ban_trait_follow_up_tooltip" },
                    { setting_id = "ban_trait_headhunter",                                 type = "checkbox", default_value = false, tooltip = "ban_trait_headhunter_tooltip" },
                    { setting_id = "ban_trait_home_run",                                   type = "checkbox", default_value = false, tooltip = "ban_trait_home_run_tooltip" },
                    { setting_id = "ban_trait_melee_attack_speed_on_crit",                 type = "checkbox", default_value = false, tooltip = "ban_trait_melee_attack_speed_on_crit_tooltip" },
                    { setting_id = "ban_trait_melee_counter_push_power",                   type = "checkbox", default_value = false, tooltip = "ban_trait_melee_counter_push_power_tooltip" },
                    { setting_id = "ban_trait_melee_heal_on_crit",                         type = "checkbox", default_value = false, tooltip = "ban_trait_melee_heal_on_crit_tooltip" },
                    { setting_id = "ban_trait_melee_increase_damage_on_block",             type = "checkbox", default_value = false, tooltip = "ban_trait_melee_increase_damage_on_block_tooltip" },
                    { setting_id = "ban_trait_melee_shield_on_assist",                     type = "checkbox", default_value = false, tooltip = "ban_trait_melee_shield_on_assist_tooltip" },
                    { setting_id = "ban_trait_melee_timed_block_cost",                     type = "checkbox", default_value = false, tooltip = "ban_trait_melee_timed_block_cost_tooltip" },
                    { setting_id = "ban_trait_piercing_projectiles",                       type = "checkbox", default_value = false, tooltip = "ban_trait_piercing_projectiles_tooltip" },
                    { setting_id = "ban_trait_ranged_consecutive_hits_increase_power",     type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_consecutive_hits_increase_power_tooltip" },
                    { setting_id = "ban_trait_ranged_increase_power_level_vs_armour_crit", type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_increase_power_level_vs_armour_crit_tooltip" },
                    { setting_id = "ban_trait_ranged_reduce_cooldown_on_crit",             type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_reduce_cooldown_on_crit_tooltip" },
                    { setting_id = "ban_trait_ranged_reduced_overcharge",                  type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_reduced_overcharge_tooltip" },
                    { setting_id = "ban_trait_ranged_remove_overcharge_on_crit",           type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_remove_overcharge_on_crit_tooltip" },
                    { setting_id = "ban_trait_ranged_restore_stamina_headshot",            type = "checkbox", default_value = false, tooltip = "ban_trait_ranged_restore_stamina_headshot_tooltip" },
                    { setting_id = "ban_trait_refilling_shot",                             type = "checkbox", default_value = false, tooltip = "ban_trait_refilling_shot_tooltip" },
                    { setting_id = "ban_trait_serrated_blade",                             type = "checkbox", default_value = false, tooltip = "ban_trait_serrated_blade_tooltip" },
                    { setting_id = "ban_trait_shield_of_isha",                             type = "checkbox", default_value = false, tooltip = "ban_trait_shield_of_isha_tooltip" },
                    { setting_id = "ban_trait_shield_splinters",                           type = "checkbox", default_value = false, tooltip = "ban_trait_shield_splinters_tooltip" },
                    { setting_id = "ban_trait_stagger_aoe_on_crit",                        type = "checkbox", default_value = false, tooltip = "ban_trait_stagger_aoe_on_crit_tooltip" },
                },
            },
        },
    },
}
