return function(H, root)
    local fixture = assert(loadfile(root .. "/qa/lua/tests/fixtures/dialogue_transaction_fixture.lua"))()
    H.test("998 installed row stages then actual Apply commits CD once", function()
        local f = fixture(root)
        H.truthy(f:click())
        H.equal(0, f.writes)
        H.equal(0, f.reconciles)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
        H.equal(false, f.view._apply.content.disabled)
        f.UI.refresh_row(f.view._rows[1], f.view)
        H.equal(true, f.view._rows[1].content.flag)
        f.view:_build_rows(f.category)
        H.equal(true, f.view._rows[1].content.flag)
        f.view:apply_pending(f.category)
        H.equal(1, f.writes)
        H.equal(1, f.reconciles)
        H.equal(true, f.stored.auto_isolation)
        H.equal(true, f.view._apply.content.disabled)
        H.equal(0, f.gut_writes, "no GUT shadow value or unsupported profile capture")
        f.view:apply_pending(f.category)
        H.equal(1, f.writes)
        H.equal(true, f:new_view()._rows[1].content.flag)
    end)
    H.test("998 pending false survives refresh and exit discards uncommitted draft", function()
        local f = fixture(root)
        f.setting.set(true)
        f:click()
        H.equal(false, f.view._pending.character_dialogue.auto_isolation)
        f.view:_build_rows(f.category)
        H.equal(false, f.view._rows[1].content.flag)
        f.view:on_exit()
        H.equal(true, f.stored.auto_isolation)
        H.equal(1, f.writes)
        H.equal(nil, next(f.view._pending))
        H.equal(true, f:new_view()._rows[1].content.flag)
    end)
    for _, failure in ipairs({ "fail_write", "fail_callback" }) do
        H.test("998 actual Apply retains draft on " .. failure, function()
            local f = fixture(root)
            f:click()
            f[failure] = true
            f.view:apply_pending(f.category)
            H.equal(true, f.view._pending.character_dialogue.auto_isolation)
            H.equal(false, f.view._apply.content.disabled)
            H.equal(0, f.gut_writes)
            f[failure] = nil
            f.view:apply_pending(f.category)
            H.equal(true, f.stored.auto_isolation)
            H.equal(1, f.reconciles)
            H.equal(true, f.view._apply.content.disabled)
        end)
    end
    H.test("998 old protocol hidden and disappearance cannot shadow-commit", function()
        local f = fixture(root)
        f:click()
        f.cd.character_dialogue_api.isolation_setting = nil
        f.view:_build_rows(f.category)
        H.equal(nil, f.view._rows[1]._dialogue_isolation)
        f.view:apply_pending(f.category)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
    end)
    H.test("998 Dialogue cannot consume another tab's profiles or defaults", function()
        local f = fixture(root)
        f.view._build_nodes = { { setting_id = "foreign", type = "checkbox", default_value = true } }
        f.view:_profile_ensure(f.category)
        f.view:_profile_capture(f.category)
        f.view:_switch_profile(2)
        f.view:reset_to_defaults()
        f.view:_queue_reset_popup()
        H.equal(nil, next(f.view._pending))
        H.equal(0, f.gut_writes)
        H.equal(8, f.view._profile_slot)
        f.view:_build_rows(f.category)
        H.equal(0, #f.view._build_nodes)
    end)
    H.test("998 installed DEFAULT refuses custom policy before nodes or reseed", function()
        local f = fixture(root)
        f:click()
        local pending = f.view._pending.character_dialogue
        -- A stale merged-owner list would arm a reseed if the policy ran late.
        f.category._owner_mod_ids = { "wt_dev" }
        f.view._build_nodes = { setmetatable({}, { __index = function()
            error("custom-tab nodes must not be read")
        end }) }
        f.view._build_rows = function() error("refusal must not repaint") end
        f.view:reset_to_defaults()
        H.equal(pending, f.view._pending.character_dialogue)
        H.equal(true, pending.auto_isolation)
        H.equal(nil, f.view._official_reseed_pending)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
    end)
    H.test("998 installed DEFAULT refuses absent category or nodes without mutation", function()
        local f = fixture(root)
        local pending = f.view._pending
        f.view.stage_set = function() error("incomplete build must not stage") end
        f.view._build_rows = function() error("incomplete build must not repaint") end
        f.view._build_category = nil
        f.view:reset_to_defaults()
        f.view._build_category = { mod_id = "wt_dev" }
        f.view._build_nodes = nil
        f.view:reset_to_defaults()
        H.equal(pending, f.view._pending)
        H.equal(nil, next(pending))
        H.equal(nil, f.view._official_reseed_pending)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
    end)
    H.test("998 installed DEFAULT delegates normal owner-qualified staging", function()
        local f = fixture(root)
        local category = { mod_id = "equipment", _owner_mod_ids = { "wt_dev", "cosmetics_tweaker" },
            _owners = { false_default = { mod_id = "wt_dev" },
                zero_default = { mod_id = "cosmetics_tweaker" } } }
        f.view._build_category, f.view._categories = category, { category }
        f.view._build_nodes = {
            { setting_id = "false_default", type = "checkbox", default_value = false },
            { content = { setting_id = "zero_default", type = "numeric", default_value = 0 } },
            { setting_id = "binding", type = "keybind", default_value = {} },
            { setting_id = "no_default", type = "checkbox" },
            { type = "group" },
        }
        local reset = f.env.get_mod("gut_dev"):dofile("scripts/mods/gui_tweaker_dev/_mod_tweaker_default_reset")
        local stage, delegated, repaints = reset.stage_defaults, 0, 0
        reset.stage_defaults = function(...)
            delegated = delegated + 1
            return stage(...)
        end
        f.view._build_rows = function(_, value)
            H.equal(category, value); repaints = repaints + 1
        end
        f.view:reset_to_defaults()
        H.equal(1, delegated)
        H.equal(1, repaints)
        H.equal(false, f.view._pending.wt_dev.false_default)
        H.equal(0, f.view._pending.cosmetics_tweaker.zero_default)
        H.equal(nil, f.view._pending.equipment, "no keybind or empty-default draft")
        H.equal(true, reset.is_armed(f.view, category))
        H.equal(false, f.view._apply.content.disabled)
        H.equal(nil, f.view._dirty, "staging is not a live write")
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
    end)
    H.test("998 installed DEFAULT accepts zero-setting loadout reseed", function()
        local f = fixture(root)
        local category = { mod_id = "wt_dev" }
        f.view._build_category, f.view._categories = category, { category }
        f.view._build_nodes = {}
        local repaints = 0
        f.view._build_rows = function() repaints = repaints + 1 end
        f.view:reset_to_defaults()
        H.equal(1, repaints)
        H.equal(nil, next(f.view._pending))
        H.equal(true, f.view._official_reseed_pending.wt_dev)
        H.equal(false, f.view._apply.content.disabled)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
    end)
    H.test("998 actual CD entry reconciles active preview only after Apply and preserves manual owner", function()
        local f = fixture(root)
        f:load_live_cd()
        H.truthy(f.api.play("pes_fixture_01"))
        f:click()
        H.equal(0.37, f.buses.music_bus_volume)
        f.view:apply_pending(f.category)
        H.equal(0, f.buses.music_bus_volume)
        H.equal(1, f.writes)
        f.cd.toggle_audio_isolation()
        f:click()
        f.view:apply_pending(f.category)
        H.equal(2, f.writes)
        H.equal(false, f.stored.auto_isolation)
        H.equal(0, f.buses.music_bus_volume, "manual ownership must survive preview release")
        f.api.stop()
        H.equal(0, f.buses.sfx_bus_volume)
        f.cd.toggle_audio_isolation()
        H.equal(0.37, f.buses.music_bus_volume)
        H.equal(0.81, f.buses.sfx_bus_volume)
    end)
    H.test("998 actual CD API writes once and VMF notify plus completion use same lifecycle", function()
        local f = fixture(root)
        f:load_live_cd()
        H.truthy(f.api.play("pes_fixture_01"))
        f.api.set_auto_isolation(true)
        H.equal(1, f.writes)
        H.equal(0, f.buses.sfx_bus_volume)
        f.cd:set("auto_isolation", false, true)
        H.equal(2, f.writes)
        H.equal(0.81, f.buses.sfx_bus_volume)
        f:click()
        f.view:apply_pending(f.category)
        H.equal(3, f.writes)
        f.playing = false
        f.cd.update(0.1)
        H.equal(0.81, f.buses.sfx_bus_volume, "natural completion restores exact saved volume")
    end)
    H.test("998 controller confirm and arrow input use the same pending setting", function()
        local f = fixture(root)
        H.truthy(f.UI.handle_controller(f.view, { get = function(_, key) return key == "confirm" end }))
        H.equal(0, f.writes)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
        f.view:apply_pending(f.category)
        local row = f.view._rows[1]
        row.content.dec.on_left_release = true
        H.truthy(f.UI.handle_row(f.view, row))
        H.equal(false, f.view._pending.character_dialogue.auto_isolation)
        H.equal(1, f.writes)
    end)
    H.test("998 runtime contract invokes isolated production setting and transaction", function()
        local f = fixture(root)
        f:load_live_cd()
        local chunk = assert(loadfile(root .. "/gui_tweaker_dev/scripts/mods/gui_tweaker_dev/_gut_dialogue_contract.lua"))
        setfenv(chunk, f.env)
        local check
        chunk().install(function(name, fn)
            H.equal("issue998_dialogue_staged_isolation", name)
            check = fn
        end)
        H.equal(nil, check())
        H.equal(0, f.writes, "runtime check must not write the real CD owner")
    end)
    H.test("998 unavailable Wwise preserves v5 setter compatibility but fails new Apply", function()
        local f = fixture(root)
        f:load_live_cd()
        H.truthy(f.api.play("pes_fixture_01"))
        f.env.Managers.world.world = function() return nil end
        local ok, value = pcall(f.api.set_auto_isolation, true)
        H.equal(true, ok, "old GUI invokes v5 setter without pcall")
        H.equal(true, value)
        H.equal(true, f.stored.auto_isolation)
        f.api.set_auto_isolation(false)
        f:click()
        f.view:apply_pending(f.category)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
        H.equal(false, f.view._apply.content.disabled)
        f.env.Managers.world.world = function() return {} end
        f.view:apply_pending(f.category)
        H.equal(true, f.view._apply.content.disabled)
        H.equal(0, f.buses.music_bus_volume)
    end)
    H.test("998 fresh CD initialization consumes only its persisted owner setting", function()
        local f = fixture(root, { auto_isolation = true })
        f:load_live_cd()
        H.equal(true, f.view._rows[1].content.flag)
        H.equal(0, f.writes)
        H.truthy(f.api.play("pes_fixture_01"))
        H.equal(0, f.buses.music_bus_volume)
        f.cd.on_disabled()
        H.equal(0.37, f.buses.music_bus_volume)
        H.equal(0, f.gut_writes)
    end)
    H.test("998 missing or degraded owner cannot consume an existing draft", function()
        local f = fixture(root)
        f:click()
        f.absent = true
        f.view:apply_pending(f.category)
        H.equal(0, f.writes)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
        f.absent = false
        f.cd.on_settings_batch_changed = nil
        f.view:apply_pending(f.category)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
    end)
    H.test("998 replaced live owner cannot consume another owner's draft", function()
        local f = fixture(root)
        f:click()
        local original = f.env.get_mod
        local replacement = { character_dialogue_api = f.cd.character_dialogue_api,
            set = function() error("replacement must not write") end,
            on_settings_batch_changed = function() error("replacement must not notify") end }
        f.env.get_mod = function(id)
            if id == "character_dialogue" then return replacement end
            return original(id)
        end
        f.view:apply_pending(f.category)
        H.equal(true, f.view._pending.character_dialogue.auto_isolation)
        H.equal(false, f.view._apply.content.disabled)
        H.equal(0, f.writes)
        H.equal(0, f.gut_writes)
    end)
end
