return function(H, repo_root)
    local root = repo_root
        .. "/general_tweaker_dev/scripts/mods/general_tweaker_dev/"
    local Policy = assert(loadfile(root .. "_gt_godmode_outgoing_policy.lua"))()

    H.test("GT Godmode final damage remains positive enemy-only", function()
        H.equal(Policy.should_override_final(10, true, true, false), true)
        H.equal(Policy.should_override_final(10, true, false, true), true)
        H.equal(Policy.should_override_final(0, true, true, false), false)
        H.equal(Policy.should_override_final(10, false, true, false), false)
        H.equal(Policy.should_override_final(10, true, false, false), false)
        H.equal(Policy.should_override_final(nil, true, true, false), false)
    end)

    H.test("GT Godmode recognizes only ordinary and super armor", function()
        H.equal(Policy.is_armored_target(2, nil), true)
        H.equal(Policy.is_armored_target(6, nil), true)
        H.equal(Policy.is_armored_target(1, 2), true)
        H.equal(Policy.is_armored_target(1, 6), true)
        H.equal(Policy.is_armored_target(1, nil), false)
        H.equal(Policy.is_armored_target(0, nil), false)
        H.equal(Policy.is_armored_target(3, nil), false)
        H.equal(Policy.is_armored_target(5, nil), false)
    end)

    H.test("GT Godmode lifts only armor-caused zero damage", function()
        local should = Policy.should_override_armor_zero
        H.equal(should(0, false, false, true, true, 2, nil, 0, 0.2, false), true)
        H.equal(should(0, false, false, true, true, 1, 6, 0, 0.2, false), true)
        H.equal(should(1, false, false, true, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, true, false, true, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, 1, false, true, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, false, true, true, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, false, 1, true, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, false, false, false, true, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, false, false, true, false, 2, nil, 0, 0.2, false), false)
        H.equal(should(0, false, false, true, true, 1, nil, 0, 0.2, false), false)
        H.equal(should(0, false, false, true, true, 3, nil, 0, 0.2, false), false)
        H.equal(should(0, false, false, true, true, 2, nil, 0.5, 0.2, false), false)
        H.equal(should(0, false, false, true, true, 2, nil, -0.5, 0.2, false), false)
        H.equal(should(0, false, false, true, true, 2, nil, 0, 0, false), false)
        H.equal(should(0, false, false, true, true, 2, nil, 0, nil, false), false)
        H.equal(should(0, false, false, true, true, 2, nil, 0, 0.2, true), false)
        H.equal(should(0, false, false, true, true, 2, nil, 0, 0.2, 1), false)
    end)

    H.test("GT owns one narrow calculate_damage hook without profile mutation", function()
        local file = assert(io.open(root .. "general_tweaker_dev.lua", "rb"))
        local source = file:read("*a")
        file:close()
        H.equal(select(2, source:gsub(
            'mod:hook%("DamageUtils", "calculate_damage"', '')), 1)
        H.truthy(source:find("_gt1008_should_override_armor_zero", 1, true))
        H.equal(source:find("DamageProfileTemplates[damage_source] =", 1, true), nil)
    end)
end
