return function(H, repo_root)
    local root = repo_root .. "/dynamic_cosmetic_portraits/scripts/mods/dynamic_cosmetic_portraits/"
    local probe = dofile(root .. "_dcp_player_scope_probe.lua")
    local file = assert(io.open(root .. "dynamic_cosmetic_portraits.lua", "rb"))
    local source = file:read("*a")
    file:close()

    H.test("DCP player-scope evidence deduplicates exact results", function()
        local state = probe.new(4)
        H.truthy(probe.accept(state, "hud", "remote:1", "portrait_a", "custom"))
        H.equal(probe.accept(state, "hud", "remote:1", "portrait_a", "custom"), false)
        H.truthy(probe.accept(state, "tab", "remote:1", "portrait_a", "custom"))
        H.equal(state.count, 2)
    end)

    H.test("DCP player-scope evidence has a hard record cap", function()
        local state = probe.new(2)
        H.truthy(probe.accept(state, "hud", "bot:2", "a", "custom"))
        H.truthy(probe.accept(state, "tab", "bot:2", "a", "custom"))
        H.equal(probe.accept(state, "score", "bot:2", "vanilla", "vanilla"), false)
        H.equal(state.count, 2)
    end)

    H.test("DCP player-scope evidence covers all primary remote surfaces", function()
        H.truthy(source:find('_scope_evidence("hud"', 1, true))
        H.truthy(source:find('_scope_evidence("tab"', 1, true))
        H.truthy(source:find('_scope_evidence("score"', 1, true))
        H.truthy(source:find('mod:info("[dcp:435]', 1, true))
        H.equal(source:find('mod:echo("[dcp:435]', 1, true), nil)
    end)

    H.test("DCP local-player lookups are safe across title transitions", function()
        local executable = source:gsub("%-%-[^\n]*", "")
        H.truthy(source:find('local function _local_player_safe(player_manager)', 1, true))
        H.truthy(source:find('pm.local_player_safe', 1, true))
        H.truthy(source:find('_rt_register("local_player_safe_network_lifecycle_609"', 1, true))
        H.truthy(source:find('title state must yield nil', 1, true))
        H.truthy(source:find('ingame state lost player', 1, true))
        H.equal(executable:find(':local_player%(%s*%)'), nil)
    end)
end
