local script_path = arg[0]:gsub("\\", "/")
local lua_root = script_path:match("^(.*)/run%.lua$") or "."
local repo_root = lua_root:match("^(.*)/qa/lua$") or "."

package.path = table.concat({
    lua_root .. "/?.lua",
    lua_root .. "/tests/?.lua",
    package.path,
}, ";")

local Harness = require("harness")

local function run_harness_self_test()
    Harness.test("self-test pass sentinel", function()
        Harness.equal("Lua 5.1", _VERSION)
    end)
    local passed, total, failed = Harness.run({ quiet = true })
    if not passed or total ~= 1 or failed ~= 0 then
        error("harness positive-path self-test failed")
    end

    Harness.test("self-test planted failure", function()
        Harness.equal("actual", "expected", "planted failure")
    end)
    local original_stderr = io.stderr
    io.stderr = { write = function() end }
    local negative_passed, negative_total, negative_failed = Harness.run({ quiet = true })
    io.stderr = original_stderr
    if negative_passed or negative_total ~= 1 or negative_failed ~= 1 then
        error("harness did not detect a planted failure")
    end

    io.write("[lua_unit_tests] SELF-TEST OK -- pass and planted-failure paths verified.\n")
end

if arg[1] == "--self-test" then
    run_harness_self_test()
    os.exit(0)
end

local suites = {
	"test_shared_weapon_appearance",
	"test_shared_career_weapon_actions",
	"test_shared_debug",
    "test_attack_labeler",
    "test_crt_ale_decay",
    "test_crt_ale_animation",
    "test_crt_bardin_disabler_probe",
    "test_crt_damage_classification",
    "test_crt_rework_master_policy",
    "test_crt_umbrella_audit",
    "test_crt_dance_of_blades",
    "test_crt_flagellation",
    "test_crt_foot_knight_policy",
    "test_crt_balance_split",
    "test_crt_retired_big_rebalance",
    "test_crt_talent_selection",
    "test_crt_wire_contract",
    "test_mod_tweaker_transaction",
    "test_mod_tweaker_profiles",
    "test_mod_tweaker_tab_labels",
    "test_gut_label_policy",
    "test_gut_gear_accent_parity",
    "test_gut_dx12_fence630",
    "test_mod_tweaker_ordering",
    "test_mod_tweaker_disabled_sections",
    "test_gut_video_profiles",
    "test_gut_cutscene_probe",
    "test_gut_cutscene_policy274",
    "test_gut_cutscene_skipwindow",
    "test_et_settings_queue",
    "test_et_health_multiplier",
    "test_et_personal_handicap",
    "test_et_special_variants",
    "test_et_enemy_modifiers",
    "test_et_boss_ideas",
    "test_et_pacing_tick_guard",
    "test_rt_harness_context_absent",
    "test_event_high_intensity_probe",
    "test_event_mission_allowlist",
    "test_event_curse_join_policy",
    "test_ct_mission_progress",
    "test_event_shadow_adventure",
    "test_gut_all_languages_diagnostics",
    "test_mod_tweaker_search",
    "test_mod_tweaker_numeric_editor",
    "test_mp_dailies",
    "test_mp_quest_boundary",
    "test_mp_shilling_ui_policy",
    "test_mp_emporium_purchase",
    "test_mp_loot_diag",
    "test_wt_passive_charge",
    "test_wt_hold_pose",
    "test_wt_overcharge_presentation",
    "test_wt_bolt_staff_overcharge",
    "test_wt_longbow_zoom_probe",
    "test_wt_flamestorm_fx",
    "test_wt_master_toggles",
    "test_wt_bardin_coverage",
    "test_wt_port_status",
    "test_wt_kruber_coverage",
    "test_wt_kerillian_coverage",
    "test_wt_saltzpyre_coverage",
    "test_wt_crossbow_offset",
    "test_wt_hand_transform_policy",
    "test_wt_warrior_priest_coverage",
    "test_wt_cwv_ownership",
    "test_wt_cwv_independence",
    "test_wt_axe_shield_heavy_chain",
    "test_wt_native_ownership",
    "test_wt_ranger_dual_preview",
    "test_cwv_remote_audio",
    "test_cwv_remote_identity",
    "test_cwv_husk_path",
    "test_cwv_old_musket_presentation",
    "test_cwv_texture_residency",
    "test_cwv_old_musket_preview",
    "test_cwv_outrider_model",
    "test_cwv_old_musket_interrupt",
    "test_cwv_anim_picker",
    "test_cwv_acquisition",
    "test_cwv_javelin_pickup",
    "test_cwv_damage_profile_wire",
    "test_cwv_cosmetic_skin_wire",
    "test_cwv_profile_package_wire",
    "test_cwv_exact_pair_state",
    "test_cwv_exact_appearance",
    "test_cwv_appearance_lifecycle",
    "test_cwv_dual_icons",
    "test_cwv_greataxe",
	"test_cwv_mod_unit_preview",
    "test_cwv_infantry_spear",
    "test_cwv_mace_hammer_identity",
    "test_cwv_crowbill_hammer_mode",
    "test_cwv_crowbill_runtime",
    "test_cwv_crowbill_presentation",
	"test_cwv_durable_transform",
	"test_cwv_relative_scale",
	"test_cwv_entry_decomposition",
    "test_cwv_dawi_maces",
    "test_cwv_crowbill_family",
    "test_cwv_axe_balance",
    "test_cwv_item_text",
    "test_cwv_smoke_bomb_probe",
    "test_cwv_combat_styles",
    "test_cwv_rapier_contract",
    "test_wt_cwv_tuskgor_default",
    "test_wt_cwv_effective_template",
    "test_cim_skin_persistence",
    "test_cim_bulk_cleanup",
    "test_cim_cwv_template_selector",
    "test_cim_cwv_template_catalog",
    "test_cim_keep_forge_interaction",
    "test_cim_athanor_icon_policy",
    "test_cim_mission_forge_widget_safety",
    "test_cim_salvage_autofill",
    "test_cim_synthetic_item_contract",
    "test_cim_trait_slot_policy",
    "test_cim_property_value_policy",
    "test_cim_tab_preview",
    "test_cim_regression_module",
    "test_woc_wire_policy",
	"test_cim_external_trait_policy",
    "test_woc_relic_policy",
	"test_woc_blightreaper_moveset",
	"test_woc_blightreaper_power",
	"test_woc_cursed_rarity",
	"test_woc_inventory_icons",
    "test_woc_appearance_policy",
	"test_woc_blightreaper_pulse",
	"test_woc_durable_transform",
	"test_woc_blightreaper_audio",
	"test_woc_attack_order",
    "test_dcp_portrait_materials",
    "test_dcp_player_scope_probe",
    "test_dcp_score_record",
    "test_cos_score_identity",
    "test_cos_husk_identity",
    "test_cos_custom_hats",
    "test_cos_grail_knight_set",
    "test_cos_resource_residency",
    "test_gut_inventory_preview_lighting",
    "test_gut_native_loadout_policy",
    "test_gut_loadout_slot_policy",
    "test_gut_mission_completion_policy",
    "test_gut_mission_vote_policy",
    "test_gut_wt_loadout_trace",
    "test_gut_exit_snapshot",
    "test_gt_dummy_collision_policy",
    "test_gut_simple_ui_bounds",
    "test_gut_hud_drag_geometry",
    "test_gut_respawn_anchor",
    "test_mod_tweaker_slider_steps",
    "test_gut_ckc_options_isolation",
    "test_gt_chest_pickup_probe",
    "test_gt_teleport_loop_policy",
    "test_cos_glow_lifecycle",
    "test_cos_glow_badge_policy",
    "test_cos_glow_instance_policy",
    "test_cos_cwv_dawi_mace_contract",
    "test_cos_wire",
    "test_peer_parity_transition",
    "test_ct_boon_catalog",
    "test_ct_boon_split",
    "test_ct_entry_decomposition",
    "test_ct_pool_floor_citadel_487",
    "test_ct_mission_graph_sync",
    "test_ct_umbrella_policy",
    "test_ct_cot_early_reward",
    "test_ct_cot_cost",
    "test_ct_chest_count_audit",
    "test_ct_spawn_pickup_two_return",
    "test_ct_ammo_guard_policy",
    "test_ct_anath_raema_contract",
    "test_ct_collectible_conversion",
    "test_ct_tower_skull_diag",
    "test_ct_tab_native_diag",
    "test_ct_parry_cooldown_contract",
    "test_ct_starting_talent_identity",
    "test_ct_bomb_cooldown_display",
    "test_ct_bot_economy",
    "test_ct_bot_coin_pickup",
    "test_ct_miasma",
    "test_ct_boon_pricing_audit",
    "test_ct_issue345_loc_status",
    "test_ct_manann_cooldown_display",
    "test_ct_progressive_difficulty",
    "test_ct_replacement_compensation",
    "test_ct_weave_curse_policy",
    "test_ct_modifier_stack_policy",
    "test_ct_progressive_elite_policy",
    "test_ct_resume_policy",
    "test_cos_offhand_preload_lifecycle",
    "test_cos_mh_package_lifecycle",
    "test_cos_runtime_modules",
    "test_cos_offhand_names",
    "test_cos_item_presentation",
    "test_cos_composite_icons",
    "test_cos_dual_offhands",
    "test_cos_offhand_commit_policy",
    "test_cos_cwv_remote_identity",
    "test_cos_la_shield_parity",
    "test_cos_la_instance_policy",
    "test_cos_la_replay_policy",
    "test_cos_weapon_pose_policy",
    "test_cos_deus_yield_policy",
    "test_gt_disconnect_grace",
    "test_gt_disable_enemy_spawns",
    "test_gt_noclip_boundary_policy",
    "test_gt_voip_disconnect_policy",
    "test_gt_stable_world_liveness",
    "test_gt_bot_heal_policy",
    "test_gt_bot_utility_policy",
    "test_gt_bot_ale_policy",
    "test_gt_bot_command_policy",
    "test_gt_godmode_indicator",
    "test_gt_network_readiness",
    "test_gt_necro_keep_policy",
    "test_gt_offline_twitch",
    "test_gt_lobby_failnotify_hardening",
    "test_gt_appearance_parity",
    "test_gt_improved_bot_combat_controls",
    "test_gt_bot_hazard_resistance",
    "test_gt_ai_takeover",
    "test_gt_bot_aid_pin_policy",
    "test_gt_solo_qol_explosion_arity",
    "test_et_boss_behavior",
    "test_gut_revive_scoreboard",
    "test_gut_scoreboard_diagnostics",
    "test_gut_hidden_passives",
    "test_gut_original_thp_names",
    "test_gut_loadout_capacity",
    "test_gut_backend_commit",
    "test_gut_bot_pose",
    "test_gut_tab_property_refresh",
    "test_gut_tab_talent_filter",
    "test_gut_tab_live_provider",
    "test_gut_localization_orphan_cleanup",
    "test_gut_career_hud_holder",
    "test_gut_cosmetics_mission_mount",
    "test_gut_module_extraction",
    "test_character_dialogue",
    "test_appearance_descriptor",
    "test_appearance_census",
}

for _, suite in ipairs(suites) do
    local register = require(suite)
    if type(register) ~= "function" then
        error(suite .. " must return a registration function")
    end
    register(Harness, repo_root)
end

local passed, total, failed = Harness.run()
if passed then
    io.write(string.format("[lua_unit_tests] OK -- %d tests passed under %s.\n", total, _VERSION))
    os.exit(0)
end

io.stderr:write(string.format("[lua_unit_tests] FAILED -- %d/%d tests failed.\n", failed, total))
os.exit(2)
