-- AUTO-GENERATED by tools/weapon-history/generate_patch_6_8_history.lua; DO NOT HAND-EDIT.
return {
    catalog_id = "wt_history_patch_6_8_v1",
    current_id = "current",
    current_source = {
        display_name = "Current (Game Version 6.12.0)",
        label = "6.12.0 source anchor",
        revision = "038498af2b565bcb10bf5ed225638293a7640c83",
    },
    derived_profiles = {},
    families = {
        [1] = {
            display_name = "Kerillian's Greatsword",
            id = "elf_greatsword",
            label_key = "wt_history_family_elf_greatsword",
            setting_id = "wt_history_elf_greatsword",
            state_order = {
                [1] = "6_7_2",
            },
            states = {
                ["6_7_2"] = {
                    direct_profile_names = {},
                    operations = {
                        [1] = {
                            change_class = "official_weapon_balance",
                            current_source_blob = "9d95add8cf0f06d1c52042e13d5f83912b7f3dd9",
                            expected_current = 1.55,
                            expected_present = true,
                            family_id = "elf_greatsword",
                            official_change_id = "P680-ELF-GS-H1-RANGE",
                            official_summary = "Patch 6.8 increased the distance of Kerillian Greatsword's first Heavy Attack.",
                            path = {
                                [1] = "actions",
                                [2] = "action_one",
                                [3] = "heavy_attack_down_first",
                                [4] = "range_mod",
                            },
                            result = 1.45,
                            result_present = true,
                            root = "Weapons",
                            source_blob = "be321d9239d7c0200102f005785587fd5d2dbf3c",
                            source_path = "scripts/settings/equipment/weapon_templates/2h_swords_wood_elf.lua",
                            source_revision = "b7c15fc61a3b34fae7d1e2de47f52198e26851ce",
                            state_id = "6_7_2",
                            template = "two_handed_swords_wood_elf_template",
                        },
                    },
                    profile_names = {},
                },
            },
            templates = {
                [1] = "two_handed_swords_wood_elf_template",
            },
        },
    },
    generation = {
        adjacent_operation_count = 1,
        global_operations = 0,
        profile_route_count = 0,
        unsupported_count = 0,
    },
    profile_specs = {},
    schema = 2,
    states = {
        ["6_7_2"] = {
            change_class = "official_weapon_balance",
            display_name = "Game Version 6.7.2",
            label_key = "wt_history_state_6_7_2",
            official_patch_notes = "https://forums.fatsharkgames.com/t/geheimnisnacht-and-the-skull-of-blosphoros-return-patch-6-8-0-hotfix-6-8-1/113884",
            source_revision = "b7c15fc61a3b34fae7d1e2de47f52198e26851ce",
        },
    },
}
