-- AUTO-GENERATED by tools/weapon-history/generate_patch_4_1_1_history.lua; DO NOT HAND-EDIT.
return {
    catalog_id = "wt_history_patch_4_1_1_v1",
    current_id = "current",
    current_source = {
        display_name = "Current (Game Version 6.12.1)",
        label = "6.12.1 source anchor",
        revision = "25fd7b8433e839b678d1c98a7a9af80918cbc252",
    },
    derived_profiles = {},
    families = {
        [1] = {
            display_name = "Bardin's Masterwork Pistol",
            id = "masterwork_pistol",
            label_key = "wt_history_family_masterwork_pistol",
            setting_id = "wt_history_masterwork_pistol",
            state_order = {
                [1] = "4_0_1",
            },
            states = {
                ["4_0_1"] = {
                    direct_profile_names = {},
                    operations = {
                        [1] = {
                            change_class = "official_weapon_balance",
                            current_source_blob = "d68819bb59bdece50b69c9401a9feb5ae238b3cb",
                            expected_current = false,
                            expected_present = true,
                            family_id = "masterwork_pistol",
                            official_change_id = "P411-MASTERWORK-PISTOL-AMMO-RELOAD",
                            official_summary = "Patch 4.1.1 stopped Masterwork Pistol reload animations from triggering on ammo pickup.",
                            path = {
                                [1] = "ammo_data",
                                [2] = "reload_on_ammo_pickup",
                            },
                            result = true,
                            result_present = true,
                            root = "Weapons",
                            source_blob = "25a4db5545750c0a5eb590e8d1bfc9882c80d30a",
                            source_path = "scripts/settings/equipment/weapon_templates/heavy_steam_pistol.lua",
                            source_revision = "872027662e076477451c8c4bf077473d8ab9e27d",
                            state_id = "4_0_1",
                            template = "heavy_steam_pistol_template_1",
                        },
                    },
                    profile_names = {},
                },
            },
            templates = {
                [1] = "heavy_steam_pistol_template_1",
            },
        },
    },
    generation = {
        adjacent_operation_count = 1,
        global_operations = 0,
        profile_route_count = 0,
        unsupported_count = 0,
    },
    profile_specs = {},
    schema = 2,
    states = {
        ["4_0_1"] = {
            change_class = "official_weapon_balance",
            display_name = "Game Version 4.0.1",
            label_key = "wt_history_state_4_0_1",
            official_patch_notes = "https://forums.fatsharkgames.com/t/patch-notes-version-4-1-1/43407",
            source_revision = "872027662e076477451c8c4bf077473d8ab9e27d",
        },
    },
}
