-- AUTO-GENERATED by tools/weapon-history/generate_patch_3_2_history.lua; DO NOT HAND-EDIT.
return {
    catalog_id = "wt_history_patch_3_2_v1",
    current_id = "current",
    current_source = {
        display_name = "Current (Game Version 6.12.0)",
        label = "6.12.0 source anchor",
        revision = "038498af2b565bcb10bf5ed225638293a7640c83",
    },
    derived_profiles = {},
    families = {
        [1] = {
            display_name = "Kerillian's One-handed Axe",
            id = "elf_one_handed_axe",
            label_key = "wt_history_family_elf_one_handed_axe",
            setting_id = "wt_history_elf_one_handed_axe",
            state_order = {
                [1] = "3_1_0",
            },
            states = {
                ["3_1_0"] = {
                    direct_profile_names = {},
                    operations = {
                        [1] = {
                            change_class = "official_weapon_balance",
                            current_source_blob = "25c9ac9c38d51cb7b588c20d46e2773ca67149eb",
                            expected_present = false,
                            family_id = "elf_one_handed_axe",
                            official_change_id = "P320-ELF1HA-BOPP-CRIT",
                            official_summary = "Patch 3.2 increased Kerillian One-Handed Axe's push-follow-up critical chance.",
                            path = {
                                [1] = "actions",
                                [2] = "action_one",
                                [3] = "light_attack_bopp",
                                [4] = "additional_critical_strike_chance",
                            },
                            result = 0.10000000000000001,
                            result_present = true,
                            root = "Weapons",
                            source_blob = "d8a526f548596c8915826352cd7f1cb9a03486f8",
                            source_path = "scripts/settings/equipment/weapon_templates/1h_axes_wood_elf.lua",
                            source_revision = "3f0e3ba442d8dcafb8b5f829ff6c2a95ae24ae63",
                            state_id = "3_1_0",
                            template = "we_one_hand_axe_template",
                        },
                    },
                    profile_names = {},
                },
            },
            templates = {
                [1] = "we_one_hand_axe_template",
            },
        },
    },
    generation = {
        adjacent_operation_count = 1,
        global_operations = 0,
        profile_route_count = 0,
        unsupported_count = 0,
    },
    profile_specs = {},
    schema = 2,
    states = {
        ["3_1_0"] = {
            change_class = "official_weapon_balance",
            display_name = "Game Version 3.1.0",
            label_key = "wt_history_state_3_1_0",
            official_patch_notes = "https://www.vermintide.com/news/patch-32-quality-of-life-update",
            source_revision = "3f0e3ba442d8dcafb8b5f829ff6c2a95ae24ae63",
        },
    },
}
