--[[
============================================================================
 wt_unlock_data.lua — shared source of truth for the weapon-unlock tables
============================================================================

Returns `{ weapon_unlock_map = {...}, cwv_conditional_managed = {...} }`. Both
`weapon_tweaker.lua` (main script) AND `wt_dev_anim_picker.lua` (dev menu)
`mod:dofile` this file directly.

WHY THIS EXISTS — load-order bug class:
  VMF calls a mod's `_data.lua` BEFORE the main script finishes execution
  (verified empirically v0.12.98-dev: log showed `[wt:dev_anim] catalog
  built: 0 entries` followed by `[VMF Mod Manager] ... [widget
  "wt_dev_anim_picker" (group)]: must have at least 1 sub_widget`). The dev
  picker's `build_widget_tree()` is called FROM `_data.lua`, which means
  any data it reads off `mod._weapon_unlock_map` is nil at that moment —
  even though main wt.lua sets `mod._weapon_unlock_map = weapon_unlock_map`
  later in its load. That order is a VMF invariant we can't fight.

The fix: put the data in a file BOTH sides `dofile` at first need. No
load-order dependency, no mirror to drift.

Edits to either table propagate to both sides automatically.
============================================================================
]]

local _DOCUMENTED_KEYS_MOD_ID = "wt"
local _DOCUMENTED_KEYS_FOLDER = "weapon_tweaker"
-- WT_DEV_OVERLAY_BEGIN:issue159-documented-keys
_DOCUMENTED_KEYS_MOD_ID = "wt_dev"
_DOCUMENTED_KEYS_FOLDER = "weapon_tweaker_dev"
-- WT_DEV_OVERLAY_END:issue159-documented-keys
local function _load_documented_keys()
    if get_mod then
        return get_mod(_DOCUMENTED_KEYS_MOD_ID):dofile(
            "scripts/mods/" .. _DOCUMENTED_KEYS_FOLDER .. "/wt_documented_keys")
    end
    return dofile("weapon_tweaker/scripts/mods/weapon_tweaker/wt_documented_keys.lua")
end
local W = _load_documented_keys()

-- SKIP DECISIONS (Kruber receiver, weapons NOT added).
-- These cross-character weapons are intentionally NOT added to Kruber's
-- careers because they are functionally identical to existing Kruber
-- natives. See CROSS_CHARACTER_PORT_DECISIONS.md.
-- v0.12.102-dev (user decision 2026-05-28):
--   * dr_1h_hammer     ~ es_1h_mace          (Bardin 1H Hammer    = Empire 1H Mace)
--   * dr_2h_hammer     ~ es_2h_hammer        (Bardin 2H Hammer    = Empire Greathammer)
--   * dr_handgun       ~ es_handgun          (Bardin Handgun      = Empire Handgun)
--   * dr_shield_hammer ~ es_mace_shield      (Bardin Hammer+Shld  = Empire Mace+Shield)
--   * dr_rakegun       ~ es_blunderbuss      (Bardin Grudge-Raker = Empire Blunderbuss)
-- v0.12.103-dev (user decision 2026-05-30, reaffirmed multiple times):
--   * wh_1h_hammer     ~ es_1h_mace          (Saltzpyre Skull-Splitter = Empire 1H Mace).
--                                            CWV handles hammer-vs-mace visual
--                                            differentiation; wt does NOT add this
--                                            cross-character port.

local DATA = {
    weapon_unlock_map = {
        -- Kruber
        -- v0.12.103-dev (2026-05-30): bulk-bake of cross-character ports from
        -- CROSS_CHARACTER_PORT_DECISIONS.md. Added Bardin batch (cog hammer,
        -- pick, dual axes, shield-axe, throwing axes, drakefire pistols,
        -- drakegun, masterwork pistol, trollhammer torpedo), Kerillian batch
        -- (1h axe, glaive, dual daggers, dual swords, sword-dagger, moonfire,
        -- shortbow, hagbane, repeater crossbow), Saltzpyre batch (1h axe,
        -- dual hammers, 2h hammer, rapier, volley crossbow, griffon-foot),
        -- WP batch (flail-shield, hammer-tome), Sienna batch (mace, dagger,
        -- flame sword, ensorcelled reaper, all 5 skullstaves, necromancy
        -- staff, coruscation staff). we_javelin added later (v0.12.110-dev
        -- era). we_life_staff (Deepwood Staff) added to all 4 Kruber careers
        -- v0.12.198-dev (user request 2026-07-02) — uses staff_life ->
        -- to_2h_hammer wield source, flagged [Untested] until confirmed.
        es_mercenary      = { W.KERILLIAN_DEEPWOOD_STAFF, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_GREATSWORD, W.KRUBER_HALBERD, W.KERILLIAN_GREATSWORD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KRUBER_MACE, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_MACE_AND_SWORD, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_FALCHION, W.SALTZPYRE_AXE, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_FLAIL, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KRUBER_SPEAR_AND_SHIELD, W.KRUBER_SWORD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KERILLIAN_LONGBOW, W.KRUBER_LONGBOW, W.KRUBER_REPEATING_HANDGUN, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.BARDIN_THROWING_AXES, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        es_huntsman       = { W.KERILLIAN_DEEPWOOD_STAFF, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_GREATSWORD, W.KRUBER_HALBERD, W.KERILLIAN_GREATSWORD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KRUBER_MACE, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_MACE_AND_SWORD, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_FALCHION, W.SALTZPYRE_AXE, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_FLAIL, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KRUBER_SPEAR_AND_SHIELD, W.KRUBER_SWORD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KERILLIAN_LONGBOW, W.KRUBER_LONGBOW, W.KRUBER_REPEATING_HANDGUN, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.BARDIN_THROWING_AXES, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        es_knight         = { W.KERILLIAN_DEEPWOOD_STAFF, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_GREATSWORD, W.KRUBER_HALBERD, W.KERILLIAN_GREATSWORD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KRUBER_MACE, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_MACE_AND_SWORD, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_FALCHION, W.SALTZPYRE_AXE, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_FLAIL, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KRUBER_SPEAR_AND_SHIELD, W.KRUBER_SWORD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KERILLIAN_LONGBOW, W.KRUBER_LONGBOW, W.KRUBER_REPEATING_HANDGUN, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.BARDIN_THROWING_AXES, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        es_questingknight = { W.KERILLIAN_DEEPWOOD_STAFF, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_GREATSWORD, W.KRUBER_HALBERD, W.KERILLIAN_GREATSWORD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KRUBER_MACE, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_MACE_AND_SWORD, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_FALCHION, W.SALTZPYRE_AXE, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_FLAIL, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KRUBER_SPEAR_AND_SHIELD, W.KRUBER_SWORD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KERILLIAN_LONGBOW, W.KRUBER_LONGBOW, W.KRUBER_REPEATING_HANDGUN, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.BARDIN_THROWING_AXES, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        -- Bardin
        -- v0.12.102-dev: wh_crossbow removed from Bardin's 4 careers. User
        -- decision 2026-05-28: wh_crossbow (Witch Hunter Crossbow) and
        -- dr_crossbow (Dwarf Crossbow) are functionally analogous; Bardin's
        -- native dr_crossbow already covers the role. wh_crossbow remains
        -- on Saltzpyre (his native) but not on Bardin.
        dr_ranger         = { W.BARDIN_AXE, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_COG_HAMMER, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_GREAT_AXE, W.BARDIN_GREAT_HAMMER, W.BARDIN_HAMMER, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SWORD, W.KRUBER_SWORD, W.SALTZPYRE_FALCHION, W.SIENNA_CROWBILL, W.BARDIN_WAR_PICK, W.BARDIN_CROSSBOW, W.BARDIN_GRUDGE_RAKER, W.BARDIN_HANDGUN, W.KRUBER_HANDGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_THROWING_AXES, W.BARDIN_TROLLHAMMER_TORPEDO },
        dr_ironbreaker    = { W.BARDIN_AXE, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_COG_HAMMER, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_GREAT_AXE, W.BARDIN_GREAT_HAMMER, W.BARDIN_HAMMER, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SWORD, W.KRUBER_SWORD, W.SALTZPYRE_FALCHION, W.SIENNA_CROWBILL, W.BARDIN_WAR_PICK, W.BARDIN_CROSSBOW, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_HANDGUN, W.KRUBER_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_TROLLHAMMER_TORPEDO },
        dr_slayer         = { W.BARDIN_AXE, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_COG_HAMMER, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_GREAT_AXE, W.BARDIN_GREAT_HAMMER, W.BARDIN_HAMMER, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SWORD, W.KRUBER_SWORD, W.SALTZPYRE_FALCHION, W.SIENNA_CROWBILL, W.BARDIN_WAR_PICK, W.BARDIN_CROSSBOW, W.BARDIN_GRUDGE_RAKER, W.BARDIN_HANDGUN, W.KRUBER_HANDGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_THROWING_AXES, W.BARDIN_TROLLHAMMER_TORPEDO },
        dr_engineer       = { W.BARDIN_AXE, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_COG_HAMMER, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_GREAT_AXE, W.BARDIN_GREAT_HAMMER, W.BARDIN_HAMMER, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SWORD, W.KRUBER_SWORD, W.SALTZPYRE_FALCHION, W.SIENNA_CROWBILL, W.BARDIN_WAR_PICK, W.BARDIN_CROSSBOW, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_HANDGUN, W.KRUBER_HANDGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_THROWING_AXES, W.BARDIN_TROLLHAMMER_TORPEDO },
        -- Kerillian
        -- v0.12.103-dev (2026-05-30): bulk-bake of cross-character ports from
        -- CROSS_CHARACTER_PORT_DECISIONS.md (Batches EK + DK). Added Kruber
        -- batch (flail, 2h hammer, tuskgor spear, executioner, bretonnian
        -- longsword, mace+sword, halberd, mace+shield, sword+shield,
        -- bretonnian sword+shield, blunderbuss, handgun, repeater handgun)
        -- and Bardin batch (1h hammer, throwing axes, greataxe, cog hammer,
        -- pickaxe, crossbow, trollhammer, drakefire pistols, drakegun, dual
        -- axes, dual hammers, grudge-raker, axe+shield, masterwork pistol,
        -- plus wh_1h_axe BONUS for 1h-axe route via Saltzpyre).
        -- v0.12.103-dev (2026-05-30): Saltzpyre batch SK1-SK15 added — all 15
        -- WH/WP source weapons routed to Kerillian (falchion, 1h hammer,
        -- billhook, 2h hammer, 2h sword, brace of pistols, crossbow,
        -- griffon-foot, dual hammers, axe+falchion, rapier, repeater pistol,
        -- flail+shield, hammer+tome, skull-splitter+shield).
        -- v0.12.103-dev (2026-05-31): Sienna batch SiK1-SiK14 added — 12 BW
        -- source weapons routed to Kerillian (crowbill, flaming flail, dagger,
        -- flame sword, ensorcelled reaper, 5 skullstaves, necromancy staff,
        -- coruscation staff). SKIPPED bw_1h_mace (~ es_1h_mace already in
        -- Kerillian's unlock_map) and bw_sword (~ we_1h_sword).
        we_waywatcher     = { W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KRUBER_GREATSWORD, W.KRUBER_MACE, W.KRUBER_SPEAR_AND_SHIELD, W.SALTZPYRE_FLAIL, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_MACE_AND_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.SALTZPYRE_AXE, W.SALTZPYRE_FALCHION, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_SKULL_SPLITTER_AND_SHIELD, W.BARDIN_HAMMER, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_AXE_AND_SHIELD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_SWORD_AND_DAGGER, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_MOONFIRE_BOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.SALTZPYRE_REPEATING_PISTOL, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_VOLLEY_CROSSBOW, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_CROSSBOW, W.BARDIN_TROLLHAMMER_TORPEDO, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_MASTERWORK_PISTOL, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        we_maidenguard    = { W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KRUBER_GREATSWORD, W.KRUBER_MACE, W.KRUBER_SPEAR_AND_SHIELD, W.SALTZPYRE_FLAIL, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_MACE_AND_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.SALTZPYRE_AXE, W.SALTZPYRE_FALCHION, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_SKULL_SPLITTER_AND_SHIELD, W.BARDIN_HAMMER, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_AXE_AND_SHIELD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_SWORD_AND_DAGGER, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_MOONFIRE_BOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.SALTZPYRE_REPEATING_PISTOL, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_VOLLEY_CROSSBOW, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_CROSSBOW, W.BARDIN_TROLLHAMMER_TORPEDO, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_MASTERWORK_PISTOL, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        we_shade          = { W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KRUBER_GREATSWORD, W.KRUBER_MACE, W.KRUBER_SPEAR_AND_SHIELD, W.SALTZPYRE_FLAIL, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_MACE_AND_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.SALTZPYRE_AXE, W.SALTZPYRE_FALCHION, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_SKULL_SPLITTER_AND_SHIELD, W.BARDIN_HAMMER, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_AXE_AND_SHIELD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_SWORD_AND_DAGGER, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_MOONFIRE_BOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.SALTZPYRE_REPEATING_PISTOL, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_VOLLEY_CROSSBOW, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_CROSSBOW, W.BARDIN_TROLLHAMMER_TORPEDO, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_MASTERWORK_PISTOL, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        we_thornsister    = { W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KRUBER_GREATSWORD, W.KRUBER_MACE, W.KRUBER_SPEAR_AND_SHIELD, W.SALTZPYRE_FLAIL, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_TUSKGOR_SPEAR, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_MACE_AND_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.SALTZPYRE_AXE, W.SALTZPYRE_FALCHION, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_RAPIER, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_SKULL_SPLITTER_AND_SHIELD, W.BARDIN_HAMMER, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_DUAL_AXES, W.BARDIN_DUAL_HAMMERS, W.BARDIN_AXE_AND_SHIELD, W.KERILLIAN_SPEAR, W.KERILLIAN_SPEAR_AND_SHIELD, W.KERILLIAN_SWORD, W.KERILLIAN_SWORD_AND_DAGGER, W.SIENNA_CROWBILL, W.SIENNA_FLAMING_FLAIL, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.KERILLIAN_DEEPWOOD_STAFF, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_MOONFIRE_BOW, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_VOLLEY_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.SALTZPYRE_REPEATING_PISTOL, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_VOLLEY_CROSSBOW, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_CROSSBOW, W.BARDIN_TROLLHAMMER_TORPEDO, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_GRUDGE_RAKER, W.BARDIN_MASTERWORK_PISTOL, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF },
        -- Saltzpyre
        -- v0.12.103-dev (2026-05-31): Kruber batch KS1/KS3/KS4/KS5/KS10/KS11/KS12
        -- added — 7 ES source weapons routed to non-WP careers (bretonnian
        -- longsword, executioner sword, greathammer, mace+sword, blunderbuss,
        -- handgun, repeater handgun). SKIPPED KS2 es_2h_sword (~ wh_2h_sword
        -- native), KS6 es_mace_shield / KS7 es_sword_shield / KS8
        -- es_sword_shield_breton / KS9 es_deus_01 (shield combos — non-WP
        -- careers lack native shield-stance support; flagged for user review).
        -- v0.12.103-dev (2026-05-31): Bardin batch BS-A added — 6 DR source
        -- weapons routed to non-WP careers (1h axe, 1h hammer, greataxe, cog
        -- hammer, 2h hammer, pickaxe). All melee. SKIPPED es_mace_shield
        -- (identical to wh_hammer_shield Saltzpyre native); es_sword_shield /
        -- es_sword_shield_breton / es_deus_01 deferred to WP receiver
        -- consideration (non-WP careers lack native shield stance).
        -- v0.12.103-dev (2026-05-31): Bardin batch BS-B added — 8 more DR
        -- source weapons routed to non-WP careers (throwing axes, dual axes,
        -- dual hammers, grudge-raker, drakefire pistols, drakegun, masterwork
        -- pistol, trollhammer torpedo). 2 melee + 6 ranged. SKIPPED dr_crossbow
        -- (identical to wh_crossbow Saltzpyre native); dr_handgun (identical
        -- to es_handgun — Kruber route is preferred and already added in KS
        -- batch).
        -- v0.12.103-dev (2026-05-31): Kerillian batch C added — 9 WE source
        -- weapons routed to non-WP careers (1h axe, glaive, elf 2h sword,
        -- dual daggers, dual swords, sword+dagger melee; shortbow, hagbane
        -- shortbow, moonfire bow ranged). 6 melee + 3 ranged. SKIPPED
        -- we_crossbow_repeater (already in non-WP rows natively).
        -- v0.12.109-dev (2026-06-03): Sienna batch D added — 8 BW source
        -- weapons routed to non-WP careers (bw_1h_mace, bw_dagger,
        -- bw_flame_sword, bw_ghost_scythe melee; bw_skullstaff_beam,
        -- bw_skullstaff_fireball, bw_skullstaff_flamethrower,
        -- bw_skullstaff_geiser ranged). 4 melee + 4 ranged. SKIPPED
        -- bw_1h_flail_flaming (~ Saltzpyre native es_1h_flail) and bw_sword
        -- (~ wh_1h_falchion native 1H sword-class).
        -- v0.12.110-dev (2026-06-04): Batch E remaining (5 weapons) + Shield-
        -- combos override (7 weapons) added — 12 source weapons per career,
        -- = 36 new entries. Batch E remaining: bw_skullstaff_spear,
        -- bw_necromancy_staff, bw_deus_01 (Coruscation Staff), we_javelin,
        -- we_life_staff — all routed to wh_1h_falchion except we_javelin
        -- (wh_1h_axe per its short-haft/throw role). Shield-combos override
        -- supersedes Batch A SKIP decisions (BS-A-skip-2/3/4) and adds 3
        -- previously-unqueued shield combos (Bardin axe+shield, Bardin
        -- hammer+shield, Kerillian spear+shield). Per user 2026-06-04: all
        -- 7 shield-combo source weapons target wh_dual_wield_axe_falchion
        -- as the 3P animation source (Saltzpyre's two-handed off-hand
        -- vocab is the closest non-WP body has to a shield-stance).
        wh_captain        = { W.SALTZPYRE_AXE, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_FALCHION, W.SALTZPYRE_FLAIL, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.KERILLIAN_SPEAR, W.KERILLIAN_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE, W.KRUBER_SWORD, W.KRUBER_TUSKGOR_SPEAR, W.SALTZPYRE_RAPIER, W.SIENNA_CROWBILL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_MACE_AND_SWORD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_SPEAR_AND_SHIELD, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_GREAT_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SPEAR_AND_SHIELD, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_GRUDGE_RAKER, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO },
        wh_bountyhunter   = { W.SALTZPYRE_AXE, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_FALCHION, W.SALTZPYRE_FLAIL, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.KERILLIAN_SPEAR, W.KERILLIAN_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE, W.KRUBER_SWORD, W.KRUBER_TUSKGOR_SPEAR, W.SALTZPYRE_RAPIER, W.SIENNA_CROWBILL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_MACE_AND_SWORD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_SPEAR_AND_SHIELD, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_GREAT_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SPEAR_AND_SHIELD, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_GRUDGE_RAKER, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO },
        wh_zealot         = { W.SALTZPYRE_AXE, W.SALTZPYRE_AXE_AND_FALCHION, W.SALTZPYRE_BILLHOOK, W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_FALCHION, W.SALTZPYRE_FLAIL, W.SALTZPYRE_2H_SWORD, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_HOLY_GREAT_HAMMER, W.KERILLIAN_SPEAR, W.KERILLIAN_SWORD, W.KRUBER_HALBERD, W.KRUBER_MACE, W.KRUBER_SWORD, W.KRUBER_TUSKGOR_SPEAR, W.SALTZPYRE_RAPIER, W.SIENNA_CROWBILL, W.SIENNA_MACE, W.SIENNA_DAGGER, W.SIENNA_FLAME_SWORD, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_BEAM_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_SOULSTEALER_STAFF, W.SIENNA_CORUSCATION_STAFF, W.KRUBER_BRETONNIAN_LONGSWORD, W.KRUBER_EXECUTIONER_SWORD, W.KRUBER_TWO_HANDED_HAMMER, W.KRUBER_MACE_AND_SWORD, W.KRUBER_MACE_AND_SHIELD, W.KRUBER_SWORD_AND_SHIELD, W.KRUBER_BRETONNIAN_SWORD_AND_SHIELD, W.KRUBER_SPEAR_AND_SHIELD, W.BARDIN_GREAT_AXE, W.BARDIN_COG_HAMMER, W.BARDIN_GREAT_HAMMER, W.BARDIN_WAR_PICK, W.BARDIN_AXE_AND_SHIELD, W.BARDIN_HAMMER_AND_SHIELD, W.KERILLIAN_SPEAR_AND_SHIELD, W.SALTZPYRE_BRACE_OF_PISTOLS, W.SALTZPYRE_CROSSBOW, W.SALTZPYRE_GRIFFON_FOOT, W.KERILLIAN_VOLLEY_CROSSBOW, W.SALTZPYRE_REPEATING_PISTOL, W.SALTZPYRE_VOLLEY_CROSSBOW, W.KRUBER_LONGBOW, W.KERILLIAN_LONGBOW, W.KERILLIAN_ELVEN_AXE, W.KERILLIAN_GLAIVE, W.KERILLIAN_GREATSWORD, W.KERILLIAN_DUAL_DAGGERS, W.KERILLIAN_DUAL_SWORDS, W.KERILLIAN_SWORD_AND_DAGGER, W.KERILLIAN_SWIFT_BOW, W.KERILLIAN_HAGBANE_SHORT_BOW, W.KERILLIAN_MOONFIRE_BOW, W.KERILLIAN_JAVELIN, W.KRUBER_BLUNDERBUSS, W.KRUBER_HANDGUN, W.KRUBER_REPEATING_HANDGUN, W.BARDIN_THROWING_AXES, W.BARDIN_GRUDGE_RAKER, W.BARDIN_DRAKEFIRE_PISTOLS, W.BARDIN_DRAKEGUN, W.BARDIN_MASTERWORK_PISTOL, W.BARDIN_TROLLHAMMER_TORPEDO },
        wh_priest         = { W.SALTZPYRE_DUAL_SKULL_SPLITTERS, W.SALTZPYRE_FLAIL, W.SALTZPYRE_FLAIL_AND_SHIELD, W.SALTZPYRE_1H_HAMMER, W.SALTZPYRE_SKULL_SPLITTER_AND_SHIELD, W.SALTZPYRE_HAMMER_AND_TOME, W.SALTZPYRE_HOLY_GREAT_HAMMER },
        -- Sienna
        bw_adept          = { W.SIENNA_CROWBILL, W.SIENNA_DAGGER, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_FLAME_SWORD, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_SWORD, W.SIENNA_BEAM_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_CORUSCATION_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF },
        bw_scholar        = { W.SIENNA_CROWBILL, W.SIENNA_DAGGER, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_FLAME_SWORD, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_SWORD, W.SIENNA_BEAM_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_CORUSCATION_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF },
        bw_unchained      = { W.SIENNA_CROWBILL, W.SIENNA_DAGGER, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_FLAME_SWORD, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_SWORD, W.SIENNA_BEAM_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_CORUSCATION_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_FLAMESTORM_STAFF },
        bw_necromancer    = { W.SIENNA_CROWBILL, W.SIENNA_DAGGER, W.SIENNA_ENSORCELLED_REAPER, W.SIENNA_FLAME_SWORD, W.SIENNA_FLAMING_FLAIL, W.SIENNA_MACE, W.SIENNA_SWORD, W.SIENNA_BEAM_STAFF, W.SIENNA_BOLT_STAFF, W.SIENNA_CONFLAGRATION_STAFF, W.SIENNA_CORUSCATION_STAFF, W.SIENNA_FIREBALL_STAFF, W.SIENNA_SOULSTEALER_STAFF },
    },

    -- #593: these are reversible live
    -- handoffs. WT owns the fallback while CWV is inactive and strips it on
    -- an active transition, then restores the saved WT preference on disable.
    cwv_conditional_managed = {
        es_mercenary      = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        es_huntsman       = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        es_knight         = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        es_questingknight = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        -- #593 follow-up: standard Saltzpyre gets the same reversible handoff.
        -- CWV active -> Empire CWV Axe+Shield; CWV absent -> Bardin WT fallback.
        wh_captain        = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        wh_bountyhunter   = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
        wh_zealot         = { [W.BARDIN_AXE_AND_SHIELD] = true, [W.BARDIN_GREAT_AXE] = true },
    },
}

-- #576/user correction: Saltzpyre receives Kruber's Empire Greathammer
-- (`es_2h_hammer`, ItemMasterList template `two_handed_hammers_template_1`),
-- not Bardin's analogous `dr_2h_hammer`. Keep the source lists readable above
-- while enforcing the catalog contract here for all standard Saltz careers.
-- #594 applies the same native-ownership boundary to shield hammers: keep
-- Kruber's `es_mace_shield` and remove Bardin's `dr_shield_hammer` regardless
-- of CWV state. Vanilla authors both from the 1h_hammers_shield base, while
-- Bardin's template adds three dwarf-specific light-attack range modifiers.
-- #368: WT and CWV are independent availability providers. Axe + Falchion is
-- therefore a normal WT Kruber row (the old cwv_managed cede is gone).
for _, career in ipairs({ "es_mercenary", "es_huntsman", "es_knight", "es_questingknight" }) do
    local weapons = DATA.weapon_unlock_map[career]
    local found = false
    for _, weapon_key in ipairs(weapons) do
        if weapon_key == W.SALTZPYRE_AXE_AND_FALCHION then found = true; break end
    end
    if not found then weapons[#weapons + 1] = W.SALTZPYRE_AXE_AND_FALCHION end
end

for _, career in ipairs({ "wh_captain", "wh_bountyhunter", "wh_zealot" }) do
    local weapons = DATA.weapon_unlock_map[career]
    for i = #weapons, 1, -1 do
        if weapons[i] == W.BARDIN_GREAT_HAMMER or weapons[i] == W.BARDIN_HAMMER_AND_SHIELD then
            table.remove(weapons, i)
        end
    end
end
-- WT_DEV_OVERLAY_BEGIN:issue948-universal-unlock-map
-- #948: the friends-only dev stream is the exhaustive compatibility lab.
-- Expand after the historical curation/removal pass so every base weapon is a
-- selectable candidate on every career, including Warrior Priest ranged
-- weapons and intentionally redundant families. The verified #368 conditional
-- replacement map remains authoritative and may hide its explicitly chosen
-- base representatives while CWV is active.
local _universal = get_mod("wt_dev"):dofile(
    "scripts/mods/weapon_tweaker_dev/wt_universal_availability")
_universal.expand_unlock_map(DATA.weapon_unlock_map)
-- WT_DEV_OVERLAY_END:issue948-universal-unlock-map

return DATA
