-- Generated by tools/rebuild_portrait_atlas.ps1. Do not hand-edit.
-- image source: textures/dynamic_cosmetic_portraits/dcp_portrait_atlas
local dcp_portrait_atlas = {
    portrait_kruber_mercenary_hat_0001 = {
        size = { 86, 108 },
        uv00 = { 0.00390625, 0.00390625 },
        uv11 = { 0.171875, 0.21484375 },
    },
    portrait_kruber_mercenary_hat_0003 = {
        size = { 86, 108 },
        uv00 = { 0.1796875, 0.00390625 },
        uv11 = { 0.34765625, 0.21484375 },
    },
    portrait_kruber_mercenary_hat_0004 = {
        size = { 86, 108 },
        uv00 = { 0.35546875, 0.00390625 },
        uv11 = { 0.5234375, 0.21484375 },
    },
    portrait_kruber_mercenary_hat_0005 = {
        size = { 86, 108 },
        uv00 = { 0.53125, 0.00390625 },
        uv11 = { 0.69921875, 0.21484375 },
    },
    portrait_kruber_mercenary_hat_0006 = {
        size = { 86, 108 },
        uv00 = { 0.70703125, 0.00390625 },
        uv11 = { 0.875, 0.21484375 },
    },
    portrait_kruber_mercenary_hat_0007 = {
        size = { 86, 108 },
        uv00 = { 0.00390625, 0.22265625 },
        uv11 = { 0.171875, 0.43359375 },
    },
    portrait_kruber_mercenary_hat_0009 = {
        size = { 86, 108 },
        uv00 = { 0.1796875, 0.22265625 },
        uv11 = { 0.34765625, 0.43359375 },
    },
    portrait_kruber_mercenary_hat_1001 = {
        size = { 86, 108 },
        uv00 = { 0.35546875, 0.22265625 },
        uv11 = { 0.5234375, 0.43359375 },
    },
    portrait_kruber_mercenary_hat_1002 = {
        size = { 86, 108 },
        uv00 = { 0.53125, 0.22265625 },
        uv11 = { 0.69921875, 0.43359375 },
    },
    portrait_kruber_mercenary_hat_1003 = {
        size = { 86, 108 },
        uv00 = { 0.70703125, 0.22265625 },
        uv11 = { 0.875, 0.43359375 },
    },
    portrait_kruber_skin_es_default = {
        size = { 86, 108 },
        uv00 = { 0.00390625, 0.44140625 },
        uv11 = { 0.171875, 0.65234375 },
    },
    portrait_kruber_skin_es_mercenary_1003 = {
        size = { 86, 108 },
        uv00 = { 0.1796875, 0.44140625 },
        uv11 = { 0.34765625, 0.65234375 },
    },
    small_portrait_kruber_mercenary_hat_0001 = {
        size = { 60, 70 },
        uv00 = { 0.35546875, 0.44140625 },
        uv11 = { 0.47265625, 0.578125 },
    },
    small_portrait_kruber_mercenary_hat_0003 = {
        size = { 60, 70 },
        uv00 = { 0.48046875, 0.44140625 },
        uv11 = { 0.59765625, 0.578125 },
    },
    small_portrait_kruber_mercenary_hat_0004 = {
        size = { 60, 70 },
        uv00 = { 0.60546875, 0.44140625 },
        uv11 = { 0.72265625, 0.578125 },
    },
    small_portrait_kruber_mercenary_hat_0005 = {
        size = { 60, 70 },
        uv00 = { 0.73046875, 0.44140625 },
        uv11 = { 0.84765625, 0.578125 },
    },
    small_portrait_kruber_mercenary_hat_0006 = {
        size = { 60, 70 },
        uv00 = { 0.85546875, 0.44140625 },
        uv11 = { 0.97265625, 0.578125 },
    },
    small_portrait_kruber_mercenary_hat_0007 = {
        size = { 60, 70 },
        uv00 = { 0.00390625, 0.66015625 },
        uv11 = { 0.12109375, 0.796875 },
    },
    small_portrait_kruber_mercenary_hat_0009 = {
        size = { 60, 70 },
        uv00 = { 0.12890625, 0.66015625 },
        uv11 = { 0.24609375, 0.796875 },
    },
    small_portrait_kruber_mercenary_hat_1001 = {
        size = { 60, 70 },
        uv00 = { 0.25390625, 0.66015625 },
        uv11 = { 0.37109375, 0.796875 },
    },
    small_portrait_kruber_mercenary_hat_1002 = {
        size = { 60, 70 },
        uv00 = { 0.37890625, 0.66015625 },
        uv11 = { 0.49609375, 0.796875 },
    },
    small_portrait_kruber_mercenary_hat_1003 = {
        size = { 60, 70 },
        uv00 = { 0.50390625, 0.66015625 },
        uv11 = { 0.62109375, 0.796875 },
    },
    small_portrait_kruber_skin_es_default = {
        size = { 60, 70 },
        uv00 = { 0.62890625, 0.66015625 },
        uv11 = { 0.74609375, 0.796875 },
    },
    small_portrait_kruber_skin_es_mercenary_1003 = {
        size = { 60, 70 },
        uv00 = { 0.75390625, 0.66015625 },
        uv11 = { 0.87109375, 0.796875 },
    },
}

return dcp_portrait_atlas
