# tools/install-hooks.ps1
#
# Idempotent installer for the repo's local git pre-commit hook.
#
# Writes a small bash shim into `.git/hooks/pre-commit` that delegates to
# `tools/hooks/pre-commit.ps1`. The PowerShell wrapper first checks the exact
# staged patch for whitespace defects, then runs `qa/run_all.ps1 -Quick
# -SkipLua` and `tools/mod-lint/lint-mod.ps1` for relevant source changes.
# It blocks commits that would have failed the CI QA workflow.
#
# Re-running this script is a no-op when the hook is already installed.
# Bypass the hook on a specific commit with `git commit --no-verify` — see
# PROJECT_STANDARDS.md § 8 for the escape-hatch convention.
#
# Issue: https://github.com/Ensrick/vermintide-2-tweaker/issues/29

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$hookPath   = Join-Path $repoRoot '.git\hooks\pre-commit'
$wrapperRel = 'tools/hooks/pre-commit.ps1'

if (-not (Test-Path (Join-Path $repoRoot '.git'))) {
    Write-Host "[install-hooks] $repoRoot is not a git repo (no .git directory). Aborting." -ForegroundColor Red
    exit 1
}

$hooksDir = Split-Path -Parent $hookPath
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

# Canonical shim — bash because git invokes hooks through sh.exe on Windows.
# Uses `pwsh` (PowerShell 7+) to match every other QA / launcher tool in
# the repo; falls back to Windows PowerShell only if pwsh is missing on PATH.
$shim = @'
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.ps1 — do not edit by hand.
# Re-run that installer to refresh. Bypass with `git commit --no-verify`.
set -e

repo_root="$(git rev-parse --show-toplevel)"
hook="$repo_root/tools/hooks/pre-commit.ps1"

if [ ! -f "$hook" ]; then
    echo "[pre-commit] missing $hook -- skipping" >&2
    exit 0
fi

if command -v pwsh >/dev/null 2>&1; then
    pwsh -NoProfile -File "$hook"
else
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$hook"
fi
'@

# Normalize to LF (sh.exe on Windows sometimes chokes on CRLF shebang lines).
$shim = $shim -replace "`r`n", "`n"

if (Test-Path $hookPath) {
    $existing = [System.IO.File]::ReadAllText($hookPath)
    if ($existing -eq $shim) {
        Write-Host "[install-hooks] pre-commit hook already installed (no changes)." -ForegroundColor DarkGray
        exit 0
    }
    # Idempotency check #2: tolerate cosmetic CRLF drift on the existing file.
    $existingNorm = $existing -replace "`r`n", "`n"
    if ($existingNorm -eq $shim) {
        Write-Host "[install-hooks] pre-commit hook already installed (line-ending normalize only)." -ForegroundColor DarkGray
        exit 0
    }
    Write-Host "[install-hooks] existing pre-commit hook content differs; backing up to pre-commit.bak and overwriting." -ForegroundColor Yellow
    Copy-Item -Path $hookPath -Destination "$hookPath.bak" -Force
}

# Write with LF line endings, no BOM.
[System.IO.File]::WriteAllText($hookPath, $shim, (New-Object System.Text.UTF8Encoding($false)))

# On Windows core.filemode is usually false and Git ignores the executable bit
# in the index, but Git for Windows still respects the bit when invoking the
# hook through sh.exe. Try to set it via icacls-equivalent; if the platform
# doesn't support it (network share, exotic FS), the hook still runs because
# git's win32 sh.exe ignores the bit for files under .git/hooks.
try {
    # PowerShell on Windows has no native chmod; use git's own update-index
    # to flag the file as executable in case the user copies the .git folder
    # around. Best-effort.
    & git -C $repoRoot update-index --add --chmod=+x .git/hooks/pre-commit 2>$null
} catch {
    # ignored — best-effort
}

Write-Host "Installed pre-commit hook" -ForegroundColor Green
Write-Host "  -> $hookPath" -ForegroundColor DarkGray
Write-Host "  -> delegates to $wrapperRel" -ForegroundColor DarkGray
Write-Host "  Bypass with: git commit --no-verify" -ForegroundColor DarkGray
exit 0
