@{
    Version = 1
    StandingProbePaths = @(
        'general_tweaker/scripts/mods/general_tweaker/_gt_debug_probes.lua'
        'general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_debug_probes.lua'
    )
    Entries = @(
        @{ Path='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/_ct_diag_cursed_chest132.lua'; Classification='active_issue'; Issues=@(349); Stream='friends_only'; Prefixes=@('[ct:132]','[ct:349]'); PrefixAliases=@(@{Prefix='[ct:132]';Issue=349;Reason='The shared owner retains the closed #132 reconciliation receipt beside #349 count evidence.'}); LoadOwner='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/chaos_wastes_tweaker_dev.lua'; LoadAnchor='_ct_diag_cursed_chest132'; Arming='automatic'; BoundAnchors=@('resets the per-mission counter when level_id changes','one settled `[ct:349]` audit per mission') }
        @{ Path='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/_ct_diag_gargoyle1124.lua'; Classification='active_issue'; Issues=@(1124); Stream='friends_only'; Prefixes=@('[ct:1124]'); LoadOwner='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/chaos_wastes_tweaker_dev.lua'; LoadAnchor='_ct_diag_gargoyle1124'; Arming='lifecycle'; BoundAnchors=@('local RUN_RECORD_CAP = 96','local TOTAL_RECORD_CAP = 512') }
        @{ Path='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/_ct_diag_skull52.lua'; Classification='active_issue'; Issues=@(52); Stream='friends_only'; Prefixes=@('[ct:skull52]'); LoadOwner='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/chaos_wastes_tweaker_dev.lua'; LoadAnchor='_ct_diag_skull52'; Arming='lifecycle'; BoundAnchors=@('local CENSUS_RECORD_CAP_TOTAL = 320','local LIFECYCLE_RECORD_CAP_TOTAL = 256') }
        @{ Path='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/_ct_diag_tab_native533.lua'; Classification='active_issue'; Issues=@(571); Stream='friends_only'; Prefixes=@('[ct:571-native]'); LoadOwner='chaos_wastes_tweaker_dev/scripts/mods/chaos_wastes_tweaker_dev/_ct_tab_panel_owner.lua'; LoadAnchor='_ct_diag_tab_native533'; Arming='lifecycle'; BoundAnchors=@('local RECORD_CAP = 64','local MAX_WAIT_FRAMES = 120') }
        @{ Path='character_weapon_variants/scripts/mods/character_weapon_variants/_cwv_smoke_bomb_probe.lua'; Classification='active_issue'; Issues=@(343); Stream='public'; Prefixes=@('[cwv:343]'); LoadOwner='character_weapon_variants/scripts/mods/character_weapon_variants/character_weapon_variants.lua'; LoadAnchor='_cwv_smoke_bomb_probe'; Arming='mixed'; BoundAnchors=@('MAX_RUNS = 3'); LegacyProbe=$true; StableLegacy=$true; RemovalIssue=499 }
        @{ Path='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/_cos_518_probe.lua'; Classification='active_issue'; Issues=@(518); Stream='public'; Prefixes=@('[cos:518]'); LoadOwner='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/cosmetics_tweaker.lua'; LoadAnchor='_cos_518_probe'; Arming='lifecycle'; BoundAnchors=@('ch.count >= 16'); LegacyProbe=$true; StableLegacy=$true; RemovalIssue=499 }
        @{ Path='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/_cos_diag_lasync.lua'; Classification='active_issue'; Issues=@(149,200,203,204); Stream='public'; Prefixes=@('[cos:sync]'); PrefixAliases=@(@{Prefix='[cos:sync]';Issue=149;Reason='One topic receipt serves the four open LA synchronization issues.'}); LoadOwner='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/cosmetics_tweaker.lua'; LoadAnchor='_cos_diag_lasync'; Arming='automatic'; BoundAnchors=@('local PERKEY_CAP = 4','local GLOBAL_CAP = 900'); StableLegacy=$true; RemovalIssue=499 }
        @{ Path='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/_cos_diag_glow.lua'; Classification='permanent_policy'; Stream='public'; Role='Manual finite wielded-material and shield-glow diagnostic command surface.'; LoadOwner='cosmetics_tweaker/scripts/mods/cosmetics_tweaker/cosmetics_tweaker.lua'; LoadAnchor='_cos_diag_glow'; Arming='mixed'; BoundAnchors=@('local _GLOW_PROBE_CANDIDATES = {','duration = 3.0','if not var then') }
        @{ Path='crafting_in_modded/scripts/mods/crafting_in_modded/_cim_diag_524.lua'; Classification='temporary_exception'; RemovalIssue=499; Reason='Issue #524 is closed and issue instrumentation remains in the public stream.'; SunsetAction='Remove through an authorized stable CIM transaction.' }
        @{ Path='event_tweaker/scripts/mods/event_tweaker/_evt_issue1309_probe.lua'; Classification='active_issue'; Issues=@(1309); Stream='public'; Prefixes=@('[et:1149t]'); PrefixAliases=@(@{Prefix='[et:1149t]';Issue=1309;Reason='Historical #1149 prefix was retained when the client Twins defect moved to #1309.'}); LoadOwner='event_tweaker/scripts/mods/event_tweaker/_evt_diagnostics.lua'; LoadAnchor='_evt_issue1309_probe'; Arming='lifecycle'; BoundAnchors=@('M.RECEIPT_CAP = 10'); LegacyProbe=$true; StableLegacy=$true; RemovalIssue=499 }
        @{ Path='event_tweaker/scripts/mods/event_tweaker/_evt_issue393_probe.lua'; Classification='active_issue'; Issues=@(393); Stream='public'; Prefixes=@('[event-inject:393]'); PrefixPath='event_tweaker/scripts/mods/event_tweaker/_evt_diagnostics.lua'; LoadOwner='event_tweaker/scripts/mods/event_tweaker/_evt_diagnostics.lua'; LoadAnchor='_evt_issue393_probe'; Arming='lifecycle'; BoundPath='event_tweaker/scripts/mods/event_tweaker/_evt_diagnostics.lua'; BoundAnchors=@('local _issue393_seen = setmetatable({}, { __mode = "k" })'); LegacyProbe=$true; StableLegacy=$true; RemovalIssue=499 }
        @{ Path='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_chest_pickup_probe_core.lua'; Classification='active_issue'; Issues=@(347); Stream='friends_only'; Prefixes=@('[gt:347]'); PrefixPath='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_bot_pickups.lua'; LoadOwner='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_bot_pickups.lua'; LoadAnchor='_gt_chest_pickup_probe_core'; Arming='command'; BoundAnchors=@('M.MAX_RECORDS = 16','M.MAX_CLASSIFICATIONS = 32'); LegacyProbe=$true; RemovalIssue=499 }
        @{ Path='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_debug_probes.lua'; Classification='standing'; Stream='friends_only' }
        @{ Path='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_diag_disconnect_failure.lua'; Classification='active_issue'; Issues=@(753); Stream='friends_only'; Prefixes=@('[gt:753]'); LoadOwner='general_tweaker_dev/scripts/mods/general_tweaker_dev/general_tweaker_dev.lua'; LoadAnchor='_gt_diag_disconnect_failure'; Arming='lifecycle'; BoundAnchors=@('local steam_state = setmetatable({}, { __mode = "k" })','local backend_reason = setmetatable({}, { __mode = "k" })') }
        @{ Path='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_diag_player_stats.lua'; Classification='active_issue'; Issues=@(797); Stream='friends_only'; Prefixes=@('[gt:797]'); LoadOwner='general_tweaker_dev/scripts/mods/general_tweaker_dev/general_tweaker_dev.lua'; LoadAnchor='_gt_diag_player_stats'; Arming='command'; BoundPath='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_player_stat_probe_core.lua'; BoundAnchors=@('M.MAX_STAT_TYPES = 256','M.MAX_CONTRIBUTIONS = 1024','M.MAX_ACTIVE_BUFFS = 1024') }
        @{ Path='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_player_stat_probe_core.lua'; Classification='permanent_policy'; Stream='friends_only'; Role='Bounded player-stat snapshot and contribution policy.'; LoadOwner='general_tweaker_dev/scripts/mods/general_tweaker_dev/_gt_diag_player_stats.lua'; LoadAnchor='_gt_player_stat_probe_core'; Arming='library'; BoundAnchors=@('M.MAX_STAT_TYPES = 256','M.MAX_CONTRIBUTIONS = 1024','M.MAX_ACTIVE_BUFFS = 1024'); LegacyProbe=$true; RemovalIssue=499 }
        @{ Path='general_tweaker/scripts/mods/general_tweaker/_gt_debug_probes.lua'; Classification='standing'; Stream='public' }
        @{ Path='general_tweaker/scripts/mods/general_tweaker/_gt_probe_dummy_hits.lua'; Classification='temporary_exception'; LegacyProbe=$true; RemovalIssue=499; Reason='Issue #198 is closed and observation-only stable instrumentation remains.'; SunsetAction='Remove through an explicitly authorized General Tweaker stable hotfix.' }
        @{ Path='gui_tweaker_dev/scripts/mods/gui_tweaker_dev/_gut_cutscene_probe257.lua'; Classification='active_issue'; Issues=@(257); Stream='friends_only'; Prefixes=@('[gut:257]'); PrefixPath='gui_tweaker_dev/scripts/mods/gui_tweaker_dev/_gut_cutscenes.lua'; LoadOwner='gui_tweaker_dev/scripts/mods/gui_tweaker_dev/_gut_cutscenes.lua'; LoadAnchor='_gut_cutscene_probe257'; Arming='lifecycle'; BoundAnchors=@('max_events = 32'); LegacyProbe=$true; RemovalIssue=499 }
        @{ Path='gui_tweaker_dev/scripts/mods/gui_tweaker_dev/_gut_diag_optionsview.lua'; Classification='permanent_policy'; Stream='friends_only'; Role='Command and one-shot options-view render-state inspection.'; LoadOwner='gui_tweaker_dev/scripts/mods/gui_tweaker_dev/gui_tweaker_dev.lua'; LoadAnchor='_gut_diag_optionsview'; Arming='mixed'; BoundAnchors=@('if not mod._opt_dumped then','if mod._opt_apply_dumped then return end') }
        @{ Path='modded_progression/scripts/mods/modded_progression/_mp_diag_fresh_profile.lua'; Classification='active_issue'; Issues=@(840); Stream='private'; Prefixes=@('[mp:840]'); PrefixPath='modded_progression/scripts/mods/modded_progression/modded_progression.lua'; LoadOwner='modded_progression/scripts/mods/modded_progression/modded_progression.lua'; LoadAnchor='_mp_diag_fresh_profile'; Arming='mixed'; BoundPath='modded_progression/scripts/mods/modded_progression/modded_progression.lua'; BoundAnchors=@('local _mp840_census_backend') }
        @{ Path='modded_progression/scripts/mods/modded_progression/_mp_loot_diag_runtime.lua'; Classification='active_issue'; Issues=@(607); Stream='private'; Prefixes=@('[mp:607]'); LoadOwner='modded_progression/scripts/mods/modded_progression/modded_progression.lua'; LoadAnchor='_mp_loot_diag_runtime'; Arming='lifecycle'; BoundPath='modded_progression/scripts/mods/modded_progression/_mp_loot_diag.lua'; BoundAnchors=@('M.MAX_RECORDS = 12','M.MAX_ITEMS = 6','M.MAX_RARITIES = 10') }
        @{ Path='weapon_tweaker_dev/scripts/mods/weapon_tweaker_dev/_wt_longbow_zoom_probe.lua'; Classification='active_issue'; Issues=@(316); Stream='friends_only'; Prefixes=@('[wt:316]'); PrefixPath='weapon_tweaker_dev/scripts/mods/weapon_tweaker_dev/weapon_tweaker_dev.lua'; LoadOwner='weapon_tweaker_dev/scripts/mods/weapon_tweaker_dev/weapon_tweaker_dev.lua'; LoadAnchor='_wt_longbow_zoom_probe'; Arming='lifecycle'; BoundAnchors=@('MAX_ATTEMPTS = 3'); LegacyProbe=$true; RemovalIssue=499 }
    )
}
