# gen_wt_coverage_confirmed.ps1 — keeps wt's chooser exclusion table in sync with
# ANIMATION_COVERAGE.md. The in-game 3P Anim-Set Chooser (Kruber) hides every
# Kruber port whose COVERAGE row is ✅. The mod sandbox can't reliably io.open the
# .md at runtime, so the ✅ set is mirrored into a generated Lua table
# `_COVERAGE_CONFIRMED_KRUBER` in wt_dev_anim_picker.lua. This script regenerates
# (or, with -Check, verifies) that table from the COVERAGE Kruber section.
#
# Parse contract (matches wt_dev_anim_picker.lua §6 spec):
#   * Scan ONLY the "## Receiver: KRUBER" section (header to next "## Receiver:").
#   * Each data row: | <weapon_key(s)> | <display> | <status> | ... |
#   * Row is confirmed-working iff the status cell contains ✅.
#   * The first cell may group several keys with "/" (e.g.
#     "dr_2h_cog_hammer / dr_2h_pick"; "we_dual_wield_daggers / _swords / _sword_dagger").
#     Split on "/", trim, and expand "_"-prefixed shorthands against the row's
#     first full key's 2-char prefix (es_/dr_/we_/wh_/bw_).
#
# Modes:
#   (default)  print the generated Lua block to stdout (paste into the module).
#   -Check     compare against the live table in the module; exit 1 on drift.
#   -Write     rewrite the table in-place between the BEGIN/END marker comments.
#
# Exit codes: 0 = in sync / generated OK · 1 = drift (under -Check) · 2 = parse/IO error.

[CmdletBinding()]
param(
    [switch]$Check,
    [switch]$Write
)

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$coverageMd = Join-Path $repoRoot 'weapon_tweaker\ANIMATION_COVERAGE.md'
$moduleLua  = Join-Path $repoRoot 'weapon_tweaker\scripts\mods\weapon_tweaker\wt_dev_anim_picker.lua'

if (-not (Test-Path $coverageMd)) { Write-Error "missing $coverageMd"; exit 2 }
if (-not (Test-Path $moduleLua))  { Write-Error "missing $moduleLua";  exit 2 }

# --- parse the KRUBER section's ✅ rows --------------------------------------
$lines = Get-Content -LiteralPath $coverageMd
$inKruber = $false
$confirmed = [System.Collections.Generic.List[string]]::new()
$validPrefix = @('es_', 'dr_', 'we_', 'wh_', 'bw_')

foreach ($line in $lines) {
    if ($line -match '^##\s+Receiver:\s+KRUBER') { $inKruber = $true; continue }
    if ($inKruber -and $line -match '^##\s+Receiver:') { break }   # next receiver section
    if (-not $inKruber) { continue }
    if ($line -notmatch '^\s*\|') { continue }                     # not a table row
    if ($line -match '^\s*\|\s*-{2,}') { continue }                # header separator

    $cells = ($line -split '\|')
    if ($cells.Count -lt 4) { continue }
    $keyCell    = $cells[1].Trim()
    $statusCell = $cells[3]
    if ($keyCell -eq 'weapon_key') { continue }                    # header row
    if ($statusCell -notmatch [char]0x2705) { continue }           # ✅ = U+2705

    # Split grouped keys, expand "_"-prefixed shorthands against the first full key.
    $parts = $keyCell -split '/' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }
    $rowPrefix = $null
    foreach ($p in $parts) {
        if ($p.Length -ge 3 -and ($validPrefix -contains $p.Substring(0, 3))) {
            $rowPrefix = $p.Substring(0, 3); break
        }
    }
    foreach ($p in $parts) {
        $key = $p
        if ($key.StartsWith('_') -and $rowPrefix) { $key = $rowPrefix + $key.Substring(1) }
        # Only keep plausible weapon keys (have a known 2-char prefix).
        if ($key.Length -ge 3 -and ($validPrefix -contains $key.Substring(0, 3))) {
            if (-not $confirmed.Contains($key)) { $confirmed.Add($key) }
        }
    }
}

$confirmed = $confirmed | Sort-Object

# --- build the Lua block -----------------------------------------------------
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('-- GENERATED by qa/gen_wt_coverage_confirmed.ps1 from ANIMATION_COVERAGE.md ✅ rows. Do not hand-edit; rerun the script.')
[void]$sb.AppendLine('local _COVERAGE_CONFIRMED_KRUBER = {')
foreach ($k in $confirmed) {
    [void]$sb.AppendLine(("    {0,-22}= true," -f $k))
}
[void]$sb.AppendLine('}')
$generated = $sb.ToString().TrimEnd("`r", "`n")

if ($Check) {
    # Pull the live keys out of the module and diff the SETS (order/comments ignored).
    $src = Get-Content -LiteralPath $moduleLua -Raw
    $m = [regex]::Match($src, '_COVERAGE_CONFIRMED_KRUBER\s*=\s*\{(?<body>.*?)\}', 'Singleline')
    if (-not $m.Success) { Write-Error 'could not find _COVERAGE_CONFIRMED_KRUBER in module'; exit 2 }
    $live = [regex]::Matches($m.Groups['body'].Value, '(?m)^\s*([a-z]{2}_[a-z0-9_]+)\s*=\s*true') |
            ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
    $expected = $confirmed
    $missing = $expected | Where-Object { $live -notcontains $_ }
    $extra   = $live     | Where-Object { $expected -notcontains $_ }
    if ($missing -or $extra) {
        Write-Host '[gen_wt_coverage_confirmed] DRIFT between ANIMATION_COVERAGE.md ✅ rows and the module table:'
        if ($missing) { Write-Host ('  missing in module (✅ in COVERAGE): ' + ($missing -join ', ')) }
        if ($extra)   { Write-Host ('  extra in module (not ✅ in COVERAGE): ' + ($extra -join ', ')) }
        Write-Host '  Run: pwsh qa/gen_wt_coverage_confirmed.ps1 -Write'
        exit 1
    }
    Write-Host ("[gen_wt_coverage_confirmed] in sync ({0} confirmed Kruber port(s))." -f $expected.Count)
    exit 0
}

if ($Write) {
    Write-Error 'in-place -Write is intentionally not implemented: the module table carries hand-written per-key comments. Paste the generated block manually and re-add comments, or extend this script.'
    exit 2
}

# default: print to stdout
Write-Output $generated
